>	more than / higher than
aad	aad	ad
abad	century
abadi	eternal
abang	elder brother
abangnya	his brother	his / her elder brother
abas	abas
abbas	abbas
abbasiyyah	abbasid
abd	abd
abdi	slave
abdul	abdul
abdullah	abdullah
abi	abi
abidin	abidin
abjad	alphabet
abpbh	baiturrahman
abraham	abraham
abstrak	abstract
abu	ash
abū	ash
acara	events
acaraacara	events
accountant	accountant
accounting	accounting
aceh	clearing	aceh
acheh	acheh	aceh
act	act
action	action
acuan	mold
ad	ad
ada	there is/are	have
adab	etiquette	manners
adabi	shairy
adakah	did / do /does	is
adakalanya	sometimes
adalah	is	is / are
adam	adam
adanya	presence
adapun	as for
adat	customs	custom
addin	addin
adha	sacrifice
adi	precious	adi
adik	younger brother	younger sibling
adikberadik	siblings	brothers and siblings
adiknya	his brother
adil	just	fair
adun	blend
advanced	advanced
aedes	aedes
aero	aero
aeroangkasa	aerospace
af	af
aff	aff
affan	affan
afghanistan	afghanistan
afrika	africa
afzan	afzan
against	against
agak	rather	quite
agama	religion	religious
agamaagama	religions
agar	so
age	age
agen	agent
agency	agency
agenda	agenda
agensi	agency
agensiagensi	agencies
agong	supreme	general	agong
agra	agra
agregat	aggregate
agresif	aggressive
agriculture	agriculture
agung	great	supreme
ahad	sunday
ahli	member	of
ahliahli	members
ahliahlinya	its members	members
ahlinya	his/her members	members	the member
ahmad	ahmed
ahmar	ahmar	stroke
ahmed	ahmed
ai	ai	ouch
aidil	aidil	eid
aidiladha	adelaide
aidilfitri	aidilfitri
ain	ain
aini	ani
air	water
airbus	airbus
airnya	water
airways	airways
ais	ice
aisberg	ice berg	icrberg	iceberg
aishah	aisha	aishah
aisyah	ayesha
ajakan	invitation
ajar	teach
ajaran	teachings	teaching
ajaranajaran	teachings
ajax	ajax
akad	contract
akademi	academy	academic
akademik	academic
akal	mind
akan	will
akar	root
akarnya	roots
akatsuki	kpi
akaun	account
akauntan	accountants	alauntan
akhbar	newspaper
akhbarakhbar	news	newspapers	news publications
akhir	last	end	close
akhirakhir	end	lately
akhirat	afterlife	hereafter
akhirnya	finally
akhlak	moral	character	morals
aki	battery	aki
akibatnya	consequently
akidah	faith	belief
aksara	alphabet	characters
akses	access
aksi	action
aksiom	axiom
akta	act
aktif	active
aktivis	activist
aktiviti	activities	activity
aktivitiaktiviti	activities
aku	i
akut	acute
al	al
ala	style
alaf	millenium	millennium
alah	yield
alahan	allergy
alaihi	alaihi
alam	nature
alamat	address
alan	alan
alandalus	al-andalus
alang	medium
alangkah	how
alasan	reasons	excuse
alasanalasan	reasons	grounds
alaska	alaska
alat	tool
alatalat	alatalat	tools
alatan	tools
alauddin	alauddin
alayubbi	alayubbi
alazhar	alazhar
albania	albania
albaqarah	al-baqarah
albert	albert
albukhari	al-bukhari
albukhary	albukhary
albuquerque	albuquerque
albus	albus
aldin	al-din
alex	alex
alexander	alexander
alfarabi	alfarabi	al-farabi
alfatihah	alfatihah
alfonso	of alfonso
alga	algae
algebra	algebra
algeria	algeria
alghazali	algazali	alghazali	al ghazali
alhaj	alhaj
alharam	alharam
alhaytham	al-haytham
alhazen	alhazen
ali	ali
alif	alif
alih	over
alim	pious
aliran	flow
aljazari	aljazari	al-jazari
alkhatab	umar	alkhatab
alkhattab	al-khattab
alkimia	alchemy
alkitab	bible
alkohol	alcohol
alkoholisme	alcoholisme	alcoholism	alkoholism
alkuna	alchemy	alkynes	alkyne
all	all
allah	god
allahyaraham	allahyaraham
allahyarham	late
allahyarhamah	late	the late (used to refer to deceased females)
allen	allen
almalik	al-malik
almarhum	late	the late (referring to a deceased person)
almasih	christ
almaunah	almaunah
almuadzam	al-muadzam	almuadzam
almutawakkil	almutawakkil	almutwakkil
aloi	alloy
alor	guarantee
alps	alpine
alquran	al-quran (koran)	al-quran	quraan
alrasyidin	alrasyidin
alternatif	alternative
alu	pestle
aluminium	aluminium	aluminum
aluminum	aluminum
alumni	alumni
am	general
amal	practice	charity
amalan	practice
amali	practical
amalkan	practice
aman	peaceful
amanah	trust
amar	amar
amaran	warning
amat	very
amatlah	is	extremely
amatur	amateur
ambil	took	take
america	america
american	american
amerika	america
amin	amen
amina	amines	amine
aminah	aminah
aminuddin	aminuddin
ammonia	ammonia
amnya	generally	general
among	among
ampang	ampang
ampuan	ampuan	used by westerners
ampun	forgiveness
amr	amr
an	an
anak	offspring	child
anakanak	kids
anakanaknya	his children	anakanaknya	his / her children
anakanda	son	child
anaknya	her
analisa	analysis
analisis	analysis
analog	analog
ananda	ananda
anatolia	anatolia
anatomi	anatomy
ancaman	treat	threat
ancient	ancient
and	and
anda	you
andaian	assumption	assumptions
andrew	andrew
aneka	various
anemia	anemia
ang	ang
angeles	angeles
anggap	consider
anggapan	assumption
anggaran	estimate	estimation
anggerik	orchid	orchids
anggota	member
anggotaanggota	personnel	the members
anggotanya	member	members
anggur	grape	wine
angin	wind
angka	figure
angkasa	space
angkasawan	astronaut	angkaswan
angkat	lift
angkatan	force	troops	armed forces
angkuh	arrogant
anglofilia	anglofilia	anglophile	anglophiles	anglophilia
ani	ani is
animasi	animation
anime	anime
animisme	animism
anita	anita
anjakan	shift
anjing	dog
anjuran	organised by
anne	anne
anod	anode
anopheles	anopheles
ansar	accompany
anson	anson
ansur	gradual	gradually
antah	bran	antah
antara	between
antarabandar	intercity
antarabangsa	international
antaramuka	interface
antaranya	between
antartika	antarctica	antartica
anti	anti
antibiotik	antibiotics	antibiotic
antigen	antigen
antiglobalisasi	anti-globalization
antipengganas	anti terrorist	anti-terrorism
antisemitisme	anti-semitism
antivirus	antivirus
antizarah	antizarah	anti-atomic	anti-particle	antimatter	antiparticle	anti particle	antizarat
antologi	anthology
antropogen	anthropogen	human impact on the environment	anthropogenic
antropologi	anthropology
anuar	anuar
anugerah	awards	award
anwar	anwar
anyaman	braid	weave
aorta	aorta
apa	what
apaapa	any
apabila	when
apakah	whether
apapun	any
aparteid	apartheid
apatah	moreover	what
apec	apec
api	fire
aplikasi	application	appication
apoptosis	apoptosis
applikasi	application	applications
april	april
aqidah	beliefs
ar	of ar
ara	fig
arab	arab
arabic	arabic
arafah	arafat	arafah
arah	direction
arahan	directions	orders
arak	alcohol
arang	charcoal	coal
aras	level
arau	arau
arca	arch	sculpture	statue
are	are
arena	arena
argentina	argentina
argumentasi	argumentation
arif	knowledgeable	wise
ariffin	ariffin
aristotle	aristotle
aritmetik	arimatic	arthimetic	arithmetic
arkeologi	archeology	archeolgy
arkib	archive	archives
arkitek	architech	architect
armada	armada
armenia	armenia
armor	armor
army	army
arrahman	arrahman
arshad	arshad
arteri	artery	the artery	arteries
arthur	arthur	arthur [ name ]
article	article
artifak	artifacts	artifact
artik	arctic
artikel	articles	article
artikelperkara	article: event
artileri	artillery
artis	artist
artritis	arthritis
arts	arts
arus	current
arvn	arvn
as	u.s.
as$	as $
asa	"putus asa" means given up	hope
asahan	shavings
asal	origin	original
asalan	origin
asalkan	as long as	provided
asalnya	originally	orgins
asalusul	origin
asalusulnya	the origins
asam	acid
asap	smoke
asar	asar
asas	base
asasasas	basics
asasi	staple	fundamental
asasnya	essentially
asean	asean
aset	asset
asia	asia
asian	asian
asid	acid
asimilasi	assimilation
asing	foreign
askar	soldier
askaraskar	soldiers	like soldiers
asli	original
asma	asma	asthma
aspek	aspect aspect aspect aspect	aspect
aspekaspek	aspects
aspirasi	aspirations	aspiration
asrama	dormitory	hostel
asri	beautiful	asri
assistant	assistant
asteroid	asteroid	asteriod
astro	stupid
astrofizik	astrophysics	astrophysi	astro physics	astrophysis
astrolab	astrolabe
astronomi	astronomy
aswad	stone
asyura	ashoora
atap	roof
atas	on
atasan	top
atasnya	it	above
atau	or
ataupun	or
ateis	atheist
atlantik	atlantic
atlas	atlas
atlet	athlete
atmosfera	atmosphere
atom	atomic	atom
atrium	atrium
atur	program	arrange
aturan	arrangement
aturatur	program	arrangement
aturcara	program
au	au
audit	audit
auf	auf
aur	aur
aura	aura
australia	australia
austria	austria
automatik	automatic
automotif	automotive
autonomi	autonomy
aw	prophet
awak	you
awal	early
awalan	pre-	prefix	first
awalnya	initially	earlier
awam	public
awan	papaya	clouds	cloud
awang	clouds	coluds
ayah	father
ayahandanya	his father	the father
ayahnya	his father
ayam	chicken
ayat	verse	sentance
ayatayat	verse2
ayer	water	ayer
ayu	beautiful	come on	pretty
ayun	swing
azab	suffering	punishment
azan	call
azhar	music	azhar
azimat	amulet	talisman	amulet / charm
aziz	aziz
azizah	she
azizan	azizan
azman	azman
azmi	azmi
bab	chapter
baba	father
babak	half
babbage	babbage
babi	pig
babylon	babylon
babylonia	babylonia
bac	bac
baca	read
bacaan	recitation	reading
bachok	highland
back	back
badak	rhinoceros	hippo
badan	body
badanbadan	bodies	parties
badannya	body	her
badar	badar	full moon	full moon full moon
badawi	badawi
badiyyah	badiyyah
badminton	badminton
badr	badr
bagai	like
bagaikan	similar to	as if	like
bagaimana	how
bagaimanakah	how
bagaimanapun	anyhow	however
bagan	chart
bagasi	baggage
baghdad	baghdad
bagi	for
bagian	given	part
bagimu	you
baginda	him / her (referring to royalty)	he
baginya	which
bagus	good
bah	flood
bahagia	happy
bahagian	the	part
bahagianbahagian	parts
bahaman	bahaman
bahan	material	ingredient
bahanbahan	materials	ingredients
bahantara	medium
bahar	sea ​​fans	bahar
baharu	new	newly
baharuddin	baharuddin
bahasa	language
bahasabahasa	bahasabahasa	languages	language
bahasanya	language
bahawa	that
bahawasanya	that
bahaya	danger
bahiyah	bahiyah
bahkan	even
bahru	bahru
bahu	shoulder
bahwa	that
baik	good
baikbaik	good	good things
baiklah	okay
baiknya	good	goodness
bainun	bainun
bait	byte	bytes
baitul	bait	baitul
baitullah	stonecutters	baitullah
baitulmuqaddis	maqdis
baja	fertilizer
bajak	rover
bajau	bajau
baju	shirt
bak	bak	like
baka	breed	gene
bakal	will	prospective
bakar	burn	roasted
bakat	talent
bakau	mangrove
baki	balance
bakr	bakr
bakri	bakri
bakteria	bacteria	bacteria, one type of microorganism
bakti	devotion	service
baku	standard
bakul	basket
bala	his	army
balai	hall
balak	timber
balam	balam
balas	respond	return	response
balasan	reply	response
balau	a type of tree / wood
bali	placenta	bali
baligh	puberty
balik	return
baling	vector
balistik	ballistic
balkan	goodness
ball	ball
balqis	the queen
balu	widow
bambu	bamboo
banci	census
bancian	census
band	band
bandar	​​city	city
bandaraya	city
bandarayabandaraya	city	cities
bandarbandar	city	cities
bandingan	comparison
banduan	prisoners	jail inmates
bandung	bandung
bangau	egret	pelican	crane
bangga	proud
bangi	new york	bangi
bangkai	carcass
bangkit	rise
bangkok	bangkok
bangladesh	bangladesh
bangsa	race
bangsabangsa	race	nations
bangsawan	aristocratic
bangun	wake	stand up
bangunan	building
bangunanbangunan	buildings
bani	children
banjar	banjar
banjaran	range	mountain range
banjir	flood
bank	bank
bantahan	objection	protest
bantal	pillow
banten	banten
bantu	help help	help
bantuan	assistance
banyak	many
banyaknya	many
bapa	father
bapanya	his father
baqarah	baqarah
bar	bar
bara	warmth
barah	cancer
barang	goods
barangan	things	goods
barangbarang	items	goods	things
barangsiapa	anyone
barat	west
baratnya	west
baris	line
barisan	line
baru	new
barubaru	recently
barulah	then
barunya	new
bas	bus
basah	alkali	wet
basikal	bicycle
basra	basra
basuh	wash
bata	brick
batak	hobo
batalion	battalion
batang	bar	stick
batara	god	male deity
batas	limit
batasan	limitation	limits
bateri	battery
batik	a type of textile
batin	spiritual	inner
batter	batter
battle	battle
batu	stone
batuan	stone	rocks	rock
batubatu	bricks / stones
batuk	cough
bau	odor	smell
bavaria	bavarian	bavaria
bawa	bring
bawaan	carrying	carrier
bawah	under
bawahan	subordinate
bawahnya	which	under
bawang	onion
bayam	spinach
bayan	bayan	parakeet
bayang	shadow
bayangan	shadow
bayangbayang	shadow
bayaran	payment
bayi	babies
bayu	wind
bbc	bbc
be	be
bebaling	throwing	berbaling	thrower	vector	bebaling	propeller
beban	load
bebas	freedom	free
beberapa	a few	some
bebola	ball
bedah	surgeon
been	telah
before	before
beg	bag
begawan	begawan
begini	so	like this
begitu	so
begitulah	thus	so
beijing	beijing
being	being
bekalan	supply
bekas	former
bekerja	work	working
bekerjasama	work	cooperation
beku	frozen
bekuan	clot
bela	advocate	keep
belah	shopping	split
belait	belait
belajar	study
belaka	sheer	mere
belakang	back	background
belalang	grasshopper
belanda	netherlands  netherlands
belang	stripe
belanga	pot
belanja	expense
belanjawan	budget
belas	reply	mercy
belayar	sailing
belgium	belgium
beli	buy
belia	youth	young
beliau	he
belibelah	shopping	prefer
beliung	tornado	hatchet
belud	eel	belud
belum	not yet
belut	eels	eel
bemula	commenced	starting
benang	thread
benar	true
benarbenar	truly
bencana	disaster
benci	hate
benda	thing
bendabenda	things
bendahara	treasurer
bendalir	fluid
bendera	flag
benggala	bengal
bengkak	swelling
bengkel	workshop
bengkok	crooked	bent
bengkulu	bengkulu
benih	benih translate from: indonesian seed	seed	seeds
benjamin	benjamin
bentan	relapse	backslide
bentara	bentara
benteng	fortress
bentong	bentong
bentuk	shape	form
bentukbentuk	bentukbentuk	shape
bentuknya	shape	form
benua	continent
bera	swollen
berabadabad	berabadabad	many centuries
beracun	poisonous	with poison
berada	be	are
beradik	siblings
beragama	religious
berahi	passion
berair	watery
beraja	have a king
berakal	rational	understanding
berakar	rooted
berakhir	ended	end	ending
berakhirnya	end
berakhlak	character
beraksi	action	play	in action
beralih	shifted	switch
beramairamai	a mass	beramairamai
beramal	do	to practice
beranak	give birth	birth	pregnant
beraneka	range	various
berang	angry
beranggapan	think
berangka	numerical	the numerical
berangkat	leave	set off	set out
berani	brave	bold
beransuransur	gradually
berantai	chain
berapa	how much	how many
berapi	fiery
beras	rice
berasa	feel
berasal	derived	from
berasaskan	based	based upon
berasingan	seperate	separate
berasrama	residential
berat	weight
beratnya	weighing	weight
beratus	hundres	hundreds
beratusratus	hundreds of
berawan	cloudy
berbagai	various
berbagaibagai	various	the various
berbahasa	speaking
berbahaya	dangerous
berbaik	be kind	reconcile
berbakti	serve
berbanding	than
berbangga	proud
berbangsa	ethnic
berbaris	lined	march
berbatu	rocky
berbau	smell
berbayar	paid-up-capital	up	paid
berbelah	divided
berbentuk	shape	form	shaped
berbeza	different
berbezabeza	different paces
berbicara	talk
berbilang	multi-
berbincang	discuss
berbuah	bear fruit	fruit
berbual	conversing	chat
berbuat	do
berbudi	courteous
berbuka	breaking of the fast	breaking
berbulu	hairy	hairy / furry
berbunga	flowering
berbunyi	read	sound
bercadang	plans
bercahaya	shine	luminous	shining
bercaj	charged
bercakap	talking	talk
bercampur	mixed
bercanggah	conflict
bercantum	attached	join
bercerai	divorced
bercetak	print
bercirikan	with features	characterized by	with such characteristics
bercitacita	aspire	bercitacita
bercorak	pattern	figured
bercucuk	farming
berdaftar	registered	register
berdagang	trade
berdakwah	preaching	preach
berdamai	bury the hatchet
berdarah	bloody
berdasarkan	on
berdaulat	sovereign
berdaya	competitive
berdekatan	nearby / close to	near	adjacent
berdepan	face
berdikari	independent
berdiri	stand
berdisiplin	disciplined
berdoa	pray
berdosa	sin
berdua	both
berdusta	lie
beredar	circulate
berehat	resting	rest
berekor	caudate	with a tail	tailed
berenang	swim	swimming
berendam	dip
berenjin	engine
bererti	means
beret	exacting
berevolusi	revolt	evolved
berfaedah	beneficial
berfalsafah	philosophical
berfikir	think
berfikiran	thinking
berfirman	said
berfungsi	function
bergabung	merge	combine
berganda	double	multiplied
berganti	changing	change
bergantung	depend
bergaya	stylish
bergelar	titled
bergelora	turbulent
bergerak	move
bergiat	active
berguna	useful
berhad	limited
berhadapan	facing	face
berhak	the correct one	the right
berhala	idol
berhalaberhala	berhalaberhala
berhampiran	near	nearby
berharap	hoping	hope
berharga	valuable
berhasil	succeed	succeeded
berhasrat	wish	with the intention
berhatihati	carefully	careful
berhenti	stop
berhias	berhias	float
berhijrah	migrate
berhormat	honorable	honourable
berhubung	on	be connected
berhubungan	in relation	relationship with
berhujah	argued	spoke
berhutang	owe	debt
beri	give
beribadah	worshipping	worship
beribadat	worship
beribu	thousands
berikan	give
berikat	allied	belted
beriklim	climate	weather or season
berikrar	pledge
berikut	following
berikutan	the
berikutnya	next
berilmu	educated	knowledge
beriman	believe	devout
berinai	dyeing	dyeing (with henna)
berindustri	industrialized
berinteraksi	interact
berirama	rhythmic
berisi	filled	contain
berisiko	risk	risky
berita	news
berjagajaga	on guard	be awake
berjalan	run	walk
berjangkit	infectious
berjanji	promised
berjasa	render a service
berjauhan	far
berjaya	successful
berjemaah	congregationally	congregation	congregational
berjiran	neighboring	neighbouring
berjiwa	spirited
berjuang	fight
berjudi	gambling	gamble
berjudul	entitled	titled	title
berjumlah	total	totaled
berjumpa	see	meet with
berjutajuta	the millions	millions
berkahwin	married
berkait	related
berkaitan	related
berkala	periodic
berkalikali	berkalikali
berkanun	statutory
berkasihkasihan	courtship
berkat	blessing	thanks to	blessings
berkata	saying	say	said
berkatakata	berkatakata	saying
berkatalah	said
berkawan	be friends
berkebolehan	capable
berkecimpung	been
berkecuali	independent
berkedudukan	position	positioning
berkehendak	desire	wants
berkehendakkan	requires	wanted only
berkekalan	sustainable	lasting
berkelahi	fight
berkelajuan	speed
berkelakuan	behaving	with certain actions	behavior
berkeluasan	widespread	area
berkemampuan	capable
berkembang	to grow
berkembar	twin
berkemungkinan	probably	likely
berkenaan	the
berkerja	work	working
berkesan	effective
berketurunan	descent
berkhasiat	nutritious
berkhatan	circumcision
berkhidmat	served	serve
berkibar	fluttering	wave
berkilat	shiny
berkilau	shiny	shining
berkisar	about	revolves
berkomunikasi	communicate
berkongsi	share	teamed up
berkualiti	quality
berkuasa	in power	power
berkuat	into
berkuatkuasa	effective	takes effect
berkuda	mounted
berkumpul	gather
berkumpulan	group	in a group
berkunjung	visit
berkurangan	reduced
berlabuh	docked	anchor
berlainan	different
berlaku	happen	occur	happened
berlakunya	of
berlalu	passed	pass
berlandaskan	based
berlangsung	take place	takeplace
berlanjut	continues
berlanjutan	last
berlari	run
berlarutan	prolonged
berlatih	training	practice
berlawan	to fight
berlawanan	contrary	in opposition to	contradiction
berlayar	sailing
berlebihan	excessive
berleluasa	widespread
berlepas	departure
berlian	daimond	diamond
berlin	berlin
berlindung	took cover
berlipat	folded
bermacammacam	bermacammacam	various	all sorts
bermaharajalela	mighty	rampant
bermain	play	playing
bermakna	means
bermaksud	means	mean
bermanfaat	beneficial
bermasalah	with problem	problematic
bermastautin	resident
bermimpi	dream
berminat	interested
bermoral	moral
bermotor	morized	motorized
bermuda	bermuda
bermula	started
bermulalah	started	began
bermulanya	commencement
bermuncul	exist
bermusim	seasonal	season
bermutu	quality	with quality
bernafas	breathe	breathing
bernam	bernam (location)
bernama	named
bernard	bernard
bernasib	lucky
berniaga	trade
berniat	intention	intend
bernilai	valued	worth
bernyawa	animate
beroleh	receive	get
berongga	hollow
beroperasi	operation	operate
berorientasikan	oriented	orientated
berpakaian	dress	dressing
berpakat	discuss	dicuss
berpaling	turn away	turn
berpandangan	opinion	view
berpandu	guided	according
berpandukan	based
berpangkalan	based
berpangkat	rank
berpanjangan	lengthy	prolonged
berparlimen	parliamentary
berpasangan	pairs
berpasukan	team
berpatutan	reasonable
berpecah	split	split / separate
berpegang	hold	holding
berpeluang	oppurtunity	opportunity
berpendapat	opine	view
berpendapatan	income
berpendidikan	educated
berpengalaman	experienced	experience
berpengaruh	influential	with influence
berperanan	role	in charge	played role
berperang	war
berperingkat	stages	in stages / staggered
berperlembagaan	constitutional
berpindah	move	berpindah
berpisah	split	separate
berpotensi	potential
berprestij	prestigious
berpuas	is
berpuasa	fast
berpuluhpuluh	tens	by tens
berpunca	originated	due
berpurapura	pretend	pretending
berpusat	based
berputar	rotate
berputus	to give up	given up	give
bersabda	said
bersahabat	freind with	friendship
bersaing	compete	competing
bersaiz	size
bersalah	fault	guilty
bersama	joint	with
bersamaan	equivalent
bersamasama	together
bersambung	connected to	connected
bersandar	lean against	rest
bersanding	enthronement ceremony done at weddings	angular
bersara	retired
bersatu	unite
bersaudara	siblings	brithers	brothers
bersebelahan	adjacent
bersedia	ready
bersejarah	historic	historical
bersekolah	go to school
bersekutu	associated
berselawat	bless	pray
berselisih	disagreement	disagree
bersemangat	enthusiastic
bersemayam	sit
bersembahyang	pray
bersempadan	border
bersempadankan	border
bersempena	in conjunction
bersemuka	face to face
bersenam	bersennam	exercise
bersendirian	alone
bersenjata	armed	equiped with weapons
bersepadu	integrated	integated
berserta	along	together with
berseru	cried
bersesuaian	appropriate	suitable
bersetubuh	sexual intercourse	intercourse
bersetuju	agreed
bersidang	conference	hold meeting	sit
bersifat	is
bersih	clean
bersikap	be
bersilang	crossed	cross
bersinar	shine	bright
bersiri	serial
berskala	scale
bersolat	praying	prayer
bersuami	married
bersuara	voiced
bersumpah	sworn	promise
bersunat	circumcision
bersungguhsungguh	earnest	really-really
bersurat	inscribed
bersusah	hard	burden
bersyukur	thankful	thankfulness / gratefulness	thankfulness	praised	grateful	be grateful	be gratefull
bertahan	survive	last
bertahuntahun	years of
bertajuk	entitled
bertakwa	fear
bertali	equipped with a rope	equipped with rope
bertam	increased
bertambah	increase
bertanam	planting	raise
bertanding	compete
bertanggung	responsible
bertanggungjawab	responsible
bertanya	ask	asked
bertapak	established	presence
bertaraf	with standard	standard	classed as
bertarikh	dated
bertarung	fight
bertaubat	repent
berteknologi	technology
bertelur	spawn	lay eggs
bertembung	clash
bertempat	located
bertempur	clashed
bertemu	meet
bertenaga	vigorous
bertentangan	opposed	conflict
bertepatan	coincide	consistent
berteraskan	based
berterusan	continued
bertha	bertha
bertiga	three	three of them
bertindak	act
bertindih	overlap	positioned one over the other
bertingkat	rise
bertiup	blow	blowing
bertolak	leave	tolerant
bertuah	lucky
bertugas	on duty
bertujuan	to
bertukar	switch	change
bertulang	bony	with these bones
bertulis	written	snatching
bertumbuh	grow
bertumpu	focus	focused / concentrated
berturutturut	consecutively
bertutur	speakra	speak
beruang	bear
beruas	beruas	segmental
berubah	change
berubahubah	changing	changes
berucap	deliver a speech
berukuran	measuring
berulang	repeated	recur
berulangulang	over and over	berulangulang
berumur	aged
berunding	negotiate
berundur	retreat	retreated
berupa	be	in the form of	alike
berupaya	can
berurusan	deal
berus	brush
berusaha	try
berusia	aging	old
berwarna	colored	coloured
berwarnawarni	colors	colourful
berwibawa	competent	commanding
berwuduk	ablution	performs
bes	base
besar	large
besarbesar	besarbesar
besarbesaran	ia	large-scale
besarnya	magnitude	largely
beserta	along
besi	iron
bestari	clever	smart
beta	beta
betapa	how
betawi	batavia
betik	papaya
betina	female
betis	calf
betong	betong
betul	right	correctly,
betulbetul	completely	right
betung	bamboo	sewer	a type of bamboo
between	between
bezanya	difference
bharata	bharata
bharu	bharu
bhd	ltd
biar	let
biarkan	let
biarlah	let
biarpun	even though
biasa	regular	usual
biasanya	usually
bibir	lip
bible	bible
bibliografi	bibliography
bicara	talk	speak
bidaah	heresy
bidah	bidah
bidang	sector	field
bidayuh	bidayuh
bidor	bidor
biduanita	artiste	singer
big	big
bijak	clever	wise
bijaksana	wise
biji	seed
bijih	ore	seed
bijirin	cereal
biju	biju
bil	bill
bila	when
bilabila	whenever	at any
bilah	blade
bilangan	amount	number
bilangannya	number	quantity
bilik	room
bilion	billion
bill	bill
billion	billion
bimbang	worry
bimbingan	guidance
bimbit	mobile
bin	son
bina	building	build
binaan	construction
binasa	destroyed	perish
binatang	animal
bintang	star	stars
bintangbintang	stars
bintangor	bintangor
binti	daughter
bintik	spot	dot
biodata	biodata
biodiesel	biodiesel
biografi	biography
biokimia	biochemistry	biokimai
biola	violin
biologi	biology
biology	biology
biopemulihan	biorecovery	biopemulihan	bio-recovery	bio recovery
bioperubatan	biomedicine	biomedical	bloperubatan
biopsi	biopsy
bioteknologi	biotechnology
biro	bureau
birokrasi	bureaucracy
biru	blue
bisa	ought
bising	noise	noisy
bisul	boil
bit	bit
blog	blog
blok	block
blood	blood
blue	blue
bmi	bmi
bn	bn
board	board
bodoh	stupidity	stupid
bogor	chicago
bola	ball
bolasepak	football
boleh	can
bolehlah	may be	it is possible	can
bom	bomb
bomba	fire	firefighter
bomoh	shaman	witch
boneka	puppet
bongsu	youngest child	the youngest
book	book
books	books
borang	form
border|px|barisan	border|px|line	border	border (px) line
border|xpx	border / xpx	border
borneo	borneo
bot	boat
botani	botany
both	both
botol	bottle
bp	for
brek	brake
brickfields	brickfields
briged	brigade
britain	britain
britannica	britannica
british	british
broadcasting	witolear
brooke	brooke
brown	brown
brunei	brunei
buah	a plural noun for more	fruit
buahbuahan	fruits
buahnya	fruit
bual	interview	bubbling
buana	depok sleman	buana
buang	discharging	throw away
buangan	exile	waste
buasir	piles	hemorrhoids
buat	make	for
buatan	made	artificial
buaya	crocodile
budak	slave	child
budaya	culture
budi	sole
bugis	bugis (noun) - an ethnic group originating in south sulewesi.	buginese	descended from the celebes islands
buih	foam	bubble
bujang	single	bachelor
bujur	oval	oblong
buka	open
bukaan	marketing	opening
bukan	not
bukanlah	not	is not
bukannya	not	is not
bukit	hill
bukti	evidence	proof
buktibukti	evidence of the	proofs
buktinya	evidence
buku	book
bukubuku	books
bukunya	his
bulan	month
bulanan	monthly
bulanbulan	bulanbulan
bulat	circle	round
bulatan	circle	roundabout
bulgaria	bulgaria
buli	bullying	bully
buloh	buloh
bulu	fur
buluh	bamboo
bumbung	roof	wall roof
bumi	earth
bumiputera	native
bumiputra	bumiputra	indigenous
bunga	flower
bungabunga	flowers
bunganya	the flowers
bungkus	pack
bunian	elves
bunting	gestation	pregnant
bunuh	murder	kill
bunyamin	brother
bunyi	sound
bunyinya	sound	sounds
burhanuddin	burhanuddin
buritan	stern
burma	burma	burmese
bursa	exchange
buruan	hunted	fugitive
buruh	labour	labor
buruj	constellation
buruk	ugly	bad
burung	bird	bird, one type of creature
bus	bus
business	business
busuk	stinky	foul
but	but
buta	blind
butang	button
butik	boutique
butterworth	butterworth
by	by
byzantine	byzantine
ca	ca
cabang	branch	branch  branch
cabaran	challenges	challenge
cacat	disabled	defective
cacing	worm	worms
cadangan	proposal
cahaya	light
cai	cai
cair	liquid	melt
cakap	said	talk
cakapnya	his words	he said	his / her words
cakera	disc
california	california
calon	candidate
caloncalon	candidates
cambridge	cambridge
cameron	cameron
campak	measles	chicken pox
campur	mixed	mix
campuran	mixture
can	full
canada	canada
canadian	canadian
cancer	cancer [ disease]	cancer
candi	temple
candu	copium	opium
canggih	technologically advanced	advanced
cangkerang	shell
canselor	chancellor	canchellor
cantik	beautiful	wonderful
cap	brand	mark
capaian	access
cape	cape
cara	ways	how
caracara	ways	methods
caranya	do	way
card	card
cari	search	find
carian	search
caribbean	caribbean
carl	name of person
carta	chart
cas	charge
cat	paint
catan	painting
catatan	note	entry
catcher	catchers
catur	chess
cause	cause
caves	caves
cawangan	branch
cdrom	cdrom
cecacing	worms
cecair	fluid	liquid
cecincin	ring	clothing
cedera	injury
cekak	insufficient
cekap	efficient
celah	gap
celaka	harm
cell	cell
celur	blanch	to cook quickly in boiling water	scald	blanching	scalded
cemas	anxious	nervous	panic
cemerlang	stellar	brilliant
cempaka	placed	cempaka
cempedak	jackfruit
cendawan	mushroom
cendekiawan	intellectual
cendekiawancendekiawan	scholars
cenderawasih	cenderawasih
cenderung	tend
central	central
centre	center
century	century
cepat	fast
cerah	bright
ceramah	talk
cerap	observatory
cerdik	clever	credik
ceres	ceres
cergas	active	energetic
ceria	cheerful
cerita	story
ceritacerita	stories
cermat	careful
cermin	mirror
cerpen	short story
certificate	certificate
cerun	slope
cetak	print
cetakan	print	printing
cetek	shallow
cfc	cfc
ch	ch
chakra	chakra
chakura	chakura
chakuranya	chakuranya
cham	cham
champa	champa
chandan	chandan
charity	charity
charles	charles
charm	charm
chartered	chartered
che	che
chee	chee
chemistry	chemistry
chen	chen
cheng	cheng
chepa	chepa
chew	chew	chew (name)
chiang	chiang
chicago	chicago
chikungunya	chikungunya
children	children
chile	chile
chin	chin
china	china
chinese	chinese
ching	it's a chinese name	ching	ching is
chola	chola
chordata	chordate	its a scientific name	chordata	chordata (scientific latin name)
chow	chow
choy	choy
christ	christ
christian	christian
churchill	churchill
cia	the cia
cik	miss
cili	chili
cina	chinese
cincin	ring
cindai	silk fabric
cinta	love
cipta	create	copyright
ciptaan	creation
circle	circle
cirebon	brandon
ciri	characteristic	feature
ciriciri	features be	feature
ciritbirit	diarrhea
cita	ends	ambition
citacita	citacita	ambition
city m ft	city ​​m ft
civilization	biography
cl	cl
clarke	clarke
class	class
clifford	clifford
club	club
cogan	standard
coklat	chocolate
collection	collection
colt	colt
columbia	columbia
committee	committee
company	company
computer	computer
concept	concept
condong	inclined
congkak	proud	congkak is a malay tradisional game
congress	congress
contoh	example
contohcontoh	examples
contohnya	for example
convent	convent
corak	pattern	design
corakcorak	patterns
cordoba	cordoba
corporation	corporations
cosmopoint	cosmopoint
council	council
crespigny	crespigny
cross	cross
crystal	crystal
cth	eg
cuaca	weather
cuba	cuba
cubaan	attempt
cucu	grandchild
cukai	tax	tax / levy
cukup	enough
culture	means same meaning in both language	culture
cuma	only
curahan	flood	flow
curi	steal	steal  steal
current	semasa
cuti	leave
cyberjaya	cyberjaya
cyprus	cyprus
d	d
dada	chest
dadah	drugs	drug
daeng	daeng
daerah	district
daerahdaerah	the regions	district
daftar	list
dagang	commerce
dagangan	trade
daging	meat
dahan	branch
dahari	dahari
dahi	forehead
dahsyat	awful	terrible
dahulu	before
dahulunya	previously
dail	dial
daily	daily
dajal	the devil
dakwaan	charge
dakwah	missionary
dakwahnya	preaching	missionary
dalam	in
dalaman	internal
dalamannya	the internals	internally
dalamnya	the insides	inside
dalang	mastermind
dalil	theoram	theorem
dalildalil	theorems	arguments
damai	peace
damansara	damansara
dan	and
dana	fund
dang	dang (name)
dangdut	dangdut
daniel	daniel
dap	dap
dapat	can
dapati	found
dapatkan	get
dapur	kitchen  kitchen  kitchen	kitchen
dara	virgin
darah	blood
darat	land
daratan	land
dari	from
darinya	from	it
daripada	from
daripadanya	from it	thereof	from him / her
darjah	degrees	degree
darjat	degree
darul	darul
darurat	in the state of emergency	emergency
darussalam	darussalam
dasar	foundation	basis
dasardasar	policies
dasarnya	essentially
dassault	dassault
database	database
datang	come
datanglah	came
datar	flat
dataran	plain
datin	datin
dato	dato
dato`	a name	dato'	dato
datoonn	datoonn	title
datu	datu
datuk	grandfather
datuknya	his grandfather	his / her grandfather
daud	daud	david
daulah	sovereign
daun	leaf
daunnya	leaves	its leaf
david	david
dawai	wire
dawud	dawud	david
daya	power
dayak	dayak
dayang	lady-in-waiting	lady in waiting
ddt	ddt
de	de
death	death
debu	dust
debunga	pollen
deepavali	deepavali
definasi	definition
definisi	definition	defination
deidara	deidara
dek	deck
dekad	decades	decade
dekat	close	near
delhi	delhi
deli	deli
delima	pomegranate
delta	delta
demam	fever
demi	for
demikian	thus	so
demikianlah	so	thus
demografi	demographic	demography
demokrasi	democracy
demokratik	democratic
demonstrasi	demonstration
denda	fine
dendam	revenge
dengan	with
dengannya	with
dengar	hear
denggi	of dengue	dengue
denis	person's name
denmark	denmark
denyut	pulse
denyutan	beat
depan	in front	next
department	department
deputy	deputy
der	der
deras	swift
derhaka	fallen
deria	sensory
derma	donation
dermaga	wharf	opening	dry dock	dock	pier	port
des	des
desa	village
desakan	pressure	pressure / urging
destinasi	destination
detik	second	moment
development	development
dewa	god
dewan	council
dewasa	adult
dewata	gods
dewi	goddess
di	in
dia	he or she	he
diabaikan	ignored	be ignored
diabetes	diabetes
diadakan	held
diagnosis	diagnosys
diajak	invited
diajar	taught
diajarkan	be taught	taught
diakibatkan	result
diakui	professed as	recognized
dialah	he/she	he
dialami	experienced
dialek	dialect
dialih	shifted	moved
dialirkan	passes	channelled
diam	silent
diamalkan	practiced
diambil	taken
diamdiam	diamdiam	tacit
diameter	diameter
diancam	threatened
dianggap	considered	said to be
dianggarkan	estimated
dianggotai	comprising
diangkat	lifted	raised
diangkut	carried	transported
dianjurkan	organized
diantara	between
diantaranya	among
dianugerah	awarded
dianugerahkan	awarded
dianuti	adopted
diarah	directed
diarahkan	directed
diasaskan	founded	was founded
diasingkan	separated
diaspora	diaspora
diatas	on
diatasi	overcame	overcome
diatur	regulated
dibaca	be read	read by
dibahagi	divided	split
dibahagikan	divided
dibakar	burned
dibalas	rewarded
dibandingkan	compared	dipandingkan	than
dibangun	developed
dibangunkan	developed
dibantu	assisted
dibatalkan	canceled
dibawa	be carried
dibawah	below
dibayar	be paid	paid
dibebaskan	released
dibekalkan	supplied
dibelah	be split
dibeli	be bought	bought
dibenarkan	allowed
dibentangkan	presented
dibentuk	be formed	made	shaped
diberi	given
diberikan	be given
diberitahu	informed
dibersihkan	cleaned
dibesarkan	grew up
dibezakan	differentiated	distinguished
dibiarkan	left
dibiayai	funded
dibicarakan	trialed	trial	trail
dibina	built
dibinakan	built	build
dibincangkan	discussed
dibolehkan	enabled	permitted
dibuang	removed	throw away
dibuat	made
dibubarkan	dissolved
dibuka	open	opened
dibuktikan	proof
dibungkus	wrap	packaged
dibunuh	killed
diburu	hunted
dicabar	challenged
dicabut	extracted	detached
dicadangkan	proposed
dicampur	mixed
dicampurkan	mixed
dicapai	achieved
dicari	sought
dicatat	recorded
dicatatkan	posted
diceraikan	divorced
diceritakan	be told	told
dicetak	be printed
dicipta	invented	created
diciptakan	made	created
dicirikan	characterized
dickson	dickson
didaftarkan	registered
didahului	preceded
didakwa	be charged
didalam	in
didapati	available
didedahkan	exposed
didenda	fine
didengar	heard	be heard
didiami	habitable
didik	students	protoge
didirikan	established
didominasi	dominated
didorong	driven
diduduki	occupied	inhabited by
diduga	expected	unexpected
diedarkan	distributed
dieksport	be export	exported
dielakkan	avoided
diem	diem
diendahkan	ignored
diertikan	defined
diesel	diesel
diet	diet
difahami	understood
difahamkan	it is understood	understood	understanding
difikirkan	thought
digabungkan	combined
digalakkan	encouraged
digambarkan	described
diganggu	be disturbed	disturbed
diganti	be replaced
digantikan	replaced
digantung	suspended
digariskan	outlined
digelar	called
digelarkan	called
digemari	liked	preferred
digerakkan	moved	deployed	be moved
digeruni	feared
digital	digital
digolongkan	classified
digoreng	fried
digubal	enacted
digugurkan	dropped
digulingkan	be defeated
diguna	used
digunakan	be used
dihadapi	faced
dihadiri	attended
dihadkan	limited
dihalang	blocked
dihalau	driven	expel
dihancurkan	destroyed	oblilerated
dihantar	be	sent
dihapuskan	destroyed	off	abolish
diharamkan	banned
diharap	expected	hoped
diharapkan	expected
dihargai	appreciated
dihasilkan	produced
dihentikan	stopped
dihias	decorated	decorated by
dihiasi	decorated	decorated with
dihidangkan	served	vegetables
dihidupkan	resurrect	enriched	swiched on
dihormati	be respected
dihubungi	contact	contacted
dihubungkan	connected
dihukum	sentenced	punished
dihuni	inhabited	occupied
dihuraikan	defined
diikat	bound
diiktiraf	recognized
diikuti	followed by	follow
diilhamkan	inspired
diimport	imported
diingat	remembered	remember
diingatkan	reminded
diingini	desired	wanted
diiringi	accompanied
diisi	filled	fill
diistilahkan	termed
diisytiharkan	declared
dijadikan	as
dijaga	be guarded	taken care of	care
dijajah	colonized
dijalankan	conducted
dijamin	guaranteed	ensured
dijana	generated
dijangka	expected
dijangkakan	expected	predicted
dijangkiti	infected
dijanjikan	promised
dijawab	answered	be answered
dijelaskan	be explained	dijelasken
dijemput	invited
dijual	sold
dijumpai	found
dijunjung	upheld	carried on the head	held up
dikaitkan	associated
dikaji	studied
dikalahkan	defeated
dikalangan	among
dikarang	written
dikatakan	said	be said
dikategorikan	categorised	categorized
dikawal	controlled
dikawasan	area	in a place
dikebumikan	buried
dikehendaki	be required	required	be required be required
dikejutkan	shocked
dikekalkan	maintained
dikelaskan	classified	dikelaskan
dikelilingi	surrounded
dikelirukan	confused with
dikelolakan	organised
dikeluarkan	issued
dikembalikan	be returned	retuned
dikembangkan	be expanded
dikemukakan	produced	submitted
dikenakan	imposed	are
dikenal	are
dikenali	known
dikenalpasti	identified
dikenang	be remembered
dikendali	operated	handled
dikendalikan	operated	conducted
dikerjakan	working
dikesan	detected
diketahui	known
diketuai	led by	led
dikhaskan	reserved	specially
dikhatan	circumcised
dikhuatiri	worried	feared
dikhususkan	dedicated	dikhusaskan
dikira	calculated
dikisahkan	told
diklasifikasikan	classified
dikongsi	shared	sharing
dikritik	criticized
diktator	dictator
dikuasai	controlled
dikuatkuasakan	enforced
dikumpul	collected
dikumpulkan	be gathered	collected
dikunjungi	visited	be visited
dikurangkan	reduced
dikurniakan	given	blessed with
dikurung	confined	caged
dilafazkan	pronounced
dilahirkan	born
dilaksanakan	implemented
dilakukan	do	done
dilalui	passed through	traveled
dilancarkan	launched
dilanda	hit
dilanjutkan	extended
dilantik	appointed
dilaporkan	reported
dilarang	forbidden	prohibited
dilarikan	run
dilatih	trained
dilema	dilemma
dilengkapi	equipped
dilengkapkan	completed	complete with
dilepaskan	released
diletak	placed
diletakkan	placed
dilihat	seen
dilihatdisebut	be called
dilindungi	protected
diliputi	covered	be covered
dilitupi	covered	closed
diluar	outside	out
diluaskan	be dilated
dilukis	painted	drawn
diluluskan	approved
dilupakan	forgotten
dimainkan	be played
dimajukan	developed
dimakan	consumed	be eatan
dimaksudkan	is
dimana	where
dimanfaatkan	be used
dimansuhkan	repealed	abolished
dimasak	cook	be cooked
dimasukkan	included	entered	inserted
dimensi	dimension
dimeterai	demerai	sealed
dimiliki	owned by	owned
dimilikinya	owned by	owned
diminati	followed	favorite	interest
diminta	asked
diminum	be drunk
dimuat	be
dimulai	begins	started
dimulakan	started
dimuliakan	graced	honored
dimusnahkan	destroyed
din	din
dinafikan	denied
dinaikkan	increased
dinamai	named	called
dinamakan	named
dinamik	dynamic
dinasihatkan	advised
dinasti	dynasty
dinastidinasti	dynasties	dinastidinasti
dinding	wall
dingin	chilly	cold	cool
dinh	dinh
dinikmati	enjoyed
dinilai	evaluated
dinyatakan	stated
diod	diod	diode
diognasa	diagnosis
dioksida	dioxide
dipakai	used
dipaksa	forced
dipamerkan	exhibited
dipanaskan	be heated
dipancarkan	transmitted
dipandang	viewed
dipandu	driven
dipanggil	called	be called
dipantau	monitored
dipaparkan	displayed
dipasang	installed
dipasangkan	installed
dipasarkan	marketed
dipastikan	uncertain
dipatuhi	observed	complied with	followed
dipecahkan	broken
dipecat	removed	fired
dipegang	held
dipelajari	be learned	learn
dipelihara	preserved
dipengaruhi	be affected
dipengerusikan	chaired
dipenjarakan	imprisonment
dipenuhi	filled
diperbaharui	renewable
diperbaiki	repaired	improved
diperbuat	made of	made
dipercayai	believed	reliable
diperdebatkan	debated
dipergunakan	used
diperhatikan	observed	observe	monitored
diperihalkan	described
diperiksa	assessed	examined	be examined
diperintah	commanded	ordered	governed
diperintahkan	be ordered
diperkatakan	said to be	said	talked about
diperkenalkan	introduced
diperkenankan	allowed
diperlakukan	be treated
diperlihatkan	shown
diperlu	required
diperluas	expanded	widen
diperluaskan	extended
diperlukan	be required
diperoleh	obtained
diperolehi	obtained
dipersembahkan	presented
dipersetujui	agreed
dipertahankan	defended
dipertandingkan	contested
dipertanggungjawabkan	accountable
dipertikaikan	questioned	dispute
dipertimbangkan	considered
dipertingkatkan	enhanced
dipertua	president	elder
dipertuan	ydp
diperuntukkan	provided
dipetik	cited	picked	quoted
dipilih	selected
dipimpin	led by	lead
dipinda	amended
dipindahkan	be transferred	transferred
dipinjam	borrowed
dipisahkan	separated
diploma	diploma
diplomasi	diplomacy
diplomatik	diplomatic
dipotong	cut	be cut
dipraktikkan	practice
diproses	process	disproses
dipuji	praised
dipukul	beaten
dipulihkan	restored	healed
dipunyai	owned
diputuskan	decided
diragui	doubt	doubted
diraikan	celebrated
diraja	royal
dirakam	recorded
diramalkan	predicted
dirampas	seized
dirancang	be planned
dirasai	dirsai	felt	dirasasi
dirasakan	felt
dirasmikan	officiated	inaugurated
dirawat	treated
dirayakan	celebrated
direka	designed
direkodkan	recorded
direktori	directory
diri	self self	self
diriku	myself
diringkaskan	summarised	summarized
dirinya	his
diriwayatkan	reported
dirujuk	referred to
disabitkan	convicted
disahkan	confirmed
disajikan	is served	presented
disaksikan	be witnessed
disalah	wrongly	mistaken
disalurkan	channelled	channeled
disamakan	equated
disambung	joined / continued	connected
disambut	welcomed
disampaikan	delivered	conveyed
disamping	well	besides
disana	there
disandang	held
disangka	thought	predicted
disapu	applied	swept
disatukan	consolidated
disayangi	loved
discharge	discharge
disease	disease
diseases	diseases
disebabkan	because
disebarkan	spread
disebelah	side
disebut	pronounced	said	called
disebutkan	mentioned
disedari	realized
disediakan	prepared
disegani	respected
disejukkan	cooled
disekat	stuck	blocked
disekitar	around
diselamatkan	saved
diselesaikan	i felt that i was unable to attend because i will to teregganu on the same day on the job matters to be resolved	solved	be solved
diseluruh	throughout
disemak	revised	checked
disembah	prayed	worshipped	worshiped
disember	december	dicember
disembunyikan	hidden
disenaraikan	listed
disenyawakan	fertilized
diserahkan	submitted
diserang	attacked
diserap	absorbed
diserikan	illuminated
disertai	desertai	be accompanied	accompanied by
disertakan	included	inserted with
disesuaikan	be adapted	adapted	suited
disiapkan	completed	finished
disiarkan	displayed	published
disifatkan	be	characterised
disimpan	stored
disimpulkan	concluded
disingkirkan	removed
disini	here
disiplin	discipline
diskriminasi	discrimination
disleksia	dyslexia
disokong	be supported	supported
displaystyle	displaystyle
disukai	preferred
disunatkan	is desirable
disuruh	asked
disusuli	followed by
disusun	arranged
disyaki	suspected
disyorkan	recommended
ditabalkan	cancelled	crowned
ditabur	sown
ditadbir	administered
ditafsirkan	interpreted
ditahan	be detained
ditakluk	conquered
ditakrifkan	defined
ditakuti	feared
ditamatkan	ended	discontinued
ditambah	added
ditambahkan	added
ditanam	buried
ditandai	be marked
ditandakan	marked
ditandatangani	ditadatangani	is sign by	be signed
ditangguhkan	be deffered	be deferred
ditangkap	be arrested	caught
ditanya	asked	being ask
ditarik	pulled	withdrawn
ditarikan	danced
ditawan	captured
ditawarkan	offered
ditayangkan	screened
ditebang	cut	cut down
ditegah	described	discouraged
ditegaskan	asserted
ditekankan	emphasized
ditelan	swallowed
ditembak	shot
ditempa	be incused	shaped
ditempatkan	placed
ditemui	found	be found
ditemukan	found
ditentang	opposed by	opposed
ditentukan	determined
diterajui	led
diterangkan	be explained
diterapkan	applied	integrated
diterbitkan	punlished	published
diterima	received	accepted
diterimanya	received
diterjemah	translated
diterjemahkan	translated
diteruskan	be continued	continued
ditetapkan	decided	set
ditewaskan	defeated
ditimpa	afflicted
ditinggalkan	left behind	left
ditingkatkan	increased
ditolak	refused	less
dituai	harvested
ditubuhkan	established	at,established
dituduh	accused	accused of
ditugaskan	assigned
dituju	destination
ditujukan	directed
ditukar	changed
ditukarkan	converted	substituted
ditulis	written
ditumpaskan	defeated
ditunaikan	encashed	discharged
ditunjukkan	shown
dituntut	claimed
diturunkan	reduced
ditutup	close	closed
ditutur	spoken
dituturkan	spoken	spoke
diubah	changed	kdiubah
diubahsuai	modified
diuji	tested
diukur	measured	be measured
diulangi	repeated	be repeated
diumumkan	diumukan	was declared
diundi	voting	voted
diuruskan	managed
diusahakan	undertaken
diusir	expelled	banished
diutamakan	priority
diutuskan	sent
dividen	dividend
division	divison
divisyen	division
diwahyukan	revealed
diwajibkan	required
diwakili	represented
diwarisi	go over	inherited
diwartakan	offered	gazetted
diwujudkan	created
dki	dki
dll	and others
dm	dm
dna	dna
doa	prayer
doctors	doctors
does	does
doktor	doctor
doktrin	doctrine
dokumen	document
dokumentasi	documentation
dolar	dollar
domestik	domestic
dominan	dominate	dominant
dominasi	domination
donald	donald
dong	come on	dong
dongeng	fairytale	myth
dorongan	encouragement
dos	dose
dosa	sins	sin
dosadosa	dosadosa	sins
douglas	douglas
down	down
dr	doctor
draco	draco
draf	draft
dragon	dragon
dram	drum
drama	drama
dramatik	dramatic
du	du
dua	two
dubur	anus
duduk	sit
duit	money
duke	duke
dulang	tray
duli	dust
duliduli	dust
dulu	previously	first
duluan	first
dulunya	previously
dumbledore	dumbledore
dun	dun
dungun	dungun
dunia	world
duniawi	temporal
duri	thorn
durian	durian
during	sulawesi
dusun	village
duta	ambassador	envoy
duti	duty
dwibahasa	dual lingual	dual language	bilingual
dwidewan	dual chambers	bicameral
dymm	hrh
e	e
early	early
earth	earth
east	east
economic	economic
ed	ed
edaran	distribution	circulation
edema	edema
edinburgh	edinburgh (location)
edisi	edition
edison	edison
editor	editor
edo	edo
edward	edward
ee	ee
efektif	effective
efluen	effluent
egypt	egypt
ehsan	ehsan	courtesy
ehwal	affairs
einstein	einstein
ejaan	spelling	ejeen
ejekan	ridicule
ejen	agent
ekologi	ecology
ekonomi	economy
ekonomik	economic
ekonominya	economic	economy
ekor	tail
ekoran	as a result
ekornya	its tail	tail
ekosistem	ecosystem
eksbibait	exbibyte	eksbibait	exabyte
eksekutif	executive
eksklusif	exclusive
ekspedisi	expedition
eksperimen	experiment
eksport	export
ekspres	express
ekspress	express
el	el
elakkan	avoid
elektrik	electric
elektrolisis	electrolysis
elektrolit	electrolyte
elektromagnet	electromagnetic	electromagnet
elektron	electron
elektronik	electronics	electronic
elemen	element
eletrik	electric
elit	elite
elite	elite
elizabeth	elizabeth
elok	well
emak	mother
emas	gold
embolus	emboli
embrio	embryo
embun	dew
emel	email
emeritus	emeritus
emigrasi	emigration
emirates	emirates
emosi	emotion	emotional
empangan	dam
emparan	centrifuge	centrifugal
empat	four
empayar	empire
empire	empire
enakmen	enactment
enam	six
encik	sir	mister
encyclopedia	encyclopedia
endemik	endemic
endometrial	endometrial
enggan	wont	reluctant
enggang	wont	hornbill (bird)
engkau	you
engkol	crank
england	england
english	english
enjin	engine
ensiklokamus	ensiklokamus
ensiklopedia	encyclopedia	encyclopaedia
entiti	entity
entry	entry
enzim	enzyme
ep	ep
episod	episode
erat	tight	strong relation
ereksi	erection
eric	eric
eropah	europe
erti	meaning
ertinya	meaning	means
es	ice
esa	one
esok	morrow	tomorrow
estet	estate
estrogen	estrogen
etika	ethics
etimologi	etymology
etnik	ethnic
euclid	euclid	euclide
eur	eur
eurasia	eurasia	eurasian
euro	euro
europe	europe
evolusi	evolution
explorer	explorer
express	express
fa	fa
facebook	facebook
faedah	benefit
faham	schools	understand
fahaman	understanding
fail	file
failfail	files
fajar	dawn
fakir	poor	fakir
faks	fax
fakta	fact
faktor	factor
faktorfaktor	factors
fakulti	faculty
falak	celestial	space
falciparum	falciparum
falsafah	philosophy
famili	family
family	family
famosa	famosa
fantasi	fantasy
fantasia	music song
faraj	vaginal
fardhu	obligatory
fardu	obligatory
farmasi	pharmacy
fasa	phase
fasakh	fasakh	talaq
fasal	clause
fasih	fluent
fasik	corrupt	wicked or evil	wicked
fast	fast
fatani	fatani
fatimah	fatimah
fatimiyyah	faction
fatwa	fatwa
fauna	fauna
fauziah	fauziah
fe+	fe+	fe
februari	february
federal	federal
federation	federation
felda	felda
fellowship	followship
fenomena	phenomenon
ferguson	ferguson
feri	ferry
feromon	pheromone	pheromo
fesyen	fashion
fetus	fetus	fetuses
feudal	the feudal
fever	fever
fi	fee
fifa	fifa
fikir	think
fikiran	mind
fikirannya	his mind
filateli	philatelic	filateli	philately
filebunga	filebunga
filem	movie	film
filemfilem	films
fili	act
filipina	filipino
finance	finance
finland	finland
fiqh	jurisprudence
firaun	pharaoh	tyrant
firma	firm
firman	commandment	word
firnas	firnas
first	first
fisiologi	physiology
fitnah	defamation	slander
fitrah	natural	disposition	natural tendency
fitri	natural
fizik	physics
fizikal	physical
fleksibel	flexible
flora	flora
florence	florence (location)
florida	florida
flow	flow
fm	fm
fn	fe
fokus	focus
folik	folic
folikel	follicles
fonetik	phonetic	phonethics	phonetics	phonetics  phonetics
fonologi	phonology
for	for
formal	formal
formasi	formation
format	format
formula	formula
forum	forums
fosil	fossil
foto	photo
fotografi	photography
fotosintesis	photosynthesis
franca	franca
francis	francis
francisco	francisco
frank	frank
frankfurt	frankfurt
franklin	franklin
frasa	phrase
fred	fred
frederick	frederica
free	free
freemason	freemasons
frekuensi	frequency
friedrich	friedrich
frigat	frigate
front	front
fru	fru
fuad	heart
fungsi	function
fungsifungsi	functions
fungsinya	functions
g	g
ga	ga
gaara	gaara
gabenor	governer	governor
gabenorjeneral	governor general
gabungan	combination
gade	gade
gading	ivory	tusk
gadis	girl
gaffar	gaffar
gagah	strong
gagal	fail
gagasan	idea
gai	gai
gajah	elephant
gaji	wage	salary
galah	pole	quant
galakan	encouragement
galaksi	galaxy
galeri	gallery
galian	minerals
galur	linked	channel	furrow
gamabunta	gamabunta
gambar	picture
gambaran	picture	image
gambargambar	the pictures
gambir	clove
gambus	a musical instrument	harp
gamelan	orchestra
ganas	violent
ganda	ganda	multiple
gandaan	multiple
gandum	wheat
gangga	ganga
gangguan	disruption	disturbance
gangsa	bronze
ganjaran	reward
ganjil	odd
gantang	buspenyakithel	bushel
ganti	replacement	substitute	replace
gantung	hang	hanging
garam	salt
garang	fierce	eclipse
garden	garten
garis	line
garisan	line
garuda	eagle	mythical bird
gas	gas
gasgas	gas-gas
gasing	top
gatal	itchy
gates	gates
gawai	gawai
gay	gay
gaya	style
gayagaya	styles
gayong	gayong
gayung	scoop	bailer	gayung
gdp	gdp
gear	gear
geber	geber
gedang	large	pawpaw
gedung	warehouse	building
gegaran	tremors	shaking	vibration
gejala	symptom
gejalagejala	gejalagejala	symptoms	symptom
gel	gel
gelang	bracelet
gelanggang	field
gelap	dark
gelaran	title
gelembung	bubble
gelisah	restless
gelombang	wave
gelora	turbulence	wave	turbulent flow
gelung	ass	coil
gemar	like
gemas	gemas (location)	exasperation
gembira	happy
gemilang	bright	briliant
gempa	quake
gempur	sulit	engage (in battle)
gemuk	fat
gen	gene
genap	even
gencatan	cessation	cease-fire
gendang	drum
general	general
generasi	generation
genetik	genetic
geneva	geneva
genital	genital
genome	genome
genre	genres
gentian	fibre	fiber
genting	critical
genus	genus
geografi	geography
geologi	geological	geology
geometri	geometry
george	george
georgetown	gianyar
gerai	stall
gerak	move	movement
gerakan	motion	movement
gerakangerakan	movement
gerald	gerald
gerbang	gate	arch
gereja	church
gerejagereja	churches
gergasi	giant
gerhana	ecplise	eclipse
gerik	gerik
gerila	guerrilla
geseran	friction
get	get
getah	rubber	latex
getaran	vibrant	vibration
ghafar	ghafar
ghaib	invisible
ghairu	ghairu
ghazali	ghazali	ghazalt
ghee	ghee
gian	gian
giant	giant
gigabait	means same meaning in both language	gigabit	gigabyte
gigi	teeth	tooth
gigitan	bite
gila	crazy
giliran	turn
gimnas	gymnast
gimnastik	gymnastics	gymnastic
ginjal	kidney
gitar	guitar
giza	giza
gizi	nutrient
glazer	mike	glazer
globalisasi	globalization	globalisation
glock	glock
gloucester	gloucester
glukagon	glucagon
glukosa	glucose
gnu	gnu
goa	goa (location)	cave
goal	goal
god	god
goh	hump
gol	gol	goal
golden	golden
golf	golf
golongan	group
gombak	crest	gombak
gonadotrofin	gonadotrophin	gonadotropin
gong	gong
gonggok	catepillar	millipedes	milipede	caterpillar	millipede	milipedes
gonorea	gonorrhea
goreng	fried
gout	gout
graf	graph
grafik	graphic
gram	gramme	gram
grand	grand
granger	granger
graviti	gravity
gred	grade
greece	greece
greek	greek
grenad	grenade
grened	grenade
grid	grid
grup	group
gua	cave
gudang	warehouse	a name of a place "pasir gudang"
gugur	fall
gugusan	cluster
guide	guide
guinea	guinea
gula	sugar
gulagula	sweets	candy
gumpalan	clump	lump
guna	use
gunaan	usage	applied
gunakan	use
gunanya	use
gundik	concubine
gunong	mount
gunpowder	gunpoweder
gunting	scissors	cut
gunung	mountain
guru	teacher
guruguru	teachers
gurun	desert
gurunya	his teacher	teacher
gus	thus
gusti	wrestle	wrestling
hab	hub
haba	heat
habis	runout	end
habitat	habitat
hablur	crystal
habsyah	habsyah	abyssinia
habuk	dust
hachibi	hachibi
had	limit
hadapan	front
hadas	ritual impurity	ritual impurities
hadhari	hadhari is	hadhari
hadiah	gift
hadiahhadiah	gifts
hadir	attend
hadirin	audience
hadis	hadith
hadishadis	hadishadis
hadith	hadith
hai	hi
haid	menses	menstruation
haiwan	animals	animal
haiwanhaiwan	animals
hajah	hajah
hajar	hajar
hajat	wish
haji	pilgrimage	haj
hajjah	hajjah
hak	right
hakhak	rights are	rights
hakikat	the fact
hakikatnya	in fact
hakim	judge
hakisan	erosion
hakka	hakka
hal	case
hala	direction
halal	halal	clean
halaman	yard	page
halangan	obstruction
halehwal	affairs
halhal	halhal
hall	hall
halnya	case
haluan	direction
halus	fine
hamba	slave
hambanya	subject (ie. subjects of god)	servants
hamdan	hamdan
hamidi	hamidi
hamil	pregnant
hampir	almost	near
hampirhampir	almost	closely
hamzah	hamzah
han	han
hanafi	hanafi
hanbal	hanbal
hancur	destroyed	broken
hang	hang
hangat	warm
hangus	burned
hans	hans
hantaran	delivery	pass
hantu	ghost
hanya	only
hanyalah	only
hanyut	float
harakah	movement
haram	illegal
harap	hope
harapan	hope
harapkan	hopefully
harfiah	literal
harga	price
harganya	price	the price
hari	day
harian	daily
harihari	everyday	daily	days
harimau	tiger
harinya	day
harmoni	harmony
harris	harris
harry	harry
harta	property
hartabenda	property	wealth
hartaharta	properties
hartanah	property
harum	fragrant
harun	harun	aaron
harus	should
haruslah	must	should
harvard	harvard
has	has
hasan	hasan	good
hashim	hashim
hasil	result
hasilhasil	the results	resultsproduct results
hasilnya	the result	results
hasrat	desire	intention
hassan	hassan
hati	liver
hatinya	his	his heart
hatta	thereupon	hatta
hawa	air
hawai	hawaii
hawaii	hawaii
hawker	turtles
hayat	life
hayatnya	life	his life
hayyan	hayyan
hb	st
he	he
head	head
hebat	great
helai	strand
helang	eagle	eagles
helikopter	helicopter
hemisfera	hemisphere
hempedu	bile
hendak	want
hendaklah	be	should	must
heng	heng
henry	henry
hentaman	impact
henti	stopping	stop
hepatitis	hepatitis
herba	herb
hermione	hermione
hero	popular sports figure	hero
hertogh	hertogh
heteroseksual	heterosexual
hiasan	decoration
hiburan	entertainment
hidan	hidan
hidangan	serving
hidayah	guidance
hidayat	guides
hidraulik	hydraulic
hidroelektrik	hydroelectric
hidrogen	hidrogen	hydrogen
hidrografi	hydrographic	hydrografic	hydrography	hydrogrpahy
hidroksida	hydroxide
hidroponik	hydrophonic	hydroponic
hidung	nose
hidup	life	live
hidupan	life	living things
hiduphidup	hiduphidup	alive
hidupnya	his	his life
hierarki	hierarchy
high	high
highland	highland
highlands	highlands
hijau	green
hijaz	hijaz
hijrah	migration
hikayat	saga
hikmah	wisdom
hikmat	blessings	wisdom
hilang	lost	lose
hilir	downstream
himalaya	himalayas
himpunan	compilation	compliation
hin	bullock
hina	despicable	low
hindi	hindi
hindia	indies	hindi
hindu	hindu
hindubuddha	hindu buddha	hindu buddist
hingga	to	until
hinggalah	up	until
hinggap	perched	perch	alight
hipotesis	hypothesis
hira	hira (name)
hiroshima	hiroshima
his	his
hishamuddin	helen
historical	historical
hit	extremely popular
hitam	black
hitler	hitler
hiv	hiv
hivaids	hivaids
hizbul	hizbul
hj	hj
hms	hms
ho	ho	o	oh
hobi	hobby
hock	hock
hodgkin	hodgkin
hokage	hokage	the hokage
hoki	hockey
hokkien	hokkien
holdings	holdings
hollywood	hollywood
holokus	holocaust
home	home
homeostasis	homeostasis is
homo	homo
homoseksual	homosexual
hon	horn
hong	hong
hormat	respect	respectful
hormon	hormone
hornet	hornet
hos	host	hose
hospitaliti	hospitality
hotel	hotel
how	how
http	http
hua	hua
hubungan	relation	relations	relationship
hubungannya	relationship
hud	hood
hudaibiyah	hudaibiyah
hudson	hudson
hugh	hugh
hujah	argument	arguments
hujan	rain
hujung	end
hujungnya	ends
hukum	law
hukuman	sentence
hukumhukum	the laws	hukumhukum
hulu	upstream
hulubalang	commander
huma	field for dry rice cultivation
human	the human
humanisme	humanism
hungary	hungary
huraian	explanation	description
hurairah	hurayrah
hurikan	taufan	hurricane
huruf	letter
hurufhuruf	alphabets	hurufhuruf
huruhara	chaos
husain	husain
hussain	hussain
hussein	hussein
hussien	hussien	hussein
hussin	hussin
hutan	forest
hutang	debt
hwa	hwa
i	i
ia	it
iaitu	is
ialah	is	is / are
ianya	it
ibadah	worship	prayer
ibadat	act of worship	worship
iban	iban
ibarat	as though	similar to	parable
iberia	lberia
iblis	devil	lucifer	demon
ibm	ibm
ibn	ibn
ibni	son of	son
ibnu	ibn
ibrani	hebrew
ibu	mother
ibubapa	parents
ibukota	capital city	capital
ibunda	native
ibunya	his mother	his / her mother
iceland	iceland
ideaidea	ideas
ideal	ideal
identiti	identity
ideologi	ideology
idola	idol
idris	idris
if	if
ihram	ihram	pilgrimage
ii	ii
iii	iii
ijazah	degree
ikan	fish
ikatan	bond
ikhlas	sincere
ikhtiar	endeavour	initiative
iklan	advertisement
iklim	climate
iklimnya	climate	its climate
ikon	icon
ikrar	pledge
ikut	follow
ikutan	follow	follow-
ilham	inspiration
ilmiah	scholarly
ilmu	knowledge
ilmuilmu	knowledge
ilmuwan	academic	scientists
imageedisigif|jilid	imageedisigifljilid
imam	priest
iman	faith
imbangan	balance
imbuhan	remuneration
imej	image
imf	imf
imigrasi	imigration	immigration
imigresen	immigration
impak	impact
imperial	imperial
impian	dream
impiana	impiana
implikasi	implication
import	import	imports
imtiaz	imtiaz
imunisasi	immunisation	immunization
in	in
inai	henna
inc	inc
inca	inca
include	include
indah	beautiful
indeks	index
indera	indera
india	india
indian	indian	india
individu	individual
individual	individual
indochina	indochina
indonesia	indonesia
indra	senses
induk	main	parent
induknya	parent
industri	industry
industriindustri	industries	industry
inersia	inersia	the inertia	inertia
infant	infant
infantri	infantry in	infantry
inflasi	inflation
influenza	influenza
info	information
informasi	information
information	information
infra	infra
inframerah	infrared
infrastruktur	infrastructure
ingat	remember
ingatan	memory
ingatlah	remember
inggeris	english
ingin	want
inginkan	want
ini	this
inilah	this is
inisiatif	initiatives	initiative
injap	valve
injil	gospel
inovasi	innovation
inovatif	innovative
input	input
insaf	realize
insan	human being	person
insiden	incident
inskripsi	inscription
inspektor	inspector
inspirasi	inspiration
institusi	institutions	institution
institusiinstitusi	institutions
institut	institute
instrumen	instrument
insulin	insulin
insuran	insurance
insurans	insurance
insurgensi	insurgensi	insurgency
insyaallah	god willing	praise the lord
intan	diamond	jewel
integrasi	integration
integriti	integrity
intelek	intellect
intelektual	intellectual
intensif	intensive
interaksi	interaction
interaktif	interactive
international	international
internet	internet
inti	core	fill material	fillings
introduction	introduction
ion	ion	iron
ip	ip
ipa	ipa
ipgm	ipgm (abbreviation)
ipoh	ipoh
ir	ir
irama	rythm	rhythm
iran	iran
iraq	iraq
ireland	ireland
iringan	accompaniment
isa	isa	jesus
isaac	isaac
isbn	isbn
ishak	isaac	ishak
ishaq	isaac	ishaq
isi	filling	contents
isipadu	volume
iskandar	iskandar
iskandariah	alexandria
iskemia	ischemic
islam	islam
islamiah	islamic
islamiyah	islamiyah
island	island
ismail	ismail	ismail ( a malay name )
isnin	monday
isotop	isotope
israel	israel
israil	israel
istana	place	palace
isteri	wife
isterinya	its wife	wife
istiadat	custom
istikharah	istikharah
istilah	term
istilahistilah	terms	sin
istimewa	special
isu	issue
isuisu	isuisu
isyak	isha
isyarat	signal
it	it
itachi	itachi
itali	italy
itik	duck
itsing	i-tsing
itu	the	that
itulah	that is	it is
ix	ix
izin	permission
izrail	angel of death
j	j
ja	ja
jaafar	jaafar
jabatan	department
jabatanjabatan	departments
jabir	jabir
jack	jack
jackson	jackson
jadi	become	became
jadikan	made
jadinya	birthday
jadual	schedules	schedule
jafar	jafar
jagaan	care
jagung	corn
jahan	jahan
jahat	evil
jahiliyah	jahiliyyah	ignorance
jahit	sew	sewing
jajahan	colony
jajahannya	colonies
jajaran	range	row
jakarta	jakarta
jakim	greatest
jalan	road
jalanan	street
jalanjalan	roads	walking
jalanraya	road
jalinan	ties
jalur	stripe
jam	hour	clock
jamak	plural
jamal	jamal
jamaluddin	jamaluddin
jamalullail	assurance
jambatan	bridge
jambi	dawn
jambu	rose apple
james	james
jamil	jamil
jaminan	guarantee
jampi	incantation	spell
jamuan	feast	reception
jan	january
janakuasa	power generation	power
janda	widow
jangan	do not	dont
janganlah	not	do not
janggut	beard
jangka	period
jangkaan	expectations
jangkamasa	duration	period
jangkitan	infection
janji	promise
jantan	male
jantina	gender
jantung	heart
januari	january
jarak	distance	length
jarang	seldom	rare
jari	finger
jarijari	rellis	finger
jaring	net
jaringan	network
jarum	needle
jasa	service
jasad	body
jasin	jasin
jasmani	physical
jata	coat of arms
jati	identity
jatuh	fall
jatuhnya	fall
jauh	far
java	java
jawa	java
jawab	answer
jawapan	answer
jawatan	position
jawatankuasa	committee
jawatannya	office
jawi	jawi
jaya	successful
jayakarta	jayakarta
jb	jb
jean	jeans
jebat	musk	jebat
jeddah	jeddah
jejak	track	trail
jejantas	flyovers	bridge
jejari	radius	fingers	radial
jelai	barley
jelapang	bowl
jelas	clear
jelata	at large
jeli	jeli	jelly
jemaah	congregation
jembal	jembal
jempol	jempol	thumb	thump
jemputan	invitation
jemu	bored
jenama	brand
jenayah	crimes	crime
jenazah	remains
jenderak	jenderak
jenderal	general
jeneral	general
jenis	type
jenisjenis	types
jentera	machinery
jentikjentik	jentikjentik
jepun	japan
jerantut	jerantut
jerat	snare
jerebu	the haze	haze	smog
jerman	german	germany
jermanik	german	germanic
jernih	clear
jersi	jersey
jerusalem	jurusalem	jerusalem
jesus	jesus
jet	jet
jeti	jetty
jewish	jewish
jibril	declare
jihad	holy war	jihad	struggle
jika	if
jikalau	if
jilid	volume	chapter
jin	genie	jim
jingga	orange
jiraiya	jiraiya
jiran	neighbour	neighbor
jirannya	neighbors	his / her neighbour	neighbors  neighbors  neighbors
jirim	matter
jisim	mass
jitra	jitra
jiwa	soul
jln	genie	road
joffri	joffri
joget	dance
johan	winner	champion
johari	johari
john	john
johns	johns
johnson	johnson
johor	johore
jolokan	prod	nickname
jong	jong	jung
jongkong	bars	bullion	chinese junk (ship)
jordan	jordan
joseph	joseph
jr	jr
jua	all
juadah	food
jual	sell	sale
jualan	sales
juara	champion
jubli	jubilee
judah	judah
judea	judea
judul	title
juga	also
jujur	honest
julai	july
julat	range
julung	first
jumaat	jumaat	friday
jumlah	amount	total
jumlahnya	amount	total
jump	jump
jumpaan	meeting	discovery
jun	june
junid	junid
junta	junta
jurang	gap
juri	jury
jurnal	journal
jurulatih	coach
jururawat	nurses	nurse
jurus	moment
jurusan	department	track
juruteknik	techinician	technicians
jurutera	engineer
juruterbang	pilot
jus	juice
jusco	jusco
just	just
justeru	hence
justice	justice or
justifikasi	justification
juta	million
jutaan	millions
jutawan	millionaire
jutsu	jutsu
k	k	la
kaabah	temple	kaaba
kaamatan	intensity	kaamatan
kabel	cable
kabinet	cabinet
kabupaten	regency
kabur	fuzzy	blur
kaca	glass
kacang	bean	nut
kacau	trouble
kacukan	hybrid
kad	card
kadang	sometimes
kadangkadang	sometimes
kadangkala	sometimes
kadar	rate
kadazandusun	kadazandusun
kadet	cadet
kadi	caddy
kaedah	method
kaedahkaedah	rules	methods
kafilah	caravan
kafir	infidel
kage	kage
kagum	impressed
kah	do	kah
kaherah	cairo
kahwin	marry	marriage
kai	kai
kain	cloth
kait	hook	correlate	related
kaitan	connection
kajang	awning
kaji	review	research
kajian	study	research
kajiankajian	study	research
kakak	sister	older sister	sister (elder)
kakashi	kakashi
kaki	foot
kakinya	his / her leg
kakitangan	staff
kakuzu	kakuzu
kala	time
kalah	lost	lose
kalam	word
kalangan	among
kalanya	sometimes
kalau	if
kalendar	calendar
kali	time	times
kalian	you
kaligrafi	kaligrafai	calligraphy
kalimah	word
kalimantan	kalimantan
kalinya	times	time
kalis	proof
kalium	potassium
kalkulator	calculator
kalkulus	calculus
kalori	calorie	calory
kalsium	calcium
kamal	kamal
kamar	chamber	room
kamaruddin	kamaruddin
kamarudin	abstract	kamarudin
kambing	goat
kamera	camera
kami	we
kamil	perfect
kamilah	ranged
kampong	village
kampung	village
kampus	campus
kamu	you
kamus	dictionary
kanada	canada
kanakkanak	kids	children
kanan	right
kanannya	right side of	right
kancah	cauldron
kandung	venter	pouch
kandungan	contents
kandungannya	contents
kandungnya	biological	contents
kangsar	hell number
kanji	starch
kanser	cancer
kanta	lens	lence
kantonis	cantonese
kanun	code
kapak	ax	axe
kapal	ship
kapalkapal	kapalkapal
kapalnya	ship
kapar	flotsam
kapas	cotton
kapasiti	capacity
kapcai	kapcai
kapilari	capillaries
kapit	clamp
kapita	capita
kapitalis	capitalist
kapitalisme	capitalism
kapitan	lieutenant
kapten	captain
kapur	lime
kara	article
karam	sink	wreck
karang	coral
karangan	essay
karbohidrat	carbohydrate
karbon	carbon
karbonat	carbonate
kardiak	cardiac
kardium	cardiac
karena	because	because the
kargo	cargo	freight
kari	curry
karib	intimate
karier	career
karim	generous
karl	karl
karotid	carotid
karsinogen	carcinogen	carcinogens
karsinoma	carcinoma
kartun	cartoon
karun	trove
karya	work
karyakarya	the works
karyanya	hsi	his work
kasar	gross
kasarnya	roughly
kasih	love
kasihan	pity
kassim	kassim
kastam	customs
kasturi	musk
kasut	shoe
kata	word
katak	frog
katakan	say
katakanlah	say
katakata	words
katakataku	my words
katanya	he / she said	he
kategori	category
kategoriahli	category of
kategoriakhbar	category: akhbar	category:news
kategorialat	category:tool
kategoribandar	city ​​category
kategoriibu	2 words: categori, mother
kategoriidentiti	catergory: identity	catoegory - identity
kategoriislam	kategoriislam
kategorikebudayaan	kategori = category, kebudayaan = cultural
kategorikelompok	category by
kategorikesihatan	kategorikesihatan
kategorikesusasteraan	kategorikesusasteraan	category: literature	literature category
kategorilogam	category:metal	category: metal
kategorimelayu	kategorimelayu
kategorimuslim	kategorimuslim
kategorinegara	category: country	category:country
kategoriorang	category of
kategoripelancongan	travel category	kategoripelancongan
kategoripendidikan	kategoripendidikan
kategoripenyanyi	kategoripenyanyi	singer category
kategoriperang	carogory:war	category : war
kategoriperayaan	festival category
kategoripermainan	kategoripermainan
kategoripolitik	political category	category: politics
kategorisains	kategorisains	category : science
kategorisejarah	category
kategorisekolah	category
kategorisistem	category system	kategorisistem
kategorisolat	category:prayer
kategorisultan	category : sultan
katholik	catholic	katholic
katod	cathode
katolik	catholic
kau	you
kaum	race	community
kaumnya	his / her community	people
kaunuhu	kaunuhu
kawah	crater
kawal	control
kawalan	control
kawan	freind	friend
kawasan	region	area
kawasankawasan	regions	areas
kawi	kawi
kay	kay
kaya	rich
kayangan	heaven
kayu	wood
kdnk	gdp
ke	to
keadaan	condition
keadaankeadaan	conditions
keadaannya	it	its situation
keadilan	justice
keagamaan	of religious	religious
keagungan	greatness
keahlian	membership	expertise
keajaiban	miracle
keamanan	security	peace
keanggotaan	membership
kearah	towards	to the direction
keat	keat
keatas	on	to
kebahagiaan	happiness
kebahagian	bliss	happiness
kebaikan	benefit	virtues	goodness
kebajikan	god	charity
kebakaran	fire
kebal	immune	insusceptible	impervious
kebanggaan	pride
kebangkitan	revival
kebangsaan	national
kebanyakan	most	mostly	majority
kebanyakannya	moslty	mostly
kebanyakkan	most
kebarangkalian	probability
kebaya	javanese blouse
kebebasan	freedom
kebelakangan	recently	last
kebenaran	truth
kebencian	hatred	hate
kebenuaan	continental
keberanian	courage	bravery
keberkatan	blessing
keberkesanan	effectiveness
kebersihan	cleanliness	hygiene
kebesaran	grand	greatness
kebetulan	accident
kebiasaan	habit
kebiasaannya	usually
kebijaksanaan	wisdom
kebimbangan	fear	worry	worried
kebolehan	capability	ability
kebolehannya	ability
kebudayaan	culture
kebuluran	starvation	hunger
kebun	garden
keburukan	bad	disadvantages
kecacatan	defects
kecaman	criticism
kecantikan	beauty
kecederaan	injury
kecekapan	proficiency	efficiency
kecelakaan	disaster	mishap
kecemasan	emergency
kecemerlangan	excellence
kecenderungan	tendency
kecepatan	speed
kecerdasan	intelligence
kecergasan	intelligence	fitness
kecil	small
kecilkecil	small	small small
kecilkecilan	small	small-scale
kecuaian	negligence
kecuali	except
kecurian	theft
kedah	kedah
kedai	shop
kedaikedai	shops	kedaikedai
kedalam	in to	into
kedamaian	residence	peace
kedatangan	arrival
kedaulatan	sovereignty
kedengaran	heard	be heard
kediaman	residence
kedoktoran	doctoral	doctorate
kedua	second
keduadua	both
keduaduanya	both
keduanya	both	second
kedudukan	position
kedudukannya	position
kedutaan	embassy
keemasan	golden
keempat	fourth
keempatempat	the four
keenam	sixth
keengganan	refusal	reluctance
kefahaman	understanding
kegagalan	failure
keganasan	terrorism	violence
kegelapan	darkness
kegemaran	favorite
kegemilangan	glory
kegemilangannya	glory
kegiatan	activity
kegiatankegiatan	kegiatankegiatan	activities
keguguran	miscarriage
kegunaan	function	use
kegunaannya	use
keguruan	teaching
kehadiran	attendance / presence	presence
kehakiman	judiciary
kehamilan	pregnancy
kehancuran	ruin	destruction
keharmonian	harmony
kehebatan	intensity	greatness
kehendak	will	wants
kehidupan	life
kehidupannya	life
kehijauan	greenness
kehilangan	loss
kehormat	honour
kehormatan	honor
keimanan	faith
keindahan	beauty
keinginan	desire
keistimewaan	privileges	speciality
keiv	keiv
keizinan	permission
kejadian	incident	occurrence
kejahatan	evil
kejahatannya	badness	evil
kejam	cruel
kejatuhan	the fall	fall
kejayaan	victories	success
kejayaannya	the victory	achievement
keji	despicable
kejohanan	tournament
keju	cheese
kejuaraan	championship	title
kejururawatan	nursing
kejuruteraan	engineering
kejutan	shock
kek	cake
kekacauan	disturbance	riot
kekadang	sometimes
kekadangnya	occasionally	sometimes
kekal	permanent
kekalahan	the defeat	defeat
kekasih	lover
kekayaan	wealth
kekebalan	immunity
kekecewaan	frustration
kekejaman	violence
kekejangan	cramp	spasm
kekeliruan	confusion
kekeluargaan	family	kinship
kekerapan	frequency
kekerasan	violence	tough
kekisi	lattice	structure
kekonduksian	conductivity
kekosongan	vacancy	void	emptiness
kekuasaan	power
kekuasaannya	power
kekuatan	strength
kekuatannya	strength
kekunci	key
kekurangan	lack
kelab	club
kelabu	gray	grey
keladi	keladi	taro
kelahiran	birth of	birth
kelainan	difference	variation	a difference
kelajuan	pace	speed
kelak	later
kelakuan	action	behaviour
kelambu	valance
kelamin	genitals	sex
kelana	rover
kelang	klang
kelantan	hymn	kelantan
kelapa	coconut
kelapan	eighth
kelaparan	hunger
kelas	class
kelayakan	eligibility	qualifications	qualification
keldai	ass	donkey
kelebihan	advantage	excess
kelebihannya	advantages	advantage
kelemahan	weakness
kelembapan	humidity	moistness	slowdown
kelengkapan	completeness
kelenjar	gland
kelentit	clitoris
kelenturan	flexibility	moudability
keletihan	fatigue
keli	catfish
kelihatan	look
kelihatannya	seem	looks like	appear
kelima	fifth
kelimalima	all five	five
keling	rivet	tamilan
kelisa	arowana	kelisa
kelompok	group
kelompokkelompok	batches	groups
kelopak	petal	sheath
keluar	quit	in this sentance "keluar" means leaves, however it also means out
keluaran	output	gain or outpur
keluarga	family
keluargakeluarga	keluargakeluarga	families
keluarganya	his / her family	family
keluarnya	discharge	out came	to come out
keluasan	wide	area	vastness	width	area(width)	broadness
keluhuran	majesty
keluli	steel
kelulusan	qualify	pass
kem	camp
kemahiran	skills
kemahuan	desire
kemajuan	progress
kemakmuran	meaning the house of prosperity under a mountain lake
kemalangan	accident
kemaluan	genitals
kemaman	immature
kemampuan	ability
kemampuannya	ability
kemangkatan	death
kemanusiaan	humanitarian	human
kemaraan	progress
kemarahan	anger
kemarau	dry	drought	draughter
kemas	tidy	neat
kemasukan	entry
kemasyarakatan	social
kematangan	maturity	matured
kematian	death
kematiannya	death
kembali	return	back
kembalinya	return of	return
kembang	breed	bloom	flower
kembar	twin
kembara	travel	adventure
kemboja	cambodia flower	frangipani	kemboja
kemegahan	splendour	grandeur	splendor
kemelesetan	recession	depreciating
kemenangan	victory
kementerian	ministry
kemenyan	incense
kemerahan	redness
kemerdekaan	the independence	independance	independence
kemerosotan	decline
kemewahan	luxury
kemisikinan	poverty
kemiskinan	poverty
kemodenan	modernity	kemodanan
kemoterapi	chemotherapy	kemo therapy
kempen	campaign
kempenkempen	campaigns	campaign
kemudahan	facility
kemudahankemudahan	facilities
kemudi	rudder
kemudian	then
kemudiannya	then	later
kemuliaan	honour	dignity
kemuncak	peak
kemuncaknya	climax
kemunculan	emergence
kemungkaran	sins / vices	disobey	vices
kemungkinan	probably	possibility	possibly
kemungkinannya	probabilities	probably
kemuning	kemuning	yellow
kemurungan	depression
kemusnahan	destruction
ken	ken
kena	be	hit	fit
kenabian	prophethood
kenal	wrong	know
kenali	know
kenangan	memories	memory
kenapa	why
kencang	strong
kencing	pee	urine
kenderaan	vehicles	vehicle
kendiri	self
kenduri	party	feast
kenegaraan	nationhood
kenichi	kenichi
kenikmatan	pleasure
keningau	keningau
kenneth	kenneth
kental	thick	tough
kentang	potato
kenya	kenya
kenyalang	hornbill
kenyataan	statement	reality
kepada	to	to / for
kepadaku	to	to me	for me
kepadamu	to you
kepadanya	to
kepadatan	density
kepakaran	expertise
kepala	head
kepalanya	his / her head	the head
kepandaian	skill	know-how
kepang	kepang
kepekatan	concentration
kepelbagaian	diversity	variety
kepemilikan	ownership	ownage
kependudukan	population
kepentingan	interests	interest
kepercayaan	trust	kapercayaan
keperibadian	personality
keperluan	need	requirement
kepesatan	momentum
kepimpinan	leadership
kepingan	pieces
kepintaran	intelligence	ingenuity
kepong	kepong
kepuasan	satisfaction
kepulauan	archipelago
kepungan	siege
kepunyaan	belong	belonging to
keputeraan	novel birthday	birthday
keputusan	decision
kera	monkey
kerabat	relatives
keracunan	poisoning
keradangan	symtoms	rashes	inflammation
kerajaan	kingdom
kerajaankerajaan	governments
kerajaannya	government
kerak	crust
kerakyatan	citizenship
keramaian	festivity	crowd
keramat	sacred
kerana	because
kerangka	framework
keranjang	basket
kerap	often
kerapu	grouper
keras	hard
kerat	cut	part
keratan	section	cutting
kerbau	buffalo	bull
kerdil	dwarf
kerelaan	willingness
kereta	car
keretapi	train
kerian	kerian
kering	dry
keris	knife	kris
kerja	work
kerjakan	do	work
kerjakerja	works
kerjanya	his	his work
kerjasama	cooperation
kerjaya	career
kerjayanya	career	his career
kernel	kernal
keroh	confusing
kerohanian	spirituality
kerosakan	damage	destruction
kertas	paper
kerugian	loss
keruh	murky	cloudy
kerumitan	complexity
keruntuhan	collapse
kerusi	chair
kes	case
kesabaran	patience
kesahan	legality
kesahihan	validity
kesakitan	pain
kesalahan	offence	offense
kesamaan	similarity
kesan	effect
kesanggupan	willingness
kesangsian	doubt	doubts
kesankesan	effects in
kesannya	the effect
kesatria	knight
kesatuan	unity
kesedaran	awareness
kesedihan	sadness
keseimbangan	balance
kesejahteraan	prosperity	wellbeing	well being
keseksualan	sexuality
keselamatan	security
keseluruh	the whole	all of
keseluruhan	whole
keseluruhannya	overall
kesembilan	nineteenth	ninth
kesempatan	opportunity
kesempurnaan	perfection
kesemua	all
kesemuanya	all
kesenangan	convenience	ease
kesengsaraan	misery
kesenian	art
kesepuluh	tenth
keseronokan	fun
kesesakan	crowding
kesesuaian	suitability	topics that have been set or designated as appropriate filling
kesetiaan	loyalty
keshogunan	shogunate
kesihatan	health
kesilapan	error
kesimpulan	conclusion
kesinambungan	continuity
keskes	cases
kesopanan	courtesy
kestabilan	stability
kesuburan	fertility
kesucian	purity
kesukanan	sportsmanship
kesukaran	difficulty
kesulitan	difficulty
kesultanan	sultanate
kesusahan	difficulty
kesusasteraan	literature
kesusilaan	morality
kesyukuran	thanks
ketagihan	addiction
ketahanan	endurance
ketahui	know
ketahuilah	know
ketakutan	fear
ketam	crabs	crab
ketangkasan	ketangakasan	agility
ketara	significant
ketat	strict
ketawa	laugh
ketegangan	tension
ketenangan	serenity
ketenteraan	military
ketenteraman	ease	order
ketentuan	certainty	provision
ketepatan	accuracy
keterangan	explanation	evidence
keterlaluan	extreme
ketetapan	resolution
ketiadaan	absence
ketiak	armpit
ketibaan	arrival
ketidak	lack of
ketidakseimbangan	imbalance
ketidakstabilan	instability	not stable
ketiga	third
ketigatiga	the three	three
ketika	when
ketinggalan	be left behind	left behind
ketinggian	height
ketua	chief
ketuaketua	the heads	ketuaketua
ketuanan	supremacy
ketuhanan	divinity
ketujuh	seventh
ketulan	lumps	hit	pieces
ketumbuhan	growth
ketumpatan	density
ketupat	delicacy made from glutinous rice
keturunan	descent
keturunannya	lineage	descendants
keunggulan	supremacy	excellence
keunikan	uniqueness
keuntungan	profit
keupayaan	capability	ability
keusahawanan	entrepreneurship
keutamaan	priority
kewafatan	death
kewajiban	liability	obligation / duty	obligation
kewajipan	obligations
kewangan	financial
kewarganegaraan	citizenship
kewibawaan	integriti	authority
kewujudan	the existence	existence
kewujudannya	existence	its existence
key	key
keyakinan	confidence
keyunanian	hellenistic
kezaliman	tyranny
khabar	news papers	newspapers
khadijah	khadijah
khafre	khafre
khairul	khairul
khalayak	public	crowd
khaldun	khaldun
khalid	khalid
khalifah	caliph
khan	khan
khas	typical
khasiat	nutrition
khasnya	particularly	specifically
khat	line
khatan	circumcision
khatib	preacher
khatulistiwa	equator
khayalan	fantasy	hallucination
khazanah	treasure
khidmat	service
khilafah	caliphate
khulafa	caliph	rightly
khusus	specific	specialize	special
khususnya	particularly
khutbah	sermons
ki	ki
kiamat	doomsday	resurrection
kian	growing
kiblat	qiblah
kijang	deer
kilang	factory
kilangkilang	factories
kilat	flash
kilau	scintillation
killer	killer
kilometer	kilometre
kim	kim
kimia	chemistry	chemist
kimpalan	weld	welding
kinabalu	kinabalu
kincir	reel
kingdom	kingdom
kini	now
kinrara	kinrara
kipas	fan
kira	about
kiraan	count
kirakira	about
kiri	left
kirinya	to his/her left	left
kisah	story
kisahkisah	stories
kisame	kisame
kit	kit
kita	we
kitab	book	holy book
kitabkitab	books	bibles
kitar	cycle
kitaran	cycle
kk	kk
kl	kl
klan	clan	clans
klasifikasi	classification
klasik	classical
klasikal	classical
klcc	klcc
klia	klia
klian	klian
klien	client
klik	click
klinik	clinic
klinikal	clinical
klon	clone
klorida	chloride
klorin	chlorine
kluang	centre
kluster	cluster
km	km
km²	km2
known	known
kocek	pocket	poket
kod	code
kognitif	kongnitif	cognitive
koh	jambi
kok	kok	shuttlecock	shuttlecork
koksidia	cocci	koksidia	coccidia
kokurikulum	cocurriculum	curriculum
kolam	pool
kolej	college
kolejkolej	kolejkolej
koleksi	collection
kolektif	collective	collection
kolesterol	cholestrol
kolonel	colonel	cononel
koloni	colony
kolonial	colonial
koma	coma
koma-koma	safron	saffron
komander	commander
komando	command	commando
komanwel	commonwealth
kombinasi	combination
komedi	comedy
komersial	commercial
komersil	commercial
komik	comic
komisioner	commissioner
komitmen	commitment
komoditi	commodity
kompang	kompang
kompas	compass
kompeni	company
kompleks	complex
komplikasi	complication
komponen	component
komponenkomponen	components
komposisi	composition
komprehensif	comprehensive
komputer	computer
komputerkomputer	computers	komputerkomputer
komunikasi	communication
komunis	communist
komunisme	communism
komuniti	community
komuter	commuter
kon	cone
konan	konan
kondom	condom
kondominium	condominium
kondusif	conducive
konflik	conflict	konfilk
konfrontasi	confrontasion	confrontation
konfusianisme	confucianism
kong	kong
kongres	congress
kongsi	partnership	share
kong m ft	m ft kong
konkrit	concrete
kononnya	so-called	apparently
konsep	concept
konsepkonsep	concepts
konsert	concert
konservatif	conservative
konsesi	concession
konsisten	consistent	consistence
konsonan	consonant
konteks	context
kontemporari	contemporary
kontinjen	contingent
kontrak	contract
kontroversi	controversy
kontrovesi	controversy
konvensional	conventional
konvensyen	convention
konvoi	convoy
koperal	corporal
koperasi	cooperative
koperat	corporate
kopi	coffee
kopra	copra	kopra	olive
kor	corp	corps
korban	sacrifice	qurban
korea	korea
koridor	corridor
korion	chorionic
koronari	coronary
korporat	corporate
korpus	corpus
kos	cost
kosa	screening
kosmetik	cosmetics	cosmetic
kosmo	kosmo
kosong	empty
kostum	costume
kota	town	city
kotak	box
kotakota	the cities	cities	kotakota
kotanya	his city
kotor	dirty
kovalen	covalent
koyak	torn
kpm	kpm
kraftangan	handicraft	crafts
krai	crayfish
kreatif	creative
kredit	credit
kriket	cricket
krim	cream
kriptografi	cryptographic	criptographic	cyrptographic	cryptography
kripton	krypton
krishna	krishna
krisis	crisis
krismas	christmas
kristal	crystal
kristen	christian
kristian	christian
kristus	christ
kriteria	criteria
kritikal	critical
kritikan	criticism	critics	critique	criticsm
kritis	critical
kromosom	chromosome
kronik	chronic
kronologi	chronology
kt	kt
ktm	ktm
ktmb	ktmb
ku	i
kuah	gravy	sauce
kuala	estuary
kualiti	quality
kuan	kuan
kuantan	kuantan is a state/town in malaysia
kuantitatif	quantitative
kuantiti	quantity
kuantum	quantum
kuasa	power
kuasakuasa	powers
kuasanya	its	his /  her power
kuat	strong
kubah	dome
kubang	wallow	kubang
kubu	fortress
kubur	grave
kubus	cube	cubic
kuching	kuching
kucing	cat
kuda	horse
kudin	knitting
kudus	holy
kufah	kufa
kufu	kufu
kuih	cake	dessert
kuil	temple
kuilkuil	temples	temple
kuku	nail
kukuh	strong	sturdy
kulai	kulai
kulat	fungus
kulim	kulim
kulit	skin
kulup	foreskin
kuman	germ
kumbang	bug	beetle
kumpulan	group	team
kumpulankumpulan	groups
kunci	key
kundang	kundang
kuning	yellow
kunjungan	visit	kujungan
kuno	ancient
kuntau	kuntau
kunyit	ginger	turmeric
kuomintang	kuomintang
kuota	quota
kuprum	copper
kupukupu	butterfly
kurakura	kurakura	turtle
kurang	less
kurangnya	least	less
kurikulum	curriculum
kursus	courses
kursuskursus	courses
kurun	century
kurung	parenthesis
kurungan	cage	brackets
kurus	thin
kusta	leprosy
kutipan	quote	collection
kutu	flea	louse
kutub	pole
kutukan	condemnation
kwsp	epf
kyubi	kyubi
l	l
labah-labah	profit	spider
laboratory	laboratory
labu	squash
labuan	labuan (location)	labuan
lada	pepper
ladang	field
ladangladang	ladangladang	farms	the farm
ladu	dumplings
lafaz	proclamation	pronounce	pronouncement
lagenda	legend
lagi	more
lagipun	moreover	eventhough
lagu	song
lagulagu	the songs
lah	is
lahad	'lahad datu" name of a place	lahad	grave
lahir	born	birth
lahirlah	born
lahirnya	inception	born
lai	lai	singapore
lain	other
lainlain	the other	others
lainnya	other
laju	"laju" means fast/speed	fast
lakilaki	boys	men
lakonan	act / portrayal	acting
laksamana	admiral
laksana	like
laku	behavior
lakukan	do
lalang	weeds
lalat	fly
lalu	past	and then	last
laluan	route	way
laluannya	path	passage
lalulintas	traffic
lam	lam
lama	long
lamakelamaan	lamakelamaan
laman	site
lamanlaman	lamanlaman	web site	sites
lamanya	ever	so long
lambang	symbol
lambat	slow
lampau	past
lampu	light	lamp
lampulampu	light	lampulampu
lanas	lanas
lanca	rickshaw	pullcart	lanca	rickshaws
lancar	smooth
land	land
landak	porcupine	pocupine
landasan	track
lang	lang	kites
langat	langat
langganan	subscriptions
langgar	hit	collide
langit	sky
langkah	step
langkahlangkah	measures
langkasuka	langkasuka
langsung	direct
language	language
lanjut	further	more
lanjutan	extension
lanka	lanka
lantai	floor
lantaran	because
lantas	thus
lanun	pirate
lanunlanun	lanunlanun
laos	galingale
lapan	eight
lapang	free
lapangan	field
lapis	layer
lapisan	layer
laporan	report
lara	ill
larang	restrict	restrictions
larangan	prohibition
lari	run
larian	running	run
laris	selling	high demand
larut	late	soluble
larutan	solution
lasak	robust	rough
laser	laser
lata	cascade
latar	background
lateks	latex
later	later
latihan	training
latin	latin
latitud	latitude
laut	sea	ocean
lautan	ocean
lava	lava
law	law
lawan	against	opponent
lawatan	visit
lawrence	lawrence
laws	laws
layak	deserve	qualify	fit
layanan	service
layanglayang	kite
layar	screen
layu	withered
lazat	delicious
lazim	common
lazimnya	habitually
lcct	lcct
league	league
lebah	bee
lebar	width
lebat	heavy	torrential	strong
lebih	more
lebihan	surplus	more
lebihlebih	lebihlebih
lebuh	highway
lebuhraya	highway
lebur	melting	melt
ledakan	explosion
ledang	ledang
leftenan	lieutenant
legenda	legend
leher	neck
lekas	hurry	quickly
lekukan	groove	indentation
lela	jaunty
lelah	exhaustion
lelaki	man
leluhur	ancestor
lemah	weak
lemak	fat
lemas	drowning	drowned
lembaga	institution
lembah	valley
lembangan	basin
lembap	wet
lembing	spear
lembu	cattle
lembut	soft
lencana	badge
lengan	arms	arm
lengkap	lslamic	complete
lenyap	vanish
leong	leong
lepas	release	last
lepasan	post
leper	flat
lereng	slope
les	les
lesbian	lesbian
lesen	license	licence
lestari	sustainable
leste	leste
lesu	lethargic
lesung	mortar
letak	park
letaknya	location	stand
letih	exhausted	tired
letupan	explosion
letusan	eruption
leukemia	white blood	leukemia
level	level
lewat	late	by
lewis	lewis
li	span	li
lian	lian
liang	hole
liar	wild
liat	clayey	tough
liberalisme	liberalism
liberty	liberty
library	library
libya	libya
licin	slippery / smooth	smooth
lidah	tongue
lidi	stick
lif	lift	elevator
life	life
liga	league
light	light
lihat	see	look
likat	viscous
lilin	wax
lilitan	winding	coil
lima	five
limau	lime
limfa	lymph
limited	limited
lin	lin
lincah	agile	nippy
lincoln	lincoln
line	line
linear	linear
ling	in petaling
lingga	phallus	lingga
lingkaran	circle	perimiter
lingkungan	environment
lingua	tongue	lingua (franca)
linguistik	linguistic
lintah	leech
lintang	latitude
lintas	traffic
linux	linux
lipatan	folds	folding	fold
lipis	lipis	seam
lipur	comfort	consolation
liputan	coverage
lirik	lyrics
lisan	oral
list	list
litar	circuit
liur	saliva
liut	leathery
liwat	sodomy
lo	lo
lobus	lobe
local	local
lock	lock
lockhart	lockhart
lockheed	the lockheed	lockheed
log	log
logam	metal
logamlogam	metal	metals
loghat	dialect
logik	logic
logistik	logistics
logo	logo
lohong	vent	volcanic vent
loji	plant
lokasi	location
lokasinya	its location
lombong	mine
lompat	jump
lompatan	jump
london	london
long	long
longgar	loose
lontar	throw
lontaran	throw
lord	lord
lorong	lane
loseng	loseng
lost	lost
lot	lots	lot
lotud	name of flower
louis	louis
low	low
loy	loy
lrt	lrt
ltd	ltd
luak	badger
luar	outside	out
luaran	outside
luarbiasa	extraordinary	unusual
luarnya	luarnya	outer	exterior
luas	wide
luasnya	broadness	area
lubang	hole
lubnan	lebanon
lubok	lubok
lucah	porn
luka	wound
lukis	draw
lukisan	painting	drawing
lukut	boro
lulus	pass
lulusan	graduate
lumayan	fair to middling	superflous	lucrative
lumba	race
lumpur	mud
lumuran	smear	spread
lumut	moss
lupa	forget
lupin	lupin
luput	lapse
luruh	autumn	drop
lurus	straight
lut	transparent	lot
luth	luth	lot
lutsinar	transparent
lutut	knee
lymph	lymph
lymphoma	limfoma
m	m
ma	ma
maaf	forgive	maff
maahad	maahad
mabuk	drunk
mac	march
macam	how
macgillivray	macgillivra
machang	machang
machine	machine
mad	mad	rank
madagascar	madagascar
madara	madara
madinah	madinah	medina
madrasah	religious school	college
madu	honey
madya	medium	vice/assistant
magelang	magelang
maghrib	dusk
maghribi	morocco
magma	magma	the magma
magnesium	magnesium
magnet	magnetic
magnetik	magnetik	magnetic
maha	great
mahal	expensive
mahar	dowry
maharaja	emperor
maharani	empress
mahathir	mahathir
mahawangsa	mahawangsa
mahayana	mahayana
mahdi	mahdi
mahir	skillful	proficient
mahkamah	court
mahkamahmahkamah	the courts
mahkota	crown
mahmud	praised
mahu	to	want
mahukan	want
mahupun	or
main	play
mainan	toy
majah	majah
majalah	magazine
majapahit	majapahit
majid	majid
majikan	employer
majistret	majistrate	magistrate
majlis	ceremony	the
majlismajlis	councils	council
majmuk	compound
majoriti	majority
maju	advanced
mak	mother
maka	then
makalah	article
makam	tomb	tomb / mausoleum
makan	eat
makanan	food
makassar	makassar
makhluk	being	creature
makin	increasingly	more
makkah	mecca	islamic
maklumat	information
makmal	laboratory	lab
makmur	prosperous	peaceful
makna	meaning
maknanya	means
makroekonomi	macroeconomics	macroeconomy	macro economic	makroekonami	mecroeconomic	macro economy	macroeconomic	macro-economy	microeconomic
maksiat	vice
maksima	the maximum	maximum
maksimum	maximum
maksud	meaning	purpose
maksudnya	meaning
maktab	college
mal	mail	mal
malah	even
malahan	instead
malaikat	angel
malam	night / evening	night
malang	unlucky
malangnya	unfortunately
malapetaka	disaster
malas	lazy
malay	states name
malaya	malaya
malayan	malayan
malaysia	malaysia	filipinas
maldives	maldives
malek	malek
malfoy	malfoy
malignant	malignant
malik	owner	king	malik
maliki	maliki
malim	malim	pilot
malu	shame
maluku	maluku	moluccas
mamalia	mammals
mammografi	mammography
mampu	afford	able
man	man
mana	where
management	management
manakah	is	where
manakala	while
manamana	any
manchester	manchester
manchu	manchurian
manchuria	manchuria
mandarin	mandarin
mandat	mandates	mandate
mandi	bath
manfaat	benefit	benefits
manga	cartoons
mangan	manganese
mangga	mango
mangkat	died
mangku	mangku
mangkuk	bowl
mangsa	victim
manhattan	manhattan
mani	sperm
manik	beads
manila	manila
manis	sweet
manja	affectionate	spoiled
manjung	manjung
mansor	mansor
mansur	mansur
mantan	former
mantap	steady
mantera	incantation	spell
manual	manual
manusia	human
manuskrip	manuscript
mao	mao
mara	relatives	danger
marah	angry
maran	tions
marhalah	arabic unit of measurement	marhalah
mari	let	here
maria	maria
mariam	mariam
marikh	mars
marin	marine
marina	marina
maritim	maritime
markah	marks
markas	headquarters
marmar	marble
marshall	marshall
martabat	dignity
martin	martin
maruah	dignity
marx	marx
marxisme	marxism
mary	mary
maryam	maryam
mas	gold
masa	time
masaalah	problem
masak	cook	cooked
masakan	food	cooking
masalah	problem
masalahmasalah	problems	the problems
masamasa	times
masanya	time
masih	still
masihi	ad
masin	salty
masingmasing	respectively	each other
masjid	mosque
masjidil	mosque
masjidmasjid	mosques
massa	mass (mass media)	mass
master	master
masters	masters
mastika	mastika
masturbation	masturbation
masuk	entry	enter
masukkan	to put in	enter
masyarakat	society	community
masyarakatmasyarakat	people
masyarakatnya	community
masyhur	famous
mata	eye
matahari	sun
matamata	spy	eye
matang	mature
matanya	his eyes
matapelajaran	subjects	subject
mataram	mataram
matawang	currency
matematik	mathematics
material	material
mathematics	mathematics
mati	death
matlamat	goals	goal
matrikulasi	matriculation
matthews	matthews
maulidur	maulidur
maupun	as well as	or
maut	death
mawar	rose
max	max
maxwell	maxwell
may	may
maya	virtual
mayang	inflorescences
mayat	body	dead body
mayatnya	his body was
maybank	maybank
mazhab	sect
mcdonnell	mcdonnell	macdonnell ranges
me	me
medan	field
media	media
medical	medical
medieval	medievel
mediterranean	mediterranean
medium	medium
mee	mee	noodles
mega	cloud
megah	majestic
megat	megat
mei	may
meiji	meiji	renewal
meja	table
mejar	major (military rank)
mekah	mecca
mekanik	mechanics
mekanikal	mechanical
mekanisme	mechanism
mekong	mekong
mel	mail
melabur	invest
melafazkan	pronounced
melahirkan	express
melainkan	except for	but
melaka	malacca
melaksanakan	implement	implemented
melakukan	do
melalui	through
melambangkan	symbolise	represent
melambatkan	delay	slowed
melampau	extreme
melampaui	exceed	exceeding
melanau	melanau	melanaus
melancap	masturbation
melancarkan	launched
melanda	hit	engulf
melanggar	violate
melangkah	step
melanjutkan	furthered	continue	extend
melantik	appoint	appointed
melaporkan	report	reported
melarang	prohibit
melarat	destitute
melarikan	run	fled	escape
melatar	backed up with
melatih	train
melawan	fight back
melawat	visit
melayan	treat
melayang	fly	flown
melayari	navigate	surfing	visit
melayu	malay
melbourne	melbourne
melebihi	exceed
melekat	sticking	stick
melemahkan	weaken
melempar	throw
melengkapi	fulfill	to complete
melengkapkan	completing	complete
melengkung	curve
melepasi	beyond	across
melepaskan	release
meletak	placed	placing
meletakkan	put
meletup	explode	exploded
meletupkan	blow up
meletus	erupt
melewar	melewar
melewatkan	delay	skip
melibatkan	involve
melihat	see
melihatkan	meihatkan	see
melihatnya	seen	view
melilit	looping	wind
melimpah	overflow
melindungi	protecting	protect
melintang	horizontal	across	transverse
melintasi	crossing	cross
meliputi	covered	cover
melompat	jump	jumping
melonjak	jumped	surge
melontar	throw
meluas	widespread
meluaskan	expand
melucutkan	deprive
melukis	paint
meluluskan	passed	pass
melumpuhkan	disable
melupakan	forget
memacu	spur	drive
memadai	adequate	adeqaute
memahami	understand
memainkan	play	played
memajukan	advance	develop
memakai	use / wear	use
memakan	consume
memaklumkan	advice	informed
memaksa	force
memaksudkan	mean
memali	memali
memalukan	embarrassing
memanaskan	heat up
memancarkan	exude	emit
memandang	view
memandangkan	as
memandu	drive	driving
memanfaatkan	beneficial	harness
memanggil	call	called
memanggilnya	call
memanjang	lengthwise
memanjangkan	prolong	extend
memanjat	climbing
memansuhkan	abrogate
memantapkan	strengthen	strenthen
memantau	monitor
memaparkan	display
memasak	cook	cooking
memasang	install
memasarkan	marketing	market
memastikan	ensure
memasuki	enter
memasukkan	insert
mematahkan	break
mematikan	to kill	turn off
mematuhi	obeyed	comply with the
membabitkan	involve	involving	involves
membaca	read	reading
membacakan	read	reads
membahagi	divided	divide
membahagibahagikan	dividing
membahagikan	divide
membahayakan	endanger
membaiki	repair	repaired
membakar	burn	burning
membalas	reply
membaling	throwing
membandingkan	comparese	compare
membanggakan	proud	make proud	boast
membangkitkan	awaken	raise
membangun	develop
membangunkan	build
membantah	disagree	dispute
membanteras	regulate	combat
membantu	help
membantunya	assisted	help
membasmi	eradicate
membasuh	wash	washing
membatalkan	cancel
membawa	brought	brings	carry
membawanya	brought	take
membayangkan	imagine
membayar	pay
membebaskan	release	liberate
membekalkan	supply
membela	defend
membelah	chop	split
membelajari	learned to
membelanjakan	spend
membeli	buy	buying
membelibelah	shopping
membenarkan	authorize	permitted
membenarkannya	allow
membenci	hate	hates
membendung	control	to prevent
membentuk	form
membentukkan	form
memberi	give
memberikan	give
memberikannya	give
memberitahu	notify
memberontak	revolt	rebel
membersihkan	clean up	cleaning
membesar	grow up
membesarkan	enlarge	raise
membetulkan	to correct / rectify	correct
membezakan	differentiate
membiak	multiply
membiarkan	let	allowed
membiayai	fund
membicarakan	speak about	discussed
membimbing	worries	guiding
membina	build
membinasakan	destroy
membincangkan	discuss
membolehkan	enable
membolehkannya	enable
membran	membrane
membuang	waste
membuat	make
membuatkan	makes
membubarkan	dissolve
membuka	open
membuktikan	prove
membuli	bullying
membunuh	killing	to kill	slay
membunuhnya	kill
memburu	hunt	hunting
memburukkan	worsen
memecah	break
memecahkan	break
memecat	fire	fired
memegang	holding
memelihara	preserve
memeluk	hug / join
memenangi	win	won
mementingkan	concerned
memenuhi	fulfill	meet
memerangi	fight against
memerangkap	trap
memerhati	observe	watch
memerhatikan	observed	observing
memerihalkan	describing
memeriksa	checked	check
memerintah	rule
memerintahkan	order
memerlukan	need
memeterai	entered into
memetik	quote	cited
memihak	to side with	side
memikirkan	think	thinks
memikul	assume	bear
memilih	chose	choose
memiliki	have
memimpin	lead
meminang	propose
meminati	interested in
meminda	amend
memindahkan	transfer
meminjam	borrow  borrow	borrow
meminta	request
meminum	drinking	drink
memisahkan	separate
memohon	request
memorandum	memorandum
memori	memory
memorial	memorial
memory	memory
memotong	chop, cutting short	cutting	cut
mempamerkan	exhibit
mempelajari	learn
mempelbagaikan	diversify	diversify / expand
mempengaruhi	influence
memperbaiki	repair	improve
mempercayai	believe
mempercepatkan	accelerate
memperdebatkan	argue	debate
mempergunakan	use
memperingati	commemorate
memperjuangkan	fight for	champion
memperkatakan	deal
memperkenalkan	memberkenalkan	introduce
memperkenankan	introducing	approve
memperkukuhkan	strengthen
memperlihatkan	show
memperluas	expand
memperluaskan	expand
memperoleh	acquire	gain	get
memperolehi	obtained	had
mempersembahkan	present
mempersoalkan	be questioned
mempertahankan	defend	defending
mempertikaikan	argue	dispute
mempertimbangkan	consider
mempertingkatkan	improve
memperuntukkan	allocate	provides
mempromosikan	promote	promoting
memproses	process	memproses	processing
mempunyai	has	have
memuat	take
memuatkan	load	loaded	filled with
memudahkan	simplify	facilitate	make easier
memudaratkan	harmful
memuja	worshipping
memuji	praised	praise
memujuk	convince	persuaded
memukul	hit	hiting
memulakan	start
memulihkan	restore
memuncak	peaked
memunculkan	appear	show
memungkinkan	made possible	allows
memungut	collect
memupuk	encourage	inculcate
memusnahkan	destroyed	destroy
memutuskan	decided
menafikan	denied
menahan	hold
menaik	increase	upward
menaiki	take
menaikkan	up
menakjubkan	spectacular
menakluk	conquer
menakluki	conquer
menakutkan	scary	scare
menamakan	named	name
menamatkan	completed	end
menambah	add	to add / increase
menambahkan	increase	add	increasing
menampakkan	reveal
menampilkan	show
menampung	accommodate
menanam	plant
menandatangani	sign (signature)	sign
menang	win	won
menangani	handle
menanggung	menanggund	bear
menangis	cry	crying
menangkap	catch	arrest	to catch
menanti	waiting
menantu	son / daughter-in-law	law
menapis	censored
menara	tower	stamping
menari	dance
menarik	interesting
menaruh	put
menasihati	advise	advice
menawan	capture
menawarkan	providing	offer
mencabar	challenging	challenged
mencabuli	violate
mencabut	take
mencadangkan	suggested	propose
mencakupi	mencakupui	account
mencampuri	interfere
mencapai	achieve	achieved
mencari	search
mencatat	record
mencatatkan	record	recorded
mencecah	reached
mencederakan	injured
mencegah	prevent
menceraikan	divorce
menceritakan	tell
mencerminkan	reflect
menceroboh	trespassing
mencetus	trigger	triggered	erupts
mencetuskan	trigger
mencipta	create	created
menciptakan	invented	indite
mencirikan	characterize
mencontohi	emulate
mencuba	try	tried
mencuci	wash
mencukupi	sufficient
mencuri	steal	stealing
mendadak	sudden
mendaftar	mendafter	sign up
mendahului	precede	pass
mendakan	precipitate
mendaki	climbed
mendakwa	claim	accused
mendalam	"dengan mendalam" more indepth	deep	indepth
mendapan	sediment
mendapat	obtained	get
mendapati	have
mendapatkan	to obtain	get
mendarat	landed
mendatar	horizontal
mendedahkan	revealed
mendekati	approach
mendekatkan	get closer	juxtapose
mendengar	mendergar	hear
menderita	suffering	suffer
mendesak	urgent	insist
mendiami	live
mendidik	educate
mendirikan	establish
mendokong	support
mendominasi	dominate
mendorong	encourage
menduduki	occupying	sit
mendukung	support
menegak	upright	straighten	vertical
menegakkan	erect
menegaskan	assert
menekan	press	pressing
menekankan	emphasised
menelan	swallow
menembak	shoot
menembusi	penetrate
menempatkan	placing	place
menempuh	go through	cover	endure
menemui	discovered	meet
menemukan	find	to bring together
menendang	kick
menengah	secondary
menentang	oppose	against
menentangnya	opposed
menentu	uncertain
menentukan	determine
menepati	fulfill
menerajui	lead
menerangi	light up	lit up	brighten
menerangkan	explain	explained	described
menerapkan	apply
menerbitkan	publish	published
menerima	receive	accepted
menerimanya	accept
menerusi	through
meneruskan	continue	continued
menetap	settle	settled	stay
menetapkan	set
menewaskan	defeat
mengadakan	hold
mengadap	audience with royalty	face
mengahwini	married
mengaitkan	connect
mengajak	invite
mengajar	teaching	teach
mengaji	recite	study
mengakhiri	end
mengakibatkan	caused	cause	result
mengaku	admit
mengakui	acknowledge
mengalah	give up	resign	give in
mengalahkan	beat	defeated
mengalami	experiencing	have
mengalihkan	divert
mengalir	flow
mengalirkan	drain
mengalualukan	welcome	welcomes
mengamalkan	practice
mengambil	taking	takes	take
mengambilalih	take over	take
mengamuk	rampage
menganalisis	analyze	analyzes
mengancam	threaten
mengandung	contains	contain
mengandungi	contains
menganggap	assume	considered
menganggapnya	consider
menganggarkan	estimate
menganggotai	participates	member of	is a member of
mengangkat	raised	carrying
mengangkut	carry	transport
menganjur	covered	oraganizes	jut
menganjurkan	organizing
menganut	subscribe
menganuti	follows	embrace	embraced
mengapa	why
mengarah	direct
mengarahkan	direct
mengarang	authored	wrote
mengasaskan	founded
mengasingkan	isolate
mengatakan	say	said
mengatasi	overcome
mengatur	arrange
mengawal	control
mengawan	climb into the sky
mengawasi	oversee	guarding	monitor
mengecam	denounced	criticised
mengecualikan	exempt
mengecut	shrink
mengehadkan	limited
mengejar	pursue	chase
mengejut	suddenly
mengejutkan	surprising
mengekalkan	keep this	maintained	maintain
mengekang	curb
mengelak	avoid
mengelakkan	to avoid	avoid
mengelaskan	classify
mengelilingi	around
mengelirukan	confuse	confusing
mengeluarkan	issue
mengemaskini	update
mengembalikan	retuurn	restored
mengembang	expand  expand	expand
mengembangkan	expand
mengembara	adventure	wander
mengemukakan	submit
mengenai	about
mengenainya	about
mengenakan	impose
mengenal	identify
mengenali	recognize
mengenalpasti	identify
mengenang	recall	remember
mengendali	handling	to handle
mengendalikan	control
mengenepikan	aside
mengepung	surrounded	surround
mengeras	harden
mengeratkan	strengthen
mengerjakan	do	prayer
mengerjakannya	performed
mengesahkan	confirmed	validate
mengesan	detect
mengetahui	know
mengetepikan	set aside
mengetuai	led	lead
menggabungkan	combine	combined
menggaji	hire
menggalakkan	encourage
menggambarkan	reflect	portrayed
mengganggu	disturb	interfere
menggantikan	replace
menggantikannya	replacing	replace
menggariskan	outlined	outlines/ outlays	outlines
menggelar	nicknamed	name	calls
menggerakkan	move	drive
menggesa	urging	urged
menggigit	biting	bite
menggubal	draft	change
menggulingkan	overthrow
mengguna	using
menggunakan	use
menggunakannya	use it	use
menggunting	cut
menghabiskan	spend
menghadap	facing	face
menghadapi	face
menghadiri	attend
menghadkan	to limit	limit	limiting
menghalalkan	legalise	justify
menghalang	prevent
menghalangnya	prevent him / her
menghalau	drive away	chase
menghampiri	approaches	approach
menghancurkan	destroyed	destroy
menghantar	send
menghapuskan	eliminate
mengharamkan	forbid	forbids
mengharapkan	hopeful	expect
menghargai	appreciate  appreciate  appreciate	appreciate
mengharungi	facing	wade	weather
menghasilkan	produce
menghayati	appreciate
menghendaki	require
menghentikan	stop
menghidap	have
menghidapi	have
menghidupkan	turn on
menghilang	disappear	disappeared
menghilangkan	get rid of
menghimpunkan	collecting	assemble
menghina	disrepectful	insult
menghindari	avoid
menghiraukan	considering	heed
menghisap	suck	sucking
menghormati	respecting	respect
menghubungkan	connecting	link
menghukum	sentenced	penalize
menghuraikan	defined	describe	explains
mengidap	suffering	suffering from	diagnosed
mengikat	binding	tied
mengiktiraf	recognize
mengikut	in
mengikuti	following	follow
mengikutinya	follow
mengimbangi	balance	balancing	offset
mengingatkan	remind
mengingkari	disobey	deny
mengira	think
mengirim	sent	send
mengiring	accompanied	side
mengiringi	accompany
mengisahkan	narrate
mengisi	fill in	fill
mengisytiharkan	declared	declare
mengkaji	review	research
mengkritik	criticize
mengorbankan	sacrifice	sacrificing
mengorbit	orbiting	orbit
menguasai	control	controlled
menguatkan	reinforce
menguatkuasakan	enforce
mengubah	modify	change
mengubahsuai	modify	modified
mengucap	utter	speak
mengucapkan	say
menguji	test	testing
mengukuhkan	strengthen
mengukur	measure
mengulangi	repeat
mengulas	comment	commenting on	commenting
mengumpul	collecting	gather
mengumpulkan	collect
mengumumkan	announce	announcing
mengunakan	using	use
mengunci	lock	seal
mengundang	invite
mengundi	vote
mengundurkan	postpone	pull back
mengunjungi	mengunjungo	visit
menguntungkan	profitable
mengurangi	decrease
mengurangkan	reduce
mengurung	imprison
mengurus	manage	managed
menguruskan	manage
mengusahakan	worked at	work	operate
mengusap	stroke	wipe
mengusir	evict	banish
mengutamakan	priority	prioritised
mengutip	collected	collect
mengutuk	condemn
mengutus	dispatched	messaged	send
menikmati	enjoy
menilai	assess	value
menimba	claim	gain
menimbulkan	raise
menimpa	befall
menindas	suppress
meninggal	pass away	passed away	died
meninggalkan	leave	leave behind
meninggalkannya	left
meninggikan	increasing	raise
meningkat	increase	increasing
meningkatkan	increase
menipu	cheat
meniru	imitate	copy
meniup	blow
menjadi	be	become
menjadikan	make
menjadikannya	makes	it
menjaga	protect
menjajah	colonize	colonised
menjalani	undergo
menjalankan	run
menjalin	bonding	establish
menjalinkan	established
menjamin	guarantees	secures	guarantee
menjana	generate
menjangkakan	estimated
menjangkau	reached	reach
menjangkiti	infect	infected
menjanjikan	promise
menjaringkan	scored
menjatuhkan	down
menjauhi	avoid	keep away from
menjauhkan	to avoid	distance	stay away
menjawab	answer
menjawat	to hold an office / position
menjayakan	success
menjejak	track
menjejaskan	affect	affects
menjelang	towards	upcoming
menjelaskan	explaining	explain
menjelma	transform	appear
menjemput	invited	pick up
menjerit	scream
menjimatkan	save	saves
menjual	sell
menjuarai	win	champion
menjumpai	find
menjunjung	honor
menjurus	lead
menolak	denied
menolong	helping	help
menonjol	vivid	prominent
menonjolkan	bumping	show
menonton	watch	watching
mensasarkan	target
menstabilkan	stabilize
mentadbir	administer
mentafsir	to judge / interpret	interpret
mentah	crude	raw
mentakab	mentakab
mentakrifkan	defines	define
mental	mental
menteri	minister
menterimenteri	ministerial
mentor	mentor
menu	menu
menuai	reap
menubuhkan	establish
menuduh	accuse
menuju	toward
menukar	switch	change
menukarkan	change
menular	spread
menulis	write
menumpaskan	beat	defeated
menumpu	focus
menumpukan	concentrate
menunaikan	fulfill	agree	discharge
menundukkan	defeat
menunggang	riding	ride
menunggu	waiting	wait
menunjukan	shows
menunjukkan	showing	show
menuntut	claim	studying
menurun	going down	decline
menurunkan	down	lower
menurut	according	by
menurutnya	adding	according to	according
menutup	close
menyahut	respond
menyakitkan	paiful	painful
menyaksikan	watch	witnessed
menyala	light
menyalahi	violate
menyalahkan	blame
menyalin	copy
menyamai	similar	equal
menyambung	continue	connect
menyambungkan	connecting	connected	connects
menyambut	welcome	receives
menyampaikan	deliver
menyandang	held
menyangka	expected	think
menyanyi	sing	singing
menyanyikan	sing
menyapu	sweep	swept
menyarankan	suggest
menyatakan	state
menyatukan	combined	unite
menyayangi	love	loves
menyebabkan	cause
menyebabkannya	causing
menyebar	spread
menyebarkan	soothe	spread
menyebelahi	side	side with
menyeberangi	crossing
menyebut	mention	say
menyebutkan	quotes
menyebutnya	calls it	call
menyedari	aware
menyedarkan	convince	awareness
menyediakan	provide
menyekat	block
menyeksa	punish
menyelamat	save
menyelamatkan	save
menyelaras	coordinate	manage
menyelaraskan	coordinate	adjust
menyelesaikan	solve
menyelia	supervise
menyeluruh	comprehensive
menyemak	review
menyembah	worship
menyembuhkan	cure
menyembunyikan	conceal	hide
menyempurnakan	complete
menyenangkan	pleasant	ease	please
menyenaraikan	list	lists
menyentuh	touch
menyerah	surrender
menyerahkan	submit
menyerang	attacks	attack	attacked
menyerap	absorb
menyertai	join
menyeru	call
menyerupai	caused	resemble
menyesuaikan	adapting	adjust
menyiapkan	completing	prepare
menyiarkan	broadcast
menyiasat	investigate
menyifatkan	described
menyimpan	store	keep
menyimpang	deviate
menyingkirkan	remove
menyokong	supporting	supports
menyuarakan	voice
menyukai	like
menyukarkan	complicate
menyumbang	contribute
menyumbangkan	contribute
menyuruh	instruct	order	told
menyusahkan	trouble	inconvenience
menyusul	follow
menyusun	compile
menziarahi	visited	visit
meraba	palpate
meragut	grazing
merah	redness
meraih	obtain	achieve
meraikan	celebrate
merak	peacock
merakam	record
merakamkan	record	filimed	recorded
merampas	confiscate	snatch
merancang	plan
merangka	design
merangkap	cum	ensnare
merangkul	embrace	embraced
merangkumi	contains	includes
merangsang	arouse	stimulate
merangsangkan	stimulate
merantau	wonder about	wander about
merasa	feel	test
merasai	feel
merasakan	feel
merasmikan	opening	officiating	officialise
merata	over
merawat	treat
merayakan	celebrating	celebrate
merayu	appeal
merbahaya	dangerous
merbok	merbok	tampaksiring
mercu	vertex
mercun	fireworks
merdeka	independent
merealisasikan	realize
merebak	spread
merebut	fight over	fight for	grab
mereka	they
merekalah	they
merendah	lows
merendahkan	lowers	lowering	reduced
merentasi	across
meresap	absorb	seep
mergong	estate
meriah	cheer	lively
meriam	cannon
meringankan	ease
merkantilisme	mercantilism
merkuri	mercury
merokok	smoke
merong	merong
merosakkan	damage	damaging	spoiling
merosot	decline
merpati	pigeon
mersing	mersing
merta	immediately
mertajam	mertajam
merugikan	cause loss	harm
merujuk	reference
merumuskan	formulate
merupakan	is
mesej	message
mesin	machine
mesingan	machine guns	machinegun
mesir	egypt
meskipun	though
mesolitik	mesolitic	mesolithic
mesopotamia	mesopotamia
mesra	friendly
mesti	must
mestilah	must be
mesyuarat	meeting
metana	the methane
metastasis	metastasis
meteorit	meteorite
meteorologi	meteorology
metropolitan	metropolitan
mewah	luxurious
mewajibkan	require	requires
mewakili	represent
mewarisi	inherited
mewujudkan	creates	established / created
mexico	mexico
meyakinkan	convince
mi	noodles
michael	michael
microsoft	microsoft
mig	mig
migrasi	migration
mikro	micro	micro-
mikroskop	microscope
milan	milan
milenium	millennium
milik	possession	posession
milikan	possession	posession
miliki	owned	have
miliknya	his	owned by him
military	military
militer	military
mill	mill
mimpi	dream
min	min
minang	minang
minangkabau	minangkabau
minat	interest
minda	mind
mineral	mineral
ming	ming
minggu	week
mingguan	weekly
minh	minh
mini	mini
minima	minimum	minimal
minimum	minimum
minit	m	minutes away	minutes	minute
minoriti	minority
minta	ask
minum	drink
minuman	beverages	drinks
minyak	oil
miri	miri
mirip	similiar	similar
misalnya	for example
misi	mission
miskin	poor
misteri	mystery
mistik	mystic
mistisisme	of mysticism	mystisism	myticism	mistisime	mysticism	mistisisme
mit	mit
mitologi	mythology
mitos	myth
mitsubishi	mitsubishi
mizan	mizan
mk	mk
mm	mm
mobil	car
mod	mode
modal	capital
mode	mode
modelmodel	model
modem	modem
moden	modern
modern	modern
modul	module
mogok	strike
mohamad	mohamad
mohamed	mohamed
mohammad	mohammad
mohd	mohd
mohor	seal
mokhtar	mokhtar	mukhtar
molekul	molecule
momogun	momogun
monarki	monarchy
mongol	mongols
monitor	monitor
monogami	monogamy
monoksida	monoxide
monopoli	monopoly
monorail	monorail
monsun	monsoon	munson
monumen	monument
monyet	monkey
mood	mood
moody	moody
moor	moor
moral	moral
more	lebih	more
morfem	morpheme
morfologi	morphology
moscow	moscow
mosi	motion
mosque	mosque
most	most
motif	motive	motives
motor	motor
motosikal	motorcycle
motto	motto
mountain	mountain
movie	movie
moyang	fathers	ancestors
mozek	mosaic
mp	mp
mpaja	mpaja
mr	mr
mrsm	patch
mrt	mrt
msc	msc
mtv	the mtv
mu	you
muadzam	muadzam
muafakat	consensus	agreement
muakkad	muakkad
muar	jawa
muara	estuary
muat	load	download
muatan	load
mubaligh	proselytizer	missionaries	missionary
muda	young
mudah	easy
mudik	upstrream	upstream
mufti	mufti
mughal	the mughal
muhajirin	muhajirin
muhamad	muhamad
muhammad	muhammad
muhibah	harmony	goodwill
muhibbuddin	muhibbuddin	muhibbudin
muhyiddin	muhyiddin
muka	face
mukah	the mukah	mukah
mukanya	his face
mukim	district
mukjizat	signs
mukmin	the believers
muktamad	final
mula	starting or beginning	beginning
mulai	from
mulamula	at first	first
mulamulanya	started	initially	first
mulanya	first
mulia	noble
multimedia	multimedia
multinasional	multinational
mulur	excrement	flexible
mulut	mouth
mulutnya	mouth
muncul	appear
munculnya	emergence
mundur	retreat
mungkin	may	maybe
munshi	munshi
muntah	vomit	vomiting
murah	cheap
murai	magpie
murid	pupil
muridmurid	students	pupils
murni	pure
murtad	apostate
murut	murut
mus	part of a scientific name of a mouse	mouse	mus	mousse
musa	musa
musafir	traveler
musang	fox
musibah	disaster
music	music
musim	season
muslim	muslim
muslimin	muslims
musnah	destroyed	destroy
mussolini	mussolini
mustafa	mustafa
mustahak	important
mustahil	impossible
mustapha	mustapha
musuh	enemy
musuhmusuh	musuhmusuh	enemies
musuhnya	his enemies
musyrik	pagans
musyrikin	pagan
musytari	jupiter
muszaphar	muszaphar
mutasi	mutation
muthalib	underdeveloped
mutiara	pearl
mutlak	total	absolute
mutu	quality
muzaffar	muzaffar
muzik	music
muzikal	musical
muzium	museum
myanmar	myanmar
n	n
na	na	good morning
nabi	prophet
nabinabi	nabinabi
nada	tone
nadi	pulse
nafas	breath
nafi	denies
nafkah	living	sustenance
nafsu	desire	lust
nafsunya	desire	desires
naga	dragon
nahu	grammar
naib	vice
naik	up
naim	naim	delightful
naismith	naismith
najib	najib
najis	excrement	feces	scat
nak	i	want
nakhoda	captain	master
nakhon	nakhon
nam	nam
nama	name
namanama	names
namanya	name	its name
nampak	see	look
nampaknya	seemingly
namrud	nimrod
namun	however
nanah	pus
nanas	pineapple
nangka	jackfruit
nano	nano
nanoteknologi	nanotechnology
nanti	later
napoleon	napoleon
nara	persons for
narkotik	narcotics	narcotic
naruto	naruto
nasa	nasa
nasi	rice
nasib	fate
nasihat	counsel	advice
nasional	national
nasionalis	nationalist
nasionalisme	nasionalism	nationalism
nasir	nasir
nasrani	christians
nation	nation
national	national
nations	regulations	nations
natrium	sodium
nature	nature
natyam	dance
naungan	protected	shade	protection
navy	navy
nazi	nazi
nd	nd
nebula	nebula
negara	country
negaraku	my country / homeland	my country
negaranegara	nations	countries
negaranya	country
negatif	negative
negeri	country
negerinegeri	states	country	the states
negetif	negative
nelayan	sailor	fisherman
nenas	pineapple
nenek	grandmother
neolitik	neolithic
neptun	name of a planet neptune	neptune
neraka	hell
nescaya	may	surely	he
net	net
network	network
networks	networks
neuron	neurons
neutral	neutral
new	new
newton	newton
ngah	ngah
ngo	ngos
ni	i	this
niaga	business	trade
niat	intention
niatnya	intention	his intention
nibong	mahakam
nigeria	nigeria
nihilisme	nihilism
nik	nik
nikah	marriage
nikmat	comfort	delectation
nil	nil
nilai	value
nilainilai	values
nilainya	value
nilam	nilam	sapphire
ninja	ninja
ninjaninja	ninjas
nipah	nipah
nipis	thin
nippon	nippon
nisaa	nissa
nisbah	ratio
nitrogen	nitrogen
nixon	nixon
nizam	nizam
nizar	nizar
no	number	no
nobat	nobat
nobel	novel	nobel
nobita	nobita
nod	node
nomad	nomad
nombor	number
nominal	nominal
noor	noor
nordin	nordin
norizan	norizan
norma	norm
normal	normal
norway	norway
nota	note
nottingham	nottingham
nov	november
novel	novel
november	november
ntv	ntv
nuh	legitimacy
nuklear	nuclear
nukleotida	nucleotides	the nucleotide	nucleotide
nukleus	nucleus
nur	light
nuruddin	nuruddin
nurul	nurul
nusa	island	nusa
nusantara	archipelago
nutrien	nutrient
ny	ny
nya	his
nyamuk	mosquito
nyanyian	singing
nyata	real
nyawa	life
nyonya	mistress
obesiti	obesity
obito	obito
objek	object
objektif	objective	objectives
oc	oo	oc
oceania	oceania
oecd	oecd
of	of
official	official
ogos	ogost	august
oh	oh
oksida	oxide
oksigen	oxygen
oktober	october
olahraga	athletics
old	means same meaning in both language
oleh	by
olehnya	it	by
olimpik	olympic	olympics
oman	oman
omar	omar
ombak	wave	waves
omega	omega
on	on
onani	masturbation
one	one
onn	part of the persons name
ontario	ontario
opera	opera
operasi	operation
operasinya	operations
operasioperasi	operations
optik	optics	optic
optimum	optimum
or	or
oral	oral
orang	person	people
orangorang	persons	people
orangorangnya	people
orde	order
order	order
ordinan	ordinance
oren	orange
organ	organ
organik	organic
organisasi	organization	organisation
organisma	the organism	organisms
organization	organization
organorgan	organs
oriental	oriental
orochimaru	orochimaru
ortodoks	orthodocs	orthodox
os	os
osman	osman
otak	brain
other	other
othman	othman
otomatik	automatic
otot	muscle
otototot	muscles
our	our
outlook	outlook
output	output
ovale	ovale
ovari	ovary
ovulasi	ovulation
own	own
oxford	oxford
ozon	ozone
p	p
pacific	pacific
pada	at	in
padahal	whereas
padam	erase	delete
padang	field
padanya	him	it
padat	compact
paderi	father	chaplain
padi	paddy
padu	solid
paduka	excellency
pagar	gate	fence
pagi	morning
paha	pacha	thigh
pahala	reward	deeds
pahat	chisel
pahit	bitter
pahlawan	warrior	hero
paip	pipe
paitan	paitan
pak	pak	uncle
pakai	adopted
pakaian	clothing
pakar	experts	expert
pakarpakar	experts
pakatan	pact	alliance
pakej	package
pakistan	pakistan
paksa	force
paksaan	force
paksi	axial	axis
paku	nail
palang	bar	barrier
palas	palas
palembang	figure-eight puffer
paleolitik	paleolithic
palestin	palestine
paling	most
paloh	paloh
palsu	false	fake
pam	pump
pamah	lowland
pameran	exhibition
pampasan	compensation
panah	arrow
panas	hot
panca	penta
pancaragam	various
pancaran	radiation	emission
pancasila	pancasila
pancutan	ejaculation
pandai	can	smart
pandak	pandak
pandang	look	view
pandangan	view
pandu	drive
panduan	guidance	guide
pangeran	prince	prince, or nobleman
panggilan	nickname	call
panggung	theater	theatre
pangkah	cross
pangkahan	crosses	cross
pangkal	base	beginning
pangkalan	base
pangkat	rank
pangkuan	lap
panglima	commander
panjang	long
panjangnya	length	in length
panji	banner
panjipanji	the banner
pantai	beach	coast
pantang	abstinence	cannot	taboo
pantas	quick	fast
panthera	panthera
pantulan	reflection
pantun	poem	pantum
papan	board
papar	show
paparan	display
papua	papuan
para	the	those
paradigma	paradigm
parah	severe
parameswara	parameswaran	parameswara
parang	knife
paranormal	paranormal
paras	level
parasit	parasite
pari	ray
paris	paris
parit	ditch
pariti	parity
parlimen	parliament
parsi	intersection	persian
parti	party
partikel	particle
partiparti	party	partiparti	parties
party	party
paruparu	lung	lungs
pas	pass
pasai	pasai
pasak	peg
pasang	tide	high tide	brace
pasangan	pair	couple
pasangannya	mate
pasar	market
pasaran	market
pasaraya	supermarket	suermarkets
pasca	post
pascal	pascal
pascaperang	pre war
pasif	passive
pasifik	pacific
pasir	sand
pasti	sure
pastikan	sure	ensure
pastinya	certainly
pasu	pots
pasukan	force	team
pasukannya	the team	his / her team
pasukanpasukan	pasukanpasukan	force	team
patah	break	broken	broke
patani	patani
paten	patent
pati	essence	starch
patma	patma
patologi	pathology
patriotik	patriotic
pattani	pattani
patuh	comply
patung	statue
patungpatung	statue
patut	should
pau	pouch	pau
pauh	ascendancy
paus	pope
pautan	link
pawagam	theather	cinema
paya	swamp
payah	hard	difficult
payu	breast
payudara	breast
payung	umbrella
pbb	un
pc	pc
pdrm	pdrm
pearl	pearl
pecah	broken
pecahan	fraction
pecutan	acceleration	accleration	accelaration
pedagang	merchant	trader
pedagangpedagang	pedagangpedagang	swords
pedagogi	pedagogy	pedagogue
pedalaman	interior
pedang	oedang	sword
pedas	spicy	hot / spicy
pedofilia	pedophilia	pedophile	pedofile	pedophiles
pedoman	guidance
pegangan	religious beliefs	hold
pegawai	official	officer
pegawaipegawai	officer	officers
peguam	lawyer
pegunungan	mountains
pei	pei
pejabat	office
pejal	solid
pejalan	walker	pedestrian
pejuang	warrior	fighter
peka	sensitive
pekan	week
pekara	sittings
pekat	concentrated	concentrated / thick
pekebun	farmers
pekerja	employee	worker
pekerjaan	employment
pekerjapekerja	workers
pekerti	character
pelabuhan	port
pelabur	investor	investors
pelaburan	investment
pelacuran	prostitution
peladang	farmers
pelajar	student
pelajaran	education	studies
pelajarpelajar	students	student
pelakon	actor
pelaksanaan	implementation
pelamin	bridal bed
pelan	plan
pelancapan	masturbate	masturbation
pelancar	launchers
pelancaran	launch
pelancong	tourist
pelancongan	tourism
pelanduk	badgers
pelanggan	customer
pelanggaran	violation	collision
pelangi	rainbow
pelantar	platform
pelantikan	appointment of	appointment
pelarian	fugitive
pelatih	trainer
pelawat	visitors
pelayan	sever	server
pelayar	browser
pelayaran	sailing	cruise
pelbagai	various
peleburan	melting	smelting
pelekat	sticker
pelengkap	fulfill	complement
pelepah	frond	feather
pelepas	release
pelepasan	release	emission
pelesenan	licensing
pelik	weird
pelincir	lubricants
pelindung	protector
pelir	penis
pelita	light
pelombongan	mining
pelopor	precursor
pelosok	corner
peluang	chance
peluasan	expansion
peluh	sweat
pelukis	painter
pelumba	racer
peluru	bullet
pemacu	drive
pemahaman	comprehension
pemain	player
pemainpemain	players
pemaju	developers	developer
pemakaian	application	consumption	dressing
pemakan	eater
pemakanan	nutrition	ingestion	diet
pemanas	heating
pemanasan	heating	warming
pemancar	transmitter
pemancaran	emission
pemandangan	view
pemandu	guide
pemangkin	catalyst
pemangku	acting
pemangsa	predators
pemantauan	monitoring
pemasangan	installation	install
pemasaran	marketing
pemasukan	entry	inclusion
pemasyhuran	promulgation
pembaca	reader
pembahagian	division	distribution
pembaharuan	renewal
pembaikan	repair	improvement
pembajaan	fertilisation	fertilization
pembakaran	burning
pembalakan	required	logging
pembalasan	reward	retaliation
pembandaran	urbanization
pembangkang	opposition
pembangun	development	developer
pembangunan	development
pembantu	assistant
pembantut	pembantut
pembatalan	cancellation
pembawa	carrier	carriers
pembayaran	payment
pembaz	buzzer	pembaz
pembebasan	release	the release
pembedahan	surgery
pembekal	suppliers
pembekalan	supplier	supply
pembelajaran	learning
pembelian	purchase
pembentukan	formation
pemberian	giving	administration
pemberontak	rebel
pemberontakan	rebellion
pembersihan	cleaning
pembesar	speakers
pembesaran	enlargement
pembezaan	differentiation	diffentiation
pembiakan	breeding	reproduction
pembiayaan	financing
pembinaan	construction
pembinaannya	construction	construction in
pembolehubah	variables
pembuangan	disposal	removal
pembuat	maker
pembuatan	manufacture	manufacturing
pembubaran	dissolution
pembukaan	wharf	opening
pembuluh	vessel
pembunuh	killer
pembunuhan	murder
pemburu	hunter
pemburuan	hunting
pemecatan	the sacking
pemegang	holder
pemeliharaan	preservation
pemelukan	conversion	embrace
pemenang	winner
pemerbadanan	incorporation
pemergian	departure
pemerhati	observer
pemerhatian	observation
pemeriksaan	inspection
pemerintah	ruler	government
pemerintahan	rule
pemerintahannya	his / her rule	rule
pemerolehan	acquisition
pemikir	thinker
pemikiran	thought
pemikirpemikir	thinker
pemilih	voter
pemilihan	election
pemilik	owner
pemilikan	ownership
pemiliknya	the owner	owners
pemimpin	leader
pemimpinpemimpin	leader	leaders
peminat	fans
pemindahan	transfer	shifting	transhipment	transfering
pemisah	dividing
pemisahan	division	separation
pemodenan	modernization	modernisation
pemproses	processor
pemprosesan	processing
pemuda	youth
pemuisi	poet
pemukul	bat	hitter
pemulihan	recovery
pemuliharaan	conservation	recovery
pemurah	generous
pemusnah	destroyer	destruction
pemusnahan	destruction
pemuzik	musician	musicians
penahanan	blockage	detention
penaja	sponsor	sponcers
penaklukan	conquest
penalti	penalty
penamaan	nomination
penambahan	addition
penampang	section
penampilan	appearance
penanaman	cultivation
penanda	marker
penang	penang
penangkapan	arrest	capture
penapis	filter
penapisan	filtering	filtration
penari	dancer
penaripenari	dancers	penaripenari
penasihat	adviser
penawanan	capture
penawar	antidote
penawaran	supply	offer
pencak	martial
pencapaian	achievement
pencarian	search
pencegah	deterrent
pencegahan	prevention
pencemaran	contamination	pollution
pencen	pension
penceraian	divorce
pencernaan	digestion
penceroboh	intruder
pencerobohan	invasion
pencetak	printer
pencetakan	printing
pencetus	pioneer	spark
pencipta	creator
penciptaan	invention
pencuri	thief
pendaftaran	registration
pendakwaan	prosecution
pendakwah	missionaries
pendalaman	interior
pendam	not reactive	latent
pendang	of pendang	pendang
pendapat	opinion
pendapatan	income
pendaratan	landing
pendatang	immigrant
pendatangpendatang	immigrants
pendawaian	wiring
pendedahan	exposure
pendek	short
pendekar	warrior
pendekatan	approach
pendengaran	hearing
penderaan	abuse
penderitaan	suffering	sufferer
pendeta	pastor	minister
pendidik	educator
pendidikan	education
pendidikannya	education	his education
pendirian	standpoint	conviction
penduduk	resident
pendudukan	residents	occupation
penduduknya	people
pendudukpenduduk	residents
pendukung	support	carrier
penebangan	felling (of trees)	felling
penebat	insulation	insulator
penekanan	emphasis
penembak	shooter	snipers
penembusan	penetration
penempatan	settlement	placement
penemuan	discovery
penentang	opponent
penentangan	resistance
penentu	determinant	detemining
penentuan	determination
peneraju	leader
penerangan	the light	explanation
penerbangan	flight
penerbit	publisher
penerbitan	publication
penerima	receiver
penerimaan	acceptance
penerokaan	exploration	venture
penetapan	determination
peng	peng
pengadil	referee
pengadilan	justice	judgement	court
pengagihan	distribution
pengairan	irrigation
pengajar	instructor
pengajaran	teaching	lesson
pengajian	study
pengakhiran	end	the end
pengakuan	admission
pengalaman	experiance	experience
pengalir	conductor
pengaliran	conduction	flow
pengamal	practitioner	practitioners
pengamalan	practice
pengaman	peacekeeping
pengambilan	taking	intake
pengangguran	unemployment
pengangkut	carrier
pengangkutan	transportation	transport
penganiayaan	persecution
pengantar	delivery	transactor
pengantin	bride
penganugerahan	conferment	award
penganut	adherents
penganutnya	adherent
pengarah	director
pengarang	author
pengaruh	influence
pengaruhnya	the influences	influence	its influence
pengasas	founder
pengasasan	founding
pengasingan	pengasingam	isolation
pengaturcara	programmer
pengaturcaraan	programming
pengawal	guard
pengawalan	control	guard
pengawasan	supervision	surveillance
pengebom	bomber
pengeboman	bombardment	bombing
pengecualian	exception
pengecutan	contraction
pengedaran	distribution	distribute
pengekalan	definition	retention
pengeksport	exporters
pengelasan	classification
pengeluar	producers
pengeluaran	production
pengembangan	expansion / development	expansion
pengembara	traveller of a voyage	nomad
pengembaraan	travelling	traveling
pengenalan	introduction	identification
pengendali	operator
pengendalian	control	operating
pengepala	header
pengepungan	siege	blockade
pengertian	meaning
pengerusi	chairman
pengesaan	pengesaan	pengessan
pengesahan	confirmation	validation
pengesan	detector
pengesanan	detection
pengetahuan	knowledge
pengetua	principal / headmaster	principals
penggabungan	merger
penggal	term
penggambaran	shooting
pengganas	terrorist
pengganti	substitute
penggantian	replacement
penggantinya	his replacement	successor
penggemar	lovers	fan
penggerak	mover
penggubah	composer
penggulingan	overthrow
pengguna	the usage	consumer	user / consumer	users	user
penggunaan	usage	the use
penggunaannya	usage	use
penggunanya	users
penghadaman	digestion
penghala	router	direction	router  router	tutorial	routers
penghalang	obstacle	barrier
penghantar	transmitter	sender
penghantaran	transmission
penghapusan	elimination	deletion
pengharaman	ban
penghargaan	appreciation
penghasilan	production
penghibur	entertainer
penghidupan	life	lifestyle
penghijrah	penghijirah	migrants
penghijrahan	migration
penghinaan	contempt
penghormatan	honour	honor
penghubung	liaison	link
penghujung	end	the end
penghulu	headman
penghuni	occupant
pengikat	fastener
pengiklanan	advertising	advertisement
pengiktirafan	recognition
pengikut	follower	followers
pengikutnya	his followers
pengikutpengikutnya	followers
pengilang	manufacturer	manufacturers
pengilangan	manufacturing
pengimbas	scanner
pengimejan	imaging
pengimport	importer
penginapan	lodging
penginfarkan	infarction
pengiraan	calculation
pengiring	escort
pengistiharan	declaration
pengisytiharan	declaration
pengkaji	researchers
pengkajian	study
pengkalan	base
pengkebumian	burial	funeral
pengkelasan	classification
pengkhususan	specialization
pengkristianan	pengkristianan	christianisation	christinaian	christianity lawyer	christianity
pengkritik	critic
penglibatan	involvement
penglihatan	vision	sight
pengoksidaan	oxidation
pengolahan	processing
pengoperasian	operating
pengorbanan	sacrifice
pengsan	faint	passed out
penguasa	authority
penguasaan	control	domination
penguat	amplifier
penguatkuasaan	enforcement
pengubahsuaian	modification	renovation
pengucapan	speech
pengukuhan	strengthening	enhancement
pengukuran	measurement
pengumpulan	collection
pengumuman	announcement
pengunaan	usage	use
pengundi	voter	voters
pengundian	poll	voting
pengunduran	retreat
pengunjung	visitor
pengurangan	reduction
pengurus	manager	management
pengurusan	management
pengusaha	entreprenuer	makers
pengusiran	expulsion
peniaga	traders
penilaian	valuation
penindasan	oppression
pening	dizziness	headache
peninggalan	legacy
peningkatan	increase	enhancement
peninjau	observer
penipuan	fraud
penjaga	keeper	guard
penjagaan	care taker	custody
penjajah	colonialist
penjajahan	colonisation	colonialism
penjana	generator
penjanaan	generation
penjangkit	infector
penjara	prison
penjaring	scorer
penjelajah	explorer
penjelas	sinking
penjelasan	explanation
penjenayah	criminals
penjual	seller
penjualan	sale
penjuru	corner
penolakan	denial	rejection
penolong	assistant
penonton	spectators
pensterilan	sterilization
pentadbir	administrator
pentadbiran	administration
pentadbirannya	administration
pentas	stage
penterjemah	transalation	interpreter
penterjemahan	translation	translate
penternakan	livestock
penting	important
penubuhan	establishment
penubuhannya	establishment
penugasan	assignment
penuh	full
penukaran	conversion	change	exchange
penulenan	originality	purification
penulis	author
penulisan	write up	writing
penumpang	passenger
penunggang	rider
penunjuk	indicator	demonstate
penuntut	student
penurunan	reduction	reduction reduction
penutup	closing	cover
penutupan	closure
penutur	speaker
penyair	poet
penyakit	desease	illness	disease	sickness
penyakitpenyakit	deseases	diseases
penyalaan	ignition
penyalahgunaan	misuse
penyalinan	copying
penyambung	link
penyambungan	continuation	connection
penyampaian	delivery
penyanyi	singer
penyapu	broom
penyaringan	filtering	screening
penyata	statement
penyataan	expression
penyatuan	union
penyayang	loving
penyebab	cause
penyebaran	propagation	spread
penyediaan	preparation
penyelamat	rescuer	savior
penyelarasan	coordination
penyelenggaraan	management	maintenance
penyelesaian	resolution	solution
penyeliaan	supervision
penyelidik	researcher
penyelidikan	research
penyembahan	worshipped	worship
penyembelihan	slaughter
penyepit	chopsticks	chopstick
penyerahan	handover	surrender	hand up
penyerang	attacker
penyerapan	absorption
penyertaan	participation
penyesuaian	adaptation
penyiaran	broadcasting	showcase
penyiasatan	investigation
penyihir	witch
penyimpan	depositor
penyimpanan	storage
penyingkiran	dismissal
penyokong	support	supporters
penyokongpenyokong	support
penyu	turtle
penyulingan	distillation
penyumbang	contributor	sponsor
penyusun	compiler
penyusunan	breastfeeding	organization
penyusupan	infiltration
people	people
peoples	peoples
peparu	lungs
pepejal	solid
peperangan	pepaerangan	war
peperiksaan	examinations	examination
per	per
perabot	furniture
peradaban	civilization	civilisation
perahu	boat
perai	peak
perairan	water
perak	silver	a state in malaysia
perakaunan	accounting	accountancy
peralatan	equipment	equipments
peralihan	transition
peranakan	hybrid	womb
peranan	role
peranannya	role
perancang	planner
perancangan	planing	planning
perang	war
perangai	attitude
peranginan	resort
perangkaan	statistics
perangperang	wars
perangsang	stimulant
perangsangan	stimulation
perantara	medium
perantaraan	medium
perantau	settled foreigner
perantauan	roaming	roming
peranti	device	devices
perarakan	parade
perasaan	feeling
perasmian	opening
peraturan	rules	regulation
peraturanperaturan	regulations
peratus	percent
peratusan	percentage
perayaan	celebration
perbadanan	corporation
perbalahan	dispute	quarrel
perbandaran	municipal
perbandingan	comparison
perbankan	banking
perbatasan	frontier
perbelanjaan	expenses  expenses	expenses
perbendaharaan	peerbendaharaan	treasury
perbezaan	perpezaan	difference	the difference
perbicaraan	trial
perbincangan	talks	discussion
perbualan	conversation
perbuatan	action	act
perbuatannya	deed	his / her actions
perbuatanperbuatan	perbuatanperbuatan	behaviours
percanggahan	conflict	discrepancy
percaya	believe
perceraian	judicial separation	divorce
percetakan	printing
percubaan	trial
percubaannya	attempt
percuma	free
perdagangan	trade
perdamaian	peace
perdana	prime
perdebatan	debate
perebutan	struggle
peredaran	circulation
perejangan	frame (frame of a vehicle)	propulsion	frame (this refers to the frame of a vehicle)	elongation
pereka	designer	inventor
perekaan	design
perempat	quarter
perempuan	girl	female
perempuannya	woman	his girl	female
perenang	swimmers
perfileman	filming	film
pergaduhan	fighting	fight
pergaulan	association
pergerakan	movement
pergi	go	went
pergigian	dental
pergolakan	turbulence
pergunungan	mountains
perguruan	teaching	college
perhambaan	slavery
perhatian	attention
perhatikan	observe
perhentian	stop
perhiasan	jewelry
perhimpunan	rally
perhitungan	calculation
perhubungan	relationship
perhutanan	forestry
peribadi	personal	private
peribahasa	proverb
perigi	well
perihal	matters	about
perikanan	fishery	fishing
perikarditis	pericarditis	percarditis
perikatan	alliance
perilaku	behavior
perincian	detail
perindustrian	industry	industrial
peringatan	reminder
peringkat	the	stage / level
peringkatperingkat	stages
perintah	order
perintis	pilot
perisai	shield
perisian	software
perisik	intelligence	spy
perisikan	intelligence
peristiwa	incident	event
peristiwaperistiwa	events to	events
perisytiharan	declaration
periuk	pot
perjalanan	travel
perjalanannya	journey
perjanjian	agreement
perjuangan	struggle	the fight
perjudian	gambling
perjumpaan	meeting
perkaedahan	methodology
perkahwinan	marriage
perkahwinannya	marriage
perkaitan	relationship
perkakas	tool	appliance
perkakasan	hardware
perkampungan	settlement	villages	village
perkamusan	lexicography
perkapalan	shipping
perkara	matter
perkaraperkara	matters
perkasa	strong
perkataan	word
perkataanperkataan	words
perkauman	communalism
perkebunan	plantation
perkembangan	development
perkembangannya	development
perkenan	assent
perkhidmatan	services	service
perkhidmatannya	services
perkilangan	manufacturing
perkiraan	estimate
perkomputeran	computing
perkongsian	partnering	partnership
perkuburan	cemetery
perkumuhan	excreation	excretion	mouth rinsing	exretion	slums
perladangan	plantation
perlahan	slow
perlahanlahan	slowly
perlaksanaan	implementation
perlakuan	treatment
perlantikan	appointment
perlawanan	resistance	match
perlembagaan	constitutional	constitution	constiutional
perlesenan	lincensing	licensing
perletakan	placement
perlindungan	protection
perlis	a state in malaysia
perlombongan	mining
perlu	need
perluasan	enlargement	expansion
perlukan	need	needed
perlulah	needs	this awareness must be instilled in the new generation, as there are bad elements who deliberately intend to harm national unity.	should be
perlumbaan	race
perlunya	the need
permai	gorgeous
permainan	game
permaisuri	queen consort
permakanan	diet
permasalahan	problematic	problem	problems
permata	diamond	jewel
permatang	ridge	dike
permintaan	request	demand
permit	permit
permohonan	application	request
permukaan	surface
permulaan	begining	beginning
permulaannya	initially
pernafasan	breathing
pernah	has been	ever	once
perniagaan	business
pernikahan	wedding
pernyataan	statement
perolehan	procurement	acquisition
peronda	patrol
perosak	pest
perpaduan	union	blend
perpatih	perpatih
perpecahan	disunity
perperangan	war
perpindahan	transfer	move
perpuluhan	decimal
perpustakaan	library
persahabatan	friendship
persaingan	competition
persamaan	equation	similarity
persatuan	association
persaudaraan	brotherhood
persediaan	preparation
persefahaman	understanding
persegi	per square	square
persekitaran	environment
persekitarannya	environment
persekolahan	school	schooling
persekutuan	alliance	federation
perselisihan	dispute
persembahan	performance	offering
persendirian	private
persengketaan	controversy
persenjataan	weaponry	arms
persenyawaan	fertilization
perseorangan	singles	single	individual
persepsi	perception
persetubuhan	sexual intercourse	intercourse
persetujuan	agreement
persiapan	preparation
persiaran	cruise
persidangan	conference	council
persimpangan	intersection	junction	crossroads
persisiran	sides	coast
persoalan	issue
persoalanpersoalan	of questions
personaliti	personality
perspektif	perspective
persuratan	correspondence
pertabalan	installation
pertahanan	defence	defense
pertalian	relationship
pertama	first
pertamanya	firstly	first
pertambahan	increase	growing
pertandingan	competition
pertanian	agriculture
pertanyaan	inquiry
pertaruhan	betting	wager / betting
pertarungan	fight
pertelingkahan	dispute
pertembungan	clash
pertempuran	battle	the battle
pertemuan	meeting
pertengahan	middle	in the middle
pertiga	thirds	third
pertikaian	dispute
pertimbangan	judgement	consideration
pertolongan	help
pertubuhan	organizations	association
pertubuhanpertubuhan	pertubuhanpertubuhan	organisations
pertukangan	craft
pertukaran	exchange
pertumbuhan	growth
pertumpahan	spillage	drop
pertunangan	engagement
pertunjukan	show
pertuturan	pleasure	speech
peru	peru
perubahan	change
perubahanperubahan	changes
perubatan	medical
perumah	host
perumahan	housing
perundangan	legislation
perundingan	negotiation	consultation
peruntukan	allocation
perusahaan	enterprise
perut	stomach
perutusan	percentage	mission
perwakilan	representation	representative
perwatakan	character
perwira	warrior	officer
pesaing	contender
pesaka	estate
pesakit	patients
pesakitpesakit	patients
pesalah	offender	offenders
pesanan	order
pesat	rapid
pesawat	plane
peserta	participant
pesilat	pesilat
pesisir	shoreline	coast
pesisiran	edges	coast
pesta	festival
pesuruh	messenger
pesuruhjaya	commissioner
peta	map
petak	square	parcel
petaling	quezon
petanda	sign
petang	evening
petani	farmer
petapeta	petapeta	maps
petempatan	settlements
peter	peter
peti	box
petikan	quote
petir	lightening	lighting	thunder	lightning
petra	petra
petrol	petrol
petroleum	petroleum
petua	tips
petunjuk	guidance	directive, indication, hint, directory, direction
pewaris	heir
pewarisan	inheritance
pewarna	dye
pga	the pga
pgk	pli
ph	ph
philip	philip
phoenix	phoenix
piagam	charter
piala	cup
piawai	the standard	standard
piawaian	standards
pihak	party
pihakpihak	parties
pil	pill
pilah	segment	choose
pilih	choose	select
pilihan	choice
pilihanraya	elections	election
pimpinan	leadership
pinang	nut	pinang
pindaan	amendment
pindah	move
ping	ping
pingat	medals
pinggan	plate
pinggang	waist
pinggir	edge
pinjaman	loan
pintar	smart
pintu	door
pinyin	pinyin
piramid	pyramid	pyramids
piring	dish	plate
pisa	pisa
pisang	banana
pisau	knife
pisifera	sfera
pistol	guns
pita	tape
pitas	pitas
pituitari	pituitary
piwaian	standard
pki	pki
pkm	pkm
pkmm	pkmm
plag	plug
plak	plaque
planet	planet
plasma	plasm
plasmodium	plasmodium
plastik	plastic
plat	plate
plate	plate
platform	platform
platun	platoon
play	play
player	player
plaza	plaza
plkn	ns
plot	plot
plumbum	lead
plural	plural
pluto	pluto
pmr	pmr
pn	interview
pneumonia	pneumonia
pogadaev	pogadaev
poh	space of
pohon	tree
pokok	tree
pokoknya	essentially	basically
pokokpokok	trees
pola	pattern
poland	poland
police	police
policy	policy
poligami	polygamy
poliklinik	polyclinic
polimorf	polymorphic
polis	police
polisakarida	polisaccharide	polysaccharides	polysaccharide
polisi	policy
politeknik	polytechnic
political	political
politik	political
politikal	political
politiknya	politics	political
polo	polo
pondok	hut
ponteng	absent	absenteeism
pontian	pontian
pop	pop
popular	popular
populariti	popularity
populasi	population
portal	portal
portugal	portugal
portugis	portuguese
pos	post
posisi	position
positif	positive
poskod	postcode
post	post
poster	poster
potassium	potassium
potensi	potential
potong	chunk	slice
potongan	deduction	cuttings (first incidence of word eg. potongan kertas) style (subsequent incedences eg. potongan teluk belanga)
potter	potter
pp	pp
ppp	the ppp
ppsmi	ppsmi
pra	pre	pre-
pragmatik	pragmatic
pragmatisme	pragmatism
praktikal	practical
praktis	practical	practice
prasarana	infrastructure
prasasti	inscription	prasasti
prasejarah	prehistoric
prasekolah	preschool
prasyarat	precondition	prerequisite
predikat	predicate
pregnancy	pregnancy
premier	premiere	premier
presiden	president
pressure	pressure
prestasi	performance
pribumi	indigenous
prima	prime	prima
primer	primer	primary
primitif	primitive
prinsip	principle
prinsipprinsip	prinsipprinsip	principles
produk	product
produkproduk	products	productsour
produktif	productive
produktiviti	productivity
profesional	professional
profesor	professor
professional	professional
professor	professor
profil	profile
progesterone	rogesterone	progesterone
prognosis	prognosis
program	program
programprogram	program	programs
progresif	progressive
project	project
projek	project
proksi	proxy
promosi	promotion
propaganda	propaganda
prosa	prose	phrase
prosedur	procedure
proses	process
prosesproses	the process	the processes
prostat	prostate
protein	protein
protes	protest
protestan	protestant
protin	protein
proto	the proto
protocol	protocol
protokol	protocol
protoplanet	protoplanetary
protozoa	protozoa
provinsi	province
psikolinguistik	psycholinguistics	psycho linguistic	psycholinguistic
psikologi	psychology
psp	playstation portable
psychology	psychology
puak	tribe
puaka	ghost	gnome
puakpuak	tribes
puan	you
puas	satisfied
puasa	fasting
public	public
published	published
publishing	publishing
pucat	pale
pucuk	shoot	bud
pudar	fading	fade
puisi	poem	poetry
puja	obeisance	worship
pujaan	idol
pujangga	poet
pujian	praise
pukimak	mom pussy	posted pussy	curse your mother	curse word, literally "mother's genitals", equivalent to 'motherfucker'	mother fucker	scandium	pukimak	curse word, literally "mother's genitals, equivalent to 'motherfucker'	cunt
pukul	o'clock	time
pukulan	stroke
pula	also
pulai	pulai
pulang	return
pulangan	returns	return
pulau	island	land
pulaupulau	islands
pulih	recover
pulmonari	pulmonary
puluh	twenty
puluhan	tens	dozens
pulut	dumpling	sticky rice
pun	also
punca	sources	cause	source
puncak	peak
puncaknya	peak
pundi	bladder
pungutan	collection
puntung	stump	butt
punya	have
pupus	extinct	extinction
pura	shrine
purata	the average
purba	ancient
pusaka	heritage
pusat	center
pusatpusat	center
pusingan	rotation	round
pustaka	library
putaran	rotation
putd	putd
puteh	puteh	white
putera	son
puteranya	son
puteri	daughter
putih	white
puting	nipple	tip
putra	putra	son
putrajaya	putrajaya
putus	detach	off
q	q
qabliyyah	qabliyyah
qada	missed days
qadar	power	arabic word
qamari	lunar
qasar	qasr prayers
qatar	qatar
qauli	qauli
qin	qin
qing	qing
qs	quote
queen	queen
quidditch	quidditch
quraish	quraish
quraisy	quraisy	qura
quran	quran
ra	reported
rabu	lung	wednesday
rabung	ridge
racun	poison
radang	inflammation
radiasi	radiation
radikal	radical
radioaktif	radioactive
raffles	raffles
raga	body	basket
ragam	manner	manners
ragbi	rugby
raguragu	raguragu
rahim	uterus	rahim
rahman	rahman
rahmat	mercy
rahsia	secret
raifal	rifle
rais	rais
raja	king
rajah	diagram
rajang	rajang
rajaraja	kings
rajawali	hawk
rajd	rajd
rajin	hard working	diligent
rakaat	rakaat	cycles
rakaman	recording
rakan	friend
rakannya	his	its friend
rakanrakan	rakanrakan	friends
raket	racket
rakit	raft
raksa	mercury
raksasa	giant
rakyat	citizens	citizen
rakyatnya	the citizens	people
ram	ram
ramadan	ramadhan	ramadan
ramadhan	ramadhan	ramadan
ramai	many	more
ramalan	prediction	forecast
ramarama	butterfly
rambai	rambai
rambang	random	liberal
rambut	hair
rambutan	rambutan	rambutans
ramlah	ramlah
ramlee	ramlee
ramli	ramli	nelly
rampasan	plunder
rancangan	plan
rancanganrancangan	rancanganrancangan	shows
rang	draft
rangka	framework	frame	skeleton	structure
rangkaian	network	chain
rangsangan	stimulus
rantai	bird	chain
rantau	region
ranting	branch
rapat	close
rapi	snares	neat
rapuh	brittle	fragile
ras	race
rasa	think
rasanya	taste	its taste
rashid	rashid
rasional	rational
rasmi	official
rasminya	official	officially
rasuah	corruption	bribe
rasul	apostle	prophet
rasullullah	prophet
rasulnabi	prophet
rasulnya	god's prophet	truth
rasulullah	prophet
rata	flat
ratarata	ratarata
ratu	queen
ratus	hundred
ratusan	thousands	hundreds
raub	raub
rawa	swamp	marsh
rawak	random
rawang	rawang	mire
rawatan	treatment
rawatib	rawatib
raya	public	celebration
rayuan	appeal
razak	razak
razaleigh	razaleigh
razali	razali
re	re
read	read
reaksi	reaction
reaktif	reactive
real	real
realiti	reality
rebab	rebab (a traditional malay musical instrument)	fiddle
rebah	lie	collapse
rebana	tambourine
records	records
rectal	rectal
reda	down	subsided
reformasi	reformation
rehat	rest
reid	reid
rejam	stone to death	stoning	spear
rejim	regime
rejimen	regimen
reka	create	design
rekaan	invention
rekabentuk	design
rekod	record
rekreasi	reaction	recreation
rektum	rectum
rel	rail
rela	willing
relatif	relative
relatifnya	relative
relau	furnace
relevan	relevant
remaja	youths / teenagers	adolescent
rembau	rembau
remington	remington
rempah	spice
rempit	rampit
renaissance	renaissance
renal	renal
renang	swimming
rencana	story	plan
rendah	low
rengas	rengas
renggam	renggam
renjer	ranger
rentap	pull
rentas	cross
rentetan	string
replika	replica
report	report
reptilia	reptile	reptiles
republic	republic
republik	republic
reputasi	reputation
resam	customs
research	research
reseptor	receptors
resistance	resistance
resmi	official	quality
resources	resources
respirasi	respire	respiration
restoran	restaurant
restu	blessing
retak	crack
retina	retina
retrieved	retrieved
review	review
revolusi	revolution
revolusioner	revolutionary	revelusioner
reynald	renald	reynald
reza	reza
rezeki	sustenance	luck
rfc	rfc
ria	happy
riayat	riayat
riba	lap
ribu	thousand
ribuan	thousands
ribut	storm
rich	rich
richard	richard
ridzuan	ridzuan
rights	rights
rima	light	rhyme	rythm
rimau	tiger
rimba	jungle
rin	resistance
rinching	rinching
rindu	longing	miss
ringan	light
ringgit	dollars
ringkas	brief	concise
ringkasan	summary
ringkasnya	in short
rintangan	resistance
rintis	pilot
risalah	pamphlet	message
risau	worry	worried
risda	risda
risik	intelligence	rumor
risikan	intelligence
risiko	risk
risk	risk
riwayat	history
rizab	reserves
rm	myr
rmk	mp
rms	rms
road	road
robert	robert
robinson	robinson	english word
roboh	collapse	gave way
robot	robot
rock	rock
roda	wheel
rogol	rape
roh	soul	spirit
rohani	spiritual
rohaniah	spiritual
roket	rocket
rokok	cigarette
rom	rome
roma	rome	pore
romantik	romantic
rombongan	group
rompak	robbery
rompin	rompin
ron	ron is	ron
ronald	ronald
ronda	patrol	round
rondaan	patrol
rongga	cavity
roosevelt	roosevelt
rosak	broken	damaged
rotan	cane	rattan
roti	bread
rousseau	rousseau
routledge	routledge
royal	royal	flush
royalti	royalty
rrc	prc
rtm	rtm
ruang	room	space
ruangan	column	space
rugi	loss
rujuk	refer
rujukan	reference
rukuk	bow
rukun	pillar	rukan
rule	rule
rumah	home
rumahnya	his / her house	the house	home
rumahrumah	homes
rumahtangga	household	housewifery
rumi	latin	romanised
rumit	complicated
rumpai	seaweed	weed
rumpun	origin	cluster	family
rumput	grass
rumus	formula
rundingan	negotiation	talks	discussion
rungus	rungus
runtuh	collapse
runtuhan	ruins of	collapse
rupa	appearance
rupanya	apparently
rusa	deer
rusia	russia
russia	russia
rusuhan	riot
rusuk	rib	side
rutin	routine
rōshi	roshi
sa	sa
saadong	saadong
saat	second	moment	time
saba	saba
sabah	sabah
sabak	sabak
sabar	patient
sabda	word
sabit	sickle
sabtu	saturday
sabun	soap
sabut	fiber	sabbath
sadum	sadum
sah	valid
sahabat	friends	friend
sahaja	only
saham	share	stock
sahara	sahara
sahih	authentic
sahsiah	attitude	personality
sai	sai
said	said
saidi	saidi
saigon	saigon
saing	competitiveness
saingan	rival
sains	science	sainsscience	sciences
saint	saint
saintifik	scientific
saintis	scientist	scientists
saiz	size
saiznya	its size	size
saja	only
sajak	poem
sajian	dish
saka	perennial
sakit	pain
saksama	fair
saksi	witness
sakti	magic	magical
sakura	sakura
salad	salad
salah	wrong
salahudin	salahudin
salak	bark
salam	greeting
salasilah	genealogy
saleh	godly
salib	cross
salim	salim
salinan	copy
saling	mutual
saliran	drainage
salji	snow
salle	salle
salleh	pious
saloma	saloma
salur	tract
saluran	channel
salursalur	salursalur	vessels
sama	same
samaada	whether
samad	samad
samada	whether
samah	profile of the board	samah
saman	summons
samasama	together	win-
sambil	while
sambungan	connection
sambutan	welcoming	response
sami	sami	priest	monk
samiri	samiri
sampah	waste	rubbish
sampai	to	until
sampan	boat
sampel	sample
samping	as well as
sampingan	side
sampul	envelope
samseng	gangster
samudera	ocean
samurai	samurai
san	san
sana	there
sanak	relative
sanbi	sanbi
sang	sang	the
sangat	very
sanggup	willing	able
sangkar	cage
sanh	sanh
sanjaya	sanjaya
sanjungan	praise
sanskrit	sanskrit
santa	saint
santan	coconut milk	cocunut milk
sanusi	sanusi
sapi	cattle
sapu	broom	sweep
sapuan	sweep
sapukan	apply
sara	sustenance
saraf	nerve
sarah	sarah
sarang	nest
sarat	loaded
sarawak	sarawak
saringan	filtering
sarjan	sergeant
sarjana	bachelor degree	master
sarung	sheath	cover
sasaran	target
saser	saser
sassanid	sassanid
sastera	literature
sasterawan	literary	scholar
sasuke	sasuke
sate	satay	sate
satelit	satellites	satellite
satria	knights	knight
satu	one
satunya	only
satusatu	a
satusatunya	the only
saud	saudi	saud
saudagar	merchant
saudara	relative
saudaranya	relative	his brother
saudi	saudi
saujana	saujana	far as the
sawa	python
sawah	field
sawat	exchanges	exchange
sawit	oil palm
saya	i
sayang	love
sayap	wing	wings
sayong	sayong assists
sayur	vegetable
sayuran	vegetable
sayursayuran	vegetables
sbp	sbp
sby	sby
scientific	scientific
scotland	scotland
scott	scott
sdn	international sdn
sea	sea
seakan	like
seakanakan	as though	similar
seandainya	in the event that
search	search
seawal	as early as	as early
sebab	because
sebabnya	reason	why
sebabsebab	reasons	causes
sebagai	as
sebagaimana	as
sebagainya	so
sebagian	a part of	in part
sebahagian	some	partial
sebahagiannya	in part	part of it
sebaik	as soon as
sebaikbaiknya	properly
sebalik	behind	despite the
sebaliknya	otherwise
sebanyak	of
sebarang	not any	no
sebatang	a / an	a single
sebatian	compounds
sebegini	this	like this
sebegitu	so
sebelah	side
sebelas	eleven
sebelum	before
sebelumnya	prior	previous
sebenar	the actual	actual
sebenarnya	actually
sebentar	just a moment	"berhenti sebentar" means wait a while
seberang	opposite	apposite	no
seberapa	as much as
seberat	weighing
sebesar	as big as
sebiji	a	piece	a single
sebilangan	some
sebuah	a	a / an
sebulan	a month
sebutan	pronunciation
secara	in
second	second
sedang	is	in the process of
sedangkan	while	when
sedap	delicious
sedar	aware
sedekah	alms
sedemikian	such	like thus
sederhana	simple	moderate
sedia	available	ready
sedih	sad
sedikit	some
sedili	sedili
sedunia	worldwide
sedutan	suction	suctionr
see	see
seekor	a	an animal
segala	all	every
segalanya	everything	all
segamat	segamat	segment	district
segar	fresh
segelintir	a small portion	some
segenap	all
segera	immediately
segi	aspect	in
segitiga	triangle
segmen	segment
segolongan	some
sehari	a day	daily
seharian	daily
seharihari	seharihari
seharusnya	should
sehelai	a	piece	a piece
sehingga	to	untill
sehinggakan	so	until
sehinggalah	until
sehubungan	connection
seimbang	balanced
seiring	line	in line
sejagat	unversal	universal
sejahtera	prosperity	prosperous
sejajar	parallel
sejak	since
sejam	hourly	one hour
sejarah	history
sejarahnya	history
sejarahwan	historians
sejarawan	historian
sejatan	evaporation
sejati	true
sejauh	as far as
sejenis	a	type
sejuk	cold
sejumlah	a number of
sejurus	immediately	just
sejuta	a million	one million	million
sekadar	just about	just
sekali	once
sekalian	all	everyone
sekaligus	at once
sekalikali	in any way	once in a while	once
sekalipun	even though
sekalisekala	every now and then	occasionally
sekarang	now
sekata	uniform
sekatan	restrictions	stuck	hindrance
sekeliling	surrounding	around
sekelilingnya	around
sekelompok	a group of	group
sekeluarga	family
sekeping	a
sekerja	colleague
seketika	momentarily
sekian	so
sekiranya	if
sekitar	around/approximately	around
sekitarnya	surrounding	the surrounding
sekolah	school
sekolahsekolah	schools	school
sekretariat	secretariat
seks	sex
seksa	penalty	torture
seksaan	torture
seksual	sexual
seksyen	section
sektor	sector
sekuat	as strong as
sekular	secular
sekumpulan	group
sekunder	secondary
sekurangkurangnya	at least
sekuriti	securities	security
sekutu	ally
sekutunya	affiliates
sel	cell
selagi	as long as
selain	other than	besides
selaku	as
selalu	always
selalunya	always	often
selam	dive
selama	as long as	for
selamalamanya	forever
selamat	safe
selang	interval
selang-seli	alternating	the alternating	celang careful	criss cross
selangor	selangor
selanjutnya	further
selaput	layer	membrane
selaras	consistent	consistent / in line with
selari	parallel
selat	strait	strait ( the strait of malaya )
selatan	south
selawat	praises
selayang	brief	selayang
selebihnya	the remaining	remainder
selekoh	curve	bend
selepas	after
selepasnya	after	later on
selera	appetite
selesa	comfortable
selesai	completed
selesema	flu	cold / flu
selia	regulated
seliaan	tutelage	supervision
selidik	investigate	survey
seljuk	selijuks	seljuks
seluar	pants
seluas	vast	area
selular	celular	cellular
seluruh	all
seluruhnya	whole	wholly
semakan	review
semakin	more
semalaya	se-malaya	one malaya
semalaysia	nba record
semangat	spirit
semanggol	semanggol
semantan	semantan
semantik	semantic	semantics
semarang	semarang
semasa	during	time
semata	only
sematamata	alone	only
sembah	obeisance	worship
sembahyang	pray	prayer
sembilan	nine
semboyan	signal
sembuh	recover
sememangnya	is
semenanjung	peninsula	coast
semenjak	since
sementara	while
semesta	universe	universal
semestinya	necessarily
semi	semi
semikonduktor	semiconductor	semi conductor
seminar	seminar
seminggu	one week
sempadan	border
sempadannya	border
sempat	time
sempena	together with	after
sempit	narrow
semporna	of semporna	semporna
sempurna	perfect
semua	all
semuanya	all
semula	back
semulajadi	natural
semut	ant	ants
sena	sena
senai	senai
senaman	exercise
senang	easy	happy
senantiasa	always
senapang	gun	rifle
senarai	list
senario	scenarios	scenario
senat	senate
senator	senator
sendeng	eccentric
sendi	joint
sendiri	alone	own
sendirian	alone
sendirinya	itself
seng	zinc
sengaja	deliberate
sengit	fierce
seni	art
senibina	architecture
seniman	artist
senior	senior
senja	twilight / dusk	dusk
senjata	weapon
senjatasenjata	weaponry
sennin	by the end of
senoi	senoi
sensasi	sensation
sensitif	sensitive
sentiasa	always
sentimen	sentiment
sentosa	halcyon
sentral	central
sentuhan	touch
sentul	sentul
senyap	quiet	silent
seolaholah	as if	as though
seorang	a person	writing
sepadan	matching
sepak	football	kick
sepang	sepang	the sepang
sepanjang	along	together
sepanyol	spain
separa	halh	partial
separuh	half
sepasang	pair
sepasukan	team
sepatah	a few
sepatutnya	supposed
sepenuh	entire	full
sepenuhnya	fully
seperi	such as
seperti	such as	as
sepertimana	as
september	september	sept
sepucuk	sepucuk
sepuluh	ten
sepupu	cousin
serafim	the seraphim	serfim	seraphim
seragam	united	uniform
seramai	of
seramik	ceramic
serang	attack
serangan	attack
serangga	insect	blade
serantau	regional
serasi	compatible
serat	fiber
serata	around the
seratas	seratas
seratus	one hundred
seraya	while
serayu	serayu
serba	well
serbia	serbia
serbuan	invation	raid
serbuk	powder
serdang	serdang
serebrum	cerebral	cerebrum
seremban	the seremban
serendah	serendah	as low as
serentak	simultaneously
seri	draw
seribu	thousand
series	series
serigala	wolf
sering	often
seringkali	often
seringnya	frequently	frequency
serius	serious
serpihan	fragments
serta	and
sertamerta	immediately
seruan	call
seruling	flute
serupa	similar
server	server
service	service
servis	service
sesaat	moment
sesak	crowded
sesama	between
sesat	astray
sesawang	web
sesebuah	a
seseorang	someone	a person
sesetengah	some
sesetengahnya	some
sesi	session
sesiapa	anyone
sesuai	appropriate
sesuatu	something
sesudah	after
sesuka	as they please	as they
sesungguhnya	indeed
sesyen	sesyan	sessions
set	set
setahun	one year
setakat	so far	so far / as at
setanding	comparable
setapak	one step	setapak
setar	setar
setara	equal
setaraf	same standard	equal
setelah	after
setem	stamp
setempat	local
setengah	half
seterusnya	the next
setia	loyal
setiap	each
setiausaha	secretary
setimpal	appropriate	commensurate
setinggi	as high as
setuju	agree
seumpama	such	like
seumpamanya	like
seumur	lifetime
severus	severus
sewa	rent
sewajarnya	duly
sewaktu	sweaktu	when	at the time of
sexual	sexual
seychelles	seychelles
sezaman	same time	contemporary
sfera	sphere
sg	st
shafie	shafie
shakespeare	shakespeare
shall	shall
shang	shang
sharif	sharif
sharifah	sharifah
sharingan	sharingan
sheikh	sheikh
shen	shen
shikamaru	shikamaru
shizuka	shizuka
shukaku	shukaku	hukaku
si	the (referring to a person)	the
sial	unlucky
siam	siam
siang	day	afternoon
siap	ready	finish
siapa	who
siapakah	who
siaran	broadcast
siasatan	investigation
siasia	vain	futile
siber	cyber
siberia	siberia
sibuk	busy
sicily	sicily
sidang	council
side	side
siew	siew
sifar	zero
sifat	nature
sifatnya	characteristics	nature
sifatsifat	properties	nature
signifikan	significant
sihat	healthy
sihir	black magic	magic
sijil	certificate
sik	do not (slang)	kesamben
sikap	attitude
sikh	sikhism	sikh
siklon	cyclone
siku	elbow
sila	please
silam	past	ago
silang	crossword puzzle	cross
silap	wrong	mistaken
silat	martial
silika	silica
silikon	silicon	silicone
silinder	cylinder
simbol	symbol
simbolik	symbolic
simen	cement
simon	simon
simpan	store	reserve
simpanan	safe	reserve
simpang	corner	junction
simptom	symptoms
simulasi	simulation
sin	sin
sinar	ray
sinaran	shine	radiation
sindrom	syndrome
singa	lion
singapura	singapore
singgah	call
singgahsana	throne	visit	rest stop
singh	singh
singkat	short	brief
singkatan	abbreviation
single	single
sini	here
sinilah	this is where	here is	here
sinonim	synonym
sintaksis	syntaxis	syntax
sintesis	synthesis
sinus	sine	curve
siput	snail
sir	sir
sirajuddin	no less
sirap	syrup
siri	series
sirih	betel
sirius	dog-star	sirius
sisa	remains	waste
sisasisa	left overs	sisasisa
sisi	side
sisik	scale
sistem	system
sistematik	systematic
sistemik	systemic
sistol	sistole
siswazah	graduate	graduates
sitc	sitc
site	site
siti	siti	comments	siti is a name of a person in malay. it's more of a femine name.
sitiawan	sitiawan
situ	there
situasi	situation
situlah	there	where
sivil	civil
sk	sk
skala	scale	scala
skalar	scalar	scale	skalar	secular
skandal	scandal
skandium	scandium
skim	scheme
skop	scope
skor	score
skrin	screen	acreen
skrip	script
skru	screw	scew
skuad	squad
skuadron	squadron
skudai	skudai
skuter	scooter
sky	sky
slanga	informal	slang
slogan	slogan
slot	slot
sm	cm
smith	smith
smk	smk
sms	sms
snape	snape
so	so
soal	about
soalan	question	questions
soalansoalan	questions in	questions
sofbal	softball
sofbol	softball
software	software
soket	socket
sokongan	support
solat	prayer
solatsolat	praying praying	solatsolat	prayers
soleh	good	good muslim
solo	solo
solomon	solomon
somalia	somalia
sombong	arrogant
son	son
songket	songket
songsang	inverse	contradictory	inverted
sony	sony
sopan	polite
sosial	social
sosialis	socialist
sosialisme	socialisme	socialism
sosioekonomi	socio-economic
sosiologi	sociology
southeast	south east
soviet	soviet
soya	soy	soya
sp	sp
speaker	speaker
special	special
spektrum	spectrum
spell	spell
sperma	sperm
spesies	species
spesifik	specific
spesifikasi	specification
spesis	species
spontan	spontaneous
sport	sport
square	square
sri	sri
srivijaya	srivijaya	kite
sriwijaya	sriwijaya
stabil	stable
stadium	stadium
staf	staff
stamford	stamford
standard	standard
stanford	stanford
star	star
start	start
statik	static
station	station
statistics	statistics
statistik	statistics
status	status
statusnya	status	his / her status
statut	statute
steel	steel
stephen	stephen
stesen	station
stesyen	station
stigma	stigma
still	still
storan	storage
story	story
stpm	stpm  stpm
strategi	strategy
strategik	strategic
street	street	corror
stres	stress
strike	strike
strok	stroke
struktur	structure
stuart	stuart
studies	studies
studio	studio
study	study
style=fontsize	style = fontsize
su	teh
suai	adaptive
suam	warm
suami	husband
suaminya	husband
suara	voice
suaranya	voice
suasana	environment
suatu	certain	one
sub	sub
subang	earring	subang
subaraknoid	subarachnoid
subjek	subject
subsidi	subsidy
subspesies	subspecies	subspecies of
substrat	substrate
subtropika	subtropical
subuh	dawn
subur	fertile
suci	holy
sudah	already
sudahpun	has been	already
sudan	sudan
sudi	willing
sudirman	sudirman
sudut	corner	angle
suez	suez
sufi	mystics
sufyan	sufyan
suhaimi	suhaimi
suharto	suharto
suhu	temperature
suhunya	its temperature	temperature
suis	switch
sujud	prostration	prostrate
suka	like
sukan	sport	sports
sukansukan	sports
sukar	difficult
sukarela	voluntary
sukarelawan	volunteer
sukarno	sukarno
sukatan	measurement	measure
sukhoi	sukhoi
suku	quarter
sukusuku	sukusuku	the tribes
sulaiman	solomon	sulaiman
sulaman	embroidery
sulawesi	sulawesi
sulfur	sulfur
sulit	difficult
sulong	the eldest
sultan	sultan
sultanah	sultanah
sultansultan	sultanates
sultanul	sultanu'l
sulu	sulu
suluk	suluk	mysticism
sulung	eldest
sulungnya	his first
sumatera	sumatran	sumatra
sumatra	sumatra
sumazau	sumazau
sumbangan	contribution
sumbangannya	the contributions	contribution
sumber	source	resource
sumbersumber	resources
sumer	sumer
sumeria	sumerian
summary	summary
sumpah	oath
sumpahan	curse
sumsum	marrow
sunah	sunnah
sunan	arrangements
sunat	circumcision	encouraged
suneo	suneo
sung	sung
sungai	river
sungaisungai	rivers
sungguh	really
sungguhpun	although	in spite of
sunnah	practice	sunnah
sunni	sunni muslims
suntikan	injection
sunway	sunway (location)
sunyi	quiet
sup	soup	sup
supaya	so
super	super
superintendant	superintendant	superintendent
support	support
sura	sura
surabaya	surabaya
surah	chapter
surakarta	surakarta
surat	letter
surau	mosque	prayer
suri	housewives
suria	suria	solar
suruhanjaya	commission
surut	receding	recede
survey	survey
susah	difficult
susilo	susilo
susu	milk
susun	layout
susunan	arrangement
susur	fringe
sutan	teta
sutera	silk
suwa	leased
swasta	pivate	private
sweden	sweden
swettenham	cruise
syafaat	intercessor	help
syafie	syafie	shafi
syah	ruler	syah
syahadah	admission	testimony
syahid	syahid	syahid (name)
syahwat	orgasm
syair	poem
syaitan	devil
syak	suspicion
syam	syria	sham
syara	the shari'ah
syarak	islamic	lslamic
syarat	requirement
syaratsyarat	conditions
syariah	sharia	shari'ah
syariat	the tenets	tenets
syarikat	company
syarikatnya	company
syarikatsyarikat	company	companies
syeikh	seyikh	sheikhs
syiah	shiite	shia
syiling	coins
syirik	associate
symptoms	symptoms
syndrome	syndrome
syria	syria
system	system
systems	systems	system
syukur	thankful	thanks	grateful
syurga	heaven	paradise
t	t
taat	obey
tabiat	behavior
table	table
tabloid	tabloids
tabur	sprinkle
taburan	cluster
tadah	cistern
tadbir	management	governance	govern
tadi	just now
tadika	kindergarten	kindergarten / preschool
tafsir	commentary
tafsiran	interpretation
tahan	withstand	last
tahanan	detainee
tahap	stage
tahi	droppings	excrement	feces
tahir	tahir	pure
tahu	know
tahun	year
tahunan	yearly	annual
tahuntahun	subsequent	years
taib	taib
taipei	taipei
taiping	taiping
taiwan	taiwan
taj	taj
tajam	sharp
tajuk	title
tak	i	not
taka	taka
takat	extent	point
takdir	fate
takhta	throne
takkan	takken	will not
takluk	conquered	subject
takraw	takraw
takrif	definition
takrifan	definition
taksiran	estimate	assessment
taksonomi	taxonomy
taktik	tactics
taktikal	tactically	tactical
takut	fear
takwim	calendar
talak	divorce
talang	chamfer
talasemia	thalassemia	thalassaemia
tali	rope
talian	online
tamadun	civilization
taman	park	garden
tamaninah	momentary pause
tamat	end
tamatnya	the conclusion
tambah	add
tambahan	addition	additional
tambang	tol fare	mine
tambun	tambun	fat
tamil	tamil
taming	taming
tampak	appearance	appear
tampar	volleyball	slap
tampil	show up
tampin	tenganan
tan	a title given to those who have served well to benefit both public and country through status or action	tonnes
tanah	soil	land
tanahair	home	homeland
tanahtanah	lands	land
tanam	plant
tanaman	translate from: indonesian crop	crop
tanda	sign
tandan	cluster
tandas	toilet
tandatanda	sign of	signs
tandatangan	signature
tanduk	horn
tang	tang
tangan	hand
tangannya	his hand	hand
tangga	steps	tengga	stairs
tanggal	date	tenggal
tanggang	unkempt	tanggang
tanggapan	perception
tanggung	bear
tanggungan	dependent
tanggungjawab	responsibilities	responsibility
tangkai	stalk	branch
tangkas	nimble	adept	agile
tangki	tank
tangkis	shuttlecock
tanglung	lanterns	lantern
tani	agriculture	farmer
tanjakan	upgrade
tanjong	tanjong	bay
tanjung	cape
tanpa	without
tanya	ask
taoisme	taoism
tapah	tapah
tapak	site
tapi	but
tar	tar
tara	tara
taraf	standard
tarafnya	status	his/her status
tari	dance
tarian	dance
tarikan	attraction
tarikh	date
tarikhtarikh	date	tarikhtarikh	the dates
tariqat	sufi
tasawuf	mysticism
tasek	lake
tasik	lake
tatabahasa	grammar
tatacara	procedure
tatkala	when
taufan	typhoon	storm
tauhid	unity of god
taun	epidemic
taurat	rabbis
tawan	conquer	captured
tawanan	captive	captives
tawar	fresh	tawar
tawaran	offer
tawau	tawau
tayangan	screening
tayar	tires
tea	tea
team	team
teater	theater
tebal	thick
tebing	edge
tebrau	tebrau
tebu	sugarcane	cane
tebuan	wasps
tebusan	ransom	repayment
technology	technology
tegak	erect
tegal	gallant	tegal
tegang	tense	stiff
tegar	firm	rigid
tegas	strict	decisive
tegasan	stresses
teguh	firm	robust
teh	tea
tekanan	pressure	preasure	pressures
teknik	technique	technic
teknikal	technical
teknikteknik	teknikteknik
teknologi	technology
teks	text
teksi	taxi	taxi cab
tekstil	textiles
tekun	hardworking	diligent
tel	tel
teladan	example
telaga	well
telah	was done	has
telahpun	has	has already
telapak	palm	tread
telefon	phone
telekom	telecom
telekomunikasi	telecommunication
teleskop	telescope
televisyen	television
telinga	ear
teliti	careful
telok	telok	bay
telor	having a speech impediment	egg
teluk	bay
telunjuk	index finger
telur	eggs	egg
tema	themes	theme
teman	friend	companion
tembaga	copper
tembakan	shot	shots
tembakau	tobacco
tembeling	tembeling
tembikar	china
tembok	wall
temenggong	manager	temenggong
temenggung	chief of security
temerloh	temerloh
tempa	wrought	hammering
tempahan	booked	booking / reservation	online
tempat	place
tempatan	local
tempatnya	place
tempattempat	places
tempayan	crock
templar	templa
tempoh	period
tempur	combat
tempurung	shell
temu	an	a name of a place "padang temu", temu also means meet
tenaga	energy
tenang	relaxed	quiet	calm
tengah	middle
tengahtengah	middle	the center
tenggang	tenggang	effort
tenggara	south east	southeast
tenggelam	sink
tengkorak	skull
tengku	tengku
tenis	tennis
tenom	tenom
tentang	about
tentangan	opposition
tentara	army
tentera	military	army
tenteram	quiet
tenteranya	army
tentu	certain	of course	surely
tentulah	surely	would
tenunan	wavw	weave
tenusu	dairy
teochew	teochew
teologi	theology
teorem	theorem
teori	theory
teoriteori	theories	and applied
tepat	accurate	accurat
tepatnya	precisely
tepi	edge	side
tepu	saturated
tepung	flour
terakhir	last
terakhirnya	last
teramai	most	busiest	most populous
terancam	threatened
terancang	organised	planned
terang	bright
terangsang	inflame
terangterangan	overt	terangterangan
terapi	therapy
terapung	floating	float
teras	terrace
terasa	felt
terasing	separated	isolated
teratai	lotus
teratas	top
teratur	neat	in order
terawal	earliest
terbabit	involved
terbahagi	divided
terbaik	best
terbakar	on fire
terbalik	reverse	best
terbang	fly
terbantut	stunted
terbanyak	most
terbaru	latest
terbatas	limited
terbenam	set
terbentang	spread
terbentuk	formed	form
terbentuknya	formation
terbesar	the largest	largest
terbilang	distinction	glorious
terbina	build	built
terbit	rise
terbitan	issue	published
terbitnya	rises	rising
terbuka	open
terbukti	proven
terbunuh	killed
terburuburu	rushing
tercapai	reached	achieved
tercatat	recorded
tercedera	injured
tercemar	contaminated	polluted
tercetus	sparked	broke
tercinta	beloved
terciptanya	invented	creation
terdahulu	preceding	earlier
terdahulunya	the former
terdapat	found	there
terdapatnya	there are	availability
terdedah	exposed
terdekat	the nearest	closest
terdengar	heard
terdesak	desperate
terdiri	consists of	consist
terdorong	pushed
terendah	the lowest
terestrial	terrestrial
terganggu	disturbed
tergantung	suspended	hanging
tergolong	classified	grouped/ belongs to
terhad	limited
terhadap	against
terhadapnya	towards	against
terhasil	produced	the resulting
terhenti	stopped
terhingga	finite	limitless	finite finite
terikat	bound
terima	received	accept
terjadi	occur	happened
terjadilah	outcome was	became	there was
terjadinya	occurence	occurrence
terjamin	guaranteed
terjangkit	infected
terjejas	affected
terjemahan	translation
terjual	sold	sold out
terjun	plunge
terkandung	contained
terkawal	controlled
terkaya	the richest
terkecil	smallest	the smallest
terkecuali	excepted	exception
terkejut	shocked
terkeluar	come out	out
terkemuka	leading
terkena	contact	incurred
terkenal	famous
terkini	latest
terkorban	casualties	killed
terkuat	strongest
terkumpul	collected	accumulated
terlak	terlak
terlalu	over	too
terlampau	over	too
terlarut	dissolved
terlatih	trained
terlebih	firstly	exceed	first
terlepas	escaped	released
terletak	situated
terletaknya	lies
terlibat	involved
terlihat	seen
terlindung	protected
terma	thermal	terms
termaju	most advanced	advanced
termaktub	enshrined
termasuk	including
termasuklah	including
termasuknya	included
termasyhur	famous	well known
terminal	terminal
termionik	thermionic emission	thermionik
termokimia	the thermochemical	thermochemistry	themochemistry	thermo chemical	thermochemical
termosfera	thermosphere	termosphere
ternakan	livestock
ternama	well-known	famous	renowned
ternyata	it appears
teromba	teromba
terowong	tunnel
terpaksa	forced
terpanjang	the longest	longest
terpelajar	educated
terpelihara	reserved
terpencil	isolated
terpengaruh	influential	influenced
terpenting	most important	the most important
terperangkap	trapped
terperinci	detailed	detail
terpilih	selected / chosen	selected
terpisah	seperate	separate
terpuji	commendable	praiseworthy
tersangkut	stuck
tersebar	spread
tersebut	said
tersedia	available	avaiable
tersekat	stuck	jammed	block
terselamat	survivors
tersembunyi	hidden
tersenarai	listed
tersendiri	distinctive	own	separate
terserlah	highlighted
tersesat	lost
tersibuk	busiest
tersimpan	contained	stored
tersirat	implicit
tersohor	renowned
tersumbat	clog
tersusun	organised	structured
tertakluk	subject
tertarik	attracted	interested
tertentu	certain
tertera	printed
tertib	orderly	order
tertinggal	left behind	left out
tertinggi	hertinggi	top
tertua	eldest
tertubuhnya	establishment	formation
tertulis	written
tertumpu	concentrated	focused
tertutup	closed
teruk	severe	bad
terulung	top	greatest
terumbu	reef
terunggul	top	premier
terus	continue	continue / direct
terusan	canal	cannels
terutama	especially
terutamanya	particularly	especially
tesco	tesco
test	test
tet	tet
tetamu	guests	guest
tetap	still	fixed
tetapi	but
tetaplah	remains	still	it is
tetikus	mouse	computer mouse
tetingkap	window
tewas	lost	lose
texas	texas
th	t.h
thai	thai
thailand	thailand
thalib	talib
thani	thani
the	the
their	their
they	hire
thomas	thomas
three	three
thumb|	thumb
thumb|px|peta	thumb|px|map
thumb|right|px|anggota	thumb|right|px|member
tiada	no
tiadanya	absence
tiang	pillar
tiap	each
tiaptiap	every office
tiba	arrive
tibatiba	suddenly	lasting
tibet	tibet
tidak	not
tidaklah	not
tidur	sleep
tifus	typhoid	typhus	tifus	typhos	typus
tiga	three
tigers	tigers	newspapers
tikar	mat
tiket	ticket
tikus	rat	mouse
tilam	mattress
timah	copper	tin	cassiterite	lead
timbalan	deputy
timbalannya	his deputy	diputy	deputy
timbang	weigh	weights	scales
timbul	arise
timbullah	arises	occured	occurred
timbulnya	emerge
timor	timor
timun	cucumber
timur	west
timurnya	the east of	eastern
tin	tin	can (ie. aluminum can)
tindak	action
tindakan	action
tindakannya	his / her actions
tindakantindakan	actions
tindakbalas	reaction	the response
tinggal	left
tinggalan	remains
tinggi	high
tingginya	height
tingkah	behavior
tingkap	window
tingkat	storey
tingkatan	form	level
tinja	defecate	excrement	waste / excretion	poo	feces	faces	discharge	waste / excrement
tinjauan	review	observation
tinju	boxing
tioman	tioman	tioman island
tiong	tiong	redhill
tipikal	typical
tipis	thin
tipu	trick	lie
tiri	step	step-
tiroid	thyroid
tiruan	imitation
tisu	tissue
tisutisu	the tissues
titah	word	royal decree
titanic	titanic
titi	bridge
titian	bridge
titik	point
titisan	drops
titiwangsa	the titiwangsa
tiub	tube
tiupan	gust	blast
tldm	rmn
tnm	tnm
today	today
toh	anyway
tok	tok	uncle	village
tokoh	figure
tokohtokoh	notables
tokong	temple
toksik	toxic
tokugawa	tokugawa
tokyo	tokyo
tol	toll
tolak	push
toleransi	tolerance
tolong	please	help
tom	tom
tomato	tomato
tombak	spear
ton	ton
tong	barrel
tongkat	cane	staff
topi	cap / hat	hat
topik	topic
topografi	topography
toraks	toraks	troacic	thoracic	toracs	thorax
total	total
tower	tower
towerdubai m ft	towerdubai m ft	tower dubai m ft
towers	towers
toyota	toyota
track	track
tradisi	tradition
tradisinya	traditionally
tradisional	traditional
tradisitradisi	traditional	tradisitradisi
traditional	traditional
trafik	traffic
tragedi	tragedy
transformasi	transformation
translation	translation
transliterasi	transliteration
transmisi	transmission
trauma	trauma
tree	tree
trek	track
tren	trends	train
trend	trend
trigonometri	trigonometry
trilion	trillion
trimester	trimester
trio	trio
trombosis	thrombosis	trombosis
trombus	thrombus
tropika	tropical
truper	trooper	troops
tsunami	tsunami
tua	old
tuah	good luck
tuai	harvest
tuala	towel
tuan	host	master
tuang	cast
tuanku	lord	your majesty
tuannya	the owner	master
tuanya	age	parents
tuaran	tuaran
tuatua	elders	elderly
tubuh	body
tubuhnya	body	her
tudm	rmaf
tuduhan	charge
tudung	scraf	headscarf	cover
tugas	task
tugasan	assignment	tasks
tugasnya	his	his / her duties	task
tugastugas	tasks	the functions
tugu	monument
tuhan	god
tuhanku	from my	my god
tuhanmu	your god
tuhantuhan	gods	deities
tuisyen	tution	tuition
tujuan	objective	purpose
tujuannya	purpose
tujuh	seven
tukang	workman	handyman
tukaran	exchange
tukul	hammer
tulang	bone
tulangtulang	bones	tulangtulang	bones bones
tulen	pure
tulis	write	written	write / writing
tulisan	writings	writing
tumbang	fall
tumbuh	gro	grow
tumbuhan	plant
tumbuhtumbuhan	vegetation
tumit	heel
tumor	tumour
tumpah	spill
tumpat	dense	tumpat
tumpuan	concentrations	concentration
tumur	tumor
tun	a title given to a few honorific people in malaysia	the tun
tunai	cash
tunas	shoot
tunduk	avoid	submit
tunggal	single
tunisia	tunisia	tunisian
tunjang	cord
tunjuk	point	show
tunku	tunku	an honorary title given in malaysia
tuntutan	claim
tuntutannya	claim
tupai	squirral	squirrel
turki	turkey
turun	stepped down	raised down	descend
turunnya	step down	descended	fall
turuntemurun	for generations	hereditary
turus	column
turut	also
turutan	succession
tutong	tutong
tutorial	tutorial
tutup	close	closed
tv	television
two	two
typhoon	typhoon	richoz
u	u
ubah	change
ubat	drugs	medicine
ubatubatan	drugs
ubi	tuber
ucapan	speech
uchiha	uchiha
uda	younger
udang	prawn	shrimp
udara	air
ufti	tribute
ugama	religion
uiam	iium	iiam
uji	test
ujian	test
ujong	ujong
ujung	tip
uk	uk
ukiran	carving
ukm	ukm
ukur	measuring	measure
ukuran	measurement
ulama	scholar	muslim scholars	muslim scholar	scholarsa	religious scholars	scholars	islamic scholar
ulang	anniversary
ulangalik	alternating	to & fro
ular	snake
ulasan	review
ulat	worm
ulu	ulus	ulu
uluhiyah	uluhiyah
ulung	accomplished	outstanding
um	um
umaiyyah	umayyads
umar	umar
umat	community	people
umatnya	his followers	the followers
umayyah	umayyad
umbi	root
umbridge	umbridge
ummah	society	community
ummaiyyah	utsman
ummu	umm	ummu
umno	raman
umpamanya	for example	such as / for example
umpan	bait
umrah	umrah	visitation
umum	general
umumnya	generally
umur	age
undang	law
undangan	invitation
undangundang	law	laws
undi	vote	poll
undian	voting	volting
unesco	unesco
unggul	superior
ungkapan	phrase	expression
ungku	ungku
ungu	purple
unik	unique
unit	unit
united	united
unitunit	units
universiti	university
universitiuniversiti	universities	university
unix	unix
unsur	element
unsurunsur	unsurunsur
unta	camel
untuk	to	for
untuknya	for him / her	it	for it
untung	profit
unuk	merits
up	up
upacara	ceremony
upacaraupacara	ceremony	events
upah	wage
upahan	hired worker	hired labour
upaya	effort
upin	upin	mr
upm	upm
upsr	upsr
urat	nerves
uri	spinning point of the top
urik	uric
urus	governance
urusan	matter	business
urutan	order	sequence
usa	usa
usaha	effort
usahanya	efforts	its
usahausaha	efforts
usahawan	entrepreneur	enterpreneur
used	used
usia	age
usj	usj
usm	usm
usman	usman
uss	uss
ustaz	teacher
usually	usually
usul	origin	motion
usus	intestine	intenstine
utama	main
utamanya	main	the main
utara	north
utaraselatan	north-south	utaraselatan
uterus	uterus
uthman	uthman
uthmaniyyah	ottoman	uthmaniyyah
utiliti	utility
utk	for
utuh	intact
utusan	envoy
uzumaki	uzumaki
v	v
vagina	vagina
vaksin	vaccine
vakum	vacuum
valley	valley
van	beethoven	van
variasi	variation
varieti	variety
vaskular	vascular
vektor	vector
vena	venous
venice	venice
ventrikel	ventricle
versi	version
vertebra	vertebral	vertebra
vichy	vichy
victor	victor
victoria	victoria
video	video
vienna	vienna
vietnam	vietnam
vincent	vincent
virtual	virtual
virus	virus
virusvirus	viruses
visi	vision
visual	visual
vitamin	vitamin
vivax	vivax	vivaz
vokal	vowel	vocal
vokasional	vocational
voldemort	harry
voltan	voltage
volume	volume
von	von
vs	versus
vulva	vulva
w	w
wa	we	wa
wabak	outbreak	oubreak
wadah	container
wafat	died
wafatnya	death
wah	wow
wahab	wahab
wahabi	wahhabism
wahai	dear / o (as in o lord)	wahai	oh
wahid	single
wahyu	revelation
wain	wine
waja	steel
wajah	face
wajar	proper
wajib	compulsory
wakaf	endowment
wakil	representative
wakilwakil	wakilwakil	representatives
waktu	time
waktunya	time
waktuwaktu	waktuwaktu	time	times
walau	although
walaubagaimanapun	anyhow	however
walaupun	although
wales	wales
wali	guardian
walk	walk
wan	wan
wang	money
wangi	nice smell	fragrant
wangsa	dynasty
wanita	woman
wanitawanita	wanitawanita	women
wap	vapor	steam	vapour
war	war
waran	warrant
warga	people
warganegara	citizen
waris	heir
warisan	heritage
warna	color	colour
warnanya	color
wartawan	reporter
was	was	war
wasallam	yours respectfully	wasallam
washington	washington
wasiat	will
watak	character
watakwatak	the characters	characters
wataniah	territorial	no comments
wawasan	insight	vision
wayang	movie
wayar	wire
we	we
weasley	weasley
weber	weber
wei	wei
were	were
west	west
westminster	westminster	the westminster
westmoreland	westmoreland
what	what
while	while
white	white
wikipedia	wikipedia
wilayah	region	territory
wilayahnya	territory
wilayahwilayah	region
wilhelm	wilhelm
william	william
willis	willis
wing	wing
wira	hero
with	with
witir	witr
women	women
work	work
would	would
wto	wto
wu	of wu
wudhu	ablution	a place where malays go to wash thier feet before entering thier mosque, to purify themselves
wuduk	ablution
wujud	existence
wujudnya	existence
xavier	xaview
xbox	xbox
xia	xia
xian	xian
xinjiang	xinjiang
xp	xp	windows xp
y	alphabet	the y
ya	yes
yaakob	yaakob
yaakub	jacob	yaakub
yahudi	jewish	jews	jew
yahwe	yahweh
yaitu	that is
yakin	confident
yakni	that is
yam	yam
yaman	yemen
yan	yan
yang	that
yasmin	yasmin	yasmin (name)
yassin	yassin
yathrib	yathrib
yatim	fatherless
yawm	yawm
yayasan	foundation
yazid	yazid was
yb	yb
ybhg	elect
years	years
yesus	and he	jesus
yew	yew
yg	i
yin	yin
yogyakarta	yogyakarta
yong	yong
york	york
your	your
yu	shark
yudhoyono	yudhoyono
yuk	yuk	go ahead
yunani	greek
yunnan	yunnan
yunus	yunus	jonah
yuran	fee	fees
yusof	yusof
yusoff	yusoff
yusuf	yusuf
zahid	zahid	ascetic
zahir	apparent	physical
zaid	zaid
zainab	zainab
zainal	zainal
zaini	zaini
zakar	penis	zahar
zakaria	zakaria
zakat	alms
zalim	cruel	tyrannical
zaman	era	time
zamanzaman	the times	eras
zamzam	of zamzam
zarah	particle
zarahzarah	particles
zat	substance
zaza	zaza
zealand	zealand
zedong	zedong (name)	zedong
zetabit	zetabyte	zetabit
zeus	zeus
zhongguo	zhongguo
zhou	the zhou	zhou
zhu	zhu
ziarah	pilgrimage	visit
zimbabwe	zimbabwe
zina	adultery
zink	zinc
zionisme	zionism
zirkonium	zirconium zirconium	zirconium	zirkonium
zohor	zuhr	zohor
zon	zone
zoo	zoo
zuckerberg	insider
zuhal	saturn
zuhrah	venus
zuhur	noon
zulaikha	zulaikha	she
zulkifli	zulkifli
 batu	stone	mile
 juta	million
 km	kilo meter	km
 m	m
 °c	c
الله	allah
بن	bin
تانه	land
دان	this urudu
→	--->
