+	+
<i>	<i>
=	=
a	and
a^	and	a^
aalebo	and / or
ab	b	ab
abc	abc
abeceda	alphabet
abecedy	alphabet	alphabetical
abrázia	abrasion
absolvovaní	graduating
absolútna	the absolute
absolútne	absolutely
absolútnu	the absolute	absolute
aby	to	that
achát	cialis	included in	agat	included	agate	ark
act	act
ad	ad
adam	adam
adama	adam
adidas	adidas
administratívne	administrative
administratívnych	administrations	administrative
adolf	adolf
adresa	address
adresu	address
adresy	addresses	address
adries	addresses
advent	advent
afganistan	afghanistan
afganistane	afghanistan
afganistanu	afghanistan
afrika	africa
afrike	africa
afriky	africa
ag	ag	g
agent	agent
aids	aids
air	air
aires	aires
aj	also
ak	if
akademický	academic	academically
akadémia	academy
akadémie	academy
akcia	action
akcie	actions
akcií	share	actions
akej	what	which
akejkoľvek	any
ako	as	if
akoby	as if	like
akou	such
akt	act
aktivita	activity
aktivite	activity
aktivitou	activity
aktivitu	activity
aktivity	activities
aktivít	active	activities
aktuálne	actual
aktívna	active
aktívne	active
aktívnych	active
aká	what	which
akákoľvek	any
aké	what	if
akéhokoľvek	any
akékoľvek	any
akési	sort of	somewhat
akú	battery
aký	what
akýkoľvek	any	any resource
akým	which
akými	such as	such
albert	albert
alberta	alberta	albert
albrecht	albrech	albrecht
album	album
albume	album
albumom	album	albums
albumov	album
albumu	album
albumy	albums
albánci	albanians
albánska	albanian	albania
albánsko	albanian	albania
aldrin	aldrin
ale	but
alebo	or
alela	allele	allelomorph
alexander	alexander
alexandra	alexandra
alexandria	alexandria
alexandrov	alexandar	alexander's
alexandrovi	alexander
algoritmus	algorithm
ali	ali
aljaška	alaska
aljašky	alaska
alkohol	alcohol
alkoholu	alcohol
all	all
alo	alo
alpha	alpha
alpy	alps
alternatívne	alternatively
alternátor	alternator
alžbeta	elizabeth	elisabeth
alžbety	elizabeth	elisabeth
am	am
amd	amd
american	american
americkej	u.s.	american
americkom	american
americká	american
americké	american
amerického	american
americkí	american	u.s.
americký	american
amerických	american
americkým	american
amerika	america
amerike	america
ameriky	america	amerika
američania	americans
američanov	americans
amiotvaré	bowfin	amiiform	amiiformes	amiotvare	amiformes	amiliformes
amoniak	ammonia
analýza	analysis
analýzy	analysiss	analysis
anatómia	anatomy
and	and
andragogika	andragogy
andrej	andrej	andrew
andreja	andreja	andrew
andy	andy
angeles	angeles
angl	english
anglicka	england
anglickej	english
anglicko	england	english
anglickom	england	english
anglicku	england
anglicky	english
anglická	england	english
anglického	english
anglický	english
anglických	english
angličtina	english
angličtine	english
angličtiny	english
ani	neither	or
anjel	angel
anjela	angel	angela
anjeli	angels
anjelov	angels
anna	anna
annalen	annalen
anny	annie's	anny	anna
anorganických	inorganic
ansoff	ansoff
anticipácia	anticipacia	anticipation
antické	antique
antických	antique	antiquity
antika	antiquity
antipatia	apathy	antipathy
antona	anton
antonio	antonio
aparátu	appliances	apparatus
aplikácia	application	aplication
aplikácie	application
aplikácií	aplications	what application
apollo	apollo
appetite	appetite
apple	apple
apríl	april
apríla	april
apríli	april
arabi	arabi	arabs	arabians
arabské	arab
arabských	arab
archeologické	archeologic	archaeological
archeologických	archaeologicals	archaeological
architekt	architect
architekta	architect
architekti	architects
architektonické	architectural
architektúra	architecture
architektúre	architecture
architektúrou	architecture
architektúru	architecture
architektúry	architecture
archív	archives	archive
arcibiskup	archbishop
arcibiskupa	archbishop	archibishop
arctos	arctos
are	are
area	area
arena	arena
areál	areal
areáli	campus	area
areálu	complex	campus
argentína	argentina
argentíny	argentina
argument	argument
aristotela	aristotle
aristoteles	aristotle
aristotelova	aristotle
armstrong	armstrong
armád	armies	army
armáda	army
armáde	army
armádu	army
armády	army
arménska	armenian
arménsko	armenian
artefakty	artifacts
arthur	arthur
aréna	arena
as	as
ash	ash
asi	about
asistent	assistant
asociácie	the association of	association
aspekty	aspects
aspoň	at least
assisi	assisi
association	association
astronomické	astronomical
astronómovia	astronomers
atentát	assassination
atlantického	atlantic	the atlantic
atlantický	atlantic
atlas	atlas
atmosféra	atmosphere
atmosfére	atmosphere
atmosférický	atmospheric
atmosférou	atmosphere
atmosféru	atmosphere
atmosféry	atmosphere
atomárny	nuclear	atomically	atomical	atomic
atp	etc.
atramentu	ink
aténach	athens
atény	athens
atóm	atom
atómami	atoms
atómov	atoms
atómových	nuclear	atomic
atómu	atom
atómy	atoms
atď	etc.
audio	audio
august	august
augusta	august
auguste	august
aus	aus
auschwitz	auschwitz
austrália	australia
austrálie	australia
austrálii	australia
austrálsky	australian	australia's
autobusy	buses
automaticky	automatically
automobil	car
automobilov	car
autonómie	autonomy
autonómiu	autonomy
autonómne	autonomously	autonomous
autor	author
autora	author
autori	authors
autoritu	authority
autorom	author
autorov	authors
avšak	but
awards	awards
azda	maybe
a jeho	and
až	and	to
b	b
ba	ba
babylonii	babylonia
babylonu	babel	babylon
bach	bach
bad	bad
baktérie	bacteria	microbes	ba
baktérií	bacteria
baltského	baltic
baláž	balaz
balík	package
bank	banks
banka	bank
bankoviek	notes
bankovky	bills	bank notes
banky	bank
banskej	mining	banská
banskobystrický	banskobystrický	banska bystrica
banská	banska
bar	bar
barcelona	barcelona
barcelony	barcelona
bardejov	bardejov
bariéry	barriers
barok	baroque
baroka	baroque
baroková	baroque
barokové	baroque
barça	barca
baset	basset
basketbal	basketball
bazilika	basilica
bašta	stronghold	bashta	bastion	hradby	basta
bb	bb
bbc	bbc
bd	bd	blu-ray disc (bd)
be	be
beagle	beagle
beatles	beatles
beethoven	beethoven
beh	run
bela	bela
belgicka	belgium
belgicko	belgium
bell	bell
ben	ben
benedikt	benedict
benedikta	benedict	benedikt
beneš	beneš	benes
benátky	venice
benátok	venice
berlín	berlin
berlína	berlin
berlíne	berlin
bernoláka	bernolaka	bernolak
best	best
beta	beta
bez	without
bezdeda	bezdeda
bezpečnosti	security	safety
bezpečnostnej	security
bezpečnostné	security	of safety
bezpečnosť	security	safety
bezpečné	safe	safety	securely
bezprostredne	immediately
bežne	normally	common
bežnej	normal
bežné	normally	common
bežného	current	common	normal
bežný	common
bežných	common
bi	bi
biblia	bible
biblie	bible
biblii	bible
bicie	percussion	drums
biela	white
biele	white
bieleho	white
bielej	white
bielkoviny	protein	proteins
bielkovín	protein	proteins
bieloruska	belorussia	belarus
bielorusko	belarus
bieloruská	belarussian	belarus
biely	white
bielych	white
bielym	white
bill	bill
billboard	billboard
biologických	biological
biskup	bishop
biskupa	bishop
biskupom	bishop
bitka	battle
bitke	battle
bitky	battle
blaho	blaho (name), good (second and third sentence)	welfare
blanc	blanc
blanokrídlovce	venom	hymenoptera	hymenopterans	poison	ants and wasps
blesku	flash	lightning
bližšie	more
blok	block
blokov	blocks
bloku	block
bloky	blocks
blues	blues
bluetooth	bluetooth
bluray	blu-ray
blízke	the near	near
blízkeho	close	near
blízkej	close	near
blízko	close
blízkom	middle
blízkosti	close	near
blízky	close	middle
blízkych	close
bob	bob
bod	point
bode	point
bodoch	podoch	points
bodom	point
bodov	points
bodu	point
body	body	points
boeing	boeing
boh	god
boha	god	bog
bohato	richly
bohatstvo	wealth
bohatá	rich
bohaté	rich
bohatú	richly
bohatý	rich
bohatých	rich
bohom	god
bohov	gods
bohovia	gods
bohu	god
bohužiaľ	unfortunately
boj	fight
boja	color	fight
boje	fight
boji	fight
bojisku	battlefield
bojoch	fights	fighting
bojov	fights	fighting
bojoval	fought
bojovali	fought
bojovalo	fought
bojovať	fight
bojovníkov	fighters
bojové	martial	combat
bojových	martial
bojujúcich	fighting
bokoch	sides
boku	side
bol	was
bola	was
boli	been	were
bolin	bolin
bolo	was	were
bombardovanie	bombardment
bonaparte	bonaparte
bond	bond
bondgirl	bond girl
boris	boris
bosna	bosnia
bosny	bosnia
botto	botto
boys	boys
boľševici	the bolsheviks
božej	god	divine
božie	gods	of god
božieho	god
boží	god
brat	play	brother
brata	brother
bratia	brothers
bratislava	bratislava
bratislave	bratislava
bratislavského	the bratislava	bratislava
bratislavský	of bratislava	bratislava
bratislavu	bratislava
bratislavy	bratislava
bratov	brother's	brothers
brazília	brazil
brazílie	brazil
brazílii	brazil
brať	brother
breh	shore	bank
brehoch	banks
brehu	bank
bridge	bridge
brigádny	brigadier
brigády	brigades	brigade
britskej	british
britská	british
britské	british
britského	british
britský	british
britských	british
británia	britain
británie	britain
británii	britain
bronzová	bronze
brána	gateway
bráni	obstructs
brániaci	defensive
bránili	prevented
brániť	defend	protect
brány	gate
bubeník	drummer
budapešti	budapest
budapešť	budapest
bude	will
budeme	we	we will be
budov	buildings
budova	building
budovať	construct
budove	building
budovy	building
budú	will be
budúce	future
budúceho	of next	next
budúci	next
budúcich	future	next
budúcnosti	future
budúcnosť	future
buenos	buenos
bulharska	bulgaria
bulharsko	bulgaria
buniek	cells
bunka	cell
bunke	cell
bunkovej	cell
bunky	cells
bunkách	cells
bush	bush
buď	either
by	by
bystrica	bystrica
bystrice	bystrica
bystrici	bystrica
bytia	being
bytie	being
bytosti	being	beings
bytosť	being
byzantskej	byzantine
byzantská	byzantium
byzantského	byzantine
byť	flat	to be
báj	baj
báseň	poem
básne	poems
básnici	poets
básnik	poet
básní	poem
báz	base
báze	base
búrky	burqa
býva	live	lives
bývajú	tend to be
býval	lived
bývalej	of the former	former
bývalá	used to
bývalé	former
bývalého	former
bývalí	past	his former
bývalý	former
bývalých	former
c	c
ca	ca
cambridge	cambridge
camp	camp
cassini	cassini
cca	about
cd	cd
celej	all	full
celkom	quite
celkovej	total
celkovo	overall
celkovou	total	all round
celková	total
celkové	total
celkového	total
celkový	the total
celku	unit
celky	units	sets
celok	whole
celom	around the	whole
celosvetovo	worldwide
celou	a	whole
celá	cell	the whole
celé	fully
celého	the whole	whole
celú	cell	entire
celý	cell	whole
celých	of whole	whole
celým	his whole	whole
cena	price
cene	price
cenné	valuable
center	center
center|px	center px	center
centier	centers
centra	center	centre
central	central	cental
centre	center
centrom	center
centrum	center
centrá	center
centrách	centers
centrálna	central	centralna
centrálnej	central
centrálnu	central
cenu	price, prize (third sentence)
ceny	price (first and third sentence), prize (second sentence)	prices	price
certifikácia	certification
cesta	way
cestami	roads
ceste	path	the road	road
cestná	road
cestou	path	way
cestoval	traveled
cestovný	cestovny	tourism	trevel
cestu	way
cesty	roads
cestách	roads	routes
cez	through	by
ch	ch
chaos	chaos
charakter	character
charakteristická	characteristic
charakteristické	characteristic
charakteristický	characteristic	characteristically
charakteristickým	characteristic	the characteristic
charakteristika	characteristic
charakteristiky	characteristics
charakterizuje	characterized
charakteru	character
charles	charles
chce	wants
chcel	like
chcela	wanted	like
chceli	like
chceme	we
chcú	wishing (first sentence), want (second and third sentence)
chemickej	chemical
chemicky	chemical	chemically
chemická	chemical
chemické	chemical
chemického	chemical
chemický	chemically
chemických	chemical
chemickými	chemical	by chemical
chemie	chemistry
chicago	chicago
chladenie	cooling	fridge
chladné	cool
chlapca	boy
chlapec	boy
chlopne	valve	valves
chlorid	chloride
chlór	chlorine
chlóru	chlorine
chod	pace	operation
chodil	went	attended
chodiť	go
chodník	pavement
choroba	disease	charoba
chorobami	diseases
chorobe	disease	chrobi
choroby	disease
chorváti	croats	croatians
chorvátska	croatia	croatian
chorvátsko	croatia
chorôb	illnesses	diseases
chorý	ill
chorých	sick
chov	breeding
chované	kept
chovu	breeding
chris	chris
chrám	temple
chráme	tample	temple
chrámov	temples
chrámu	temple
chrámy	temples
chránené	protected
chránený	protected by
chráni	protects
chrániť	protect its	protect
chrípka	flu
chrípky	of flu	flu
chudobných	poor	the poor
church	church
churchill	churchill
chuť	taste
chvost	tail
chvíli	moment
chvíľu	moment	while
chyba	error
chybu	error	mistake
chyby	errors
chytadlovce	strain	tsitadlovce	chytadlovce	tentaculata
chápanie	snoring	understanding
chápať	conceived	understand
chápe	to understand
chémia	chemistry
chémie	chemistry
chémii	chemistry
chýb	error
cicavce	mammals
cicavcov	mammals
ciele	goals	targets
cien	prices
ciest	roads	road
cievky	coil
cievy	blood vessels	vessels
cieľ	duties
cieľa	goal
cieľom	finish	goal
cieľov	goals
cintorín	cemetary	cemetery
cintoríne	cemetery
cirkev	church
cirkevná	ecclesiastical
cirkevné	ecclesiastically
cirkevného	ecclesiastical
cirkevný	ecclesiastical
cirkevných	church
cirkvi	church
cirkvou	church
cirkví	churches	church
cisár	emperor
cisára	emperor
cisárstva	empire
cisárstvo	empire
citlivosť	sensitivity
citlivé	sensitive
city	city
civilizácie	civilization	civilisation
club	club
co	what	co
colorblack	color: black
company	company
cook	cook
copa	copa
corporation	corporation
cos	cos
counterstrike	counter-strike	counterstrike
country	country
cpu	cpu
cs	cs
csc	phd
cudzích	foreign
cukrová	sugary
cultural	cultural
cup	cup
cupu	cup
cyklu	cycle
cyklus	cycle
cykly	cycles
cyprus	cyprus
cyrila	cyril
cítiť	feel
dajú	be	can be
dal	gave
dala	she	gave
dali	were able to	could be	give
dalo	could
dalí	dalí	give
dane	taxation
danej	given	the
daniel	daniel
danom	given
daná	given
daného	given	invoked	the invoked
daní	tax
danú	this	given
daný	dana
daných	these	of the
dareia	darius	dareia
dark	dark
darwin	darwin
darwina	darwina	darwin
das	das
data	data
databáza	database
databázy	database
datuje	dates
dav	mass	crowd
dave	dave
david	david
day	day
daň	tax	day
dať	data	give
dcéra	daughter
dcérou	daughter
dcéru	daughter
dcéry	daughters
de	de
death	death
debussy	debussy
dec	dec
december	december
decembra	december
decembri	december
dedine	village
dediny	villages	village
dedičstva	heritage
dedičstvo	heritage
deep	deep
definitívne	definitely
definoval	defined
definovaná	defined
definované	defined	a defined
definovaný	defined
definovať	define
definuje	defines
definícia	definition
definície	definitions
dei	dei
deje	going
dejiny	history
dejinách	the history	history
dejín	history
dekrét	decree
dekrétov	decrees
dekréty	decrees
del	del
delenia	divisions	division
delenie	division
delia	divided
deliteľnosť	divisibility
deliť	divide
della	della
delta	delta
delí	divided
delíme	divided
demografia	demography
demokracia	democracy
demokracie	democracy
demokraciou	democracy
demokraciu	democracy
demokrati	democrats
demokratickej	democratic
demokratická	democratic	demoicratic
demokratických	democratic
denne	daily
deportácie	deportation	deportations
depresia	depression
depresie	depression
der	der
derivácia	derivative	derivation
derivácie	derivative
deriváciu	derivation
des	des
desať	ten
desaťročí	desat'rocí	decades
desiatich	ten
desiatky	tens of
desiatok	tens	tens of
destruction	displaying	destruction
detaily	details
deti	children
detstva	childhood
detstvo	childhood
detí	kids	children
deväť	nine
deväťdesiatych	giving ten	nineties
devín	devin
deň	day
di	di
dialógy	dialogues
diamant	diamond
diamantov	diamonds
diamantu	diamond
diamanty	diamonds
diania	event	events
diaľnic	highways
diaľnica	freeway	highway
diaľnice	highway
dickens	dickens
diel	part
diela	works
dielach	works
dielami	works	pieces
diele	work
dielo	work
dielom	part	part, work
dier	holes
diera	hole
diery	holes
dievčatá	girls
dieťa	diet	child
dieťaťa	baby	child
dieťaťom	child
diferenciál	differential
digital	digital
digitálne	digitally	digital
diktatúra	dictatorship
dinosaurov	dinosaurs
dinosaury	dinosaurs
diplomatické	diplomatic
direktórium	directory	directorium
disciplín	disciplines
disciplíny	discipline
disk	disk	disc
diskografia	discography
diskov	discs	disc
diskriminácia	discrimination
diskriminácie	discrimination
diskrétny	discrete	discreet	descrete
disku	disk	drive
diskusie	discussion
disky	disks
disponuje	has
dispozícii	available	disposition
distribúcie	distribution
dityramb	dityramb	dithyramb
divadelné	theatrical	theatrically
divadla	theaters	theater	theatre
divadlo	theater
divadlá	theater
divov	wonders
divízia	division
divízie	division	divisions
divízií	division
dizajn	design
dióda	diode
diódy	diodes
dl	dl
dlhej	long
dlho	long time	long
dlhodobo	long-term	long term
dlhodobé	durably
dlhom	long
dlhá	long	veneer
dlhé	dihe
dlhého	long
dlhú	debt	long
dlhých	comfortable stay
dlhšie	longer
dlhšiu	extended	longer	more
dlhší	long period
dna	gout	dna
dne	of	day
dnes	today
dnešnej	today
dnešnom	today
dnešná	current	today's
dnešné	today
dnešného	this day	today
dnešný	current
dnešných	today
dni	days
dns	dns
dní	days
do	to	in
doba	era	time
dobe	time
dobra	good
dobre	well
dobrovoľne	voluntarily
dobrá	good
dobré	good	well
dobrú	good
dobrý	good
dobrých	good	option for good
dobrým	a good	good
dobu	time
doby	time
dobyl	conquered
dobyli	captured
dobytie	conquest
dobytka	cattle
dobytok	cattle
dobytí	conquest
dobyť	captured
dobách	times
dochádza	arrive	comes about
dochádzalo	there
dodnes	till now	today
dodržiavanie	adherence	respect
dodáva	given	adds
doga	mastiff
dohoda	agreement
dohode	agreement
dohodli	agreed
dohodu	agreement
dohody	of
dohromady	together
dohôd	agreements
dojem	impression
doklady	papers
dokonale	fully	perfectly
dokonalosti	perfection
dokonalý	perfect
dokonca	even
dokončení	completion
dokončený	completed	finished
dokopy	together
doktor	d	doctor
dokument	document
dokumentov	documents
dokumentu	document
dokumenty	papers
dokázal	managed to	managed
dokázali	elicit	able
dokázať	prove
dokáže	can	prove
dokážu	the detection of	can
dole	down
dolina	valley
doline	valley
dolnej	lower	bottom
dolnom	lower
dolná	dolna	bottom
dolné	lower
dolný	dolny
dolu	down
dolárov	dollars
dom	house
doma	home
dome	house
dominuje	dominates
domnievajú	believe
domov	home
domovom	home
domu	house
domy	houses
domáca	home	domestic
domáce	home	homemade
domáceho	home
domácej	home
domáci	home
domácich	domestic	of domestic
domácnosti	households
domácu	domestic	homemade
domény	domain
don	don
donedávna	until recently	recently
dont	don't
dopad	impact
dopadu	impact
dopamínu	dopamine
doplnené	addition	supplemented with
doprava	transport
dopravná	transport
dopravné	congested traffic	transport
dopravný	conveyer	transport
dopravných	transport
dopravu	transport
dopravy	transport
dopredu	forward
dopyt	demand
dopytu	demand
doručovacej	delivery
dosah	range
dosahoval	reached
dosahuje	reaches
dosahujú	it reaches	reaches
dosiahla	reached
dosiahli	reached
dosiahne	reaches
dosiahnutie	achievement
dosiahnuť	achieve
dosiahol	reached
dosiaľ	to date	yet been	been
doska	board
doske	board
dosky	board
doslova	literally
dospel	reached
dospelosti	adulthood
dospelých	adults
dostal	recieved	get
dostala	received	got
dostali	were
dostalo	received	got
dostane	will	gets
dostaneme	get
dostanú	get
dostatok	sufficient
dostatočne	enough
dostatočné	enough
dostať	get
dostupný	available
dostáva	gets
dostávajú	this reaches	reaches
dosť	enough
doteraz	yet	so far
dotkne	touch
dotyk	touch
dotykom	touch	contact
dotyku	touch
dovnútra	inside
dovolené	vacation	allowed
dovtedy	meantime
dozadu	backwards	back
dozvedel	learned
dočasne	temporary	harvest festival
dočasné	temporarily	temporary
došlo	was	occurred
dr	dr.
drahé	expensive
drahý	expensive
draselný	potassium	potassic
dresy	jerseys	shirts
dreva	wood
drevené	wooden
drevo	wood
drobné	tiny
drog	drugs
drogy	drugs
druh	type
druhej	second	other
druhmi	species
druhom	second
druhou	other	two
druhov	types
druhu	kind of
druhy	types
druhá	second	mate
druhé	second
druhého	second
druhú	other
druhý	other	types
druhýkrát	second
druhým	the second	second
družstva	cooperative	team
družstvo	cooperative	team
dráh	railways
dráha	orbit
dráhach	precious
dráhe	expensive
dráhou	expensive
dráhu	track	orbit
dráhy	orbit	expensive
dráma	drama
drámy	drama
držal	held
držali	held	hold
držať	hold
drží	holds	holder
dub	oak
dubček	oakling
dubčeka	dubcek	dubchek
duch	spirit
ducha	spirit
duchovnej	spiritual
duchovné	spiritual	spiritually
duchovný	spiritual	duchovny
duchovných	spiritual
duchu	spirit
dunaj	danube
dunaja	danube
dunaji	danube
dunajská	dunajska
durič	beagle	hounds
dusík	nitrogen
dusíka	nitrogen
dutine	cavity
dutiny	cavity	cavities
duša	soul
dušan	dušan	dushan
duše	soul
dva	two
dvadsať	twenty
dvadsiateho	twentieth
dvaja	two
dvakrát	twice
dvanástich	twelve
dvanásť	twelve
dvd	dvd
dve	two
dvoch	two
dvojica	pair	two
dvojice	pairs	two
dvoma	two
dvomi	two
dvor	justice	court
dvora	courtyard	justice
dvore	justice
dvořák	dvorak
dym	smoke
dynamické	dynamic
dynastia	dynasty
dynastie	dynasty
dá	it is possible
dánska	denmark	former
dánsko	denmark
dát	data
dáta	data
dátum	date
dáva	gives
dávajú	give
dával	daval	let himself receive
dávali	they have given	give
dávid	david
dávida	david
dávky	requirements
dávno	long ago
dážď	rain
dóm	house
dôb	time
dôjde	will
dôjsť	be	happen
dôkaz	evidence
dôkazov	proofs	evidence
dôkazy	evidence
dôležitosť	importance
dôležitou	important
dôležitá	important
dôležité	important	useful
dôležitý	important,	important
dôležitých	important
dôležitým	important
dôraz	emphasis
dôsledkom	result
dôsledku	consequence	because
dôsledky	the consequences	consequences
dôsledok	result
dôstojníkov	officers
dôveru	dover
dôvod	reason
dôvodom	reason	the reason
dôvodov	reasons
dôvodu	because
dôvody	grounds
dýchania	breathing
dýchanie	breathing
dýchaní	breathing
dějiny	history
dĺžka	lenght
dĺžke	lenght	length
dĺžkou	length	lenght
dĺžku	lenght	length
dĺžky	lenghts	lenght
dĺžok	lenghts	lengths
dňa	gout	day
dňoch	on	days
dňom	bottom
džed	dzhed	djed	jed	dzed
e	e
east	east
ed	ed.
edison	edison
eduard	edward
efekt	effect
efektu	effect
efekty	effects
efektívne	effectively	effective
egypt	egypt
egypta	egypt
egypte	egypt
egyptské	egyptian
egyptských	egyptian
egypťania	egypt	egyptians
einstein	einstein
ekliptike	ecliptic
ekliptiky	ecliptic
ekologické	ecological
ekológia	ecology
ekonomickej	economic
ekonomicky	economically
ekonomická	economic	economics
ekonomické	of economics	economics
ekonomického	economic
ekonomickú	economic
ekonomický	economic	economically
ekonomických	of economic	economic
ekonomika	economics	economy
ekonomike	economy
ekonomiku	economy
ekonomiky	economy
ekonómia	economics	economy
ekosystém	ecosystem
ekosystému	ecosystem
el	el
elektrickej	electric	electrically
elektricky	electric	electrically
elektrická	electrical
elektrické	electric
elektrického	electrical	electric
elektrický	electrically
elektrických	electrical	electric
elektrickým	electrocuted	electric
elektromagnetické	electromagnetic
elektromagnetického	electromagnetic
elektromotor	electric motor	electromotor
elektronickej	electronicq	electronic	electronically
elektronické	electronic
elektronických	electronic
elektronika	electronics
elektroniky	electronics	electrons
elektrárne	power plant	electrical power plants
elektróde	electrode
elektrón	electron
elektrónov	electron
elektróny	electrones	electrons
elementov	elements
elvis	elvis
elán	elan
email	e mail	email
emailové	emails	email
emailových	email
emailu	email
emil	emil
emisie	emissions
emisií	issue
en	en
encyklopédia	encyclopedia
encyklopédie	encyclopedia
end	end
energetické	energetic
energia	energy
energie	energy
energiou	energy
energiu	energy	of energy
entropia	entropy
enzýmy	enzymes
epitaf	epitaph
epizód	episodes
erb	coat of arms
eric	eric
erich	erich
ernest	ernest
erupcie	eruption
es	ec	es
estónska	estonian	estonia
estónsko	estonia
et	et
etanol	ethanol
etapa	stage
etapy	stages	stage
ethernet	ethernet
etické	ethics
etika	ethics
etnické	ethnic
etnických	ethnic
etymológia	etymology
eu	eu
eura	euro
euro	euro
eurobankovky	euro banknotes	euro bank notes
euromince	coins
euromincí	euro coin
eurozóny	eurozone
európa	europe
európania	europeans
európe	europe
európou	europe	europol
európska	european
európske	european
európskeho	european
európskej	european
európskou	european
európsku	europsku	european
európsky	europsky	european
európskych	european
európu	europe	europa
európy	europe	europa
eva	eva
evanjelici	evangelicals
evanjelickej	evangelical	evangelic
evanjelický	evangelical
evolúcie	evolution	of evolution
existencia	existence
existencie	existence
existencii	existence	axistencii
existenciu	the existence	there
existoval	there
existovala	existed
existovali	existed	there
existovať	exist
existuje	there	exists
existujú	exist
existujúce	existing
existujúcich	existing
experiment	experiment
experimentu	experiment
experimenty	experiments
experimentálne	experimental
explorer	explorer
explózia	explosion	explosions
expozícia	explosion	exposition	exposure
expozície	expositions	exposition
expresionizmus	expressionism
externé	externally
extrémne	extrim	extreme
eú	eu
ešte	also	still	more
f	f
fa	fa
facto	de facto
fajčenia	smoking
fakt	fact
fakticky	effectively
faktor	factor
faktorom	factor
faktorov	factors
faktory	factors
fakty	facts
fakulta	faculty
fanúšikov	fans
fanúšikovia	fans
farba	color
farbou	color	paint
farbu	color
farby	color
farbách	colours	colors
farebné	colourful
farebných	color
farieb	color
fatra	fatra
fatry	fatry	fatra
fauna	fauna
favorit	favorite
fašizmu	fascism
fc	fc
fci	fci
fe	fe
február	february
februára	february
februári	februari	february
federatívna	federal
federácia	federation
federácie	federation
felicia	felicia
fenol	fenol	phenols	phenol
ferdinand	ferdinand
ferdinanda	ferdinand
festival	festival
fi	fi
figúra	figure
figúry	figures
filenz	file nz
filip	philip
filipa	filipa	philip
film	film
filme	film
filmoch	films
filmov	films
filmový	the cinematic	film
filmu	movie	muvie
filmy	movies
filozof	philosopher
filozofi	philosophers
filozofia	philosophy
filozofickej	philosophical	philosophic	philosophy
filozofická	philosophical
filozofické	philosophical
filozofických	philosophical
filozofie	philosophy
filozofii	philosophy
filozofiou	philosophy
filozofiu	philosophy
filozofov	philosophers	philosopher
financií	finance	france
finančne	financially
finančné	financially	financial
finančných	finanhttp://www.google.rs/url?source=transpromo&rs=rssf&q=http://www.google.com/mobile/translate/cial	financial
finále	finale
firewire	firewire
firiem	companies
firma	company
firmou	by company	by
firmy	company
flash	flash
fleminga	fleming
florencia	florence
florencie	florence
florencii	florence
florida	florida
floyd	floyd
flóra	flora
folk	folk
for	for
foriem	forms
forma	form
formami	forms	form
forme	form
formou	by	form
formovať	form	format
formu	form
formy	form
formálne	formally	formal
formát	format
formátov	formats,	formats
formátu	format
formáty	formats
fosfor	phosphorus
fosforu	phosphorus
fotografie	photo
fotografií	photos	photo
fotosyntéza	fitisynteza	photosynthesis
fotosyntézy	photosynthesis
fotónov	photons
fr	fr
frac	frac
fracpi	frac pi
francisco	francisco
francúzi	french
francúzska	french
francúzske	french
francúzskeho	french
francúzskej	french
francúzsko	france
francúzskom	french
francúzsku	french	france
francúzsky	french	france
francúzskych	french
francúzština	french
frank	franc	frank
františek	pastille	frantishek
františka	francis	františek
franz	franz
freddie	freddie
frekvencia	frequency
frekvencie	frequency
frekvenciou	frequency
frekvenciu	frequency
frekvencií	frekvency	frequency
fresku	fresco
fresky	frescoes
freud	freud
fridrich	frederick
friedrich	friedrich	frederich
from	from
front	queue	frontline
fronte	front
frontu	front
ftp	ftp
fungovanie	operation
funguje	works
fungujú	are working
funkcia	function
funkcie	functions	features
funkcii	function
funkciou	function	functionalized
funkciu	function
funkcií	function
funkčné	functional	functionally
futbal	football
futbale	football
futbalové	soccer
futbalový	football
fx	f x
fyzici	physicians	physicists
fyzickej	physical
fyzicky	physically
fyzická	physical
fyzické	physical
fyzických	physical
fyzika	physics
fyzike	physics
fyziku	physics
fyziky	physics
fyzikálna	physicality	physical
fyzikálne	physico	physical
fyzikálny	physical
fyzikálnych	physics	physical
fyzikálnymi	physical
fyziologické	physiological
fáza	phase
fázach	phases
fáze	phase
fázu	phase	beans
fázy	phase	phase to
fínska	finland
fínsko	finland
fínsku	finland
fórum	forum
fúzia	merger	fusion
g	g.
ga	ga
gabriel	gabriel
galaxie	galaxy
galaxií	galaxies	galaxy
galilei	galilei
galileiho	of galilei	galileo
galileo	galileo
galéria	gallery
galérie	gallery
game	game
gamma	gamma
gejza	geza
gen	gene
generácia	generation
generácie	generation
generál	general
generála	gen.	general
generáli	generali	generals	general
generálmajor	major general
generálneho	general
generálny	general
generálov	generals
genetickej	genetic
geodetiky	geodesics
geografia	geography
geografické	geographical
geografie	geography
geologické	geological
geológia	geology
geometria	geometry
geometrie	geometry
geomorfológia	geomorphology
georg	george	georg
george	george
ghándhí	ghandhi
gigi	gigi
giovanni	giovanni
girl	girl
gitara	guitar
gitarista	guitar player	guitarist
gitaru	guitar
gitary	guitars (second and third sentence), guitar(fourth sentence)
globálneho	global
gluón	gluon	gluons
gnu	gnu
goniometrických	trigonometric
google	google
gotickej	gothic
gotická	gothic
gotika	gothic
gotiky	gothic
gott	gott
gr	gr
gradient	gradient
graffiti	graffiti
grafickej	graphics
grafická	grafic	graphic card	graphiccard
grafické	graphic
grafický	graphically
grafických	graphic
grammy	grammy
grand	grand
gravitačne	gravitationally
gravitačnom	gravitational
gravitačná	gravitational
gravitačné	gravitationally
gravitačného	gravity
gravitačný	gravitational
gravitácia	gravitation
gravitácie	gravitation
gray	gray
great	velky
green	green
gregor	gregor
gregora	gregory
group	group
gruzínska	georgia
gruzínsko	georgia
gréci	greeks
grécka	greek
grécke	greek
gréckeho	greek
gréckej	greek
grécki	greek
grécko	greek	greece
gréckokatolíckej	greek	greek catholic	greek orthodox
gréckom	greek
grécku	greek
grécky	greek
gréckych	greek
grékov	greeks	grreek
gréčtine	greek
gróf	count	earl	grof
grónska	greenland	of greenland
grónsko	greenland
gule	ball
guns	guns
gustáv	gustav	gustáv
guľa	sphere
gymnázia	high school	gymnasium
gymnáziu	grammar school	high school
gymnázium	high school
génu	gene
h+	h+
habsburgovcov	habsburg
hala	hall
hall	hall
halucinácie	hallucination
hamlet	hamlet
hans	hans
hard	hard
hardvér	hardware
hardvéru	hardware	and banking
harmónie	harmonies	harmony
harry	harry
havel	havel
havárii	breakdown	crash
hdp	gdp
hebrejci	hebrew	jews	hebrews
heinrich	heinrich
henrich	henrich	henry
henricha	henrich	henry
henry	henry
hercegovina	herzegovina
herec	actor
herečka	actress
heslo	password
hetfield	hetfield
hier	games
high	high
himmler	himmler
hinduizmus	hinduism
historici	historians	history
historickej	historical	history
historicky	historically
historická	historical	history
historické	historical
historického	historical
historický	historically	historical
historických	historical
historik	historian
historikov	historians
history	history
história	history
histórie	history
histórii	history
históriu	history
hitler	hitler
hitlera	hitler
hitov	hits
hiv	hiv
hl	hl
hladina	level
hladiny	levels
hlas	voice
hlasov	votes	voice
hlasovanie	vote
hlasovaní	vote
hlasy	voices
hlava	head
hlave	head
hlavne	mainly
hlavnej	main
hlavnom	main
hlavnou	head	main
hlavná	main
hlavné	main
hlavného	of chief
hlavnú	main
hlavný	main
hlavných	main
hlavným	main	important
hlavnými	main
hlavou	head
hlavu	head
hlavy	head
hlboké	deep	ranges deeply into
hlbšie	deeper
hlinka	earth
hlinku	hlinku	hlinka
hliny	clay
hliník	aluminium	aluminum
hliníka	aluminium	aluminum
hlási	system reports	commits to
hláv	head	heads
hmloviny	nebula
hmota	mass
hmotnosti	weight
hmotnosť	weight
hmotnosťou	weight
hmotné	materially
hmotný	tangible	weight
hmotných	material
hmotou	mass
hmotu	mass
hmoty	mass
hmyz	insect
hmyzu	insects
hmôt	materials
hnedé	brown
hnedý	brown
hneď	immediately
hnutia	movement	movements
hnutí	movement
ho	him
hoci	although
hodiny	clock
hodnosti	values	rank
hodnosť	rank
hodnota	value
hodnotami	values
hodnote	value
hodnotenia	reviews	evaluation
hodnotenie	evaluation
hodnotou	value
hodnotu	value
hodnoty	values
hodnôt	values
hodín	hours
hokej	hockey
hokeji	hockey
hokejové	hockey
holandska	netherlands
holandsko	the netherlands	netherlands
holandsku	netherlands
holandský	dutch
hollywood	hollywood
holokaustu	holocaust
holotúrie	holothurians	sea cucumber	holothuroi	holoturie	holothuria	holothurie	holothuroidea
home	home
homogénne	homogeneous
hora	mountain
hore	up
horizont	horizon
horizontu	horizon
hormón	hormone
hormónov	hormons	hormones
hormóny	harmony	hormones
hornej	upper	top
horniny	rocks
horninách	rocks of
hornom	upper
horná	upper	horn
horného	upper
hornín	rocks
horný	upper	horny
horské	mountain	mountainous
horských	mountain
hory	mountains
horách	mountains
horúce	hot
horšie	worse
hospodárska	economic
hospodárske	economic	the economic
hospodárskeho	economic
hospodárskej	of	world
hospodársku	economic
hospodársky	economic
hospodárskych	economic
hospodárstva	economy
hospodárstvo	economy
hossa	hossa
hot	hot
hotel	hotel
house	house
hovoria	say	says
hovoriacich	speaking
hovoril	said
hovorili	said
hovorilo	said
hovoriť	talk
hovorovo	colloquially
hovorí	says
hovoríme	we say
hra	game
hrad	castle
hradby	walls
hrade	castle
hradnej	castle
hradného	castle
hradom	castle
hradov	castles
hradu	castle
hrady	castles
hrajú	play
hral	played
hrala	played
hrali	play	played
hranica	limit
hranicami	boundaries
hranice	the border	border
hranici	border
hraniciach	borders	border
hranicou	boundary	border
hranicu	limit	border
hranie	playing	play (first word), playing (second and third word)
hraničí	border
hraníc	border
hrať	play
hrdinov	heroes
hrdinu	hero
hre	game
hrebeň	ridge
hrob	grave
hrobky	tombs
hrobu	grave
hrom	thunder
hromadne	mass	massively
hromadnej	mass	public
hromadná	mass
hronom	hronom
hrozbou	threat
hru	game
hrubá	gross	thick	coarse
hrubý	hruby
hruď	chest
hry	games
hrá	game
hrách	peas
hráč	player
hráča	player
hráči	players
hráčom	player	playing
hráčov	players	the players
hrúbka	blunder	mistake
hso	hso
hsľs	hsĽs	hsl's
html	htlm
http	http
huby	mushrooms
hudba	music
hudbe	music
hudbou	music
hudbu	music
hudby	music
hudobnej	music
hudobná	music
hudobné	music	musically
hudobného	music	value
hudobní	music
hudobníci	musicians
hudobníkov	musicians
hudobný	music	musical
hudobných	poor	music
humenné	humenne	humenné
hurban	hurban
husle	violin
huslí	violin
husto	densely
hustota	density
hustote	density
hustotou	density
hustotu	density
hustoty	density
husák	husak
husľové	violin
hviezd	stars
hviezda	star
hviezdu	whistle	star
hviezdy	star
hymna	anthem
hyperón	hyperons	hyeron	hyperon
hélia	helium
hélium	helium
hôr	choir
hĺbka	depth
hĺbke	depth
hĺbky	depth
hľadanie	houses	searching
hľadaní	mrl	hungry
hľadať	seek	hungry
hľadiska	terms of
hľadá	searches
i	and
ian	ian
iana	iana
iba	only
ibm	ibm
ich	their
icq	post	icq
ide	it
idea	idea
ideológia	ideology
idey	ideas
ideí	ideas
ie	ie
igor	igor
ihneď	immediately
ihrisku	course
ii	ii
iii	iii
im	them	they
imigrantov	immigrants	imigrants
impéria	empire
impérium	empire
imrich	imrich
in	in
inak	otherwise
inc	inc.	inc
incident	incident
inde	other place	elsewhere
index	index
india	india
indická	indian
indického	indian
indický	indian
indie	india
indii	india
indikátor	indicator
individuálne	individual
indonézia	indonesia
indonézie	indonesia
inej	other	others
infekcia	infection
infekcie	infection
infekčné	infectious	infection
inflácia	inflation
inflácie	inflation
informatika	informatics
informačné	information
informácia	information
informácie	information
informáciu	information
informácií	info	information
infraštruktúra	infrastructure
ing	engineer
iniciatívy	initiatives
iniciály	initials
inokedy	sometimes	another time
inom	a	other
inou	other
integrované	integrated
integrovaný	integrated
integrál	integral
intel	intel
intenzita	intensity
intenzitu	intensity	intensity of
intenzity	intesity	intensity
intenzívne	intensive	intense
interakcie	interaction
internet	internet
internete	internet
internetové	internet
internetový	webshop
internetových	internet
interrupcie	termination	abortion
interval	interval
intonácia	intonation
investície	investments
iná	different	ina	another
iné	ine	others
iného	other
inému	other
iní	other
inú	well
iný	other	ins
iných	other
iným	other
inými	other	in other
inšpirované	inspired
inštitúcie	institutes	institutions
inštitúcií	institutional	institution
inštrukcie	instructions
inštrukcií	instruction	instructions
io	io
ip	internet protocol	ip
ipv	ipv
irak	iraq
iraku	iraq
iron	iron
irán	iran
isbn	isbn
islam	islam
islamu	islam
island	iceland
islande	iceland
iso	iso
istanbul	istanbul
istej	some
isto	sure	surely
istom	same
isté	certainly
istého	same
istú	the same	use the same
istý	sure of	sure
istých	same
istým	same
it	it
iv	also	iv
ivan	ivan
ivana	ivan
ix	ix
izrael	israel
izraela	israel
izraelská	israel	israeli
izraelské	israeli	israel
ióny	ions
iľjič	iljic	ilyich
išiel	go	went
išlo	was
j	j
ja	i
jack	jack
jackson	jackson
jacques	jacques
jadier	cores
jadra	cores	kernel
jadre	core
jadro	core
jadrom	core
jadrovej	nuclear
jadrová	nuclear
jadrové	nuclear
jadrového	nuclear	its nuclear
jadrových	nuclear	atomic
jadrá	kernel	the core
jakub	jacob
james	james
jan	jan	john
jana	jana
janko	janko
január	january	januar
januára	january
januári	january
japonci	japanese
japonska	japan
japonsko	japan
japonsku	japan
japonských	japanese
jar	spring
jari	spring
jarmok	fair	market
jaroslav	jaroslav
jaskyne	cave
jaskyňa	cave
jasne	clear	clearly
jasnosť	clarity
jasné	clear	clearly
jasný	bright
jav	phenomenon
java	java
javom	commonplace	phenomenom
javov	phenomena	events
javu	phenomenon	prove
javy	phenomena
javí	turn	seems
jazera	lake
jazere	lake
jazero	lake
jazerá	lake	lakes
jazier	lakes
jazyk	language
jazyka	language
jazykmi	languages	​​languages
jazykoch	​​languages	languages
jazykom	language
jazykov	language
jazykové	language	jazyke
jazykových	language
jazyku	language
jazyky	languages	​​languages	language
je	is
jean	jean
jeden	one
jedenásť	eleven
jedinca	individual
jedince	individual	specimens
jedincov	individuals	individua
jedine	alone	only one
jedinec	individual
jedinou	single	only
jediná	only
jediné	alone	the only one
jediného	the only one	one
jedinú	only
jediný	only	the only one
jediným	the only
jedla	meal
jedna	one
jednak	both
jednej	one
jedno	one
jednoducho	easily	just
jednoduché	simple
jednoduchý	simple
jednoduchých	simple
jednoduchšie	easier
jednom	once
jednosmerného	one-way	dc
jednota	unity
jednotiek	units
jednotka	unit
jednotkami	units
jednotkou	unit
jednotku	unit
jednotky	units
jednotkách	units
jednotlivca	individual
jednotlivcov	individuals
jednotlivé	the individual	individual
jednotlivých	individual
jednotlivými	individual
jednotné	uniformly
jednotný	unified	single
jednoty	unity
jednou	once
jednoznačne	unambiguously	clearly
jednu	one
jedny	one
jedného	one
jedným	one
jeho	his
jehovovi	jehovah
jej	its
jersey	jerey	jersey
jeruzalem	jerusalem
jeruzalema	jerusalem
jeseň	autumn
ježiš	jesus
ježiša	jesus
joe	joe
johann	johann
john	john
johna	john
jon	jon
josef	joseph	josef
josep	josep
joseph	joseph
joviálne	jovian
jozef	joseph
jozefa	joseph
jožo	jozo	jožo
ju	her
judas	judas
judr	dr.
juh	south
juhoslávie	yugoslavia
juhovýchode	southeast
juhovýchodnej	southeast
juhozápade	southwest
juhozápadnej	southwest
juhozápadnom	southwest	southwestern
juhu	south
jupiter	jupiter
jupitera	jupiter
juraj	george	juraj
juraja	george	juraj
južne	south
južnej	southern	south
južnom	south
južná	south
južné	south
južného	southern
južnú	south
južný	south
južných	southern
ján	jan	ian
jána	jana
jánom	jan
jánošík	janosik	janoshik
jódu	iodine
júl	jul
júla	july
júli	july
júlia	julia
július	julius
jún	june
júna	june
júni	june
k	k
kadmium	cadmium
kalendár	calendar
kalendári	calendar
kalibru	caliber
kalifornia	california
kam	where
kambrium	cambrium	cambrian period	cambrian
kamene	stones	stone
kamennej	stone
kamenná	stone
kamenné	stone
kameň	stone
kameňa	stone
kameňov	stones
kampane	campaign
kampanila	company	campanila	campanile
kampaň	campaign
kanada	canada
kanade	canada
kanady	canada
kandidát	candidate
kandidátov	candidates
kant	kant	cant
kanta	kant
kanál	sewer	channel
kanálov	channels
kanály	channels
kanón	cannon	gun
kanónu	gun
kanóny	cannon
kapacita	capacity
kapacitou	capacity
kapacitu	capacity
kapacity	capacities
kapela	band
kapele	band
kapely	band
kapiel	bands
kapitál	kapital	capital
kapitálu	capital with	capital
kapitán	captain
kaplnka	chapel
kaplnke	chapel
kaplnky	chapel
karboxylových	carboxylic
karcinóm	carcinoma
karcinómu	cancer
kardinál	cardinal
kardinála	cardinal
karel	karel	charles
kariet	cards
kariéra	career
kariéry	career
karl	karl	carl
karol	karol
karola	karol	carola
karpaty	carpathians
karpát	carpathian
karta	card
kartu	card
karty	cards
katarína	katarina
katastrálne	cadastral	catastrophic
katedra	department
katedrála	cathedral
katedrály	cathedral
kategória	category
kategóriadejiny	category: history
kategóriaeuromince	category coins
kategóriahráči	players category	category: players (two words)
kategóriakrajiny	category country
kategórialokality	category : site
kategóriamestá	category: cities	category: cities (two words)
kategórianarodenia	category: birth (two words)
kategóriaokres	category: district	district category
kategóriaosobnosti	category: personalities	kategoriaosobnosti
kategóriapolitici	category: politicians (two words)	category:politicians
kategóriaposlanci	category members
kategóriatalianski	category : italian	kategoriatalianski
kategóriaúmrtia	category: deaths (two words)	category deaths
kategóriačlenovia	kategory
kategóriaštáty	category: states (two words)
kategórie	category	categories
kategórií	category	categories
katka	katka	kate
katolicizmus	catholicism
katolíci	catholics
katolícka	catholic
katolícke	catholic
katolíckej	catholic
katolíckych	catholic
kaukaz	caucasus
kaukazu	caucasus
kazachstan	kazakhstan	kazachstan
kazachstanu	kazachstan	kazakhstan
kaštieľ	mansion
každej	each
každom	each
každoročne	annually	yearly
každá	every	each
každé	every	each
každého	everyone	every	each
každému	each
každú	every	each
každý	everyone
každých	every
kde	where
keby	if	he
kedy	when
kedykoľvek	than ever (first sentence), anytime (second and third sentence)	any time
kedysi	erst	once
kelti	celts
keltské	celtic
keramiky	ceramics
keď	when
keďže	since
kg	kg
kilometrov	kilometers
king	king
kino	cinema
kiss	kiss
kladie	places
kladný	positive	econo
klasicizmu	classicism
klasickej	classical
klasická	classic
klasické	classical	classic
klasického	classical
klasickú	classic
klasický	classically	classic
klasických	classical
klasickým	classical (first sentence), typical (second and third sentence)	classical	classic
klasifikácia	classification
klavír	piano
klesne	decreases
klesá	drops	declining
klient	client
klienta	client
kliešťovité	clamp	tick	ticks	pincer
klimatické	climatic
klimatických	climatic
klimatológia	climatology
klimax	climax
klub	club
klube	club	cuba
klubom	club
klubov	clubs
klubu	club
kluby	clubs
klávesnica	keyboard
klávesnice	keyboard
klávesy	keys
kláštor	monastery
kláštora	monastery	convent
kláštore	monastery
klíma	climate
klímy	climate	change
km	km
kmene	strain	tribe
kmeň	strain
kmeňa	strain of
kmeňov	strains
knieža	prince	of prince
kniežatstvo	principality
kniežaťa	prince
kniha	book
knihe	book
knihu	book
knihy	books
knižnica	library
knižnice	library
kníh	books
koalícia	coalition
koalície	coalition
koho	whom	who
kol	wheel	col.
kola	wheels	round
kole	round
koleso	wheel
kolesá	wheel	wheels
kolmo	upright
kolo	round
kolumbia	colombia
kolíše	varies
kombinácia	combination
kombinácie	combinations	combination
kombinácii	combination
kombináciou	combination
kombináciu	combination
komenského	comenius
komerčne	commercial	commercially
komerčné	commercially
komerčný	commercial
komisia	commission
komisie	commission
komory	chambers	chamber
kompilácie	compile
kompletne	completely
komplex	complex
komplexné	complex
komplexných	complex
komplexu	complex
komplikácie	complications
komponenty	component	components
komunikovať	communicate
komunikácia	communication
komunikácie	communications
komunikáciu	communication
komunisti	communists	comunists
komunistickej	communist
komunistická	communist
komunistické	communist
komunistického	communist
komunistických	communist
komunistov	communists
komunita	community
komunite	community
komunity	communities	community
komunizmu	communism
komunizmus	communism
komárno	komarno
komét	comet
kométy	comet
komôr	chambers
konajú	held	take place
konal	place
konala	held
konali	held	acted
konania	proceedings	actions
konanie	action
konať	do	act
konca	end
konce	ends	end
koncentračných	concentration	work camp
koncentrácia	concentration
koncentrácii	concentration	concept
koncentráciu	concentration
koncepcia	conception
koncepcie	concept
koncept	draft
koncert	concert
koncerte	concerts	concert
koncertné	concert
koncertov	concerts	concert
koncerty	concerts
konci	end
koncom	the end of	end
koncové	end
koncového	end
koncový	end	final
koncových	end	endings
koncu	end
kone	horses
konektor	connector
konektory	connectors
konečne	finally
konečnom	final
konečné	finally	final
konečný	final
konferencie	conference	coneference
konferencii	conference
konflikt	conflict
konfliktov	conflicts	conflict
konfliktu	conflict
konflikty	conflicts
kongres	congres	congress
koniec	end
konkrétne	concretely
konkrétnej	specific	concrete
konkrétny	specific	concrete
kontakt	contact	contakt
kontakte	contact
kontaktu	contakt	contact
kontakty	contacts
kontext	c	context
kontinent	continent
kontinentu	continent
kontinenty	continents
kontinentálne	continental
kontrast	contast	contrast
kontrola	control
kontrolou	control
kontrolu	control
kontroly	control
konvent	convention
konventu	convention
koná	act
končatiny	extremities	legs
končí	ends	finishes
konštanta	constant
konštantín	konstantin
konštantínopol	constantinople
konštrukcia	construction
konštrukcie	construction	constructions
konštrukciu	construction
korene	roots
korisť	prey
koruna	crown
korunu	crown
koruny	crown	crowns
kosovo	kosovo
kosti	bones
kostné	bone
kostol	church
kostola	church
kostole	church
kostolov	churches
kostoly	churches
kostí	bones
kosť	bone
kotliny	basin
kov	metal
kovov	metal	metals
kovové	coffee	metal
kovu	metal
kovy	metals	meterial
kováč	blacksmith	kovac	kovach	smith
koza	goat
kozmickej	cosmic	space
kozmického	cosmic	space
kozmonaut	cosmonaut	astronaut	austronaut
kozmonautika	astronautics	cosmonautics
kozorožec	capricorn	ibex
kozy	goats
koľko	how many
koňa	horse	act
kościół	koscuiol	kościół
koša	basket	trash
košice	kosice
košiciach	kosice
košický	kosice	košice
košíc	kosice
koščová	regis	koscova
koža	skin
kože	skin
kr	cr	kr
kraj	region	end
kraja	region
kraje	region
kraji	region
krajina	country
krajinami	countries
krajine	country	extreme
krajinou	country
krajinu	country
krajiny	country
krajinách	countries
krajinám	countries
krajín	landscapes	countries
krakov	krakow
kremík	silicon
kremíka	silicon
kresťania	christians
kresťanov	christians
kresťanskej	christian
kresťanská	christian
kresťanské	christian
kresťanských	christian
kresťanstva	christianity
kresťanstvo	christianity
krista	christ
kristus	christ
kritici	critics
kritické	critical
kritika	criticism	critic
kritike	criticism
kritiku	criticism	criticue
kritiky	critics
kritizoval	criticized
kritériá	criteria
kritérií	criteria
krivka	curve
krivky	curve
križiackych	crusader
križovatka	crossroad	junction
križovatke	intersection
križovatky	intersection	crossroad
krk	neck
krku	neck
krok	step
krokom	step
krokov	steps
kroku	step
kroky	action	steps
kromaňonec	cromanion	kromanonec	cromagnonian	kromanion	cro-magnon
kruh	circle
kruhov	circles
kruhu	circle
kruhy	circles
kružnice	circle
krv	blood
krvi	blood
krvné	blood
krvou	blood
krvácanie	haemorrhage	bleedings
kryštalickej	crystallic	crystalline
králi	kings
krása	beauty
krásna	gorgeous
krásu	karst	beauty
krásy	beauties	beauty
krát	times
kráter	crater
kráterov	craters	crater
krátery	craters
krátka	short
krátke	short
krátkej	short
krátko	shortly
krátkom	short
krátku	prints a short	short
krátky	short
kráľ	king
kráľa	king
kráľom	king
kráľov	kings
kráľovi	king
kráľovnej	queen
kráľovnou	queen
kráľovná	queen
kráľovskej	royal	kings'
kráľovská	royal
kráľovské	royal
kráľovského	royal
kráľovský	royal	kingly
kráľovských	royal
kráľovstva	kingdom
kráľovstve	kingdom
kráľovstvo	kingdom
krídla	wing
krídlatcovité	kridlatsovi	pterygoid	immigrants	stromidae	strombidae
kríza	crisis
kríze	crisis
krízy	crisis
kríž	crisis	kriz
kríža	cross	crisis
ksč	communist party
kto	who
ktorej	which
ktorom	which
ktorou	which
ktorá	that
ktoré	which
ktorého	kotor	which
ktorému	whom
ktorí	who
ktorú	that
ktorý	who
ktorých	which
ktorým	which
ktorými	which
ku	to
kuba	cuba
kubizmus	cubism
kuby	cuba
kukurica	corn
kukurice	corn
kult	cult
kultúr	cultures
kultúra	culture
kultúre	culture
kultúrna	cultural
kultúrne	cultural
kultúrneho	cultural
kultúrnej	cultural	of culture
kultúrny	cultural
kultúrnych	cultural
kultúrou	culture
kultúru	culture
kultúry	culture
kurt	court
kurtu	court
kurz	course
kusov	piece	pieces
kv	kv
kvalita	quality
kvalite	quality
kvalitné	quality
kvalitu	quality
kvality	quality
kvantovej	quantum	quantium
kvapalina	liquid
kvapaliny	liquid
kvapalnom	liquid
kvapalné	liquid
kvet	flower
kvetov	flowers
kvety	flowers
kváder	cuboid	square	block
kvôli	because of
kyjev	kiev
kyselina	acid
kyselinami	acids	acid
kyselinou	acid
kyselinu	acid
kyseliny	acid
kyselín	acid	acids
kyslík	oxygen
kyslíka	oxygen
kyslíkom	oxygene	oxygen
kábel	cable
kábla	cable
káble	cables
káva	coffee
kód	code
kódovanie	coding
kódu	code
kópie	copy
kórea	korea
kôra	bark
kôre	root	crust
kôry	crust	kory
kôz	goats
kôš	blackbird
kúpele	spa
kúpeľov	baths
kúpil	bought
kým	kym
kľúč	wrench	key
kňaz	priest
kňaza	priest
kňazi	priest	priests
kňazov	priests
l	i
la	la
lacnejšie	cheaper
ladislav	ladislav
ladislava	ladislav	ladislava
las	las
laser	laser
lat	lat.
latinskej	latin
latinsky	latin
latinské	latin
latinského	latin
latinský	latin
latinčina	latin
latinčine	latin
latinčiny	latin
laurázia	laurazia	laurasia
lcd	lcd
league	league
lebo	because
led	ice
legenda	legend
legendy	legends
lekár	doctor
lekára	doctor
lekárstva	medicine
len	only
lenin	lenin
lenina	lenin
lennon	lennon
leonarda	leonarda	leonard
leonardo	leonardo
leopold	leopold
lepšie	better
lepšiu	better
lepší	better	superior
les	forest
lesa	forest
lese	forest
lesná	forest	lesna
lesoch	forests
lesov	forrests	forests
lesy	woods	forests
let	flight
leta	summer
lete	summer
leteckej	air
letecká	air
letecké	aviation	on aviation
letectva	air force
letectvo	aviation
letiska	airport
letisko	airport
letisku	airport
letiská	airports
letnej	summer
letná	summer	letna
letné	summer
letných	summer
leto	summer
letá	summer	flight
leucín	leucine	leucin
lev	lev	leo
levoči	levoca
ležia	lies	lie
ležiace	lying
leží	lies
liberalizmu	liberalism
liberalizmus	liberalism
liekov	drugs
lieky	drugs
lietadiel	aircraft
lietadla	aircraft
lietadlo	aircraft	plane
lietadlá	aircraft
liečba	treatment
liečbu	treatment
liečby	treatment
life	life
liga	keague
lige	league
light	light
ligy	league
like	like
limit	limit
lincoln	lincoln
line	line
lineárne	linearly
liniek	lines
linka	line
linkin	linkin
linky	lines
linux	linux
linuxu	linux
lipidov	lipids
lipidy	lipids
liptovskej	liptovskej, (the name)	liptov
liptovskom	liptovský	liptov
liptovská	liptovska
liptovský	liptovsky
lisabonská	lisabon	lisbon
list	paper	sheet	letter
liste	letter
listnaté	deciduous	broad-leaved
listov	letters
listu	sheet
listy	leaves
literatúra	literature
literatúre	literature
literatúru	literature
literatúry	literal	literature
literárne	literary
literárneho	literary
literárnej	literal	literature
literárny	literary
literárnych	literature
litva	litvanian	lithuania
litvy	lithuania
live	live
lode	ship
lodi	ship
lodí	ship	ships
log	log
logika	logic
logiky	logic
logo	logo
lokalita	location	locality
lokality	site
lokálne	local
lokálnych	local
lomu	quarry
london	london
londýn	london
londýna	london
londýne	london
longitudinálna	longitudinal
longitudinálnej	longitudinal
lopta	ball
loptička	ball
loptou	ball
loptu	ball
lopty	ball	balls
lord	lord
lorenzo	lorenzo
los	los	moose
lotyšsko	latvia
louis	louis
louvre	louvre
love	love
loď	aircraft carrier (first and third word), merchant ship (second word)	ship
ložiská	bearings
lu	lu
luciferín	luciferin	lucifer
ludwig	ludwig
lunárneho	lunar
luther	luther
luxembursko	luxemburg
lučenec	lučenec
lynx	lynx
lyrika	lyrics
lyžiach	jumping
láska	love
lásku	love
lásky	love
látka	substance	splint
látkami	slats
látkou	substance
látku	substance	bar
látky	substance	sticks
látok	substances
lávy	lavy
légie	legion	legions
línia	line
línie	line
líniu	line
líza	liza
líši	differ	piece of data differs
líšia	differ in	diferr by
lúč	beam	trigger
lúče	beams	rays
lúčov	beam	rays
lýceu	lyceum
m	m.	m
ma	has
mac	mac
macedónska	macedonian
macedónsko	macedonian	macedonia
machine	machine
machu	machu
madame	madame
madona	madonna
madonna	madonna
madrid	madrid
mafstory	mafstory
magma	magma
magmy	magma
magnetickej	magnetic
magnetickom	magnetic
magnetickou	magnetic
magnetická	magnetic
magnetické	magnetic
magnetického	magnetic
magnetický	magnetically	magneticky
magnetických	magnetic
magnetickým	magnetic
magnetizácia	magnetization
magnetizácie	magnetization
magnetosféra	magnetsphere
magnetu	magnet
maiden	maiden
mail	mail
majetku	property
majetok	property
majster	master
majstra	master
majstrov	masters	champions
majstrovstiev	championship
majstrovstvá	championship
majú	maya	they have
mal	had	should
mala	had
malej	small
mali	had
maliar	painter
maliara	painter
maliari	painters	artist
maliarstvo	painting
malo	little	had
malom	small
malou	small
malta	malta
malte	malta
maltuziánstvo	malthusian	maltuziánstvo	malthusianism	maltuzianstvo	maltusianism
malty	mortar	malta
malware	malware
malá	small	had
malé	small	male
malého	small	a small
malú	small
malý	small
malých	small
malým	small	a small
malými	small	by small	vy small
man	man
manažment	management
manchester	manchester
mandát	mandate
manhattan	manhattan
manipulácia	handling	manipulate	manipulation
manžel	husband
manžela	husband
manželka	wife
manželkou	his wife	wife
manželku	wife
manželky	wives	wife
manželstva	marriage
manželstvo	marriage
mapa	map
mapy	maps	map
marca	march
marci	march
marec	march
maria	maria
marie	marie
marihuana	cannabis	marijuana
marihuany	marijuana
mariner	mariner
marián	marian
mark	mark
marka	mark
marketingu	marketing
markíza	markiza
marley	marley
mars	mars
marse	mars
marsu	mars
martin	martin
martina	martina	martin
martine	in martin	martin
marx	marx
mary	mary
maríno	san marino	marino
maršala	marshal
masaryk	masaryk
masové	mass
masív	solid
matej	matt
mateja	matthew	matej
matematická	mathematical
matematických	mathematical
matematika	mathematics
matematike	mathematics
matematiku	mathematics
matematiky	mathematics
materiál	material
materiálom	material
materiálov	materials
materiálu	material
materiály	material	materials
maternice	cancer
materskej	parent
matica	matrix
matice	matrix
matičnej	matrix
matka	mother
matkou	mother
matku	mother
matky	mothers
matuška	matuška	matuska
matúš	matus	matúš
mauzóleum	mausoleum
max	max
maximum	maximum
maximálna	maximum
maximálne	themselves	maximum
mačiek	cats
mačka	cat
mačky	cats
maďari	hungarians
maďarov	hungarians
maďarska	hungary	hungarian
maďarskej	hungarian
maďarsko	hungary
maďarskom	hungarian
maďarsku	hungary	hungarian
maďarská	hungary
maďarské	hungarian
maďarského	hungarian	the hungarian
maďarský	hungarian
maďarských	hungarian
maďarčine	hungarian
maľba	painting
maľby	paintings
mať	mate
mckenna	mckenna
me	me
mechanicky	mechanically
mechanická	mechanical
mechanické	mechanic	mechanical
mechanika	mechanics
mechaniky	mechanics
mechanizmu	mechanism
mechanizmus	mechanism
medaila	medal
medi	copper
medici	medici
mediciovcov	medici
medicíne	medicine
medicíny	medicine
medián	medians	median
medveď	bear
medzi	between
medzinárodne	multinational	internationally
medzinárodnej	international
medzinárodná	international
medzinárodné	international	internationally
medzinárodného	international
medzinárodnú	international
medzinárodný	multinational	international
medzinárodných	international
medzinárodným	international
medzitým	meanwhile
mena	currency
mene	currency	name
menej	less
menia	change
meniť	change
meno	name
menom	name
menovania	appointment
menovaný	appointed
menovej	monetary
menu	menu
meny	currency
mená	currency	names
mení	change
menšej	smaller
menšia	less
menšie	smaller
menšina	minority
menšiny	minority
menšiu	less
menší	smaller
menších	smaller
menším	lower	smaller
menšín	minorities
merania	measurement
meranie	measurement
meraní	measurements
mercury	mercury
meria	measured	lasts
merkúr	mercury
merkúra	mercury
mesačnej	monthly
mesačné	monthly	month
mesiac	month
mesiaca	month
mesiace	months
mesiaci	month
mesiacoch	months
mesiacom	month
mesiacov	months
messenger	messenger
mesta	city	of
mestami	cities
meste	city
mesto	city	​​city
mestom	city
mestskej	city
mestská	mestska
mestské	an urban	urban
mestského	city's
mestskú	municipal
mestský	urban
mestských	urban
mestu	city
mestá	city	morava
mestách	towns	places
mestám	of	cities
metabolizmu	metabolism
metabolizmus	metabolism
metafyzika	metaphysics
metal	metal
metale	metal
metallica	metallica
metallicy	metallica
metalové	metal
metalových	metal
metalu	metal
metamfetamín	methamphetamine
meter	meter
metionín	metionine	methionine
metla	broom
metod	methods
metoda	metod	method
metra	metro
metrického	metric
metro	metro
metropolitná	metropolitan
metrov	meters
metán	methane
metánu	methane
metód	methods	method
metóda	method
metódou	method	by
metódu	method
metódy	methods
mexiko	mexico
mezopotámia	mesopotamia
mezopotámie	mesopotamia
mezopotámii	mesopotamia
meď	honey
mhd	mhd
mi	me
michael	michael
michail	michail	mikhail
michal	michal	michael
michala	michal	michael
michalovce	michigan	michalovce
michelangela	michelangelo
michelangelo	michelangelo
michelangelovi	michelangelo
microsoft	microsoft
midi	midi
mien	names
mier	peace
miera	degree
miere	rate
mieri	peace
mierne	little	slightly
mierneho	moderate
mierou	rate	measurement
mierovej	peace
mieru	rate	peace
miery	rate	measurements	measures
miest	sites
miesta	location	places
miestach	locations
miestami	at times	places
mieste	place
miestna	local	place
miestne	local
miestneho	local
miestnej	local
miestnosti	rooms (first and second sentence), room (third sentence)	rooms
miestny	local
miestnych	local
miesto	place
miestom	place	place (first and third word), point (second word)
mike	mike
mikuláš	mikuláš	nicholas
mikuláša	nicholas
milan	milan
milana	milan
milión	million
miliónov	million
milióny	million	millions
miloslav	miloslav	miroslav
miláne	milan
miláno	milano
mimo	outside	out
mimoriadne	extremely
min	min.
minca	coin
mince	coins	coin
minci	coin
minciach	coins
mincovne	mint
mincí	coins	coin
mineralr=	mineralr	mineral
minerálne	in minerals
minerálnych	of mineral	mineral
minerálov	minerals
minerály	minerals
minimum	minimum
minimálna	minimum	minimal
minimálne	minimum	minimal
minister	minister
ministerstvo	ministry
ministra	minister
ministri	ministers
ministrov	ministers
mintzberg	mintzberg
minulosti	past
minulého	last	of last
minúta	minute
miroslav	miroslav
misia	mission
misie	pilgrimage	mission
mladosti	youth
mladosť	youth
mladá	young
mladé	young
mladého	a young	young
mladý	young
mladých	young
mladší	younger
mladších	younger
mlieka	milk
mlieko	milk
mliečnej	milk	lactic
mládež	youth
mládeže	youth
mláďat	young adult	young
mláďatá	pups	young	young animals
mnoho	many
mnohokrát	many times
mnohé	many	numerous
mnohí	many
mnohých	many
mnohým	many	numerous
mnohými	many	by many
množstva	number of	variety
množstve	quantity of the	amount
množstvo	number of	number	quantity
množstvom	lots of	many	number
množstvá	number of
množstvách	quantities
mníchov	munich
mníchove	munich
mobilná	mobile
mobilné	mobile
moc	power
moci	can
mocnosti	powers	power
mocností	powers
modalita	modality
model	model
modelom	model
modelov	models
modelu	model
modely	models
modernej	modern
moderná	modern
moderné	modern
moderného	modern	of modern
moderný	modern	modernism
moderných	modern	of modern
modrá	blue
modré	blue
modrý	blue
modul	module
modulu	module
moduly	modules
mohla	to
mohli	to	could
mohlo	could
mohol	could
molekula	molecule
molekule	molecule
molekuly	molecules
molekúl	molecule	molecules
molybdén	molybden	molybdenum
moment	moment
momente	moment	time
momentu	moment
momentálne	moment
mona	mona
monarchia	monarchy
monarchie	monarchy
mongolsko	mongolia
monitor	monitor
monografia	monography	monograph
monte	monte
moon	moon
mor	plague
mora	sea
morava	moravia
morave	morava	moravia
moravu	moravia
moravy	morava	moravia
more	sea
mori	sea
moria	seas
morom	sea
morskej	marine	sea
morské	marine	sea
morských	marine
moru	sea
morálka	morale	morality
morí	sea
moskva	moscow
moskve	moscow
moskvy	moscow
moslimov	muslims
moslimovia	muslims
most	bridge
moste	bridge	mostly
mostom	bridge
mosty	bridges
motivácia	motivation
motor	motor
motora	engine
motorom	engine
motorov	engine	engines
motoru	engine	motor
motory	engines
motív	motif
motívom	motive
motívov	motives
motívy	patterns	motives
mount	mount
mozart	mozart
mozgu	brain
mozog	brain
močovod	ureter
možno	may	maybe
možnosti	opportunities	possibility
možností	options
možnosť	option	possibility
možnosťou	option
možná	possible	can
možné	possible
možný	possible	can
možných	possible
mr	m.r.	mr
mrakov	clouds	cloud
mramor	marble
mramoru	marble
ms	wc	ms
mt	mt
mtv	mtv
mu	him
mudr	mudr	md
musel	had
musela	had to	had
museli	had
muselo	had
musia	have
music	music
mussolini	mussolini
musí	needs to	must
musíme	we have
mutácie	mutation
muž	man
muža	man
muži	men
mužov	men
mužského	men's	male
mužstva	team
mužstvo	team
my	we
myslenia	thinking
myslenie	thinking
myslí	mind	thinks
mystika	mysticism	mystique	musticism
mytológia	mythology
mytológie	mythology
myš	cape	mouse
myši	mice
myšlienka	the idea	idea
myšlienkou	idea
myšlienku	idea
myšlienky	ideas	thoughts
myšlienok	ideas of	ideas
má	i	has
máj	may
mája	may
máji	may	they have
mála	small	had
málo	little	it	a little
máme	we have
márgit	marge	margit
mária	maria
márie	maria
márii	mary
máriou	maria
máriu	maria
mávajú	tend
mäkké	soft
mäsa	mass
mäso	meat
média	medias
médium	medium
médiá	media
médiách	media	the media
médií	media
mód	mod
móda	moda	style
móde	fashion
módu	fashion	mode
môj	my
môže	can	it can
môžeme	we can
môžete	you can
môžu	may	they can
múdrosti	wisdom as	wisdom
múr	wall
múru	wall	mur
múzea	museum
múzeu	museum
múzeum	museum
múzeá	museum
múzeí	museums
mýtu	myths	myth
mýtus	myth
mňa	me
mŕtve	dead
mŕtveho	dead
mŕtvych	dead
mš	ms
n	n
na	to	on
nachádza	situated
nachádzajú	located	are
nachádzala	located
nachádzali	situated	remained
nachádzalo	located	were located
nachádzame	we find
nachádzať	been placed	situated
nacionalizmus	nationalism
nacisti	nazis
nacistické	nazi
nacizmu	nazism	nazi
nad	over
nadmorskej	altitude
nadobúda	attain
nadol	below
nadvládou	rule
nadvlády	domination
nadväzuje	follow-up
nadčeľaď	superfamily
nahor	up
nahradená	replaced
nahradené	replaced
nahradil	replaced
nahradila	replaced
nahradili	replaced
nahradiť	replace
nahral	recorded
nahrala	recorded
nahrali	recorded
nahrádza	replaces	replaced
nahrávky	recordings
najavo	clear
najbežnejšie	the most common	most common
najbližšie	nearest	closest
najdlhšia	the longest	longest
najdlhšie	for longer	longest
najdlhšou	the longest	longest
najdlhší	longest
najdôležitejšia	the most important	most importantly
najdôležitejšie	most important	most importantly
najdôležitejšou	most important	the most important
najdôležitejších	most	the most
najdôležitejším	most	most importantly	most important
najdôležitejšími	most important	the most important
najlepšie	most beautiful	best
najlepší	best
najlepších	the best
najlepším	the best	best
najmenej	at least
najmenšia	smallest	the smallest
najmenšie	smallest
najmä	mainly
najneskôr	at last
najnižšia	lowest
najnovšie	newest	the latest
najnovších	the latest	newest	latest
najprv	first
najrýchlejšie	fast as possible	the fastest
najskôr	earliest
najstaršia	oldest	the oldest
najstaršie	oldest	the oldest
najstarší	oldest	the oldest
najstarších	oldest	the oldest
najstarším	the oldest
najviac	most
najvyššej	top	highest
najvyššia	the highest	highest
najvyššie	the highest	top
najvyššieho	supreme
najvyššiu	highest	up
najvyššou	top
najvyšší	highestbidder	the highest	highest
najvyšších	top
najvyšším	the highest	highest
najväčšej	most	greatest
najväčšia	the largest
najväčšie	hardest	greatest
najväčšieho	greatest	the largest
najväčšiu	greatest	largest
najväčšom	biggest	the largest
najväčšou	most	largest
najväčší	biggest	hardest
najväčších	top
najväčším	the biggest	hardest
najväčšími	major
najvýznamnejšie	most	most important
najvýznamnejšou	najvyznamejsou	most notable
najvýznamnejší	most important	the most
najvýznamnejších	the most	the most important
najvýznamnejším	the most important	most well-known
najznámejšia	the best known	most famous
najznámejšie	famous
najznámejšou	the most famous	the best known
najznámejší	famous	most famous
najznámejších	famous	best known
najznámejším	most well known	famous	most famous
najčastejšie	most	most often
nakoniec	finally	after all
nakoľko	as
namiesto	instead
nanebovzatia	assumption
naopak	conversely
naozaj	real	really
naplno	fully	full
napokon	ultimately
napoleon	napoleon
napoleona	napoleon
napomáha	helps
naposledy	last time	last
napr	for example
napriek	despite
naproti	opposite
napríklad	for example
napätia	tensions
napätie	tensions
napätím	tensions
napísal	written	wrote
napísané	written
napísaný	written
naraz	at once
nariadil	ordered
narodenia	birth
narodenie	national	birth
narodení	birth of
narodil	born
nasa	nasa
nasadenie	motivation	deployment
nasledoval	followed by
nasledovala	followed by
nasledovali	followed by	followed
nasledovalo	followed by	followed
nasledovne	as follows
nasledovné	following	as follows
nasleduje	follows
nasledujú	followed	then followed
nasledujúca	following first	following
nasledujúce	following	the following
nasledujúceho	following
nasledujúcej	next
nasledujúci	following	next
nasledujúcich	following	the following industry
nasledujúcom	next
naspäť	slept
nastal	occurred
nastala	occurred
nastalo	occurred
nastane	there
nastavenia	settings
nastavenie	setting
nastať	occur
nastáva	teaching	set
nastávajú	occur	sets
nastúpil	he joined	joined
national	national
nato	then	nato
natočený	filmed	shot
natoľko	so
natrvalo	permanently
navonok	outwardly
navrhnuté	designed
navrhnutý	designed
navrhol	proposed
navyše	in addition	moreover
navzájom	each other
navštevoval	visited	attended
navštívil	visited	visited the
navštíviť	visit
navždy	forever
naznačuje	suggests
naznačujú	suggests
nazval	labeled	alive
nazýva	called the	called
nazývajú	call
nazývali	called it	called
nazývame	called
nazývaná	called
nazývané	called
nazývaný	called
nazývaných	called
nazývať	call	s call
naďalej	continue to	continue
naň	it	on it
naša	our
naše	our
našej	our
našich	our
našiel	found
našli	found	find
našom	our own	our
našťastie	fortunately	nastase
ne	not
nebezpečenstvo	danger
nebezpečné	perilously
nebol	was not
nebola	not	it wasnt	was not
neboli	or
nebolo	was not
nebude	not	will not be
nebudú	will	will not be
nech	may	my
nechal	had
nechala	had	allowed
nechcel	didn't want	did not want to
nedajú	not
nedeľu	sunday
nedokázal	could	did not prove
nedokázali	did not manage to	failed to
nedokáže	unable	unable to
nedostatkom	lack of	scarcity
nedostatku	lack of	lack
nedostatok	lack
nedostatočne	lack of	insufficient	poorly
nedošlo	did not occur	no
nedá	neda	can not
nedávno	recently
neexistuje	no	not exist
neexistujú	not exist
negatívne	negatively	negative
negatívny	negative
neho	it
nej	it
nejakom	some
nejaké	some
nejakého	some
nejakú	some
nejaký	some kind of	some	any
nejakým	some
nejde	not
nekonečne	infinitely
nekov	metalloid	non-metal
nemajú	do not have	they have no prime
nemal	not	do not have
nemala	not
nemali	not	did not have
nemalo	not
nemci	germans
nemcom	german	germans
nemcov	nemcov	germans
nemecka	germany
nemeckej	german
nemecko	germany
nemeckom	german
nemeckou	german
nemecku	germany
nemecky	german
nemecká	germany
nemecké	german
nemeckého	german
nemeckí	german
nemeckú	german
nemecký	german
nemeckých	german
nemeckým	german
nemeckými	german
nemocnica	hospital
nemocnice	hospital
nemocnici	hospital
nemohli	not	could not
nemohol	not	could not
nemožno	can not
nemožné	impossible	impossibly
nemu	it
nemusia	not
nemusí	do not	need not
nemá	do not have	nema
nemôže	can not	can not go
nemôžeme	we can not	can not
nemčina	german
nemčine	german
nemčiny	german
neobsahuje	does not contain	not contain
neobsahujú	containing	not contain
neobyčajne	extremly	extremely
neoficiálne	unofficial
nepodarilo	not	failed to
neposlednom	not	not least
nepoužíva	used
nepoužívajú	do not enjoy	do not use
nepravidelné	irregularly
nepresne	inaccurately
nepretržite	continuously	continously
nepriamo	indirectly
nepriateľa	enemy
nepriateľom	enemy
nepriateľov	enemy	enemies
nepriateľovi	enemy	enemies
neptún	neptune
neptúna	neptune
nepár	strange	odd
nerastné	mineral
nerastných	mineral
neraz	often
neschopnosť	inability
nesie	bears
neskorej	late
neskoro	late
neskoršie	later
neskoršieho	later
neskoršom	later
neskorší	later
neskorších	later
neskôr	later
nesmie	not	may not
nesmierne	enormously
nespokojnosť	dissatisfaction
nesprávne	wrong
netscape	netscape
network	network
neustále	constantly
neutrónov	neutrons	neutron
neuznané	unrecognized
nevedel	did not know	did not
nevhodné	unduly
nevie	can not
nevyhnutne	necessarily
nevyhnutná	necessary
nevyhnutné	necessarily
nevýhodou	disadvantage
nevýhody	cons	disadvantages
new	new
news	news
newton	newton
newtonov	newton
nezamestnanosti	unemployment
nezamestnanosť	unemployment
neznáma	unknown
neznáme	unknown
neznámy	unknown
nezávisle	independently
nezávislosti	independence
nezávislosť	independence
nezávislá	independent
nezávislé	independent	independently
nezávislý	an independent	independent
nezávislých	independent
nezávislým	by a separate
nezávisí	independent
neúspechu	failure
neúspešne	unsuccessfully
neďaleko	not far
než	than
nhl	nhl
nich	them
nie	not	we
niekde	somewhere
niekedy	sometines
niekoľko	couple	several
niekoľkokrát	several times
niekoľkých	few	a few	several
niekoľkými	some
niekto	someone
niektoré	some
niektorí	some
niektorý	some
niektorých	of some
niektorým	some
niektorými	some
nielen	not just	not only
niet	no
niečo	anything
niečoho	something
night	night
nijako	nothing
nikde	nowhere
nikdy	never
niklu	nickel
nikto	no one
nim	them
nimi	them
nirvana	nirvana
nitra	inside	nitra
nitre	nitre
nitrianska	nitra
nitrianske	nitra	nitria
nitriansky	nitriansky
nitry	nitra
nič	nothing
nižšej	lower
nižšia	lower
nižšie	below
nižšiu	lower	a lower
nižší	lower
nižších	lower
no	but	no
noc	night
noci	night
noha	foot
nohy	feet
nominálnej	nominal
norma	norm	standard
normalizácia	normalisation	standardization	normalization
normy	standards
normálne	normally	normal
normálnej	normal
normálny	normal
normálnych	normally
nosili	wear
nosič	carrier	carier	rack	bearer
notredame	notre	notre-dame	notre dame
novads	novads
novej	new
novela	amendment	novel
november	november
novembra	november
novembri	november
noviny	newspaper
novinách	newspaper
novo	new
novom	new
novou	new
novozámocký	nové zámky	novozámocká
nová	new	nova
nové	new
nového	new	novi
novému	new
novín	newspaper	newspapers
novú	new	new moon
nový	new
nových	new
novým	new
novými	make new	new	with/by new
novšie	later	newer
nr	nr
nulová	zero
nutne	necessarily
nutnosť	need
nutné	necessarily
nvidia	nvidia
náboj	charge	shots
náboja	charge
náboženskej	religious
náboženská	spiritual	religious
náboženské	religious
náboženského	religion	religious
náboženský	religiously	religious
náboženských	spiritual	religious
náboženským	a religious
náboženstiev	religions
náboženstva	religions	religion
náboženstvo	religion
náboženstvom	religion
náboženstvá	religions	religion
nádej	hope
nádoby	container
nádor	tumor	tumour
nádoru	tumor
nádrž	tank	reservoir
nádrže	tanks
nádvorie	quadrum
nádychu	breath	intake of breath
náhle	suddenly
náhrada	replaces
nájdeme	found	we find
nájdené	founded	found	foundit
nákazy	infection
nákladov	costs
náklady	costs	costs by
nálezisko	site
náleziská	locality
nálezov	awards
nálezy	findings
nám	we
námestia	square
námestie	square
námestí	square
námetom	theme
námornej	marine
nápis	inscription	writing
nápisy	subtitles	signs
nárast	increase	growth
národ	nation
národa	nation
národnej	national
národnom	national
národnosti	nationality	nationalities
národnostné	national	nationally
národnostných	national
národností	nationalities
národnosť	nationality
národnou	national
národná	national
národné	national	people
národného	national
národnú	nations
národný	national	nation
národných	national
národným	for national	national
národom	nation
národov	people	nation
národy	nations
nárok	demand
nároky	claims	demands
náročné	demanding	difficult
nás	our
násilia	violence
násilie	violence
násilne	forcibly
následkom	following	caused by
následky	consequences
následne	subsequently
následné	subsequently
následným	next i	next
následok	result
nástroj	body	tool
nástroje	instruments	tools
nástrojom	tool of	tool
nástrojov	tools
nástup	get
nástupca	successor
nástupcom	successor
nástupcu	successors	successor
nástupe	taking
nástupom	arrival	onset
náuka	science
návrat	arrival	return	back
návrate	came home	returning
návratu	return
návrh	proposal
návrhov	of proposals	proposals
návrhu	concept	design
návrhy	proposals	suggestions	plans
návšteve	visit
návštevníkov	visitors	visitors of
návštevy	visit	visits
názor	view
názorov	views	name	view
názoru	opinion	believer
názory	opinions
názov	name
názvom	name	filename
názvov	these are specified	names	name
názvu	of the name of	name
názvy	names
náš	our
nášho	our
ním	them
nízka	low
nízke	low
nízkej	a low	low
nízko	low
nízkou	a low	low
nízku	a low
nízky	low
nízkych	low
nízkym	threads	low
nížina	lowlands	lowland
nížiny	lowlands	lowland
nórska	norway
nórsko	norway
nórsku	norway
nútení	forced
nútený	forced	forced to
o	of	for
oba	both	two
obaja	two
obal	packaging	cover
obavy	concerns
obce	community	village
obchod	trade
obchode	trade
obchodnej	business	trade
obchodná	shopping	trading	trade
obchodné	business	commercially
obchodníci	merchants
obchodný	business
obchodných	of commercial
obchodným	business
obchodu	trade
obchody	departures	trade
obci	community
obciach	communities
obcí	community
obdobia	period
obdobie	period
období	season	period
obdobím	season	period
obe	two
obec	community
obeh	circulation
obehu	circulation
obete	victims
obetí	casualties	victim
obeť	victims
obeťou	sacrifice	victim
obežnej	orbital	orbit
obežnou	heaviest	orbit
obežná	obese
obežné	current
obežnú	current
obežných	orbital	obese
obidva	both
obidvoch	two
obieha	orbits
obiehajú	orbit
obiehajúce	orbiting
objav	discovery
objavené	discovered
objavený	the real
objavil	discovered
objavila	appeared
objavili	discovered
objaviť	emerge	discover
objavovať	discover	arise
objavuje	discovers	appears
objavujú	appears
objavy	discoveries
objednávku	order
objekt	object
objektom	object
objektov	objects	object
objektu	object
objekty	objects	object
objem	volume
objemom	volume
objemu	volume
obklopené	surrounded	surrounded by
obklopuje	surrounds
obkľúčenia	siege
oblak	cloud
oblakov	clouds
oblaku	cloud
oblaky	clouds
oblasti	the	area
oblastiach	areas
oblastí	the	areas
oblasť	area
oblasťami	areas
oblasťou	area
oblačnosť	cloudiness	clouds	cloud cover
oblečenia	clothing
oblečenie	clothes
obliekania	dressing
oblohe	sky
oblohy	sky
oblúk	obluk	arch
oblúka	arc
obmedzenia	restrictions
obmedzenie	restriction
obmedzená	limited
obmedzené	limited
obmedzený	limited	restrictions
obmedzuje	determine	limits
obmýva	washes
obnovenie	restoration
obnoviť	restore
oboch	two
oboma	both
obr	fig.	figure
obrana	defence	defense
obrane	defense
obranné	defensive
obranu	defense
obrany	defense
obrat	turnover
obratník	tropic
obraz	picture
obraze	picture
obrazom	image
obrazov	images
obrazovke	screen
obrazu	image
obrazy	images
obrovské	huge
obrovskú	huge	enormous
obrovský	vastly	great
obrovských	huge
obruči	ring	rim
obrátil	turned its
obrázkov	images
obrázku	picture
obrázky	pictures
obrázok	picture
obsadenie	occupation
obsadené	booked	occupied
obsadení	cast	seizing	casting the
obsadil	occupied
obsadili	took over	occupied
obsadiť	cast
obsah	content
obsahom	a	content
obsahoval	contained
obsahovala	contained
obsahovať	include
obsahu	content
obsahuje	contains	includes
obsahujú	contains
obsahujúca	containing
obsahujúce	containing	including
obsahujúcich	containing	including
obuv	shoe	shoes	footwear
obuvi	shoes	footwear
obvod	circuit
obvode	circuit
obvodov	circuits
obvodu	circuit
obvody	circuits
obvykle	usually
obyvatelia	people
obyvateľa	capita
obyvateľmi	inhabitants	inhabitans
obyvateľov	inhabitants
obyvateľstva	population
obyvateľstvo	population
obyvateľstvom	population
obyvateľstvu	population
obyčajne	usually
obzvlášť	particularly
obývané	inhabited
občania	citizens	people
občanov	citizens
občas	from time to time	sometimes
občianska	civil
občianske	civil
občianskych	civil
občianstvo	citizenship
obľúbené	favourite	favorite
obľúbený	popular	clan
obľúbeným	popular	favorited
ocele	steel
ocenenia	awards
ocenenie	appreciation
oceán	ocean
oceáne	oceane	ocean
oceánom	ocean
oceánov	oceans
oceánu	ocean
oceľ	steel
ochorenia	disease
ochorenie	disease
ochorení	diseases
ochrana	protection
ochrane	protection
ochranou	protection
ochranu	protection
ochrany	protection
od	from
odboja	resistance
odbor	department
odborná	professional
odborné	expertly
odborníci	specialists	experts
odborných	professional	of professional
odbory	domains	unions
odchod	departure	leaving
odchode	departure	leaving
odchádza	leaves
odchýlky	deviations
oddelenia	department
oddelenie	department	oddečenie
oddelené	separately	separated
oddeľuje	separates
oddiel	division	section
oddieli	division	section
oddiely	divisions	troops
odev	clothing
odhadov	estimate	estimates
odhaduje	estimates
odhady	estimates	trade
odišiel	left
odišli	they went	left
odkaz	link
odkazy	links
odkiaľ	from where
odklon	departure
odlišná	different
odlišné	differently
odlišný	different	diferent
odlišných	different	diferent
odlišuje	different
odlišujú	different
odlíšiť	differentiate
odmieta	refuses to
odmietajú	refuse
odmietal	refused
odmietla	refused
odmietli	rejected
odmietol	rejected	refused
odohral	took place	played
odohrala	occurred
odohráva	place
odolnosť	immunity
odolné	resistant	hardily
odovzdal	gave
odpadu	waste
odpor	resistance
odporcov	opponents
odporúča	recommended	recommends
odpoveď	answer
odráža	reflects
odstránenie	removing	removal
odstrániť	remove
odsúdená	doomed
odtiaľ	from there
odvesny	ordinate
odvetvia	subdivisions	industry
odvetví	industry
odvodené	derived
odvoláva	reference
odvtedy	since
odísť	you leave
of	of
ofenzíva	offensive
ofenzívy	offensive
oficiálna	official
oficiálne	official	officially
oficiálny	official
oficiálnych	official
oficiálnym	official
ohanbia	pubic	public
ohlas	response
ohrozenia	threat
ohrozenie	thread	threat
ohľadom	about
ohľadu	regardless
ohňa	fire	of fire on
oka	eye
okamihu	moment	time
okamžite	immediately
okien	windows
okná	window
oko	eye
okolia	surroundings	ambient
okolie	neighborhood
okolité	surrounding
okolitého	ambient
okolitých	neighboring
okolností	circumstances
okolo	about	around
okolí	neighborhood	around
okolím	surroundings	their surroundings
okom	eye
okraj	edge
okraji	edge
okrajoch	edges
okrajom	edge
okrem	except	besides
okres	district
okresy	districts	district
okruh	circuit
okruhu	circuit
október	oktober	october
októbra	oct.	october
októbri	october
okupácie	occupation
olej	oil
oltár	altar	altair
olympijské	olympic
olympijských	olympic
omnoho	much	more
on	he
ona	she
ondrej	ondrej	andrew
ondreja	ondrej	andrew
one	one
onedlho	soon	before
oni	they
online	online
ono	it
op	op.
opak	opposite
opakovane	repeatedly
opakuje	repeats
opatrenia	measures
opačnom	otherwise	opposite
opačným	otherwise	opposite
opec	opec
open	open
opera	opera
operačné	operationally
operačného	operating
operačný	operation	operating
operačných	of operating	operating
operačným	operating
operu	opera
opery	opera
operácia	operation
operácie	operations
operácii	operation	surgeries
operáciu	operation	surgery for
operácií	operations	surgeries
opevnenia	fortified	fortifications
opevnenie	fortification
opevnení	fortification	defenses
opiera	based
opis	description
opisuje	describes
opozície	opposition
oproti	against
optickej	optical
optická	optical
optické	optical
optických	optical	relations
opustil	left
opustili	abandoned	left
opustiť	leave
opátstvo	abbey
opäť	abbot
opísal	described by	described
opísať	described by	described
opúšťa	leaves
orange	orange
orava	orava
orchester	orchestra
organickej	organic
organické	organic
organických	organic
organizme	body	organism
organizmov	organism	organisms
organizmu	organism
organizmus	organism
organizmy	organisms
organizuje	organizes
organizácia	organization
organizácie	organisations
organizácii	organisation	organisations
organizáciou	organization	organisation
organizáciu	organization	organization by
organizácií	organisation	organisations
orgán	organ
orgánmi	organs	crack down
orgánom	organ
orgánov	organs
orgány	organs
orientované	oriented
orientovaný	oriented
orientácia	orientation
orientáciu	orientation
orol	eagle
os	axis
osada	settlement	village
osady	settlements	sattlements
osem	eight
osemdesiatych	eighties
osi	axis
osifikácia	ossifications	ossification
oslavujú	celebrate
oslavy	celebrations
oslobodenia	to set free	liberation
oslobodenie	liberation	exemption
oslobodení	relief
oslobodili	liberated
oslobodiť	free
osmanskej	ottoman	osman
osn	un
osoba	person	entity
osobe	person
osobitné	separately
osobne	personally
osobnej	personal
osobnosti	personality
osobností	personality
osobnosť	personality
osobná	personal
osobné	personal	personally
osobného	personal	person
osobnú	person
osobný	personal
osobných	personal	private
osobou	person
osobu	person
osoby	people
osobám	person
osou	axle	axis
ostal	remained
ostali	remained
ostalo	remained
ostane	remains
ostatné	moreover
ostatní	others
ostatných	other	others
ostatným	other
ostatnými	others
ostro	sharply
ostrov	island
ostrova	island
ostrove	island
ostrovoch	islands
ostrovov	islands
ostrovy	islands
ostáva	remains
osud	fate
osvetlenie	lighting
osvietenstva	enlightenment
osvietenstvo	enlightenment	enlightment
osád	settlements
osídlenia	settlements
osídlenie	settlement
osídlené	populated
osôb	people
otca	father
otcom	father
otcovi	father
otec	father
otepľovania	warming
otroci	slaves
otroctva	slavery
otrokov	slaves
otto	otto
otvorene	openly	open	opened
otvorenie	opening
otvorená	opened on	open
otvorené	openly	open
otvorenú	open
otvorený	open
otvory	openings	holes
otázka	question
otázkach	questions	issues
otázke	question
otázkou	question of
otázku	question
otázky	questions
otázok	questions
otáčania	rotation	twisting
out	out
oveľa	much
oviec	sheep
ovládal	control	control pc
ovládač	driver
ovládať	to control	controls	command (first sentence), control (second and third sentence)
ovocie	fruit
ovplyvnená	affected
ovplyvnené	affected
ovplyvnený	influenced	influenced by
ovplyvnil	influenced
ovplyvnila	affected
ovplyvniť	influence
ovplyvňuje	influences
ovplyvňujú	influence	influences
ovzdušia	atmosphere	the air	air
ovčiak	sheepdog
oxid	oxide
oxidačné	oxidation	oxidant
oxidom	oxide
oxidov	oxides	oxsides
oxidu	carbon	oxid
ozbrojené	armed
ozbrojených	armed
označenia	designation
označenie	marking	label
označené	marked
označením	label
označil	described	marked
označili	identified
označiť	mark
označoval	marked
označovali	marked
označovaná	labelled	labeling
označované	known
označovaný	called	labeling
označovať	denote	mark
označuje	indicates
označujeme	denote
označujú	indicates	mark
oznámil	announced
ozón	ozone
ozónu	ozone
očakáva	expected
očakávať	expect
oči	eyes	eye
očí	eye
oženil	married
p	p
pacient	patient
pacienta	patient
pacientov	patients
padla	fell
padlo	fell
padol	fell
pakistan	pakistan
pakistanu	pakistan
palace	palace
paleolitu	paleolithic
palestíny	palestine	of palestine
paliva	fuel
palivo	fuel
palivá	fuel
palube	board
palác	palac	thumb
paláca	castle	palace
paláce	palace
paláci	palace
palív	fuels
pamiatka	monument
pamiatkou	monument
pamiatku	memory
pamiatky	monuments
pamiatok	sites
pamäte	memory
pamäti	memory
pamätná	memorable	smart
pamätné	memorable
pamätník	memorial
pamätných	commemorative	memorial
pamäť	memory aid	memory
pamäťou	memory
pancier	armor
pancieru	armor
panda	panda
panna	virgin	panna
panne	virgin	panne
panny	panny
panovania	reign
panovník	ruler
panovníka	ruler
panovníkov	monarchs
panstva	estate
panva	basin
panvy	basin
papier	paper
papiera	paper
para	steam
paradoxne	paradoxically
paralelne	parallel
paralelný	parallel
parametre	parameters
paris	paris
park	park
parku	park
parky	parks
parlament	parliament
parlamentných	parliamentary
parlamentom	parliament
parlamentu	parliament
partie	game
partizáni	guerilla	partizani
partizánmi	partisans
partizánom	partisan	partisans
partizánov	partisans
partizánske	partisan	partizanske
partnerské	partnering	partner
party	party
pary	steam
paríž	paris
paríža	paris
paríži	paris
patent	patent
patria	belong	are
patril	was one	belonged to
patrila	included
patrili	belong	were
patrilo	included	belonged	belongs
patronát	patronat
patrí	belongs
paul	paul
paula	paula
pavel	paul
pavla	pavol	paul
pavol	paul
paľbu	fire
pb	rb
pc	pc
pechota	infantry
pechoty	corps
pedagóg	pedagogue
pedológia	pedology	pedagogy
peniaze	money
penis	penis
penisu	penis
pentium	pentium
per	per
percento	percentage
periodickej	periodic
perióda	period
peru	peru
perverzia	perversion
perzie	persia
perzskej	persian
perzského	persian
peržania	the persians
pes	dog
pestovanie	growing	cultivation
pestuje	grown	breeds
peter	peter
petra	petar
petrohrad	st. petersburg
petržalka	fc	petrzalka
petržalke	petržalka	petrzalka
petržalky	petržalka	petrzalka
pevne	solid	oven
pevniny	dry land	mainland
pevnom	hard
pevnosti	strength
pevnosť	strength
pevná	brand name
pevné	solid
pevného	solid
pevný	inch hard	exchange
pevných	solid
pečať	seal
pečene	baked	liver
peňazí	upon	upon production
ph	ph
phd	dr.	phd
phdr	dr.
phi	phi
physik	physicist	physik
piata	fifth
piatich	five
piatimi	five
piaty	fifth
picasso	picasso
picchu	picchu
pieseň	song
piesne	songs	song
piesni	song
piesní	song	songs
pieta	piety
pietro	pietro
piešťany	piestany
pilot	pilot
pink	pink
pioneer	pioneer
pionier	pioneer
pistols	pistols
place	place
planét	planets
planéta	planet
planéte	planet
planétka	asteroid	planetoid
planétky	asteroid
planétok	planet	planets
planétou	planet
planétu	planet
planéty	planet
platby	payments
platia	apply	valid
platiť	pay
platne	plates
platnosti	force
platné	plates
platní	plate	plates
platí	pays	pay
platón	plato
platóna	plato
platňu	plate	valid
plaváreň	swimming pool
play	play
playoff	playoff
plemena	breeds
plemeno	breed
plemená	race
plemien	breeds
plne	fully	full
plnej	full
plnenie	fulfillment
plnom	full
plná	full
plné	fully	full
plní	full of	full
plný	full
plocha	area
plochami	areas
ploche	area
plochou	area
plochu	area
plochy	areas	area
plodu	foetus	fetus
plody	fruits
plodín	crops
plošina	platform	flatbed
pluralizmus	pluralism
plus	plus
plyn	gas
plynné	fluent
plynov	gas
plynu	gas
plyny	gases
plán	plan
plánov	plans
plánoval	planned
plánovania	planning
plánovanie	scheduling
plánované	planned	planned to
plánu	plan
plány	plans
plášť	plastic
plášťa	plastic
plôch	areas
pn	pn
po	after
pobrežia	coast
pobrežie	coast
pobreží	coast
pobyt	stay
pobytu	stay
pochopiť	understand
pochovaný	buried
pochybnosti	doubt	doubts
pochádza	as coming	coming
pochádzajú	comes from (first and second sentence), originate from (third sentence)	come
pochádzajúce	coming
pochádzal	came
pochádzala	came
pochádzali	originated	came
pocit	feeling	why
pocity	procity	feelings
pod	below	under
podania	filing	versions
podanie	filing
podaní	administration	filed
podarilo	managed
podarí	manage	manage to
podať	give	hand
podhradie	podhradie	extramural
podiel	share
podieľa	participates
podieľajú	share	participate
podieľal	involved	took place
podieľali	partecipated	participated
podlieha	subject
podmienkach	conditions
podmienkami	conditions
podmienkou	condition
podmienky	conditions
podmienok	conditions
podnebia	climate
podnebie	climate
podnebím	climate
podnety	stimuli
podnik	company	business
podnikania	business
podnikov	company	business
podniku	business
podniky	businesses
podoba	resemblance	form
podobe	stab	form
podobne	similarly
podobná	similarity to	similiar
podobné	similiar	similiarly	similarly
podobnú	like
podobný	similar to	similar
podobných	for similar	similar
podobným	similar
podobu	form
podoby	form
podobá	form
podpisom	signature
podpora	support	promotion
podpore	support
podporou	support
podporoval	support	supported
podporovala	supported
podporovali	support
podporovalo	supported
podporované	supported
podporovaný	supported
podporovať	support
podporu	support
podporuje	supports
podporujú	supports
podpory	support
podpísal	signed a	signed
podpísali	signed a
podpísaná	signings
podrad	suborder
podrobnosti	details	particulars
podstata	essence	nature
podstate	essentially
podstatne	significantly
podstatné	significantly
podstatnú	significant
podstatou	nature
podstatu	nature
podstaty	nature
podujatia	events
podvozku	chassis	chasis
podvozok	chassis
podzemných	underground
podáva	administer	given
podľa	according to
pohlavia	sex
pohlavné	sexually
pohlavného	genital	sexual
pohlavný	sexual
pohlavných	sexual	sex
pohon	drive
pohoria	mountains
pohorie	mountain range
pohorí	mountains
pohraničné	border
pohyb	movement
pohybe	movement
pohyblivé	moving
pohybom	motion	move
pohybov	movements
pohybovať	move
pohybu	motion	move
pohybuje	moves
pohybujú	sag	move around
pohyby	funeral	movements
pohár	cup
pohára	cup
pohľad	look	view
pohľade	looking
pohľadu	point of view	view
pohľady	view
pojem	concept	notion
pojmom	term
pojmu	term	of the
pojmy	terms
pokiaľ	unless
pokles	decrease
poklesu	decline
pokoja	peace
pokoji	peace	room
pokračoval	continued
pokračovala	continued
pokračovali	continued
pokračovanie	continue
pokračovať	continue	to continue
pokračuje	continues
pokrok	progress
pokrytá	covered
pokryté	cover
pokrytý	covered
pokrýva	covers
pokrývajú	will cover the	cover
pokus	attempt
pokuse	attempt
pokusom	attemp	attempt
pokusov	attempts
pokusy	attempts	tries
pokémon	pokemon
pokémonov	pokemons	pokemon
pokúsil	tried
pokúsili	attempted
pokúša	tries
pokúšal	attempted
pokúšali	tried to	tried
pol	half
pole	field
poli	field
polia	fields
poliaci	poles
politici	politicians
politickej	political
politickou	political
politicky	politically
politická	a political	political
politické	political
politického	political
politickú	political
politický	politically
politických	political
politickým	political
politik	politic	politician
politika	policy
politike	policy
politikou	policy
politikov	politicians
politiku	policy
politiky	policy
pologuli	hemisphere	semisphere
poloha	location
polohe	position	location
polohopis	topography
polohu	location
polohy	position
polohách	elevations
polomer	radius
polostrov	peninsula
polostrova	peninsula
polostrove	peninsula
polovica	half
polovice	half
polovici	half
polovicu	half
polovodiče	semiconductors
polovodičov	semiconductors
položené	highest	asked
polysacharid	polysaccharide
polárnych	polar
polí	fields
polícia	police
polície	police
pomalky	pomalky	tardigrade	slowly	smaller	less
pomaly	slowly
pomalšie	slower
pomenovania	names
pomenovanie	name
pomenovaná	named	labeled	addressing
pomenované	named	named by
pomenovaný	named
pomer	ratio
pomere	ratio
pomerne	usually	relatively
pomerov	conditions
pomeru	radio	ratio
pomery	circumstances
pomník	monument
pomoc	help
pomoci	help
pomocou	with the help of	by
pomohol	helped	help
pompadour	pompadour
pomáha	helps
pomáhajú	help
pomáhali	helped
pomôcť	help
ponuku	offer
ponúka	offer
ponúkajú	offer
ponúkol	offered	offered the
pop	pop
popis	description
poprad	poprad
poprade	poprad
popradu	poprad
popredia	fore
popri	in addition	besides
popularita	popularity
popularite	popularity
popularitu	popularity
populácia	population
populácie	population
populárna	popular
populárne	popular
populárnej	the popular
populárny	popular
poradie	order
poradí	respectively	order
porazil	defeated
porazili	defeated
poraziť	beat	defeat
poriadku	order
poriadok	order
porodila	gave birth	birth
porovnanie	comparison	comparision
porovnaní	comparison
port	port
porte	port
portrét	portrait
portugalska	portugal
portugalsko	portugal
portál	portal
porucha	failure
poruchy	disturbance
porážka	defeat
porážke	stroke	defeat
porážku	defeat
poskytnúť	provided
poskytovať	provide
poskytuje	provide	provides
poskytujú	provide	provide so
poslal	sent
poslanca	member	deputy
poslanci	members of parliament	parliamentarian
poslancov	members
poslanec	parliamentarian	deputy
poslednej	last	the last
poslednom	last
poslednou	last
posledná	a last	last
posledné	last	the last
posledného	last	last of	the last
poslednú	last	final
posledný	last
posledných	past	last
posledným	s latest	last	the latest
post	post
postava	figure
postavenia	standing	position
postavenie	position
postavená	built
postavené	built
postavení	position
postavením	standing	position
postavený	built (first and second sentence) constructed (third sentence)
postavil	put	built
postavili	built
postaviť	stand on	construct
postavou	character	figure
postavy	figures	characters
postoj	stance
postoje	postures	attitudes
postup	procedure
postupne	gradually
postupnosti	sequence
postupnosť	sequence
postupným	gradual	by successive
postupom	procedure
postupov	procedures
postupovali	follow	proceeded
postupovať	do
postupu	procedure
postupujúce	progressing	advancing
postupy	procedures	methods
postáv	characters
postúpili	forwarded	advanced
posun	shift
posádka	crew
posádky	crew
potenciál	potential
potlačenie	suppression
potlačení	suppressed
potlačiť	suppress
potok	stream
potoka	brook	creek
potom	then
potomkov	offspring	descendants
potomkovia	progeny
potrat	abortion
potratu	abortation	abortion
potrava	food
potraviny	grocery	foodstuffs
potravinársky	food
potravou	food
potravy	food
potravín	food
potreba	need
potrebná	required
potrebné	needed	needs
potrebnú	need	needs
potrebný	required
potrebných	of necessary	necessary
potrebu	need
potrebuje	needs
potrebujú	need	i need
potreby	needs
potrieb	needs
potter	potter
potvrdenie	confirmation
potvrdené	confirmed
potvrdil	confirmed
potvrdili	confirmed
potvrdzuje	confirms
poukazujú	showing	points
použil	used
použili	have used	used
použitia	use	used
použitie	use
použitá	used
použité	use
použití	use	used
použitím	using	using a
použitý	used
použitých	used
použiť	use	used
používa	to use	used	uses
používajú	decoys
používal	was used	used the
používala	used
používali	used
používalo	used
používania	using	used
používaná	being used by	used
používané	used both
používaním	using	being used by
používaný	use
používaných	used
používaným	being used by	use
používatelia	across
používateľ	the user
používateľa	users'	users
používateľov	reviews	users
používať	use	used
povahu	nature
považoval	considered
považovali	considered
považovaná	considered
považované	considered
považovaný	considered
považovať	consider the	consider
považská	povazska	považská
považuje	considered
považujú	i consider
povedal	said	he said
povedané	spoken	said in	said
povedať	say
povedomia	awareness
poveril	commissioned
povesti	reputation
poviedka	story
povinnosti	responsibilities
povinnosť	obligation
povinné	mandatory
povinný	required
povodia	basins	basin
povolenie	permission
povolené	allowed
povrch	surface
povrchom	surface
povrchové	surfactants	surface
povrchových	of surface	surface
povrchu	surface
povstalci	rebels
povstalcom	rebels
povstalcov	rebels
povstaleckej	rebel
povstalecké	rebel
povstania	uprising
povstanie	uprising
povstaní	uprising
pozadia	background
pozadí	background
pozdĺž	along
pozemné	ground
pozemných	land
pozemského	earth's
pozitívne	positive	positively
poznajú	know
poznal	identified
poznali	know
poznania	knowledge
poznanie	knowledge
poznatkov	knowledge
poznatky	knowledge
poznať	know
poznáme	know	sweat
poznámka	note
poznámky	notes
pozor	warning	care
pozornosti	attention
pozornosť	attention
pozorovania	observations
pozorovanie	observation
pozorované	observed	the observed
pozorovaní	observations
pozorovatelia	observers
pozorovateľ	observer
pozorovateľa	observer
pozorovateľné	observer
pozorovateľný	vantage	noticable
pozorovateľov	observers
pozorovať	watch	to look
pozorujeme	observed
pozostatky	remains
pozostáva	comprises	consist
pozri	see	look
pozícia	position	pisition
pozície	position
pozícii	holdings
pozíciu	position
pozícií	holdings
poézia	poetry
poézie	poetry
počas	during
počasia	weather
počasie	weather
počatia	conception
počesť	honour	honor
počet	number of
početné	numerically
početných	numerous
počiatkom	precursor	early
počiatku	beginning
počiatky	origins
počiatočné	an initial
počte	number of	number
počtom	sum	number of
počtu	count	of	number of
počty	figures	numbers
počuť	hear
počíta	awakened	counts
počítač	computer
počítača	counts	computer
počítače	pcs	computers
počítači	computer in	computer
počítačmi	computers
počítačoch	computer	computers
počítačom	computer
počítačov	computers
počítačovej	computer
počítačová	computer
počítačové	computer
počítačový	computer
počítačových	computer	a computer's
počítaču	pc
počítať	count
poľa	field
poľnohospodárska	agricultural
poľnohospodárske	agricultural
poľnohospodárskej	agricultural
poľnohospodárskych	agricultural
poľnohospodárstva	of agriculture	agriculture
poľnohospodárstve	of agriculture	agriculture
poľnohospodárstvo	agriculture in	agriculture
poľom	field	slash
poľska	polish	poland
poľskej	poland's
poľsko	poland
poľskom	polish
poľsku	poland
poľská	poland
poľské	polish
poľského	polish
poľský	polish
poškodenia	damage
poškodenie	damage	to destroy the
pošty	post offices	post
pošvy	sheath	vagina
požiadal	asked for	asked
požiadaviek	requirements
požiadavku	requirement	request
požiadavky	requirements
prach	dust
prachu	dust
pracoval	worked
pracovala	worked
pracovali	worked
pracovať	work
pracovnej	work	working
pracovná	study	labour
pracovné	job	work related
pracovného	job	occupational
pracovníci	workers	worker
pracovníkov	employees	staff
pracovný	study
pracovných	work	office
pracuje	works
pracujú	work
pracujúcich	workers
praha	prague
prahe	prague
prahy	threshold	thresholds
prakticky	virtually
praktické	practical	the practical
praktického	practical	of practical
pramene	sources
pramení	source
prameňov	springs
pravda	true
pravdepodobne	probably
pravdepodobnosti	likelihood
pravdepodobnosť	probability
pravdepodobné	probably	likely	most likely
pravdou	true	truth
pravdu	truth
pravdy	truth
pravej	right
pravek	prehistory
praveku	prehistoric
pravidelne	regularly
pravidelné	regularly
pravidla	rules
pravidlo	rule
pravidlá	rules
pravom	right	legal
pravoslávna	ecumenical	orthodox
pravoslávnej	orthodox
pravoslávni	orthodox
pravouhlého	rectangular
pravá	right
pravé	just
pravý	to edit	true
prax	practice	experience
praxe	practice
praxi	practice
pražskej	prague
pre	for
prebehla	was conducted	happened
prebehli	took place
prebieha	progress
prebiehajú	underway
prebiehal	was conducted	ran over
prebiehala	in progress	conducted
prebiehali	conducted
prebiehať	in progress
prechod	transition
prechode	transition
prechodné	transiently
prechodom	transition
prechodu	transition
prechádza	passes
prechádzajú	cross	pass
pred	before
predaj	sale
predaja	sales	sale
predalo	sold
predbežne	provisionally
predchodcov	predecessor
predchodcu	predecessor
predchádza	preceeds
predchádzajúce	anterior	previous
predchádzajúceho	having several
predchádzajúcej	previous
predchádzajúcich	previous
predkov	ancestors
predkovia	ancestors
predlohy	master
predložil	submitted	presented
predmet	subject
predmetom	subject
predmetov	objects	subject
predmetu	subject
predmety	items
prednej	front
prednosť	precedence	preferred
predná	front
predovšetkým	mainly
predpisov	regulations
predpokladal	assumed
predpokladalo	expected
predpokladu	provided
predpoklady	assumption	assumptions
predpokladá	assume	assumes
predsa	yet
predseda	chairman
predsedníctvo	presidency
predsedom	president
predsedov	presidents
predsedu	president
predsiene	atrium
predstava	idea
predstavenia	performance
predstavil	introduced	presented
predstavitelia	representatives
predstaviteľ	representative
predstaviteľmi	representatives
predstaviteľom	representative
predstaviteľov	representatives
predstaviť	imagine
predstavoval	was
predstavovali	accounted	accounted for
predstavu	idea
predstavuje	a	represents
predstavujú	represents	are
predstavy	ideas
predstáv	ideas
predtým	previously	before
prehliadač	(web) browser	browser
prehliadača	browser
prehliadačov	browsers	browsears
prehľad	overview
prejav	speech	speech, demonstration
prejave	speech
prejavil	express	showed
prejavili	showed
prejavom	expression
prejavov	expressions	manifestations
prejavovať	display	manifest
prejavu	performance	expression
prejavuje	shows
prejavujú	show
prejavy	manifestations	displays
prejde	passes
prejsť	go
preklad	translation
preklade	translation
preklady	translation	translations
prekonať	overcome
prekážky	barriers	obstacles
prelome	turn	between
premena	transformation
premenu	transformation
premeny	converting	conversion
premiér	prime minister
premiéra	prime
prenasledovanie	persecution
prenikli	penetrated
preniká	penetrates
prenos	transmission
prenosu	transmission
prenáša	transfers
prenášajú	carry	transfer
prenášať	trasmitted	transmitted
prepojenie	connection
prepojené	linked
prerušenie	interrupt	interruption
presadil	asserted
presadiť	reposition	enforce
presadzoval	promoted	championed
presahuje	exceeds
presley	presley
preslávil	famous	was famous
presne	exactly
presnejšie	more accurate	more
presnosť	accuracy
presnosťou	accuracy
presná	accurate	correct
presné	accurate	exactly
presný	accurate
press	press
prestal	stopped	stooped
prestavba	reconstruction
presvedčenia	convictions	beliefs
presvedčení	convinced	beliefs
presvedčený	confident	sure	conviction
presvedčiť	convince
presťahoval	moved
preteká	race
preto	so	therefore
pretože	because
prevahu	preponderance
prevažne	mainly	mostly
prevažná	preponderant
prevencia	prevantion	prevention
previesť	to convert
prevláda	prevalent
prevládajú	overcome	predominate
prevod	transfer
prevzal	took
prevzali	took over	assumed
prevádzke	operation
prevádzkuje	operates
prevádzky	operation	of its operation
prezident	president
prezidenta	president
prezidentom	president
prezidentské	president	presidential
prezidentských	presidential
prečo	why
prešiel	passed
prešla	walked	passed
prešli	go to	went	passed
prešlo	went	speech	passed
prešov	prešov
prešove	prešov	presov
prešovský	prešov	presov
prežil	survived
prežitie	survival
prežívanie	survival	experience
pri	at
priame	direct	directly
priameho	in direct	direct
priamo	directly
priamou	direct
priamu	direct
priamy	direct
priamym	direct
priatelia	friends
priateľ	friend
priateľa	friends	friend
priateľmi	friends
priateľom	friend of	friend
priateľov	friends
približne	approximately
približuje	close	gives a brief
prichádza	comes	comes from
prichádzajú	come	they come
prichádzali	coming in
pridal	added
pridali	added
pridaním	by adding	added
pridáva	adds	devolved
pridávajú	adding
priebeh	course	adults
priebehu	during	story
prieliv	strait	channel
priemer	diameter	average
priemere	average
priemerne	on average	average
priemerná	an average
priemerné	on average	average
priemerný	average	mean
priemerom	diameter
priemeru	average
priemysel	industry
priemyselne	industrially	industrial
priemyselnej	industry	industrial
priemyselná	industrial
priemyselné	industrially	industrial
priemyselných	industrial
priemysle	industry
priemyslu	industry
prieplav	canal	seaway	cannal
prieskum	study	survey
priest	priest
priestor	space
priestore	space
priestoroch	premises	spaces
priestorom	space
priestorov	premises
priestorové	the spatial
priestoru	space
priestory	spaces
prievidza	prievidza
prijal	received
prijala	accepted	adopted
prijali	accepted	take
prijatia	accepting	adoption
prijatie	adoption
prijatá	accepted by	adopted
prijaté	acceptable	accepted
prijatý	accepted
prijať	accept
prijíma	receives
prijímajú	are accepted	prima	received
prikázal	commanded	ordered
primárna	primary
primárne	primary
primárny	primary
primátor	mayor
princ	prince
princa	prince
princíp	principle
princípe	prinicple
princípom	principle
princípov	principles
princípu	principle
princípy	principles
priniesla	brought
priniesli	brought
prinieslo	brought
priniesol	brought
prináša	brings
pripadá	devolved
pripojenia	connections	connection
pripojenie	connection
pripojené	connected
pripojil	joined
pripojiť	connect
pripomína	reminds
pripravená	ready
pripravené	ready
pripravený	ready	prepared
pripravil	prepared
pripravoval	prepared
pripravuje	prepares
prirodzene	naturally
prirodzené	natural	naturally
prirodzeného	natural
prirodzený	natural	nature
prirodzeným	natural
prispel	contributed
prispela	contributed
prispeli	contributed
prispelo	contributed
prispieva	contributes
prispôsobiť	adapt
prisťahovalci	immigrants
prisťahovalcov	immigrants
pritom	while
priviedol	bring	led
priviesť	bring
privilégium	privilege	privilegium
pričom	and	which
prišiel	came
prišla	came
prišli	lost	came
prišlo	came	lost
pro	for
problém	problem
problémami	problems
problémom	the problem
problémov	problems
problému	problem
problémy	problem	problems
proces	process	proces
procese	process
procesom	process
procesor	processor
procesora	processor	cpu
procesorov	processors
procesory	processors
procesov	processes
procesu	process
procesy	processes
produkcia	production
produkcie	production
produkcii	production
produkciu	production
produkovať	produce
produkt	product
produktom	product
produktov	product
produktu	product
produkty	product	products
produkuje	produces
produkujú	produce a
prof	prof.
profesionálne	professional	professionally
profesionálnych	professional
profesor	professor
profesora	professor	proffesor
profil	profile
profile	profile
program	program
programe	program
programoch	programs
programom	program
programov	programs
programu	the
programy	programmes	programs
projekt	project
projekte	project
projektov	projects
projektu	project
projekty	projects
prorokov	prophets
prospech	benefit
prostredia	environment
prostredie	environment
prostredníctvom	through
prostredí	environment
prostredím	environment	enviroment
prostriedkami	means
prostriedkom	means
prostriedkov	resources
prostriedky	resources
prostriedok	means
protest	protest
protestanti	protestants
protestantské	protestant
proteín	protein
proteínov	protein
proteíny	proteins
proti	agaubst	against
protitankové	anti-tank
protitankových	anti-tank	against
protiútok	counterattack
protocol	protocol
protokol	protocol
protokolov	protocols
protokolu	protocol
protokoly	protocols
protón	protone	proton
protónov	protons
protónové	proton
protóny	protons
provincia	province
provincie	province	provinces
provincii	province
prsníka	breast
prstence	rings
prstencov	rings
prstenec	ring
prudko	suddenly	sharply
prusko	prussia
prvej	first
prvkami	elements
prvkom	element
prvkov	elements
prvku	element
prvky	elements
prvok	element
prvom	first
prvou	first
prvočísel	primes
prvočíslo	prime	prime number
prvá	first
prvé	the first	first
prvého	first
prvému	first
prví	first
prvú	first
prvý	first seen	first
prvých	first
prvýkrát	first time	for the first time
prvým	first
prvými	first
prác	works	working
práca	work	thesis
prácach	work
práce	work
práci	work
prácou	work
prácu	job	work
práv	rights
práva	justice	right
práve	just
právna	legally	legal
právne	legally
právneho	legal
právny	law	legal engagement
právnych	of legal	legal
právo	right
právom	right
právomoc	authority	power
právomoci	powers
príbeh	story
príbuzných	relatives
príchod	arrival	arrival of
príchode	arrival
príchodom	arrival	joining
príchodu	arrival	arrival of
prídavné	additionally
príjem	income
príjmy	incomes
príkaz	command	order
príkazy	commands	orders
príklad	example
príkladmi	examples of	examples
príkladom	one example of	examples
príklady	examples
príležitosti	occasion	opportunities
príležitostne	occasionally
príležitosť	aportunity	opportunity
príliš	too
prímerie	ceasefire
prínos	benefit	prinos
príp	ext
prípad	case	the case
prípade	case
prípadne	possibly	falls
prípadné	potential	falls
prípadoch	cases that	cases
prípadov	cases	causes
prípady	cases
príprava	preparation
príprave	preparation of	preparations
prípravu	preparation
prípravy	preparation
prírastok	increase
príroda	nature
prírode	nature
prírodnej	natural
prírodná	natural	nature
prírodné	natural
prírodný	natural
prírodných	natural
prírodu	nature
prírody	nature
príslušnosti	affiliation	membership
príslušnosť	affiliation	competence
príslušné	respectively	respective
príslušného	the	relevant
príslušníci	members
príslušníkov	of
príslušných	respective	appropriate
prísne	strictly
prístav	port
prístavu	harbor	ports
prístavy	ports
prístroj	standing position	apparatus
prístroja	apparatus
prístroje	apparatus
prístrojov	devices
prístup	access
prístupné	accessible	accesible
prístupové	access
prístupu	usage
prísť	passcode	come
prítok	tributary
prítoky	tributaries	inflows
prítomnosti	presence
prítomnosť	signal	presence
prítomnosťou	by the presence of	presence
prítomné	present
prítomný	present
prívrženci	followers	supporters
príznaky	symptoms	symptons	signs
príčin	causes
príčina	reason	cause
príčinou	cause
príčinu	cause
príčiny	causes
prózy	prose
prúd	prud	stream
prúdenie	convection
prúdom	current	stream
prúdov	currents
prúdu	prud	stream
prúdy	prudy	streams
ps	ps
psa	dog
psilocybín	psilocybin	psilocybine	psylocibin
psov	dogs
psy	dogs
psychické	mental	psychical
psychológia	psychology
psychóza	psychosis
psychózy	psychosis
public	public
publikoval	published
pulz	pulse
pulzu	pulse
punkerov	punks
punku	punk
purple	purple
pustil	released	got down to
px	px	pixel
px|n	px/n
px|pair	px pair
px|s	pxs	px / s
pyramíd	pyramid
pyramída	pyramid
pyramídy	pyramids
pád	fall
páde	case of	fall
pádom	pad	fall
pádu	november
pán	mr
pána	mr.	mister
pápež	pope
pápeža	pope
pápeži	pope
pápežom	pope
pápežov	pope	pope's
pápežovi	pope
pápežské	papal
pár	few	some
páry	couple	steam
párč	plot
pás	passport
pásiem	bands
pásma	band
pásme	gaza
pásmo	band	level
pásov	passports	belts
pásožiabrovce	pasoziabrovce	elasmobranchii
pásu	passport
pásy	passports	passport	pass
päť	five
päťdesiatych	the fifties	fifties
písal	wrote
písania	writing
písanie	writing
písané	written
písať	write
písma	fonts	writing
písmen	letters
písmena	letters
písmeno	qualifier	letter
písmenom	word	letter
písmená	letters
písmo	letter
písmom	letters
písomná	written
písomné	written	written documents
písomných	written
píše	writes
pól	pole	half
pólu	pole
póly	poles	poly
pôda	according to
pôde	soil	signed
pôdu	soil	land	ground
pôdy	soil	pods
pôrode	childbirth
pôsobenia	action	effect
pôsobenie	action
pôsobení	action	action reply
pôsobením	to joining	activity
pôsobia	operate
pôsobiace	operating
pôsobiacich	operating
pôsobil	he worked	worked
pôsobili	worked
pôsobiť	he worked
pôsobnosti	scope
pôsobnosť	scope	ability to act
pôsobí	worked	he worked
pôvod	flood
pôvode	origin	flood
pôvodne	originally
pôvodnej	original	the original
pôvodná	flood
pôvodné	floods
pôvodného	original	the original
pôvodní	flood
pôvodný	flood
pôvodných	original
pôvodným	flood	original
pôvodu	origin
púšte	desert
púšť	desert
pľúc	lungs
q	quarter
queen	queen
r	r
rachel	rachel	rechel
rad	series
rada	council
rade	place	board
radi	like
radikálne	radical	radically
radič	controller
radnica	town hall	city hall
radou	board	council
radov	ranks	series
radu	series	council
rady	board
radšej	rather
raid	raid
raj	heaven	eden	paradise
rakety	missiles	rockets
rakoviny	cancer
rakúska	austrian
rakúske	austrian
rakúskej	austrian
rakúsko	austria
rakúskom	austria
rakúskouhorska	austria-hungary
rakúskouhorsko	austria-hungary
rakúsku	austrian
rakúsky	austrian
rameno	shoulder	arm
ramená	shoulders
rané	wound
rast	growth
rastie	growing
rastislav	rastislav
rastislava	rastislav
rastlina	plant
rastlinná	vegetal	plant
rastlinných	plant
rastlinstvo	vegetation
rastliny	plants
rastlinách	plants
rastlín	plants	plant
rastu	growth
rastú	growth
rasy	race
ray	ray
raz	once	time
reagovať	respond
reaguje	reacts
reagujú	responsive
reakcia	reaction
reakcie	reactions	reaction
reakciou	reaction
reakcií	response
reaktor	reactor
reaktora	reactor
real	real
reality	reality
realizmu	realism
realizovať	implement
realizuje	implemented	realizes
realizáciu	implementation
rebríčkoch	rankings	charts
rebríčku	ranking	ladder
records	records
red	red
redaktor	editor
redukcia	reduction
redukuje	reduces
referencie	references	reference
reforiem	reform
reforma	reform
reformu	reform
reformy	reform	reforms
reformácia	reformation	reform, reformation
reformácie	reformation
reggae	reggae
regionálne	regional
región	region
regióne	region
regiónov	regions	the regions
regiónu	region
regióny	regions
reklamy	advertising	advertisement
rekonštrukcia	reconstruction
rekord	record
relativity	relativity
relatívne	relative	relatively
reliéf	relief
reliéfu	relief
remarque	remarque
renesancia	renaissance
renesancie	renaissance
renesančná	renaissance
rené	rene
represia	repression	repressia	suppression, repression	retaliation
reprezentuje	represents
reprezentujú	represents	representing
reprezentácia	representation
republika	republic
republike	republic
republikou	republic
republiku	republic
republiky	republic
republík	republic	republics
resp	resp	or
respektíve	respectively
revolučná	revolutionary
revolučné	revolutionary
revolúcia	revolution
revolúcie	revolution
revolúcii	revolution
revolúciou	revolution
revolúciu	revolution
rex	rex
rezerva	reserve
rezervácie	reservations
rezistorov	resitors	resistors
rezistory	resistors
reálna	real	world
reálne	real
reálnom	real
reálnych	of real
reč	rec	speech
reči	talk
reštaurácia	restauration	restaurant
reťazca	chain
reťazec	string	chain
režim	mode	regime
režime	mode
režimu	regime
rf	rf
rfc	rfc
riaa	riaa
riadenia	control	management (first and third sentence), governance (second sentence)
riadenie	management
riadená	management
riadené	guided	controlled
riadi	controls	governed
riadia	governed
riadil	directed
riaditeľ	director	advise
riadiť	manage	direct
riadku	line
riadok	line
riasy	cirruses	kelp
richard	richard
richarda	richard
riek	rivers
rieka	river
riekami	rivers
rieke	river
riekou	river
rieku	river
rieky	river
riešenia	solutions	solution
riešenie	solution
riešení	solution
riešením	solution	recourses
rieši	deals	solves
riešiť	solve
right|thumb|mapa	right / thumb / map
right|thumb|škoda	medium	right/thumb/skoda
rihanna	rihanna
rimania	romans	the romans
rio	rio
rizika	risk
riziko	risk
rj	r.j.	rj
rna	rna
road	road
robert	robert
roberta	robert	roberta
robespierre	robespierre
robia	do
robili	do
robiť	do
robotníkov	workers
robí	do	makes
rock	rock
rockovej	rock
rocku	rock
rod	genus	family
rodina	family
rodine	family
rodinou	family
rodinu	family
rodiny	families	family
rodičia	parents
rodičov	parents
rodnom	native
rodu	house	family
rodáci	natives
rodín	families
roger	roger
rok	year
roka	year
rokmi	years
rokoch	years
rokom	year
rokov	years
rokovania	negotations	negotiations
rokovaniach	negotiations
rokovaní	talks	negotiations
roku	of	in
roky	years
roll	roll
rolling	rolling
rolu	role
roman	roman	novel
romantizmu	romanticism
romantizmus	romanticism
román	roman
románe	novel
románu	romania	novel
ropa	oil
ropné	oil	alcohols
ropných	oil	of oil
ropy	oil
rose	rose
roses	roses
rotor	rotor
rotora	rotor
rotácia	rotation
rotácie	rotation
rotáciu	rotation
rovina	plane
rovine	plane
roviny	plain	plane
rovnakej	the same	same
rovnako	same	just
rovnakom	the same
rovnakou	same
rovnaká	the same	same
rovnaké	exactly the same
rovnakého	the same	same
rovnakú	the same	same
rovnaký	the same	same
rovnakých	the same	same
rovnakým	the same	same
rovnica	equation
rovnice	equation
rovnomerne	uniformly	evenly
rovnováhe	balance
rovnováhy	balance	equilibrium
rovná	equal to	equal
rovné	straight
rovníc	equations
rovníka	equator
rovníku	equator
rovný	equal
royal	royal
rozbočovač	splitter	hub
rozdelenia	distribution	separation
rozdelenie	distribution
rozdelená	divided
rozdelené	divided
rozdelení	division
rozdelením	allocation	distribution
rozdelený	divided
rozdelila	divided
rozdeliť	divided
rozdeľuje	divides
rozdeľujú	divides
rozdiel	difference
rozdielne	different
rozdielom	difference
rozdielu	difference	the difference
rozdiely	differences
rozhodla	decided
rozhodli	down their	decided
rozhodlo	decided
rozhodne	decidedly	definitely
rozhodnutia	decisions
rozhodnutie	decision
rozhodnutí	decision
rozhodnúť	resolved	decide
rozhodol	decided
rozhodovať	certainly	decide
rozhoduje	decides
rozhovore	interview	discussion
rozhrania	interface
rozhranie	interface
rozhraní	interface
rozkaz	order
rozklad	decomposition
rozkladajú	decomposed
rozkladu	decomposition	decay
rozkladá	degrade
rozkvetu	flowering	bloom
rozličné	different	various
rozličných	different
rozlišovanie	distinction
rozlišuje	distinguishes
rozlišujeme	distinguish	we distinwuish
rozlišujú	distinguishes	a distinction
rozloha	area
rozlohou	area
rozlohu	area
rozlohy	dimension	area
rozloženie	distribution
rozlíšenie	resolution	differentiate
rozlíšením	resolution
rozlíšiť	distinguish
rozmach	expansion
rozmanitosť	diversity
rozmedzí	range	boundary
rozmer	dimension
rozmerov	dimensions
rozmery	dimensions
rozmnožovania	reproduction
rozoznávame	distinguish	recognize
rozpad	decay
rozpade	collapse	the break
rozpadla	split
rozpadu	break-up	decay
rozpore	conflict
rozpočet	budget
rozpočtu	budget
rozprestiera	stretches	spread
rozpráva	speaks	to talk
rozpätie	range
rozpúšťa	melting	dissolved
rozsah	range
rozsahu	range
rozsiahla	large	extensive
rozsiahle	extensive
rozsiahlu	extensive	vast
rozsiahly	extensive
roztok	solution
roztoku	solution
rozum	sense
rozumie	means
rozumu	reason
rozvinul	developed
rozvoj	development
rozvoja	development	advancement
rozvoji	development
rozvojom	development	with the development
rozvoju	development
rozvíjal	developed
rozvíjať	develop
rozširuje	extends
rozšírenia	extension
rozšírenie	extension	the extension
rozšírená	expansion
rozšírené	widespread
rozšírený	extended	expansion
rozšíril	extended
rozšírila	expanded
rozšírili	extended
rozšíriť	expand
ročne	per annum	annual
ročné	yearly	per annum
ročník	vintage	year
ročný	year-old	annual
roľníci	peasants
roľníkov	peasants	farmers
rss	rss
rubovej	reverse
ruch	tourism
ruchu	tourism
rudolf	rudolf
rudy	genera	ore
ruiny	ruins
ruje	oestrus
ruka	hand
ruke	hand
rukou	hands
ruku	hand
ruky	hand
rukách	the hands	hands
rumunska	romania
rumunsko	romania
rumunsku	romania
rus	russian
rusi	russians
ruska	russia
ruskej	russian
rusko	rusko	russia
ruskom	russian
rusku	russia
rusky	russian
ruská	russian	russia
ruské	russian
ruského	russian
ruský	russian
ruských	russian
ručne	by hand	manually
ružomberka	ruzomberok
ružomberku	ružomberok	ruzomberok
ružomberok	ružomberok
rysy	features
rytmus	rhythm	rhytm
ryža	rice
rád	series
rádio	radio
rádioaktívnych	radioactive
rádovo	in the order	on the order	order
rádu	series
rámci	frame
ráno	morning
rástla	grew	rasta
rásť	growth	grow	to grow
ráz	character	time
ráž	rye
rím	rim	rome
ríma	rome	roma
ríme	rime	rome
rímska	roman
rímske	roman
rímskeho	roman	the roman
rímskej	roman
rímski	roman
rímskokatolíckej	roman catholic
rímskokatolícky	roman catholic
rímskonemecký	roman-german
rímskou	roman
rímsky	rimsky	roman
rímskych	roman
ríša	empire
ríše	empire
ríši	empire	rishi
ríšou	empire
ríšu	empire	risu
róbert	robert
rómov	roms
rómovia	romovia	roms
rôzna	different	varied
rôzne	various
rôznej	different	various
rôzni	various
rôznu	different
rôznych	different	various
rôznym	different
rôznymi	different	take different
rúd	ore	metals
rúk	hands
rýb	fishes	fish
rýchle	fast	quickly
rýchleho	fast
rýchlejšie	faster
rýchlo	quickly
rýchlosti	rate
rýchlosť	velocity	speed
rýchlosťou	speed	at the speed
rýchly	fast
rýchlym	fast
rým	rym	rhyme
s	with
sa	the
sabbath	sabbath
sada	set
sadizmus	sedizmus	sadism
sama	herself
sami	sami	themselves
samica	female
samo	only	samo
samosprávy	self-government
samostatne	individually	independently
samostatnej	independent	separate
samostatnosti	independence
samostatná	independent
samostatné	independently
samostatný	a standalone	standalone
samostatných	separate
samotnej	itself	sole
samotnom	itself
samotná	itself	the place itself
samotné	alone	itself
samotného	alone	itself
samotný	/
samotných	themselves
samovraždu	suicide
samozrejme	of course	naturally
samuel	samuel
samé	alone	same
samého	its earliest
san	san
santa	santa
sarkofág	sarcophagus	sarcophahus
satan	satan
satana	satan
sativa	sativa
saturn	saturn
saturna	saturn
saturnu	saturn
savany	savannah
schizofrénia	schizophrenia
schizofrénie	schizophrenia
school	school
schopnosti	ability
schopností	ability
schopnosť	ability
schopnosťou	ability
schopná	able to	able
schopné	capable to	capable
schopní	able	able to
schopný	able to	able
schválenia	authorisations	approval
schválený	approved
schéma	shem
schémy	schemes	schematic
science	science
scientology	scientology
scientológia	scientologie	scientology
scientológie	scientology
scéna	scene
scéne	scene
scénu	scene
scény	scene
se	se
seba	yourself	each other
sebe	themselves
sebou	you
secesia	art nouveau	modern style
sedem	seven
sedemdesiatych	the seventies	seventies
sedmohradsko	transylvania
seizmické	seismic
seizmických	seismically	seismic
sekcia	section
sektor	sector
sekundu	second
sekundárne	secondary
sekvencia	sequence
sekvencie	sequence
sekúnd	seconds
sem	travels	here
semená	seeds
sen	dream
september	september
septembra	september
septembri	september
seraf	seraf	seraph	seraphim
seriál	series	serial
seriálu	serials
server	server
servera	server
serverov	servers
servery	servers
service	service
sestra	sister
sestry	sisters
set	set
sever	north
severe	north
severne	north
severnej	north
severnom	north
severná	north
severné	north
severného	north
severnú	north
severný	arctic	northern
severných	northern
severným	north
severovýchode	northeast
severozápade	northwestern	northwest
severozápadnej	northwestern	northwest
severu	north
sex	sex
sexuálna	sexual
sexuálne	sexually
sezóna	season
sezóne	season
sezónu	season
sezóny	season
sfarbenie	colouring	coloration
sfére	sphere	area
sféry	sphere	fields
shakespeare	shakespeare
show	show
si	a
siaha	reaches
siahajú	go back	reach
sibír	sibir
sibíri	siberia
side	side
siedmich	seven
siete	network
sieti	network
sietí	networks	network
sieť	network
sieťach	different networks	network
sieťou	network
sieťovej	ac	network
sieťová	other network	network
signál	signal
signálov	signals
signálu	signal
signály	signals	signal
sila	power
silami	forces
sile	force	power
silne	strongly
silnej	strong
silnejšie	more powerful	stronger
silno	strongly
silná	strong	full
silné	strongly	strong
silnú	strong
silný	strong
silných	powerful	of strong
silným	strong	potent
silnými	strong
silou	force	by force
silu	power
sily	power
silám	forces
sin	sin	son
singel	single
single	single
singlom	single	single,
sio	sio
sir	sir
situácia	situation
situácie	situations
situácii	situations
situáciu	situation
situácií	situacion	situation
sk	sk
ska	ska
skala	rock
skalné	rocky	rock
skaly	rocks
skandium	scandium	skandium
skener	scanner
skenera	scanner
skenery	scanners
skinheads	skinheads
skla	glass
skladajú	consists	consist
skladatelia	composers
skladateľ	composer
skladateľa	componist	composer
skladateľov	composers
skladba	composition	song
skladbe	song
skladbu	composition	song
skladby	track	tracks
skladieb	songs
skladá	consists	consist
sklo	glass
sklon	slope
sklonku	end	the close
sklony	inclinations
skomponoval	composed
skončení	completion	end
skončil	ended	finished
skončila	ended
skončili	ended
skončilo	ended	finished
skoro	almost
skoré	early	score
skr	skr.
skratka	abbreviation
skratkou	abbreviation
skratky	abbreviations
skript	scipt	script
skrátene	short
skupina	group
skupinami	groups
skupine	group
skupinou	group
skupinu	group
skupiny	groups
skupinách	groups
skupinám	group	groups
skupín	groups
skutočne	indeed
skutočnosti	indeed	fact
skutočnosť	fact
skutočnosťou	fact
skutočná	real
skutočné	indeed	really
skutočný	real
skype	skype
skôr	rather
skúma	interrogates
skúmania	reconnaissance	research
skúmanie	exploration
skúmať	to explore	investigate
skúsenosti	experiences
skúsenosť	experiences	experience
slabo	weakly
slabá	weak
slabé	weak
sledoval	followed
sledovanie	monitoring	watching
sledovať	to follow	watch
slepánikovité	slepanikovites	typhlopidae	slepanicovy	leptotyphlopidae	slepanic	slepanikovi	slepanikovite
slepáňovité	slepanovi	slepanovies	rhinotyphlops	slepanovy	leptotyphlopidae	slepanoves
sliezsko	silesian
slnečnej	solar
slnečná	solar
slnečné	sunny	solar
slnečného	sunny	solar
slnečný	solar
slnečných	sun
slnka	sun
slnko	sun
slnkom	sun	sink
slnku	sun
sloboda	freedom
slobodne	free
slobodná	maiden	free
slobodné	free
slobodného	free
slobodný	free
slobodných	of free	free
slobodu	freedom
slobody	freedom	liberty
slohu	style
slov	word	words
slova	words
slovakia	slovakia
slovami	words
slovania	slavs
slovanov	slavs	slaves
slovanskej	slavic
slovanské	slavic	slovakia
slovanského	slovak
slovanských	slavic
slovenska	slovakia
slovenskej	slovak
slovensko	slovakia
slovenskom	slovak
slovenskou	slovak
slovensku	slovakia
slovensky	slovak
slovenská	slovakia	slovak
slovenské	slovakia	slovak
slovenského	slovak
slovenskí	slovenian	slovenski
slovenskú	slovakia	slovak
slovenský	slovak
slovenských	slovak
slovenským	slovak
slovenskými	slovak
slovenčina	slovencina	slovak
slovenčine	slovak
slovenčiny	slovak	slovak language
slovinsko	slovak
slovník	dictionary
slovo	word
slovom	word
slová	words
slováci	slovaks
slovák	slovák	slovakia
slovákov	slovaks
služba	service
službe	services	service
službu	service
služby	services	servicese
službách	services
služieb	services
slávi	praises	celebrate
slávne	famous
slávnosti	celebrations
slávnostne	solemnly
slávy	fame
slúži	serves
slúžia	they serve	serves
slúžil	served
slúžili	served
slúžiť	serve
sme	are
smer	direction
smere	direction
smeroch	directions	ways
smerom	direction	towards
smerov	directions
smeru	direction
smeruje	directed	heads
smery	directions
smetana	smetana
smrti	death
smrť	death
smrťou	death	death of
sms	sms
smútok	sadness
snaha	effort
snahe	to
snahu	efforts	effort
snahy	efforts
snažia	trying to
snažil	tried
snažila	tried to	tried
snažili	tried to	tried
snaží	trying to
snehu	snow
snemu	congress	diet
snp	slovak national uprising
snr	snr
sns	cis	sns
snáď	perhaps
snímka	picture	tape
snímky	images	images of
so	with
sobota	saturday
sobáš	marriage	sobas
socha	statue
sochou	statue
sochu	statue	sculptures
sochy	sculptures
sochár	sculptor
sochára	sculptor
sochári	sculptors
sochárske	sculpture	sculpturally
sochárstve	sculpture
sochárstvo	sculpture
socialistická	socialist
socialistických	socialist
socializmu	socialism
sociálna	social
sociálne	social
sociálneho	social
sociálnej	social
sociálnu	social
sociálny	social
sociálnych	social
sodného	sodium
sodný	sodium
sodík	sodium
sodíka	sodium
sofia	sofia
softvér	software
softvéru	software
software	software
sokrates	socrates	socrat
solanum	solanum
soli	salt
solí	salt
som	i	am
someliér	similer	wine waiter	sommelier
sond	probes
sonda	probe
sondy	probe
sony	sony
sopečnej	volcanic
sopečná	vulcanic	volcanic
sopiek	volcanoes
sopka	volcano
sopky	volcano	vulcanos
sovieti	soviets	the soviets
sovietska	soviet
sovietske	soviet
sovietskeho	soviet
sovietskej	soviet
sovietski	soviet
sovietskom	soviet
sovietsky	soviet
sovietskych	soviet
sovietskym	soviet
soľ	salt
spadá	falls
spam	spam
spaľovacích	combustion
spaľovaním	combustion
spektra	spectrum
spektrum	spectrum
spev	song
spevák	singer
speváka	singer
spevákov	singers
speváčka	singer
spieva	sings
spisov	files
spisovatelia	writers
spisovateľ	writer
spisovateľov	writers
spisy	writings
spišskej	spis	spisska
spišská	spish	spisska
spišský	spish	spissky
splniť	satisfy	met
spod	from under	under
spodnej	lower	low
spodná	lower
spojencami	allies
spojenci	allies
spojencom	ally
spojencov	allies
spojenectvo	alliance
spojenia	connection	fusion
spojenie	connection
spojenom	united
spojená	associated	connected
spojené	united	mainly
spojeného	associated
spojení	connection
spojením	connection	by combining
spojený	connected
spojených	united
spojenými	united	related
spojil	combined
spojili	combined	merged
spojiť	link
spolková	federal
spolku	association
spolok	association
spoločenská	community	societal
spoločenské	community	social
spoločenského	social
spoločenský	socially	social
spoločenských	societal	social
spoločenstva	community
spoločenstvo	community
spoločne	together
spoločnej	common
spoločnosti	society
spoločností	company	societies
spoločnosť	society
spoločnosťou	company	by
spoločné	together
spoločného	joint	common
spoločnú	common
spoločný	common
spoločných	common
spoločným	common
spolu	together
spoluhlásky	consonants
spolupracoval	collaborated	cooperate
spolupracovať	cooperate
spolupráca	cooperation
spolupráce	co-operation	cooperation
spolupráci	cooperation
spoluprácu	collaboration	cooperating
spomedzi	among
spomenuté	listed	the listed
spomenúť	mentioned	of the mentioned
spomína	mentioned
spomínaných	mentioned
spontánne	spontaneously
spor	dispute
sporné	questionable
sporov	disputes	dispute
sport	sport
spory	disputes
spotreba	consumption
spotrebu	consumption
spotreby	consumption
spoznal	know	got to know
spočiatku	first
spočíva	lie	is
spracovania	processing
spracovanie	processing
spravidla	generally
sprevádzané	accompanied	accompanied by such
správ	movements were recorded	reports
správa	right	from the right
správania	acting	behavior
správanie	behavior
správcu	keeper	manager
správe	report
správna	proper	the proper
správne	correct
správnej	correct
správny	administrative
správou	control	management
správu	management
správy	news
spája	connects
spájajú	associated
späť	back
spôsob	method	way
spôsobe	how	causes
spôsobená	caused
spôsobené	caused
spôsobený	caused	caused by
spôsobil	causes receiving	causes
spôsobila	caused
spôsobili	caused
spôsobilo	to possible	generate
spôsobiť	cause	to cause
spôsobmi	ways
spôsobom	method	way
spôsobov	ways
spôsobu	how	way
spôsobuje	causing	causing a
spôsobujú	cause
spôsoby	ways	approaches
spôsobí	causes
spĺňa	meet	fulfills
sql	sql
square	square
sr	sr
srbi	serbians	serbs
srbska	serbia
srbsko	serbia
srbsku	serbia
srdca	heart
srdce	heart
srsti	coat
srsť	coat
ss	ss
ssr	ssr
st	st
stabilitu	stability
stabilné	stable
stadium	stage
stal	was	has become
stala	become
stali	become	stood
stalin	stalin
stalina	stalin
stalingrad	stalingrad
stalingradu	stalingrad
stalo	become	became
standard	standard
stane	become
stanica	station
stanice	station	temples
stanici	station
stanislav	stanislav
stanley	stanley
stanovené	on the designated	given	designated
stanovuje	specifies	sets
staníc	stations
stanú	become	tent
star	star
starej	old
starom	old
starosti	troubles	worry
starostlivosti	care
starostlivosť	solicitude
starovek	ancient	ancient history	medieval	antiquity
starovekej	ancient
starovekom	ancient
staroveku	antiquity
staroveké	ancient
starovekého	ancient
staroveký	antiquity
starovekých	ancient
stará	old
staré	old
starého	old
starí	old	age of the
starý	old
starých	old
staršia	older
staršie	older
staršieho	older
starší	elderly	older
starších	older
state	state
stav	status	state
stavali	built	bet
stavač	shorthaired	pointer
stavať	build
stavba	construction
stavbe	construction
stavbou	building	construction
stavbu	construction
stavby	construction	constructions
stave	state	statae
stavebné	structurally
stavebný	building	construction	structural
stavebných	construction
stavia	to build	builds
stavieb	buildings
stavom	state
stavov	conditions
stavovcov	vertebrates	vertebrate
stavu	state
stavy	states
stačí	enough
stať	become
ste	you	you are
steel	steel
stene	wall
stenu	wall
steny	walls
stepi	steppe
steve	steve
stiahli	download	withdraw
stiahnuť	download
stigmatizácia	stigmatism	stigma	stigmatization
sto	hundred
stoja	stand
stojí	standing
stolice	stool
stone	stone
stopy	track	tracks	traces
storočia	century
storočiach	centuries
storočie	a century	century
storočí	century
stovky	hundred	hundreds
strach	fear
strachu	fear
strana	page
stranami	parties
strane	the	side
stranou	aside
stranu	page	side
strany	by
stranách	sides
strata	loss
strate	loss	lose
strategické	strategic
strategického	a strategic	strategic
stratil	lost
stratila	lost
stratili	lost
stratilo	lost
stratou	loss
stratu	loss
straty	loss
stratégia	strategy
stratégie	stategie	strategy
stratégiu	strategy
stred	center
streda	streda, it is the name of city in this context, if it is no the name of city then it is wednesday	wednesday
strede	wednesday
stredisko	customer care centre	center
strediskom	center
stredne	medium	moderately
strednej	central
strednom	middle	central
stredná	middle	central
stredné	middle	medium
stredného	central
strednú	middle	high school
stredný	central
stredných	medium size	secondary
stredom	through the middle	center	centre
stredomoria	mediterranean
stredovek	middle ages
stredovekej	medieval	middle ages
stredoveku	medieval
stredoveké	medieval
stredovekého	the medieval
stredovekých	medieval
stredozemného	mediterranean
stredu	wednesday
street	street
strelec	shooter
strely	missiles
stres	stress
stretli	meet
stretnutia	meeting
stretnutie	meeting
stretnutí	a meeting	meeting
stretnúť	meeting	encounter
stretol	met
stretávame	meet
strieborné	silver
striebro	silver
striedavo	alternately
striedavého	ac
striedavý	changing	alternately
stroj	machine
stroja	machine
stroje	machinery	machines
strojov	machines
strom	tree
stromov	trees
stromu	tree
stromy	trees
struny	strings
stráca	obscure
strán	sides	parties
stránka	page
stránkach	website
stránke	page
stránku	page
stránky	website
stránok	web	pages
strát	strata
strávil	spent
strún	strings
studenej	cold
studená	cold
stupeň	degree
stupne	degrees
stupni	degree
stupňa	grade	degree of	stupna
stupňom	degree
stupňov	degrees
styk	contact
styku	connections	contact	intercourse
styky	relations
stál	was
stála	become
stále	still
stáli	become
stály	become
stáročia	for centuries	centuries
stáva	happen	the constitution
stávajú	become	becomes
stáť	stat	stand
stúpa	rises
stĺp	column	pillar
su	are
subjekt	subject
subjektu	entity
suchá	dry
suché	search
suchý	dry
sudcov	judge	judges
suky	females	bitch
sumatra	sumatra
sun	sun
suroviny	raw materials
surovín	raw materials	materials
surrealizmus	surrealism
susedných	neighboring	adjacent
susedí	neighbors
sv	st.	ne
svadba	wedding
svahoch	slopes
svalov	muscle
svedkovia	witnesses
svedčia	show
svedčí	testifies	testify
svet	world
sveta	world
svetadiel	continent
svete	world
svetelných	light
svetla	light
svetlo	light
svetlom	light
svetom	world
svetovej	world
svetovou	world
svetová	world
svetové	world
svetového	world
svetovú	world	presence
svetový	world
svetových	world's
svetu	world
sviatkom	feast
sviatku	holiday	feast
sviatky	holydays	holidays
sviatok	holiday	feast
svoj	their
svoje	their	its
svojej	its
svojho	his	collection
svojich	their
svojim	his	its
svojimi	their
svojmu	his
svojom	its
svojou	its
svoju	own	its
svojím	his	its
svätej	saint
svätopluk	svatopluk
svätopluka	svatopluk
svätá	holy
svätého	holy
svätý	sacred
svätých	saints
swot	swot
sydney	sydney
symbol	symbol
symbolizuje	symbolizes
symbolom	symbol
symboly	symbols
symfýza	symphysis
symptómy	symptoms
syn	son
syna	son
synagóga	synagogue
synagógy	synagogues
syndróm	syndrome
synom	son
synonymá	synonyms
synov	sons
synovi	son
syntézu	synthesis
system	system
systematika	systematics	systematika
systém	system
systémami	systems
systéme	systems	system
systémoch	systems
systémom	system
systémov	systems
systému	system
systémy	systems	system
sám	alone
séria	serie	series
série	series
sérii	series	serie
sériové	serial
sériový	serial
sériu	series
síce	indeed	although the	although
sídla	settlements
sídli	housed
sídlisko	housing estate	commuterville
sídliská	sidliska	suburb of bratislava
sídlo	headquartered
sídlom	resided	seat of
síl	forces
sínus	sine
síra	sir
sírovej	sulphurus	sulfuric
sírová	sulfuric
síry	sulfur
sôch	sculptures
sú	are
súbežne	concurrently
súbor	file
súborom	file
súborov	files
súboru	file
súbory	files	ensembles
súd	barrel	court
súdnictvo	jurisdiction
súdny	forensic	judicature
súdom	trail	kegs
súdov	barrels
súdu	barrel
súdy	barrels
súhlas	consent	agreement
súhlasil	agreed
súhlasu	consent	consent of the
súhrn	summery	summary
súhvezdia	constellation
súhvezdí	constellation
súkromná	privately owned	private
súkromné	privately
súkromných	private
súlade	in harmony	line
súmrak	sumrak	twilight	dusk
súostrovie	archipelago
súper	super
súpera	opponent
súperom	opponent
súperov	opponent	opponents
súperovi	opponent
súpiska	supiska	inventory
súradnice	coordinates
súradníc	coordinates
sústava	system
sústave	system
sústavou	system
sústavu	system
sústavy	system
sústavách	systems
sústredil	concentrated	he concentrated
sústrediť	concentrate	focus
sústreďuje	focus
sútokom	confluence
sútoku	confluence	junction
súvisia	related
súvisiace	related
súvisiacich	related
súvislosti	regarding	connection
súvislosť	relationship
súvisí	related
súčasne	at the same time	at a time
súčasnej	current
súčasnom	current	contemporary
súčasnosti	nowadays	present
súčasnosť	present times	present
súčasná	current	present-day
súčasné	at the same time	existing
súčasného	contemporary
súčasnú	at the same time	at a time
súčasný	current	nowadays
súčasných	current
súčasným	current	todays
súčasti	components
súčasť	suceso	component
súčasťou	a part
súčet	sum
súčiastky	parts are	parts
súčtu	the sum
súťaž	contest
súťaže	competitions	competition
súťažiaci	competitor
sčasti	in part	partly
sčítania	census
sľúbil	promised
sťahovať	download	move
t	t
ta	ta
tabak	tobacco
tabule	board
tabuľa	board
tabuľka	table
tabuľke	table
tabuľky	table
tajne	secretly
tajomníka	treasurer	secretaries
tajovského	tajovského	tahovskeho
tak	so
takej	a	such
takejto	such
takisto	also
takmer	nearly
takom	this
takomto	this	such
taktiež	also
takto	so
takzvané	so-called
takzvaný	so-called	called
taká	such
takáto	takato	such
také	also	such
takého	such	like that
takéhoto	such
takéto	such
takú	shalom	such
takúto	such	takuto
taký	also
takých	such
takýchto	lans
takýmto	this
takýto	these	this
takže	so
talent	talent
taliani	italians
talianska	tallinn	italy (country), italian	italian
talianske	italian
talianskeho	italian
talianskej	italian
taliansko	italy	italian
talianskom	italian
taliansku	italian
taliansky	italian
taliban	taliban
tam	there
tance	dance	dances
tanec	dance
tank	tank
tankom	tank
tankov	tanks
tankové	tank
tankového	tank
tankových	tank
tanku	tank
tanky	tanks
tatra	tatra
tatranská	tatranska
tatranský	tatransky	tatra
tatry	tatras
tatrách	tatras
taveniny	melt
tcp	tcp
te	te
technickej	technical
technicky	technically
technická	technical
technické	technical
technických	technical
technika	technology
technike	technology
techniku	tehnics	technology	technology, technique (the last sentence)
techniky	techiques	techniques
technológia	technology of	technology	technological
technológie	technologies	technology
technológiu	technology
technológií	technology
techník	technician	techniques
teda	therefore
tehotenstva	pregnancy	pregnanncy
tej	taj	that
tejto	this
tekutín	fluid
tela	body
tele	calf
telefón	phone
telefóny	phones	telephones
telesa	body
telesnej	physical
telesná	physical
telesné	physically	physical
teleso	body	solid
telesom	body
telesá	body
televízia	television
televízie	tv	television
televízne	tv	television
telies	bodies
tell	tell
telo	body
tempom	rate	tempo
ten	the
tendenciu	tend to	tendency
tenis	tennis
tenisové	tennis
tenká	thin
tento	this
tentokrát	at times	this time
tenzor	tensor
tenzora	tensor
teológie	theology
teoreticky	theory	theoretically
teoretická	theoretical
tepelne	heat
tepelnej	thermal
tepelná	thermal	heat
tepelné	heat	thermic
tepla	heat
teplo	heat
teplom	heat
teplota	temperature
teplotami	temperatures
teplote	temperature
teplotou	temperature
teplotu	temperature
teploty	temperature
teplotách	temperatures
teplé	warm
teplôt	temperature	temperatures
terapia	therapy	theraphy
teratogén	teratogene	teratogen	tetrogen
teraz	terez	terrase
teriér	terrier
termálne	thermal
termín	the term	term
termínom	term
teror	terror
teroristické	terrorist
teroristických	terrorist
teroristov	terrorist
terorizmu	terrorism	terorism
terorizmus	terrorism
teroru	terror
terra	terra
terrier	terrier
teréne	field	terrain
terénu	terrain
terézia	theresa
terézie	theresa
terčom	target
tesla	tesla
tesne	just
test	test
testy	tests
tetovania	tattoos
tetovanie	tattoo
texas	texas
text	text
textil	textiles
textilný	textile
textoch	texts
textov	texts
textu	text
texty	texts
teória	theory
teórie	theory
teórii	theory
teóriou	theory
teóriu	theory
teórií	theory
tečie	flows
that	that
thc	thc
thdr	thdr.	thdr,
the	the
theorie	theory
thomas	thomas
tiahne	stretches
tichého	pacific (ocean)	silent
tichý	quiet
tie	these	the
tieto	these
tieňa	shadow
tiež	also
tiger	tiger
tigre	tigers	tigre
time	time
times	times
tiso	tiso
tisíc	thousand
tisíce	thousands
titul	title
titulnú	title
tituly	titles	title
tj	ie
tkaniva	tissue
tkanivo	tissue	texture
tkanivá	tissue
tkanív	tissue
tlak	pressure
tlakom	pressure
tlaková	pressure	compression
tlaku	pressure
tlač	print	printing
tlače	print
tlačiareň	printer
tlačiarne	printer
tlačiarní	printer
tlačiť	push
tmavé	dark
to	it
toho	the	it
tohoto	this
tohto	this
tok	flow
tokio	tokyo
toku	flow of (first and third sentence), train of (second sentence)	flow
toky	flows
tom	the
tommy	tommy
tomto	this
tomu	this	it
tomáš	tomas	tomash
tomáša	thomas	tomash
ton	tons	ton
top	top
topenia	melting
topológia	topology
totalita	totality
totiž	namely
toto	this
tour	tour
touto	this
tovar	product	goods
tovaru	product	goods
továreň	factories	factory
tower	tower
town	town
toľko	so much	much
tr	tr
tradične	traditionally
tradičnej	traditional
tradičná	traditional
tradičné	traditionally
tradičného	traditional
tradičný	traditional
tradičných	traditional
tradícia	tradition
tradície	tradition
tradícii	tradition
tradíciou	tradition
tradíciu	tradition
tradícií	tradition
tragédia	tragedy
traja	three
transfer	transfer
transformácia	transformation
transformácie	transformation
transformátor	transformer
transport	transport
transportér	transporter	personnel carrier
tranzistorov	transistors	transistor
tranzistory	transistors
tranzverzálna	tranzverzalna
trasa	route
trase	route	punishment
trate	track
trať	track
treba	be	should
trenčiansky	iowa	westmeath
trenčín	trencin
trenčíne	trencin
tresku	bang
trest	penalty	punishment
trestné	criminal	punishable
trestný	criminal
trestu	penalty
tretej	third
tretia	third
tretie	third
tretieho	third
tretina	third
tretiny	third
tretí	third
tretím	third	the third
treťom	third
treťou	third
trh	market
trhu	market
trhy	markets
tri	three
trieda	class
triedy	class
trikrát	three times
trnava	trnava
trnave	trnava
trnavský	punjab
troch	three
trochu	bit	some
trojice	trinity
trojuholník	triangle
trojuholníka	triangle
trojuholníku	triangle
troma	three
tromi	three
tropické	tropical
trpel	suffered	suffered from
trup	body	trunk (first and fourth word), fuselage (second word), hull (third word)	trunk
trupu	hull	trunk
trval	took
trvala	lasted
trvalo	took
trvalé	permanently
trvalý	travel	lasted
trvania	duration
trvanie	duration
trvať	last
trvá	take	lasts
tréner	coach
trénera	coach
trón	throne
trónu	throne	tron
tuhé	solid
tukov	lipides	fat
tuku	fat
tuky	fats
tunel	tunnel
turci	turks
turecka	turkey
tureckej	turkish
turecko	turkey
turecku	turkey
turecká	turkey	turkish
tureckého	turkish
turistov	tourists
turkami	turks
turkov	turks
turné	tourpokrok	tour
tv	you
tvar	shape	face
tvare	form
tvarom	shape
tvarov	shapes
tvaru	shape	face
tvary	shapes
tvoj	your
tvorba	creation
tvorbe	making	creation	formation
tvorbou	creation	formation
tvorbu	production	formation
tvorby	of
tvorcovia	makers
tvorená	formed
tvorené	formed by
tvorený	formed
tvoria	are	form	trova
tvoriace	forming
tvorila	formed	created
tvorili	made	were
tvorilo	made	consisted
tvorivej	creative
tvorivosti	creativity
tvorivosť	creativity
tvorivého	creative
tvoriť	form the
tvorí	forms	form
tvrdenia	claims	argument
tvrdenie	claim
tvrdia	claim	say
tvrdil	claimed
tvrdili	claimed
tvrdosť	hardness
tvrdé	hard
tvrdí	states	says
tvrdý	hard	tough
tvár	shape	face
tváre	form
tvárou	shape	face
ty	you
tych	-ties	ties
typ	type
typicky	typically
typická	typical
typické	typical
typický	typically
typickým	typical
typickými	typical
typom	type
typov	types
typu	type
typy	types
tzn	ie
tzv	ie	socalled
t j	that is	i.e.
tá	the	ta
tábor	camp	tabor
tábora	camp
tábore	camp
táboroch	camps
táborov	camps
tábory	camps
táto	this
téma	topic
témou	topic	theme
tému	topic
témy	temy
tí	these	you
tím	team
tímu	team
tímy	teams
títo	these	tito
tón	tone	t
tónov	tones
tónu	tonne
tóny	tony
tú	tu	it
túto	this
tých	ties
týchto	these
týka	relates
týkajú	touch upon	relate
týkajúce	cases	related	contemporaneous
tým	team
tými	those
týmito	by these
týmto	these	this
týždeň	week
týždne	weeks
týždňa	week
týždňoch	weeks
týždňov	weeks
u	at	in
ucho	ear
uctievanie	worshipping	worship
udalosti	events
udalostí	events
udalosť	event
udelil	ubele
udeľuje	grants
udp	udp
udržanie	maintaining	retention
udržať	hold	maintain
udržiava	maintains
udržuje	maintains
udáva	specifies the	specified
uefa	uefa
uhla	angle
uhlia	coal
uhlie	coal
uhličitan	carbonate
uhličitého	dioxide
uhličitý	carbonic	dioxide
uhlom	angle	degree
uhlov	angles
uhlu	angle
uhly	angles
uhlík	carbon
uhlíka	carbon
uhlíkové	carbon
uhol	angle
uhorska	uhorska	austria-hungary
uhorskej	ugrian	hungaro
uhorsko	hungary	hungaro
uhorsku	hungary	uhorsko
uhorského	uhorskeho	ugrian
uhorský	ugrian
uhľovodíkov	hydrocarbons
uhľovodíky	hydrocarbons
uk	university	uk
ukazuje	shows
ukazujú	show	they show	shows
ukladanie	store
ukončenie	termination
ukončená	completed
ukončení	ended	termination
ukončil	ended	completed
ukončiť	exit	stop
ukrajina	ukraine	ukraina
ukrajinci	ukrainians
ukrajine	ukraine
ukrajinská	ukrainian
ukrajiny	ukraine	ukraina
ukázal	showed
ukázala	showed
ukázali	showed an
ukázalo	shown	it turned
ukázať	to show
ul	st.	street
ulica	street
ulice	street
ulici	streets	street
uliciach	streets
uloženie	save	storage
uložená	saved
uložené	saved
ulrich	ulrich
ulíc	street	streets
umelci	artists
umelcov	artists
umeleckej	art	greatest artistic
umelecká	artistical
umelecké	artistic
umeleckého	artistic	artistik
umelecký	artistic	artistically
umeleckých	artistic
umelo	artificially
umelé	artificial
umenia	arts
umenie	art
umeniu	art
umení	arts
umením	wheel of art	art
umiestnenie	location
umiestnená	location
umiestnené	placed
umiestnený	located
umiestnil	placed
umožnil	allowed
umožnila	allowed
umožnili	allow	allowed
umožnilo	allowed
umožní	allows	allow
umožňuje	proliferate	allows
umožňujú	allows
umrel	died
und	und
unesco	unesco
uniknúť	leak	escape
unikátne	unique
united	united
university	university
univerzita	university
univerzite	university
univerzity	university
univerzálne	universal
univerzít	universities
unix	unix
up	up
uplatnenie	application	use
uplatňuje	employs the	employs
uplatňujú	employs the	employs
upozorňujú	attention
upravené	neatly
upravený	adjusted	well-ordered
upravuje	regulates	adjusts
uprostred	midst	in the middle of, middle	in the middle
ur	ur
urobil	did
urobila	did
urobili	did
urobiť	do	make
ursus	ursus	ursus, bear
urán	uranium	uranus
uránu	uranium
určenie	designation
určená	determined
určené	intended	the key applications targeted
určený	determined
určených	are going	for
určil	deduce	determine
určite	certainly
určitej	a	some
určitom	certain	some
určité	specific	certainly	particular
určitého	defined
určitú	some	cartain
určitý	certain	some	a certain
určitých	some
určitým	certain	some
určiť	determine
určuje	determines
určujú	determines	determine
us	us
usa	usa
usb	usb
usiloval	sought	strove
uskutočnil	carried out	conducted	place
uskutočnila	took place
uskutočnili	were contucted	were conducted
uskutočnilo	place	happened
uskutočniť	to accomplish	realize
uskutočňuje	place
usporiadanie	organization
usporiadané	orderly
usporiadaných	sorted	arranged
uss	uss
utc	utc
utc+	utc+
utiekol	fled
utrpeli	suffered
utrpenie	suffering	misery
utvorili	formed
uvažuje	considered
uvedená	given
uvedené	given	stated	the given
uvedený	given
uvedených	mentioned	the mentioned
uvedomil	realized
uvedomiť	realize
uviedli	said
uviedol	said	introduced
uviesť	mention	held
uvoľnenie	release
uvoľňuje	release	liberates
uvoľňujú	liberates
uvádza	states	report said
uvádzajú	are presented	show
uzavrel	closed
uznanie	recognition
uznané	recognized
uznať	recognize	accept
uznáva	recognizes
uzol	node	hub
učenia	they shall make	learning
učenie	learning
učil	taught
učilište	school
učitelia	teachers
učiteľ	teacher
učiteľov	teachers
učí	teach
už	already	yet	no
užitočné	useful	usefully
užívania	use
užívateľ	user
užívateľov	users
užšom	narrow
v	in
va	va
vajíčka	eggs
valca	cylinder
valec	cylinder
valley	valley
van	van
vancouver	vancouver
vaporizér	vaporiser	vaporizer
variant	variant
varianty	variants
vatikán	vatican
vatikánu	vatican
vec	thing
veci	things
veciach	matters
vecí	things
veda	leads	science
vedci	scientists	scientiists
vedcov	scientists
vedeckej	scientific
vedecká	scientific
vedecké	scientific
vedeckého	scientific
vedecký	scientifically
vedeckých	scientific
vedel	knew
vedeli	know
vedenia	management
vedenie	management
vedená	conducted
vedení	led
vedením	leadership
vedie	leads
vedieť	know
vedomia	consciousness
vedomie	consciousness
vedomosti	knowledge
vedomý	conscious	aware
vedou	lead
vedu	science
vedy	science
vedú	science
vedúca	head
vedúce	leading
vedúci	head
vedľa	led
vek	age
vektor	vector
vektora	vector
veku	age
velenie	command
velením	command of	command
velil	commanded	commanding
velitelia	commanders
veliteľ	commander
veliteľa	commander
veliteľom	commander
veliteľov	commanders	commander
veliteľstvo	headquarters
veličina	variable	value
veličiny	variables
venovala	given
venovať	devote
venuje	deals
venuša	venus
venuše	venus	venuse
venuši	venus	venuse
verejne	publicly
verejnej	public
verejnosti	public
verejnosť	public
verejná	verejna
verejné	public	publicly	publicy
verejného	public
verejných	of public
veria	to believe	believe
veriaci	believer
veriacich	believers
veril	believed
verili	believed
versailles	versailles
vertikálne	vertical
verzia	version
verzie	versions
verzii	version
verziu	version
verziách	version	versions
verzií	versions
verí	believe
ves	ves	village
vesmír	universe	space
vesmíre	universe
vesmíru	universe
veta	sentence
vetra	wind
vetry	winds
vetvy	branch
vety	sentences	sentence
večer	evening
večera	dinner
veľa	many	a lot of
veľkej	large	great
veľkom	great	welcome
veľkonočné	easter
veľkosti	size
veľkostí	sizes	size
veľkosť	size
veľkosťou	size
veľkou	great
veľká	big	great
veľké	large
veľkého	big	velkeho	huge
veľkému	a magnificent	magnificent
veľkú	large	you large
veľký	great
veľkých	large
veľkým	huge	big
veľkými	large
veľmi	very
veľmoci	superpowers	great powers
veža	tower
veže	towers	tower
veži	tower
vežu	tower
vhodnou	appropriate
vhodná	appropriate	suitable
vhodné	properly
vhodný	suitable
vhodným	suitable
vi	vi
viac	more
viacero	several
viaceré	several	multiple
viacerí	several
viacerých	multiple	more
viacerými	several	more
viackrát	only once	several times	once
viacmenej	or less	more less
vianoce	christmas
viazané	bound
viazaný	bound
viaže	binds
videl	see	saw
videli	see	saw
video	video
videoklip	video clip
vidieku	countryside	rural
vidieť	to see
viditeľná	visible
viditeľné	visible
viditeľný	visible
vidno	seen	visible
vidí	sees
vidíme	we see
vie	knows	can
vied	sciences
viedenskej	vienna
viedenskom	viennese	vienna
viedenská	vienna
viedeň	vienna
viedla	led
viedli	led	lead
viedlo	lead
viedne	vienna
viedni	vienna
viedol	led
vieme	know
viera	faith	belief
vierou	faith
vieru	faith	belief
viery	faith
viesť	lead
vietnam	vietnam
vietname	vietnam
vietnamu	vietnam
vietor	wind
vii	vii
viktor	viktor
viliam	william
vinci	vinci
vinu	blame
vista	vista
vitamín	vitamin
vladimir	vladimir
vladimír	vladimir
vladislav	vladislav
vlajka	flag
vlajky	flag
vlasti	home	country
vlastne	actually
vlastnej	own
vlastnom	own
vlastnosti	properties
vlastností	properties
vlastnosť	property
vlastnosťami	properties
vlastnosťou	feature	properties
vlastnou	own
vlastné	own	actually
vlastní	own	possess
vlastníctva	property	ownership
vlastníctvo	ownership
vlastnú	own
vlastný	own	my own
vlastných	of own
vlastným	own	their own
vlasy	hair
vlhkosti	moisture
vlhkosť	humidity
vlieva	flows
vlk	wolf
vlka	wolf
vlna	guilt	wave
vlnovej	wavelenght	wave
vlnu	wave
vlny	waves
vlád	council
vláda	government
vládca	ruler
vládcom	ruler
vládcov	rulers
vládcovia	rulers
vláde	government
vládla	government
vládli	government	ruled
vládne	ruled by	ruled
vládol	reigned	ruled
vládou	government
vládu	government
vlády	government
vlákien	fibres	made fiber
vlákna	threads	fibers
vlákno	fiber
vníma	percieves	perceive
vnímania	perception
vnímanie	perception of	perception
vnútornej	internal	inner
vnútorná	inner
vnútorné	are inter	inner
vnútorného	of the internal	internal
vnútornú	internal	are inter
vnútorný	internal
vnútorných	internal
vnútorným	by internal	internal
vnútra	interior
vnútri	inside
vnútro	inside
vnútrozemí	inland
vo	at	in
voda	water
vodca	leader
vodcom	leader
vodcov	leaders
vodcu	leader
vode	water
vodivosť	conductivity
vodič	driver
vodiča	driver's	driver
vodičov	drivers
vodnej	water
vodná	water	vodna
vodné	water	ewage	by day
vodného	water
vodný	water	aqueous
vodných	aqueous
vodopády	waterfalls
vodou	water	by water
vodstvo	waters
vodu	water
vody	water
vodík	hydrogen
vodíka	hydrogen
vojaci	military
vojakmi	soldiers
vojakom	soldiers	soldier
vojakov	soldiers	vojakov
vojen	wars
vojenskej	military
vojenská	military
vojenské	military
vojenského	military
vojenskú	military
vojenský	militarily
vojenských	military
vojna	war
vojne	war
vojnou	war
vojnové	war
vojnového	war
vojnových	war
vojnu	war
vojny	war	wars
vojnách	wars
vojsk	troops	armed forces
vojska	troops	army
vojskami	troops
vojsko	army
vojská	troops
vojskám	armies	troops
vojtech	vojtech
vojvodu	duke
volebnom	election
volebné	election
volebného	election
volebný	electoral
volení	elected	voted	nominated
volený	chosen
volieb	voting	elections
volá	calls	ox
volí	optional	elects
von	von
vonkajšej	the outer	outer
vonkajšia	external
vonkajšie	its external
vonkajšieho	external dimension	external
vonkajší	external
vonkajších	outer	external
vonkajším	external
vopred	in advance
voyager	voyager
vozidiel	vehicles
vozidla	vehicle
vozidlá	vehicles	vehicle
voči	towards	against
voľba	choice
voľbu	choice
voľby	elections	election
voľbách	elections
voľne	free
voľnej	the free
voľnom	freedom	free
voľné	free
voľného	free
voľný	free	leisure
voľných	baggy
voľným	free
vp	vp
vplyv	impact
vplyvom	influence	influenced by
vplyvov	impact	this results
vplyvu	impact
vplyvy	impact	effects
vpravo	right
vracia	returns	back
vraj	supposedly	said
vraví	it is said	said
vraždu	murder
vraždy	murder
vrch	top
vrchnej	top
vrchný	's high
vrchol	top	peak
vrchole	top
vrcholom	peak
vrcholy	peaks	peacks
vrchom	top
vrchov	hills
vrchu	top
vrchy	mountains
vrstiev	layers
vrstva	layer
vrstve	layer
vrstvou	layer
vrstvu	layer
vrstvy	layers
vrstvách	layers
vrátane	including
vrátil	returned
vrátila	returned
vrátili	returned
vrátiť	return
vs	versus
vsi	vsi	village
vstup	input
vstupe	input	entering	entry
vstupné	entry price	ticket
vstupom	input
vstupu	input
vstupuje	entered	enter
vstúpil	vstupil	entered
vstúpila	entered	came
vstúpiť	input
vtedajšej	former
vtedajší	then
vtedajších	then
vtedy	then
vtákov	birds
vtáky	birds
vybavenie	equipment
vybavené	equipped
vybavený	with	equipped
vybral	chosen
vybrali	selected	chose
vybrané	selected	the selected
vybrať	select
vybudovali	built
vybudovanie	building
vybudovaná	built
vybudované	built	constructed
vybudovaný	built
vybudovať	build
vychádza	based
vychádzajú	based	be published
vychádzal	based
vydal	issued
vydala	released	published
vydali	issued
vydania	issue
vydanie	edition
vydané	issued
vydaní	edition of
vydaný	issued
vydavateľstvo	publishing house	publishing
vydať	issue
vydáva	publishing
vydávať	issue	emit	publish
vyhlásenie	proclamation
vyhlásení	a statement
vyhlásením	a statement	statement
vyhlásený	proclaimed
vyhlásil	said	announced
vyhlásila	declared	said
vyhlásili	proclaimed
vyhnúť	avoid	to evade
vyhral	won
vyhrali	win	won
vyhráva	wins
vyjadrenie	expression	statement
vyjadril	said	expressed
vyjadriť	express
vyjadruje	expresses
vyjadrujú	expresses
vykonal	done
vykonať	perform	execute
vykonáva	performs
vykonávajú	performed
vykonávanie	execution	pursuance
vykonávať	exercise
vylučuje	excreted	excludes
vylučujú	excreted	excludes
vymedzené	defined
vymenúva	enumerates
vyobrazenie	representation
vyplýva	emerge	results
vypočítať	calculate
vypracoval	developed	made
vypukla	broke
vypĺňa	fills the	fills
vyriešiť	solve
vyrobené	manufactured
vyrobený	made
vyrobiť	produce
vyrába	produces
vyrábajú	produced
vyrábali	produced
vyrábané	produced
vyrábať	produced	produced by a
vysiela	sends
vysielač	transmitter
vyskytovali	occurred
vyskytuje	occurs
vyskytujú	occurs
vysokej	high
vysoko	high
vysokou	high
vysoká	high
vysoké	high
vysokého	high
vysokú	high	visoko
vysoký	high	tall
vysokých	tall
vysokým	high	higher
vysokými	high
vystavené	consist	exposed
vystupoval	featured	performed
vystupuje	acts
vystupujú	acts
vystúpenia	performances
vystúpeniach	performances
vystúpenie	appearance
vystúpení	performances
vystúpil	made
vystúpili	made
vysvetlenie	explanation
vysvetliť	explain
vysvetľuje	explains
vysvätený	ordained	sanctified
vysťahovalectvo	emigration
vytesal	carved out	carved
vytesať	carve
vytlačené	printed
vytvorenie	create	creating
vytvorená	created
vytvorené	crafted	created
vytvorením	by creating
vytvorený	created
vytvoril	created
vytvorila	created
vytvorili	have created	created
vytvorilo	be* created	created
vytvoriť	create
vytvorí	create
vytvára	creates
vytvárajú	form
vytváranie	creation	formation
vytvárať	creates	create
využil	used
využili	used the
využitia	use	use made	significant
využitie	usage	exploitation
využitím	exploitation
využiť	use	used
využíva	uses	utilizes
využívajú	exploits	exploit a	are used
využíval	used
využívali	used
využívanie	use
využívané	used
využívaný	used in the first	used
využívať	exploit	use
vyvinul	developed
vyvinula	developed
vyvinuli	developed
vyvinutý	developed
vyvinúť	developed
vyvolali	induced
vyvolalo	caused
vyvolať	cause
vyvoláva	raises a	evokes	induce
vyvíja	develops
vyvíjajú	develop
vyzerá	looks
vyznania	religion	confession
vyznačuje	characterized by	characterized
vyznačujú	characterized by	characterized	are distinguished
vyčerpanie	depletion
vyše	more than	than
vyšetrenie	examination
vyšiel	released
vyšla	came out	published
vyšli	came out	trailhead
vyšlo	published
vyššej	higger	higher
vyššia	above	higher
vyššie	above	higher
vyššieho	higher
vyššiu	higher	more
vyššou	more
vyšší	taller	higher
vyšších	senior	higher
vyšším	hugher	above
vyžaduje	require	requires
vzadu	behind	at the back
vzal	took
vzbury	rebellion
vzdal	gave up	gave
vzdať	surrender	give up
vzdelania	education
vzdelanie	education	earned
vzdelávacie	an educational
vzdelávania	education
vzdelávanie	education
vzdialenosti	distance
vzdialenostiach	distances
vzdialenosť	distance
vzdialenosťou	distance
vzdialené	remoteling	remotely
vzdialený	a remote
vzdialených	remote	distant
vzduch	air
vzduchu	air
vzhľad	appearence	appearance
vzhľadom	relative
vzhľadu	appearance
vznik	formation
vznikajú	arise
vznikajúce	the nascent
vznikali	emerged	created
vznikať	rise
vznikla	appeared	was	was formed
vznikli	created
vzniklo	created
vznikne	appears	there is
vzniknuté	incurred
vzniknúť	incurred but	uprise
vznikol	originated	was
vznikom	creation	formation
vzniku	of
vzniká	emerges	arises
vzor	pattern
vzorec	formula
vzorky	samples
vzorom	model
vzoru	pattern
vzostup	rise
vzrástol	increase	increased
vzácne	rare
vzájomne	reciprocally	each other
vzájomnej	mutual
vzájomné	mutual
vzájomného	mutual
vzájomných	mutual
vzťah	relation	relationship
vzťahoch	relations
vzťahom	relationships	relationship
vzťahov	relations
vzťahu	relation
vzťahuje	applies
vzťažnej	reference
v londýne	in london
v oblasti	in
v roku	in
v tej	in the	in
václav	vaclav
váh	weights
váhu	weight
vám	you
vápenatý	calcium	calcic
vápenca	limestone
vápence	calcite
vápencov	limestone
vápenec	limestone	calcareous stone
vás	you
vážený	weighted
vážne	serious	seriously
vážnej	classical, serious	classic
väzba	binding	conscious
väzbou	bond
väzbu	link
väzby	ties
väzenia	prison
väzení	dear
väznice	purlins	prison
väznici	purlin
väzňov	prisoners
väčšej	greater
väčšia	more
väčšie	more
väčšieho	a bigger
väčšina	majority	most of
väčšine	most	most ranks
väčšinou	mostly
väčšinu	most
väčšiny	majority	most	most of
väčšiu	more
väčšom	bigger
väčšou	more
väčší	bigger	more
väčších	larger
väčším	greater	more
vírus	virus
vírusom	virus
vírusov	viruses
vírusu	virus
vírusy	viruses
víťaza	winner
víťazstva	victory
víťazstve	victory
víťazstvo	victory
víťazstvom	victory
vôbec	at all	all
vôd	water
vôle	crop
vôli	will	optional
vôľa	will	call	ox
vôľu	will
výber	selection
výberu	i select	choice
výbežku	salient	foreland
výbor	committee
výborne	tasty
výboru	committee
výbuchu	explosion
východ	east
východe	east
východiskom	starting	recourse
východne	east
východnej	eastern
východnom	eastern
východná	east	vychodna
východné	east
východného	of eastern	eastern
východnú	east
východný	east	eastern
východných	the eastern
východným	eastern
východu	east
výchova	to educate	nurturing
výcvik	training
výdavky	outlay	expenditure
výhodou	benefit	advantage
výhody	advantages
výhradne	special	exclusively
výkon	performance
výkonom	performance
výkonu	performance
výkony	performances	performance
výlučne	only
výmena	exchange
výmene	exchange
výmenu	exchange
výmeny	exchanges
výnimkou	exception	an exception to
výnimku	exception	special exception
výnimky	exceptions
výnimočne	exceptionally
výnosy	income
výpočet	calculation	calculate
výpočty	computation	calculations
výprav	expeditions
výprava	expedition
výpravu	expedition
výpravy	delegation	expedition
výraz	term	expression
výrazne	noticeably	markedly
výraznejšie	distinct	significant
výrazná	significant
výrazné	markedly	significant
výrazný	distinct	significant
výrazu	definition	expression
výroba	production
výrobca	producer	manufacturer
výrobcov	vendors
výrobcovia	producers	manufactures	manufacturers
výrobe	produced
výrobkov	products
výrobky	products
výrobných	production	productive
výrobu	manufacturing
výroby	production
výroky	sayings	statements
výročie	anniversary
výsady	privileges
výskum	research of	research
výskume	research
výskumné	research
výskumov	researches
výskumu	research
výskumy	research
výskyt	occurrence
výskytu	occurrence
výsledkom	the result	result
výsledkov	results
výsledku	results
výsledky	results
výsledný	resulting	the resulting
výsledok	the value of a
výslovnosť	pronunciation	pronounciation
výstavba	construction
výstavbe	construction
výstavbou	the construction	construction
výstavbu	construction
výstavby	construction	constraction
výstup	output
výstupné	output
výtvarné	artistically
výtvarného	fine	fine art
vývin	development
vývoj	development
vývoja	development
vývoji	development	progress
vývojom	development
výzbroj	equip
význam	significance
význame	awarded
významne	significantly
významnejšie	significant
významnou	an important	significant
významná	with a very important	very important
významné	significantly
významnú	prominent
významný	eminent
významných	of important
významným	famous	eminent
významnými	significant
významom	importance	eea
významu	meaning	significance
výška	altitude	height
výške	of	height
výškou	height
výšku	height
výšky	height
výživy	nutrition
včely	bees
vďaka	thanks
vĺn	waves
vľavo	left
všade	everywhere
však	however	but
všeobecne	generally	general
všeobecnej	of generic	general
všeobecnosti	generally	general
všeobecná	general entry	general
všeobecného	of general	general
všeobecný	general
všeobecných	general
všetci	all	everyone
všetka	all
všetko	everything	all
všetky	all
všetkého	all
všetkému	everything	all
všetkých	all	of all
všetkým	all
všetkými	all
všetok	all	dispose
všimol	noticed
vždy	always
w	w.
waffenss	waffen-ss
wagner	wagner
waldemar	waldermar	waldemar
wales	wales
wall	wall
warhol	warhol
washington	washington
waters	waters
wc	wc
web	web
webe	web
webové	web
webových	web-based
webu	web	site
white	white
wifi	wi-fi
wikipédia	wikipedia
wikipédie	wikipedia
wilhelm	wilhelm
william	william
windows	windows
winston	winston
with	with
wojtyła	wojtyla
wolfgang	wolfgang
world	world
wpa	wpa
x	x
xi	xi
xiv	xiv
xml	xml
xp	xp
xv	h	xv
xvi	xvi
y	in
yoko	yoko
york	york
yorku	york
your	your
z	of	z
za	for
zaberajú	occupy
zaberá	interested in	takes up
zabezpečenie	security	ensure
zabezpečil	placed	ensure
zabezpečiť	ensure	secure
zabezpečuje	ensures	provides
zabezpečujú	provide	ensures
zabezpečí	ensure
zabil	killed
zabiť	killed
zabraňuje	prevents
zabrániť	prevent
zachoval	maintained
zachovala	preserve	remained
zachovali	preserve	preserved
zachovalo	preserved
zachovaná	preserved
zachované	the preserved	remained
zachovať	preserve	remain
zachránil	saved
zachrániť	rescued
zachytené	spotted
zachytiť	catch	capture
zachytáva	captures
zachytávajú	capture
zadarmo	free
zadnej	back
zahraničia	abroad	foreign
zahraničnej	foreign
zahraničná	foreign
zahraničné	foreign
zahraničnú	foreign
zahraničných	foreigh	foreign
zahraničí	abroad
zahrňuje	includes
zahynulo	killed
zahŕňa	includes
zahŕňajú	includes
zajatcov	prisoners
zajatí	captured	captivity
zakladateľ	founder
zakladateľa	founder
zakladateľom	founder
zakladá	based	founding
zakázal	banned	prohibited
zakázané	scheduled	forbidden
založenie	establishment	founding
založená	founded	based
založené	found	to found
založený	based
založil	founded
založili	founded	established
založiť	found	establish	set up
zamerania	focus
zameranie	aim	focus
zameraná	oriented	focused
zamerané	oriented	focused
zameraný	oriented	aimed
zameriava	focus	aimed at
zamestnania	jobs	employment
zamestnanie	job
zanechal	left
zanikla	disappeared
zaoberajú	deal
zaoberal	dealt with	deal with
zaoberá	dealing	concerns
zapisuje	writes
zapojenie	engagement
zapísal	signed up
zaradiť	classify
zaraďuje	rejoice
zaraďujú	rejoice
zariadenia	equipment
zariadenie	device	equipment
zariadení	equipment
zariadením	with accessories
zas	again
zasa	turn	again
zasahovať	interfere
zasahuje	interferes
zase	again
zasiahla	hit
zaslúžil	deserve	deserved	merited
zastavil	stopped
zastavili	stop
zastaviť	stop
zastaví	stop
zastupiteľstvo	council
zastupuje	represents	represents the
zastával	stopped
zastúpenie	representation
zastúpené	represented
zatiaľ	while	so far
zatmenia	eclipse
zatmenie	twilight	eclipse
zaujíma	are interested	occupied
zaujímal	interested	adopted	became interested
zaujímavosti	attractions	interesting facts	other interesting
zaujímavé	interesting
zavedenie	introduction
zavedený	introduced
zaviedla	applied	established	introduced
zaviedli	established	introduced	installed
zaviedol	introduced
zaznamenal	recorded	noted
zaznamenaná	recorded
zaznamenané	reported
zaútočili	attack
začal	started	began
začala	started
začali	started	began
začalo	started	began
začať	start	begun
začiatkoch	beginning	beginnings
začiatkom	beginning
začiatku	beginning
začiatky	beginnings
začiatok	inception	top	beginning
začne	will	starts
začnú	start	i start
začína	begins
začínajú	start	begin
začínal	started	starts
zaľudnenia	congestion
zašiel	gone
zaťaženie	loads	load condition
zažil	sewed	has experienced
zbaviť	rid
zbernice	bus
zbierka	collection
zbierky	collection
zbor	group	corps
zboru	committee	corps
zbrane	weapons
zbraní	weapons	arms
zbraň	weapon
zdanlivo	seemingly
zdenka	zdenka
zdieľanie	sharing
zdravie	health
zdravotné	health
zdravotnícka	health
zdravotníctva	public health	health	of health
zdravotný	medical
zdroj	source
zdroja	source
zdroje	sources	resources
zdrojom	source
zdrojov	resources
združenia	association
zdá	whether	seems
zelená	green
zelené	green
zelených	greens
zem	earth	ground
zeme	earth
zemetrasenia	earthquake
zemetrasenie	earthquake
zemetrasení	earthquake
zemi	country
zemiakov	potatoes
zemiaky	potato
zemného	natural	ground
zemný	natural
zemou	earth	ground
zemskej	earth	earth's
zemskom	earth	earth's
zemská	earth
zemského	provincial	earth's
zemský	earth
zemským	earth
zeppelin	zeppelin
zhodné	identical	identically
zhodujú	tally
zhora	from above
zhromaždenia	assembly
zhromaždenie	gathering	meeting
zhruba	about	roughly
zimná	simpsons	winter
zimné	winter
zimný	winter
zimných	winter
zimy	winter
zirkón	zircon
zisk	profit
zisku	profit
zisky	profits
zistil	found
zistili	found	found out
zistilo	found	found out
zistiť	find out
zistí	find
zjavenia	reveal	revelation
zjednodušenie	simplification
zjednotenie	unification
zlata	gold
zlato	gold
zlatom	golden	gold
zlatá	golden	gold
zlaté	gold
zlatú	gold
zlatý	golden	gold
zle	wrong	with difficulty
zlepšenie	improvement
zliatiny	alloy
zlom	break
zlomu	break
zločinov	crimes
zločiny	crimes
zloženia	composition
zloženie	composition
zložená	composed	built
zložené	bracket	compound
zložení	content	components
zložením	a composition	composition
zložený	composed	composition
zložiek	components
zložil	passed
zložité	complex	difficult
zložka	component
zložkou	component
zložku	component
zložky	components
zlá	bad	evil
zlé	bad
zlúčeniny	compounds
zlúčeninách	compounds
zlúčenín	compounds
zlý	bad
zmena	change
zmenami	changes
zmene	change
zmenil	changed	to change
zmenila	changed
zmenili	changed	change
zmenilo	changed
zmeniť	change
zmenky	bill
zmenou	change
zmenu	change
zmeny	changes
zmenám	changes
zmení	changes	change
zmes	mixture
zmesi	mixture
zmesou	mixture
zmien	changes
zmienka	reference
zmienku	mention
zmiešané	mixed
zmluva	contract
zmluve	contract
zmluvu	contract
zmluvy	contract
zmlúv	contracting	contract
zmysel	sense
zmysle	sense
zmyslom	sense
zmyslu	sense
znak	character
znakmi	feature	characters
znakom	sign
znakov	characters
znaku	character	sign
znaky	characters	signs
znamenajú	mean
znamenal	meant	noticed
znamenalo	meant	mean
znamená	means
značiek	brands
značka	brand
značku	brand
značky	brand
značne	significantly	highly
značnej	significant
značná	considerable
značné	considerably
značnú	significant
značný	considerable
značí	purports	mean
znie	sounds
zničená	destroyed
zničené	destroyed
zničili	destroyed
zničiť	destroy
znižuje	decreases
znižujú	reduces	reduce
znova	over
znovu	again
známa	known
známe	known	famous
známeho	known	famous
známej	known
známi	known	known for
známky	stamps
známou	known
známy	known
známych	known	the known
známym	known	-known	know
známymi	famous
znázorňuje	shows the	shows
zníženie	reduction
zníži	lowers	reduced
znížiť	reduce
zo	from
zobrazenia	display
zobrazenie	view
zobrazená	displayed	display
zobrazené	shown
zobrazení	display
zobrazený	shown
zobraziť	display
zobrazovanie	imagery	display
zobrazovaní	displaying
zobrazuje	shows
zobrazujú	shows
zobrazí	view
zodpovedajú	correspond
zodpovednosti	liability	responsibility
zodpovednosť	responsibility
zodpovedný	responsible
zodpovedá	commanded	corresponds
zoh	olympics
zohráva	plays
zomrel	died
zomrela	died
zomreli	died
zoo	zoo
zosilnenie	amplification
zosilňovač	amplifier
zosilňovača	amplifier
zoskupenia	group
zostal	remaied	remained
zostala	remained
zostali	remained
zostalo	remained
zostane	will remain
zostava	report	setup
zostať	stay
zostáva	remains
zostávajú	remain
zoznam	list
zozname	list
zoznamu	list
zoznámil	met	got to know
zrak	sight
zrejme	probably	obviously
zrejmé	obviously
zreteľne	evidently	distinctly
zriadenia	establishment
zriadenie	betrayed	government
zriedka	seldom	rarely
zriedkavo	rarely
zriedkavé	rare
zrušenie	cancel
zrušená	canceled
zrušené	cancelled	canceled
zrušení	abolished
zrušil	canceled
zrušiť	cancel
zrážkami	rain fall	precipitation
zrážky	precipitation
zrážok	precipitation
zrýchlenie	increment
zssr	ussr
zub	teeth	tooth
zubov	teeth
zuby	teeth
zur	zur
zuzana	zuzana	richard
zv	zv.
zvané	called
zvaný	called
zviera	animal
zvierat	animals
zvieratá	top friends
zvieraťa	pet	animals
zvláštne	strange	special
zvláštnosťou	particularities
zvláštnu	special
zvláštny	special
zvláštnym	special
zvlášť	separately
zvolen	elected
zvolene	chosen	the chosen
zvolený	selected
zvolil	chosen
zvuk	sound
zvukov	sounds
zvuková	sound	compatible sound
zvukové	sound	audibly
zvukových	audio
zvuku	sound
zvuky	sounds
zvykne	tends to	tends
zvyknú	get used
zvykom	habit
zvyky	habits
zvyčajne	usually
zvyšku	rest of	rest
zvyšky	remains	remnants
zvyšných	remaining
zvyšok	the rest	rest
zvyšovanie	increase
zvyšuje	increases
zváranie	welding
zväz	union
zväze	union
zväzku	volume
zväzok	volume
zväzom	union
zväzu	union
zväčša	mainly	mostly
zväčšuje	increases
zvíťazil	won
zvýšenej	increased
zvýšenie	increase
zvýšeniu	increase	increasing
zvýšená	increased
zvýši	increase	increases
zvýšil	raise	increased
zvýšila	increased
zvýšiť	raise
z nich	of them	from them
zábery	shots	conclusions
záhrada	garden
záhrade	garden
záhrady	garden	gardens
zákaz	ban	order
základ	radix	basis
základe	the basis
základne	basic
základnej	primary	basic
základnou	foundation of	basic
základná	main	base
základné	basic
základného	basic
základnú	primary	between basic
základný	base
základných	primary	basic
základným	basic
základom	the basis
základy	foundations
základňa	base
základňu	base	between basic
zákon	bill	law
zákona	law	act
zákone	testament	law
zákonmi	laws
zákonník	code
zákonom	act
zákonov	laws
zákony	laws
zákroku	surgery	operation
záležitosť	affair	matter
záleží	depends
záliv	gulf
zálive	gulf
zálivu	gulf
zámkoch	castles
zámkov	locks
zámku	castle
zámky	locks
zámok	castles	castle
zámorské	overseas
zánik	decline	extinction
zániku	extincion	extinction
západ	west
západe	west
západne	west	western
západnej	western
západnom	western
západnou	western	fit
západná	western
západné	west	western	sets
západného	west	the west
západnú	west	western
západný	west
západných	western	of western
západnými	western
západu	westerners	west
zápal	burn	bishop
zápas	match
zápase	wrestling
zápasov	matches
zápasy	fights	match
zápis	record	writing
zápisu	registers
záporné	negative	thirty
zároveň	also	while	at the same time
zásad	meetings
zásada	meeting rooms	principle
zásade	meets	basically	in principle
zásadne	meet
zásady	principles
zásah	intervention
zásahu	hitting	of interference	intervention
zásahy	intervention	interventions
zásluhou	thanks
zásob	stocks last	supplies
zásobovanie	supply
zásoby	stock of	reserves	stock
zástupcom	representative
zástupcov	representatives
zástupcovia	representatives	representatives from
záujem	interested
záujmu	your interest	interest
záujmy	interests
záver	conclusion
závere	end	conclusion
záveru	conclusion
závisia	depend
závislosti	dependence
závislosť	addiction	dependence
závislá	depend
závislé	dependent	dependents
závislý	dependent	addicted
závisí	depends
záznam	record
záznamu	record
záznamy	records
zéland	zealand	zeland
zélandu	zealand
získa	afford
získal	gained	won
získala	gained	won
získali	gained
získalo	gained	was obtained
získanie	having an
získané	awarded
získaných	obtained
získava	obtains
získavajú	gain	obtain
získaval	gained
získavať	acquire	obtains
získať	get
zóna	zone
zóny	zone
zúčastnil	took part	participated
zúčastnili	attended	participated
zúčastnilo	took place	attended
zúčastňuje	participates	takes part
zďaleka	far	nearly
zľava	discount	right
zš	primary school	zs
|	/
~	-
 	/
 km	km
 rokov	years
  	during	none
  intel	intel
  °c	c
®	r
°c	c
½	1/2
ánd	and
ázia	asia
ázie	asia
ázii	asia
éra	epoch	era
éry	era
írska	irish	ireland
írsko	ireland
ísť	be	surely
ú	u.	at
úctu	account
údaje	dates
údajne	suposedly	allegedly
údajov	data sheet	data
údolia	valley	valleys
údolie	do	valley
údolí	valley
úkor	expense
úloh	tasks	task
úloha	function	problem
úlohe	role
úlohou	task
úlohu	role
úlohy	homeworks	tasks	role
úmerná	proportional	proportional to
únia	union	union of
únie	union
únii	union
úpadku	decline
úpadok	decline
úplne	completely
úplnej	full	complete
úplná	completely
úplné	absolute
úplný	he speaks	speaks
úprava	induction
úpravy	changes	alignments	treatment
úrad	office
úradný	official
úradným	official	clerical
úradu	office
úrady	offices
úroveň	level
úrovne	levels	level (first and third sentence), levels (second sentence)
úrovni	level
úrovňou	level
úsek	sections	sections on
úseku	section	section(first and third word), department(second word)
úseky	sections
úsilie	effort
úspech	success
úspechom	success
úspechu	success
úspechy	successes
úspešne	successfully
úspešná	successful	succesful
úspešné	successfuly
úspešný	succesful
úst	mouth
ústav	institute	constitution
ústava	constitution
ústave	constitution	verbally
ústavný	constitutional
ústavných	constitutional
ústavou	constitution	constitutionally
ústavu	institute
ústavy	constitution
ústi	enters	leads to
ústnej	speech	oral
ústredným	main	central
ústí	mouth
útok	attack
útokmi	attacks
útokoch	attacks
útokom	attacks	attack
útokov	attacks
útoku	attack
útoky	attacks
útvar	formation
útvarov	staff
útvary	formations
úv	uv
úvahy	account
úvod	introduction
územia	territory	lands
územiach	territories	lands
územie	territory	territory of
územiu	territory
územné	territorially
území	territory
územím	territory	land
úzke	narrow
úzko	narrowly	closely
úzky	narrow
účasti	participation
účastníci	participants
účastník	participant
účasť	participation
účel	purpose
účelom	to	purpose
účely	purposes
účinkom	effect of	effect
účinku	of the effect of	effect
účinky	effects
účinne	works to	effective
účinnosť	efficiency	effect
účinná	the active	become an effective contributor
účinné	effective
účinok	effect
účtovníctvo	accounting	/	accountancy
über	cool
č	ch
čajkovskij	tchaikovsky (composer)	tchaikovsky
čakali	waiting	waited
čakať	wait
čas	time
čase	case	time
časoch	time
časom	over time	time
časopis	magazine
časopise	journal	magazine
časopisov	magazines
časopisu	magazine
časopriestor	spacetime
časopriestoru	space-time
časovo	by time	time
časovom	time
časová	time
časové	time
časový	time
častejšie	more common	more
časti	of	parts
častiach	parts
častica	particle
častice	particles
často	early	often
časté	of	frequent
častí	section	parts
častíc	particles
času	time
časy	times
časť	section
časťami	parts
časťou	frequent
čechov	czechs
čechy	bohemia	cecchi	czech republic	guilds
čechách	bohemia
čele	head	the head
čeliť	face
čerpal	drew
červenej	red	chernevej
červenou	red
červená	red
červené	red
červeného	red
červený	red
červených	red
česi	czechs
česka	czech	czech republic
českej	czech
česko	czech
českom	czech
československa	czechoslovakia
československej	czechoslovak
československo	czechoslovakia	czechoslovak
československu	czechoslovakia
československá	czechoslovakia
československé	czechoslovakia	czechoslovak
československého	czechoslovak
československý	czechoslovak
česku	czech	czech republic
česky	czech
česká	czech	czech republic
české	czech
českého	czech
český	czech
českých	czech
čestný	honorary	honest
čeľade	family
čeľaď	celad
češtine	czech
či	or	if
čiara	line
čiarou	line
čiary	lines
čias	ever	time
čiastočne	partially
čiech	bohemia
čierna	black
čierne	black
čierneho	the black	black
čiernej	black
čiernemu	black
čiernu	black
čierny	black
čiernych	black
čile	chile
čin	act
činidlo	agent
činnosti	activities
činností	activities
činnosť	are	activity
činnosťou	activity
činu	offense	china
činy	china
čisto	cleanly	clean	pure
čistá	clean	pure
čisté	clear
čistého	clean	pure
čistý	net	clean
čiže	strange	thus	that
čl	cl.
člen	member
členenie	breakdown	division	devision
členmi	members
členom	member
členov	members
členovia	members
členských	member
členstvo	membership
človek	one
človeka	man
človekom	man
človeku	human	man
článkoch	articles
článkov	articles
článku	article
články	article	articles
článok	article	aricle	chlanock	clanok
čmeľ	chmel	bombus	bumblebee	cmel	čmel	bumble bee	bumble-bee
čo	what
čoho	which
čom	what
čomu	what	which
čoraz	more
čoskoro	soon
čou	hangzhou	cou	chou	zhou
čreva	intestine
črty	features
čsr	csr
čssr	ussr
čím	thereby	what with
čína	china
číne	offense	cine
čínou	china
čínska	chinese
číny	acts
čísel	code	numbers
čísiel	numbers
čísla	facts	numbers
číslami	numbers
čísle	number
číslic	numbers
číslice	numbers	number
číslo	integer	number
číslom	document number	number
číta	read	chita	reads
čítanie	reading
čítaní	reading	readings
čítať	quote	readable
číňania	chinese
ďalej	further
ďaleko	far
ďalekohľad	binoculars	telescope
ďalekohľadom	telescope
ďalšej	other
ďalšia	another	next
ďalšie	other	the next
ďalšieho	further
ďalšiemu	next
ďalšiu	following	further
ďalšom	its later	the next
ďalšou	another
ďalší	beaver	next
ďalších	other	more
ďalším	other
ďalšími	other
ľ	l'
ľad	ice
ľadovec	glacier
ľadovom	ice
ľadového	ice
ľadový	lada
ľadu	ice
ľahko	easily	easy
ľahké	easy	lightweight
ľahký	easily
ľahšie	easier
ľavej	left
ľavom	left
ľubomír	lubomir
ľubovoľné	arbitrary
ľud	folk	people
ľudia	people
ľudovej	folklore	people
ľudová	peoples	ludova
ľudové	folk
ľudovít	ludovit	Ľudovit	Ľudovít
ľudovíta	ludovit	ludovits
ľudovú	people
ľudový	folk
ľudových	folk
ľudskej	of human	human
ľudskom	human
ľudskou	human
ľudská	human
ľudské	human
ľudského	lucskeho	of the human
ľudskú	human
ľudský	humanely	human
ľudských	human
ľudstva	mankind
ľudstvo	humanity
ľudu	people
ľudí	people
ľuďmi	with people	people
ľuďoch	people
ľuďom	to people	people
ňom	nom	went	him
ňou	nou
ňu	it	her
š	and	s
šachmat	sach-mat	sachmat	sach mat	checkmate
šancu	chance
šesť	six
šesťdesiatych	sixties
ševčenko	shevchenko	Ševčenko
šiesta	the sixth	sixth
šiestich	six
šindlerová	sindler	sindlerova
širokej	wide
široko	wide
široké	wide
širokú	broad
široký	wide
širšom	wider
škoda	skoda
škodlivé	harmful
škody	damage
škola	school
škole	school
školstva	education
školstvo	education
školu	school
školy	school
školách	schools
škvrny	spots
škvŕn	stains	stain
škótska	scotland
škótsko	scotland
škótsky	scottish
škôl	schools
šošoviek	lens	lenses
šošovka	lens
šošovky	lens
španiel	spaniel
španielska	spanish
španielske	spanish
španielsko	spain
španielsku	in spain	spanish
španielsky	spain	spanish
špecializované	specialized
špecifické	specific	more specific
špecifický	specific	specifically
špecifických	specific
špecifikácie	specifications
špeciálna	special
špeciálne	specially
špeciálnej	special
špeciálny	special
špeciálnych	special
špeciálnym	special
špekulácie	speculation
šport	sport
športová	sport	sports
športové	sportove	sports
športových	sports
športy	sport	sports
štadión	stadium
štadióna	stadium
štadióne	stadium
štandard	standard
štandardnej	standard
štandardné	standard
štandardný	standard
štandardom	standard
štandardov	standards
štandardu	standard
štandardy	standards
štatistiky	statistics
štefan	stephen	stephan
štefana	stephen	stephan
štefánik	stefanik
štefánika	stefanik	Štefánik
štiavnica	shtiavnica	stiavnica
štr	page	str
štruktúr	structures	structure
štruktúra	structure
štruktúre	structure
štruktúrou	structure
štruktúru	structure
štruktúry	structure
študenti	students
študentov	students	student
študijných	study
študoval	studied
študovať	study	to study
študuje	study	studies
štvorca	square
štvrtej	forth	fourth
štvrtá	forth	fourth
štvrtý	fourth
štvrť	quarter of
štyri	four
štyria	four
štyrmi	four
štyroch	four
štábu	staff	crew
štádia	selected	stage
štádium	stage
štát	country	state
štáte	country	state
štátmi	states	countries
štátna	state
štátne	state
štátneho	state	vigorous
štátnej	state
štátny	state
štátnych	state
štátnym	state	a hefty
štátoch	states
štátom	state
štátov	states
štáty	states
štít	shield
štítna	thyroid
štítnej	thyroid
štítu	shield
štúdia	studies
štúdie	study
štúdiom	dissertations
štúdiové	studio
štúdiu	study
štúdium	study
štúdií	study
štúr	stur	Štúr
štúra	stura	stur
štýl	atrium	style
štýle	style
štýlom	style
štýlov	styles
štýlu	style
štýly	styles
švajčiarska	switzerland	swiss
švajčiarsko	switzerland
švajčiarsku	swiss	switzerland
švédska	swedish
švédsku	swedish
švédsky	swedish
šét	saves	consista	set	seth	boss
šírenia	sirenia	spreading
šírenie	sirenia	spread
šíri	spreads
šíria	spread
šíriť	spread	to spread
šírka	width	match
šírky	latitude	matchsticks	width of
šľachta	slachta
šľachty	aristocracy	nobility
šťastia	luck
šťastie	lucky
ťah	move
ťahu	tension
ťažba	mining	mining of
ťažbu	mining	mining of
ťažby	mining	harvesting
ťažiska	cg	gravity
ťažisko	center of gravity
ťažko	hard	hardly
ťažkosti	difficulties
ťažká	heavy	difficult
ťažké	hard	difficult
ťažký	bags	hard
ťažkých	heavy
ťaží	tazi	benefit
ťažšie	harder
žalúdok	stomach
že	that
železa	iron
železnej	iron
železnica	railroad	railway
železnice	railroad	railway
železničnej	railroad	railway
železničná	railway
železničné	railway	railways
železná	iron
železné	zelezne	iron
železo	iron
žena	woman
žene	woman	women
ženou	woman	wife
ženské	women
ženu	woman
ženy	women
žeriavotvaré	cranes	gruiforms	gruiformes	gruidae
žiadal	asked	requesting
žiadali	asked
žiaden	harmonization	no
žiadna	no
žiadne	no
žiadnej	no
žiadnom	any	no
žiadnu	no
žiadny	no
žiadosť	request
žiarenia	radiation
žiarenie	radiation
žiarením	radiation
žiarovky	bulb
židia	jews
židom	jews
židov	jews	zidov
židovskej	jewish	hebrew
židovská	jewish
židovského	jewish
židovský	jewish
žien	women
žigmund	zigmund
žije	lives
žijú	live	livr
žijúce	living
žijúcich	living
žil	lived
žila	lived	vein
žili	lived
žilina	žilina	Žilina	zilina
žiline	ziline	zilina
žilinský	punjab	zilinski
žiliny	zilina
žilo	lived
živiny	nutrients
život	life
života	life
živote	life
životnosť	life
životné	environment	living
životného	environment	living
životný	life
životných	living
životným	life
životom	life
životopis	vitae	cv
životu	life
živočíchov	animals
živočíchy	animals	creature
živočíšne	animal
živočíšnej	stockbreeding	animal
živočíšnych	animal
živá	living	alive
živé	living	alive
živín	nutrients
živých	living
žiť	live
žliaz	glands
žltá	yellow	zita
žlté	yellow
župy	county
žáner	genre
žánre	genres
žánrov	genres
žánru	genre
žľaza	gland
žľazy	gland
→	>
−	-
